### ISSUE TITLE
will this be for the official docker image?

### ISSUE THREAD

**Issue by babatundebusari** [nextcloud/docker#1]
will this be for the official docker image?

**Comment by nickvergessen** [comment]
yes, see https://help.nextcloud.com/t/docker-image-available/351

**Comment by babatundebusari** [comment]
`official` docker image and someone else's docker image are 2 entirely different things

**Comment by nickvergessen** [comment]
It will be as official as it can get, but will be maintained by community. Anyone else can fork it and create a second docker....

**Comment by jospoortvliet** [comment]
The idea was to create a space for collaboration. In reality, the biggest difference between 'official' and 'unofficial' in a community is if a group of people is dedicated to it or if it is an individual effort, in my experience.

As nobody really has gotten started yet that means anyone can still step up and get this moving.

**Comment by pierreozoux** [comment]
Yes, this will be the official image, please comment and once the maintainers are happy, we can PR docker.

**Comment by stp-ip** [comment]
To clarify:

This container image will be community maintained, but under the umbrella of nextcloud.
It is not yet an official docker hub image aka available from /_/nextcloud, but we will do our best to work with docker to make this possible.

**Comment by pierreozoux** [comment]
Ok, closing this for now.
