### ISSUE TITLE
Migrate to PHP 7

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/docker#10]
It would be nice if the Docker image could benefit from the increased speed of PHP7.

**Comment by Wonderfall** [comment]
I agree, we should at least provide a PHP 7 version. There's an official image `php:7.0-fpm`, and even `php:7.0-fpm-alpine` so we can finally use Alpine Linux as a base for this image.

At the moment there are some unofficial Nextcloud images which use PHP 7, including mine, if you wanna try.

**Comment by pierreozoux** [comment]
Does Nc officially support php 7?

If yes, then, just PR, and I'd accept it, if not, we'd need a tag then.
(You can PR also, and I'd accept it)

**Comment by qrevel** [comment]
I'm actually using [wonderfall/nextcloud](https://hub.docker.com/r/wonderfall/nextcloud/) and it works really great. I  was waiting the official image but I can't switch to it if it doesn't provide php7 using alpine.
