### ISSUE TITLE
include cron

### ISSUE THREAD

**Issue by wuast94** [nextcloud/docker#1002]
Sry if i´m wrong but i think crontab should be installed by default in image becouse its an funktion from nextcloud. 

![image](https://user-images.githubusercontent.com/16965460/74611128-88c65700-50f9-11ea-8dfe-6cb7409e16f2.png)

And in the info Text stand that cron is recommend and i cant use it

yes i can write my own dockerfile (wich is possible when using dockker compose but didnt when using unraid or some other management tools from docker). 

another and better way do do this is to include env in docer files where i can install packages when starting the container. for example this repo is using this and i love it (look into dockerfile): https://github.com/fhem/fhem-docker
![image](https://user-images.githubusercontent.com/16965460/74611225-24f05e00-50fa-11ea-86d6-f4f84d42cf6c.png)

by the way i´m using nextcloud:18.0.1-apache

**Comment by dassio** [comment]
we really need cron for  external sync

**Comment by SnowMB** [comment]
Cron is already installed in the container (#220), but the containers are built to run a single process. The [cron example](https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles/cron) just shows how to alter the image to run cron as 2nd process in a single container using supervisord. 

However running 2 processes in one container adds complexity, so an alternate solution is running cron in another container like here: 

https://github.com/nextcloud/docker/blob/430ce875c237bfe3759c0547669d3bbebedd7310/stack.yml#L29-L36

**Comment by pankid** [comment]
Sorry if this is the wrong spot to ask, but is it expected for to keep seeing the crontab hasn't run error under settings when using a second nextcloud container to handle cron? Does it matter which cron setting in the gui the nextcloud app container is set to?

**Comment by JuniorJPDJ** [comment]
Cron should be mentioned in docker compose, which is also provided in examples ;)

**Comment by JuniorJPDJ** [comment]
> Sorry if this is the wrong spot to ask, but is it expected for to keep seeing the crontab hasn't run error under settings when using a second nextcloud container to handle cron? Does it matter which cron setting in the gui the nextcloud app container is set to?

It's not, you did something wrong

**Comment by J0WI** [comment]
More examples can be found in #627
