### ISSUE TITLE
Cannot authorize desktop sync apps

### ISSUE THREAD

**Issue by p3palazzo** [nextcloud/docker#1004]
Nextcloud-Docker 16.0.8 and sync apps on Mac and Linux version 2.6.2. I can use the Web interface normally, but I am unable to complete the initial sign-in process through the desktop applications.

When the sign-in process opens a browser window, after clicking through the "Grant access" buttons I always end up with the Nextcloud web page throwing an "Internal Server Error. The server was unable to complete your request." Meanwhile, the desktop application returns: "There was an error accessing the 'token' endpoint. Error transferring https://some.domain.com/login/v2/poll - server replied: Bad Request."

Nextcloud is intalled behind a reverse proxy as follows:

````
Nextcloud-Docker <----------------------> OpenVPN server <----Client requests
      Apache                                  Ubuntu/Apache
 VPN IP 10.8.0.5                VPN IP 10.8.0.1 / Public IP x.x.x.x
                                       https://some.domain.com
Machine in my office                            VPS
````

Relevant parts of my Apache `domain.conf` on the VPS server:

```
<IfModule mod_ssl.c>
Listen 443
NameVirtualHost some.domain.com:443
<VirtualHost *:443>
	ProxyPass / http://10.8.0.5:8080/
	ProxyPassReverse / http://10.8.0.5:8080/
ServerName some.domain.com
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{SERVER_NAME}/$1 [R,L]
RewriteRule ^/\.well-known/carddav https://%{SERVER_NAME}/remote.php/dav/ [R=301,L]
RewriteRule ^/\.well-known/caldav https://%{SERVER_NAME}/remote.php/dav/ [R=301,L]
RewriteRule ^/ - [QSA,L]
</VirtualHost>
</IfModule>
```

Relevant parts of my Nextcloud-docker config:

```
  'trusted_domains' => 
  array (
    0 => 'some.domain.com',
    2 => 'localhost:8080',
  ),
  'overwrite.cli.url' => 'https://some.domain.com',
  'loglevel' => 2,
  'trusted_proxies' => 
  array (
    0 => '10.8.0.1',
  ),
  'overwritehost' => 'some.domain.com',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/',
  'overwritecondaddr' => '^10\\.8\\.0\\.1$',
```

The public server did not log any errors.

The Docker container logs do not seem helpful:

```
172.19.0.1 - - [17/Feb/2020:19:27:25 +0000] "GET /login/v2/flow HTTP/1.1" 200 4698 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:73.0) Gecko/20100101 Firefox/73.0"
172.19.0.1 - - [17/Feb/2020:19:27:32 +0000] "GET /custom_apps/deck/css/activity.css?v=b654c2cc-12 HTTP/1.1" 200 595 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:73.0) Gecko/20100101 Firefox/73.0"
172.19.0.1 - - [17/Feb/2020:19:27:33 +0000] "GET /core/img/actions/confirm-white.svg?v=2 HTTP/1.1" 200 694 "https://intranet.abaco-arquitetura.com.br/core/css/guest.css?v=6b31ae32-12" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:73.0) Gecko/20100101 Firefox/73.0"
172.19.0.1 - - [17/Feb/2020:19:27:34 +0000] "GET /core/fonts/Nunito-Regular.woff2 HTTP/1.1" 200 19889 "https://intranet.abaco-arquitetura.com.br/core/css/guest.css?v=6b31ae32-12" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:73.0) Gecko/20100101 Firefox/73.0"
172.19.0.1 - - [17/Feb/2020:19:27:34 +0000] "GET /core/fonts/Nunito-Bold.woff2 HTTP/1.1" 200 20037 "https://intranet.abaco-arquitetura.com.br/core/css/guest.css?v=6b31ae32-12" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:73.0) Gecko/20100101 Firefox/73.0"
172.19.0.1 - - [17/Feb/2020:19:27:33 +0000] "GET /apps/accessibility/js/accessibility?v=0 HTTP/1.1" 200 1060 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:73.0) Gecko/20100101 Firefox/73.0"
172.19.0.1 - - [17/Feb/2020:19:27:33 +0000] "GET /apps/theming/js/theming?v=12 HTTP/1.1" 200 1272 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:73.0) Gecko/20100101 Firefox/73.0"
172.19.0.1 - - [17/Feb/2020:19:27:33 +0000] "GET /apps/theming/image/logo?v=12 HTTP/1.1" 200 3139 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:73.0) Gecko/20100101 Firefox/73.0"
172.19.0.1 - - [17/Feb/2020:19:27:39 +0000] "GET /login/v2/grant?stateToken=3tNSGOXf63axUtjkCUrXRDgTnMUOJfMCZ83lZnjTgGg3BhyyZqHUeDDfyg69Xeqj HTTP/1.1" 200 4772 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:73.0) Gecko/20100101 Firefox/73.0"
127.0.0.1 - - [17/Feb/2020:19:27:48 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.3.14 (internal dummy connection)"
127.0.0.1 - - [17/Feb/2020:19:27:53 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.3.14 (internal dummy connection)"
127.0.0.1 - - [17/Feb/2020:19:27:55 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.38 (Debian) PHP/7.3.14 (internal dummy connection)"
172.19.0.1 - - [17/Feb/2020:19:28:04 +0000] "GET /core/img/favicon-touch.png HTTP/1.1" 200 3204 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:73.0) Gecko/20100101 Firefox/73.0"
172.19.0.1 - - [17/Feb/2020:19:28:04 +0000] "GET /core/img/favicon.ico HTTP/1.1" 200 3563 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:73.0) Gecko/20100101 Firefox/73.0"
172.19.0.1 - - [17/Feb/2020:19:27:58 +0000] "POST /login/v2/poll HTTP/1.1" 404 833 "-" "Mozilla/5.0 (Macintosh) mirall/2.6.2stable (build 20191224) (Nextcloud)"
172.19.0.1 - - [17/Feb/2020:19:28:13 +0000] "GET /login/v2/grant HTTP/1.1" 500 5754 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:73.0) Gecko/20100101 Firefox/73.0"
```

**Comment by andreasrolke** [comment]
Try this:

 'trusted_domains' => 
  array (
    0 => 'some.domain.com',
    2 => 'localhost:8080',
  ),
  **'overwrite.cli.url' => 'http://some.domain.com',** (http without s, helped me!!)
  'loglevel' => 2,
  'trusted_proxies' => 
  array (
    0 => '10.8.0.1',
  ),
  'overwritehost' => 'some.domain.com',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/',
  'overwritecondaddr' => '^10\\.8\\.0\\.1$',

**Comment by robbieh** [comment]
I have the same problem with a similar setup. Can't find any way to make it work.

**Comment by p3palazzo** [comment]
Thank you, @andreasrolke. I made the change you suggested and also added the server's own VPN IP to the 'trusted domains' array, but nothing worked :(

**Comment by Aephir** [comment]
Same issue here, though using nginx.

The nextcloud web page doesn't throw error though, it just sticks on the `Account access` page a spinning wheel in the `Grant access` button. But the desktop app returns the same error as you report.

I could get the mobile app up and running by creating credentials manually, and then creating a QR code, but I'm stuck with no access from my MacOS app.

**Comment by tvallois** [comment]
Hi, i've the same problem, though using nginx.

Same behavior as @Aephir has described.

**Comment by EaseRider** [comment]
Thank you @Aephir 

Adding the overwriteprotocol and setting the cli.url to https finally helped me. 

`  'trusted_domains' => array (
    0 => 'nextcloud.mydomain.com',
  ),
  'overwrite.cli.url' => 'https://nextcloud.mydomain.com',
  '**overwriteprotocol**' => 'https',`

My docker setup is: nginx-proxy -> nginx (nextcloud) -> nextcloud.

**Comment by Scoth42** [comment]
I'm running into this as well trying to get a desktop client synced. Android worked fine. I have the overwriteprotocol and overwrite.cli.url in there, to no avail.

**Comment by ccellist** [comment]
I am having the same problem, also running nginx with dockerized Nextcloud. Any updates on this?

**Comment by p3palazzo** [comment]
I believe [the fix linked by Aephir above](https://github.com/nextcloud/docker/issues/1004#issuecomment-632927462) solved the issue for most cases.

**Comment by ccellist** [comment]
Unfortunately @fuxx solution doesn't work for me from the linked ticket. I have had both overwrite.cli.url and overwriteprotocol set for some time and logins are still failing. Inspecting the grant form the form url is set to http, not https. This on Nextcloud 20.0.6 behind Nginx rev proxy.

**Comment by pdemaret** [comment]
The solution given by @EaseRider was all I needed  to solve the authorization with the Macos desktop app. I just removed the ** in front and after the 'overwriteprotocol' if this can be of any help, added this to my config.php and presto it worked !
Docker Nextcloud 21.0.2 behind Nginx rev proxy.

**Comment by erdoukki** [comment]
> The solution given by @EaseRider was all I needed to solve the authorization with the Macos desktop app. I just removed the ** in front and after the 'overwriteprotocol' if this can be of any help, added this to my config.php and presto it worked !
> Docker Nextcloud 21.0.2 behind Nginx rev proxy.

Same ! thanks...
