### ISSUE TITLE
Ship 18.0.1 on stable

### ISSUE THREAD

**Issue by Bleuzen** [nextcloud/docker#1018]
Nextcloud 18.0.1 is now to 100% on the stable channel.
https://github.com/nextcloud/updater_server/commit/196a6828f25582576cd514ade5f8d972d09be8d2

**Comment by tilosp** [comment]
Fixed by https://github.com/nextcloud/docker/pull/1022

**Comment by Bleuzen** [comment]
@tilosp 18.0.2 is out now on stable, so another update is needed.
https://github.com/nextcloud/updater_server/pull/341

Also, the tags are updated on github, but stable and production are not updated on docker hub yet.
