### ISSUE TITLE
Change PHP memory_limit (I am going crazy)

### ISSUE THREAD

**Issue by b3nis** [nextcloud/docker#1019]
Hi all dear Nextcloud docker users and developers!

I have an issue that is driving me crazy. I have been trying to increase the memory_limit for PHP for days but I can't get it working.

What I get in the log:
`Allowed memory size of 536870912 bytes exhausted (tried to allocate 16384 bytes) at /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#117`

What I have found/tried:

1. If I run **docker exec --user www-data nextcloud-app php -i | grep memory_limit** I get 512MB
2. If I run **docker exec --user www-data nextcloud-app php -ini** I get all the settings and, again, I can see 512MB as memory limit
3. I have tried editing the php.ini-production files, a few of them can be found under /var/lib/docker/overlay2/ - which I probably shouldn't because I get an issue when trying to save my container, but it doesn't really matter since I can just download a new one if I need one
4. I have tried editing the .htaccess file, both of them (found in the docker volume and under /home/app/)
5. I have tried editing the user.ini

Nothing has worked. If someone has a solution to this I will send you a virtual beer or buy you own IRL if you are not too far away.

Big thanks in advance!

**Comment by gbalcewicz** [comment]
Hi @b3nis try this https://github.com/nextcloud/docker/issues/1014#issuecomment-595887548

**Comment by b3nis** [comment]
Solved by @gbalcewicz in #1014
