### ISSUE TITLE
Can't upload more than a 1gb file

### ISSUE THREAD

**Issue by JordanPlayz158** [nextcloud/docker#1030]
Hi! I am using NextCloud Docker Image (Insecure docker-compose example) with a NGINX Reverse Proxy and I can't seem to upload a file greater than 1gb, if I try to it will give me the 504 Could not reassemble chunks error message

Here is my nginx.conf for Reverse Proxy
https://paste.fastermc.xyz/enapajiler.nginx

Here is my nginx.conf for NextCloud 
https://paste.fastermc.xyz/namehowezo.nginx

Here is my php.ini for NextCloud
https://paste.fastermc.xyz/omegunohoy.coffeescript

Here is my www.conf for NextCloud
https://paste.fastermc.xyz/akecoqugob.pl

**Comment by J0WI** [comment]
Closed by #1379
