### ISSUE TITLE
add support for ACMEv2 to jrcs/letsencrypt-nginx-proxy-companion (docker-compose)

### ISSUE THREAD

**Issue by thomas-merz** [nextcloud/docker#1032]
> According to our records, the software client you're using to get Let's 
> Encrypt TLS/SSL certificates issued or renewed at least one HTTPS certificate 
> in the past two weeks using the ACMEv1 protocol. Here are the details of one 
> recent ACMEv1 request from each of your account(s):
> 
> Client IP address:  1.2.3.4
> 
> User agent:  simp_le/0.13.0 
> 
> Hostname(s):  "myhostname.mydomain.tld" 
> 
> Request time:  2020-03-05 17:07:51 UTC 
> 
> Beginning June 1, 2020, we will stop allowing new domains to validate using 
> the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before 
> then, or certificate issuance will fail. For most people, simply upgrading to 
> the latest version of your existing client will suffice. You can view the 
> client list at: https://letsencrypt.org/docs/client-options/
> 

I can also see in ./entrypoint.sh in the running docker container "jrcs/letsencrypt-nginx-proxy-companion" the following echo command(s):  
"Error: ACME v2 API is not yet supported by simp_le." and "See https://github.com/zenhack/simp_le/issues/101"  

Please add support for ACMEv2 for docker-compose and use one of the existing clients that will suffice. Thank you!

**Comment by canihavesomecoffee** [comment]
v1.12 of the companion (https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/releases/tag/v1.12) starts using ACME v2, and the version on Docker Hub (https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion) is updated...

Shouldn't you just upgrade the Docker image to get the latest version?
