### ISSUE TITLE
Installation Error Nextcloud Docker

### ISSUE THREAD

**Issue by svelloso** [nextcloud/docker#1036]
Hi,

"
Error
Could not create or write to data /media/dados/nextcloud/data directory
"
 
In first page I received the above error.

Authorization error? I tried chmod 0777 and chown www-data and it didn't work.

Thank you in advance for your help.

**Comment by svelloso** [comment]
in time.

I have installed Ubuntu Server Arm64 (Raspberry computer).

I submitted the following Docker command:

sudo docker run -d \
-v nextcloud: /media/data/nextcloud \
-v apps: /media/data/nextcloud/apps \
-v config: /media/data/nextcloud/config \
-v data: /media/data/nextcloud/data \
-v theme: /media/data/nextcloud/theme \
-p 8080: 80 \
nextcloud

Note: /media/data/nextcloud is a USB drive.

Can I use a USB drive for all directories?

I accessed Nextcloud at http://localhost:8080/.

Thanks.

**Comment by svelloso** [comment]
still in time.

on the DBMS configuration page (MariaDB) the directory /var/www/html/data is displayed. Can't I change?

Thanks.

**Comment by svelloso** [comment]
still in time ...

In the documentation https://hub.docker.com/_/nextcloud there is a reference to the "unnamed docker volume", that I confess I didn't understand very well.

Which of the options (-v or --mount flag) should I use in order to be able to store the data on USB drives?

Thank you again.

**Comment by joshtrichards** [comment]
Hi @svelloso - I hope you found a solution through another channel. As this channel isn't a general support channel, but for reporting bugs and submitting enhancement ideas for the community Docker image, it's not the best channel for these types of queries. 

> sudo docker run -d
-v nextcloud: /media/data/nextcloud
-v apps: /media/data/nextcloud/apps
-v config: /media/data/nextcloud/config
-v data: /media/data/nextcloud/data
-v theme: /media/data/nextcloud/theme
-p 8080: 80
nextcloud
Note: /media/data/nextcloud is a USB drive.

It looks like you are trying to mix bind volumes and named volumes - and also mixing up host paths versus in-container paths. The second parameter (after the colon in each `-v` line) is the directory *within* the container not on your host. 

As this is a fairly old issue and many things have changed (and it doesn't really belong here anyway), I'm going to close this out. Feel free to follow-up at the [Nextcloud Help Forum](https://help.nextcloud.com) with questions or troubleshooting assistance.
