### ISSUE TITLE
Security release process

### ISSUE THREAD

**Issue by StephenLittBelch** [nextcloud/docker#1045]
For security releases such as Nextcloud v18.0.3 and v17.0.5, are image updates to docker-library made quickly as possible as part of the security release process, or would a derived image with the updated Dockerfile need to be used if eager to update? I’m nervous to wait for the docker-library pull request to be created/merged, depending on the (unknown: https://github.com/nextcloud/server/issues/20119) severity of the update.

Edit: Seeing the recommendation in https://github.com/nextcloud/server/issues/18485, I used the https://github.com/nextcloud/docker#adding-features instructions to build an updated derived image from _nextcloud:18.0.2-apache_, until the merge of https://github.com/docker-library/official-images/pull/7680

**Comment by J0WI** [comment]
Duplicate of
https://github.com/nextcloud/docker/issues/999
https://github.com/docker-library/official-images/pull/7677#issuecomment-603196571
https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what
