### ISSUE TITLE
no smbclient included in the latest image

### ISSUE THREAD

**Issue by 556556bt** [nextcloud/docker#105]
I just download the latest full nextcloud docker image and try it on sinology DSM. However, it said "smbclient" is not installed. Mounting of "SMB / CIFS", "SMB / CIFS using OC login" is not possible. 

I checked doc. and it requires to install smbclient or the PHP smbclient module to be installed on the Nextcloud server. However, I don't know to do it on docker image and make the modules installed persistently.

**Comment by Zennoe** [comment]
There is an example that shows you how to add SMB to your container: (https://github.com/nextcloud/docker/blob/master/.examples/Dockerfile.smb)
You can then build the image as explained in the docs: (https://docs.docker.com/get-started/part2/#build-the-app)

**Comment by kosli** [comment]
works like a charm :+1:  i suppose the issue can be closed.
