### ISSUE TITLE
Trying to load certain files causes HTTP 302

### ISSUE THREAD

**Issue by manuth** [nextcloud/docker#1055]
As only a small number of files (identified by their extensions) are loaded directly or passed to `index.php` there are some apps such as the `firstrunwizard` which can't show files correctly as a `302` error is returned instead of the actual file.

## Steps to reproduce
1. Boot up the `.examples/docker-compose/insecure/mariadb/fpm/docker-compose.yml`-environment
2. If necessary set a password for the administrator
3. If necessary wait for the additional apps to install
4. Notice that the intro video of the `firstrunwizard` doesn't load
5. Copy the address of the video and open it in a new tab
6. Notice that you're redirected to `http://localhost/apps/files/`

## Expected Behavior
The files should load correctly.

## Actual behavior
Some files don't load and refer to `/apps/files/` instead.

## Workaround
I think the source of the problem might be here:
https://github.com/nextcloud/docker/blob/269a08113889884e3d3607df81ca1aba8f4dd408/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf#L104-L106
and here:
https://github.com/nextcloud/docker/blob/269a08113889884e3d3607df81ca1aba8f4dd408/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf#L167-L171

I found myself able to fix this issue by removing these sections and adding this piece of code instead:

```nginx
        location / {
            try_files $uri /index.php$request_uri @inexistent;
        }

        location @inexistent {
            rewrite ^ /index.php;
        }
```

**Comment by cfelder** [comment]
This was very useful for me when using **nextcloud-fpm** and **nginx** in containerised environments where **nginx** is using a subdirectory as webroot, e.g. /cloud whereas the subdirectory is mounted as host directory onto the default webroot of nextcloud-fpm ``/var/www/html`` which is used for installing all necessary files by the entry point script as well

Example:

nginx:
``-v /usr/share/nginx/html:/usr/share/nginx/html``

nextcloud-fpm:
``-v /usr/share/nginx/html/example.com/cloud/:/var/www/html``
