### ISSUE TITLE
remoteip.conf config not suitable for intranet

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/docker#1068]
The defautl configuration for  /etc/apache2/conf-enabled/remoteip.conf in nextcloud-apache docker image contains:
```
RemoteIPHeader X-Real-IP
RemoteIPTrustedProxy 10.0.0.0/8
RemoteIPTrustedProxy 172.16.0.0/12
RemoteIPTrustedProxy 192.168.0.0/16

```

Please replace the RemoteIPTrustedProxy directive for RemoteIPInternalProxy directive.
RemoteIPTrustedProxy will ignore X-Real-IP for private addresses , so If you are connecting inside intranet with a private IP, the real IP will not show on the logs , only the proxy will show. If you change the directive, the client IP will appear in the logs as expected.

**Comment by kesselb** [comment]
I suggest to turn remoteip off, configure trusted proxies and make sure the pass the original ip address as x-forwarded-for.

**Comment by jsalatiel** [comment]
Hi kesselb, Maybe that fixes IP for nextcloud instance , but it will keep apache logs with the wrong ip.

**Comment by J0WI** [comment]
Closing in favor of https://github.com/nextcloud/docker/issues/1103
