### ISSUE TITLE
Directory permissions for running Nextcloud without root

### ISSUE THREAD

**Issue by tobru** [nextcloud/docker#107]
To make the official Nextcloud Docker image compatible with OpenShift out-of-the-box, some directory permissions need to be amended. For more information about this topic, see [OpenShift Docs -> Creating Images -> Guidelines -> OpenShift Container Platform-Specific Guidelines -> Support Arbitrary User IDs](https://docs.openshift.com/container-platform/3.5/creating_images/guidelines.html#openshift-container-platform-specific-guidelines). The important part:

> For an image to support running as an arbitrary user, directories and files that may be written to by processes in the image should be owned by the root group and be read/writable by that group

```
RUN chgrp -R 0 /some/directory \
  && chmod -R g+rwX /some/directory
```

This means all directories which get writen into should have these permissions. At least

* `/usr/src/nextcloud/custom_apps`
* `/usr/src/nextcloud/config`
* `/usr/src/nextcloud/data`
* `/usr/src/nextcloud/themes`

A working Dockerfile can be found here: https://github.com/tobru/nextcloud-openshift/blob/dev/Dockerfile. With these changes the Nexcloud image runs perfect on OpenShift.

Are the maintainers of the official Dockerfiles willing to incorporate the proposed permission change? I'm happy to create a PR, but wanted to first discuss this topic. My wish is to bring Nextcloud to OpenShift without having to customize the official Docker image as done in https://github.com/tobru/nextcloud-openshift/blob/dev/Dockerfile

**Comment by SnowMB** [comment]
From the docs:
> Because the container user is always a member of the root group, the container user can read and write these files. The root group does not have any special permissions (unlike the root user) so there are no security concerns with this arrangement. In addition, the processes running in the container must not listen on privileged ports (ports below 1024), since they are not running as a privileged user.

Wouldn't that create a problem with the apache container?

**Comment by tobru** [comment]
I must admit that I'm working with the FPM image on OpenShift, having two containers in a Pod: Nginx and Nexcloud FPM.

So as long as the Apache image also listens on a port > 1024 it should work as-is. Of course I can give it a try if you want.

**Comment by tobru** [comment]
I've created a PR https://github.com/nextcloud/docker/pull/131 which - when merged - solves this issue. It's not 100% as described in the original description, but it allows the image to be run on environments where the container doesn't run as root. Would be great to have the PR reviewed and tested. Feedback is very welcome.
