### ISSUE TITLE
Internal server error using docker-compose

### ISSUE THREAD

**Issue by opelx** [nextcloud/docker#1070]
Hi,

on my box I have several docker stacks running (gitlab etc.) which are accessible trough jwilder's nginx reverse proxy. I added nextcloud today, also want to use these. But I get an "Internal Server Error" like this here (original in German)

        Internal server error

        The server could not complete the request.

        If this happens again, please send the following technical details to your server administrator.

        More details can be found in the server log.
        Technical Details

            Remote address: 192.168.1.251
            Request identifier: jV7tDfKep1C1ReWFm6jX

Well, I'm the server administrator :(
Here is my docker-compose for nextcloud

    version: '3'
    services:
      db:
        image: mariadb
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: 
          always
        volumes:
          - db:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=XXXXXX
          - MYSQL_PASSWORD=XXXXXX
          - MYSQL_DATABASE=nextcloud
          - MYSQL_USER=nextcloud
      redis:
        image: redis:alpine
        restart:
          always
      app:
        image: nextcloud:fpm-alpine
        restart: 
          always
        environment:
          - MYSQL_HOST=db
          - REDIS_HOST=redis
        depends_on:
          - db
          - redis
        volumes:
          - nextcloud:/var/www/html
          - /srv/docker/nextcloud/data:/var/www/html/data
      web:
        image: nginx:alpine
        restart: 
          always
        networks:
          - frontproxy_net
          - default
        ports:
          - 7080:80
        environment:
          - VIRTUAL_HOST=nextcloud.example.com
          - VIRTUAL_PORT=7080
        depends_on:
          - app
        volumes:
          - nextcloud:/var/www/html:ro
          - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
          - ./nginx/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
      cron:
        image: nextcloud:fpm-alpine
        restart: always
        volumes:
          - nextcloud:/var/www/html
        entrypoint: /cron.sh
        depends_on:
          - db
          - redis
    volumes:
      db:
      nextcloud:
    networks:
      frontproxy_net:
        external: true

and my for nginx-proxy if relevant (no letsencrypt)

    version: '2'
     services:
       front_proxy:
         container_name: front_proxy
         image: jwilder/nginx-proxy:latest
         restart: always
         environment:
           - DEFAULT_HOST=default.home.lan
         networks:
           - frontproxy_net
         ports:
           - "80:80"
           - "443:443"
         volumes:
           - "/var/run/docker.sock:/tmp/docker.sock:ro"
           - "./vhost.d:/etc/nginx/vhost.d:ro"
     networks:
       frontproxy_net:
         external: true

So, how to fix the problem? Any other hints?

**Comment by opelx** [comment]
solved, I forgot to "import" the nextcloud_data bind mount volume.

**Comment by rchovan** [comment]
I have same issue. But I have updated my installation from latest 18.0.2 to latest 18.0.3 and after upgrade, I can't start app.

```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

Nothing special in logs:

```
Configuring Redis as session handler


AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.25.0.5. Set the 'ServerName' directive globally to suppress this message


AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.25.0.5. Set the 'ServerName' directive globally to suppress this message


[Thu Apr 23 07:45:00.477964 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.17 configured -- resuming normal operations


[Thu Apr 23 07:45:00.478005 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'


172.25.0.1 - radoslav [23/Apr/2020:07:45:23 +0000] "GET /status.php HTTP/1.1" 500 425 "-" "Mozilla/5.0 (Windows) mirall/2.6.4stable-Win64 (build 20200303) (Nextcloud)"


172.25.0.1 - - [23/Apr/2020:07:45:26 +0000] "GET / HTTP/1.1" 500 717 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0"


172.25.0.1 - - [23/Apr/2020:07:45:27 +0000] "GET / HTTP/1.1" 500 717 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0"


172.25.0.1 - radoslav [23/Apr/2020:07:45:55 +0000] "GET /status.php HTTP/1.1" 500 425 "-" "Mozilla/5.0 (Windows) mirall/2.6.4stable-Win64 (build 20200303) (Nextcloud)"


172.25.0.1 - radoslav [23/Apr/2020:07:46:27 +0000] "GET /status.php HTTP/1.1" 500 425 "-" "Mozilla/5.0 (Windows) mirall/2.6.4stable-Win64 (build 20200303) (Nextcloud)"


172.25.0.1 - radoslav [23/Apr/2020:07:46:59 +0000] "GET /status.php HTTP/1.1" 500 425 "-" "Mozilla/5.0 (Windows) mirall/2.6.4stable-Win64 (build 20200303) (Nextcloud)"


172.25.0.1 - radoslav [23/Apr/2020:07:47:32 +0000] "GET /status.php HTTP/1.1" 500 425 "-" "Mozilla/5.0 (Windows) mirall/2.6.4stable-Win64 (build 20200303) (Nextcloud)"


172.25.0.1 - radoslav [23/Apr/2020:07:48:04 +0000] "GET /status.php HTTP/1.1" 500 425 "-" "Mozilla/5.0 (Windows) mirall/2.6.4stable-Win64 (build 20200303) (Nextcloud)"


172.25.0.1 - radoslav [23/Apr/2020:07:48:35 +0000] "GET /status.php HTTP/1.1" 500 425 "-" "Mozilla/5.0 (Windows) mirall/2.6.4stable-Win64 (build 20200303) (Nextcloud)"


172.25.0.1 - radoslav [23/Apr/2020:07:49:08 +0000] "GET /status.php HTTP/1.1" 500 425 "-" "Mozilla/5.0 (Windows) mirall/2.6.4stable-Win64 (build 20200303) (Nextcloud)"
```

**Comment by opelx** [comment]
After more testing it seems, that in my case the error disappeared after removing the old volumes. I did change the images to php-alpine from apache. Here rises the question how to restore all settings in those case.

**Comment by robowraith** [comment]
I had the same problem because I mounted the directories of my old (non-docker) Installation. It seems the server did not like the "old" index.php. After removing the old directories content and restarted the containers, the error vanished.
