### ISSUE TITLE
Add an optional NEXTCLOUD_ADMIN_EMAIL variable

### ISSUE THREAD

**Issue by freechelmi** [nextcloud/docker#1074]
It could be really useful to add an optional 

NEXTCLOUD_ADMIN_EMAIL

variable.

This is needed to automate the provisioning of the first user and optionally sending him/her a password reset email so he/she can choose his/her password

**Comment by joshtrichards** [comment]
I would suggesting using auto-config hooks for this:

https://github.com/nextcloud/docker?tab=readme-ov-file#auto-configuration-via-hook-folders

These hooks can execute any `occ` commands.

The email value can be set via `occ user:setting ADMIN_ACCOUNT` in the post-install hook. A password reset can be triggered via `occ user:resetpassword` in the same hook script to get the workflow you're seeking.
