### ISSUE TITLE
Compose failed with Dockerfile and Nextcloud:latest

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/docker#1075]
Hello,

I tried to build an Docker Image with elasticsearch and other things.

But since Nextcloud:latest use Ubuntu Focal (20.04) the build fails with this error:

https://paste.dasnetzundich.de/view/b86ce046

This is the Dockerfile:

https://paste.dasnetzundich.de/view/ed2ff963

Tried this the Tag latest and production.

**Comment by kesselb** [comment]
> But since Nextcloud:latest use Ubuntu Focal (20.04) 

The images here extend from php based on debian buste or alpine.

**Comment by kesselb** [comment]
> sudo add-apt-repository ppa:ondrej/php

The php docker images work different. Don't use apt to install additional packages. Check the php image documentation for more details.

Closing the report as unrelated to nextcloud/docker.

**Comment by Happyfeet01** [comment]
With this Dockerfile it works really fine. 


https://paste.dasnetzundich.de/view/aa6e26a4
