### ISSUE TITLE
Customize php-fpm configuration in stable-fpm

### ISSUE THREAD

**Issue by khartahk** [nextcloud/docker#1080]
I'm trying to increase `pm.max_children` in `stable-fpm` but it's not working. 
I've tried adding `/usr/local/php-fpm.d/www2.conf` with
```
[www]
pm.max_children = 100
```
But it doesn't appear to be working. Should this be done this way and I just don't know how to check for the effects or is there some other proper route?

I really don't want to copy the `www.conf` to my host config folder and override it by mounting the file in the same place as I don't want to risk breakage in the future.

What would be the proper way to do this?

**Comment by J0WI** [comment]
Please try again with `/usr/local/etc/php-fpm.d/www2.conf`.

**Comment by khartahk** [comment]
How can I verify it's working or where can I check out running php-fpm configuration?

**Comment by doc75** [comment]
@khartahk on my side the default was reached when trying to upload multiples files or a big files through the Web interface (Drag & Drop). If you reach the limit, then you should see something like that in the logs of the nextcloud container:
```
app_1    | [<Date removed>] WARNING: [pool www] seems busy (you may need to increase pm.start_servers, or pm.min/max_spare_servers), spawning 8 children, there are 0 idle, and 6 total children
```

Above you can see that it spawn 8 children which is above the default value of ( (if I remember well).

**Comment by J0WI** [comment]
> How can I verify it's working or where can I check out running php-fpm configuration?

E.g. with https://www.php.net/manual/en/install.fpm.configuration.php#pm.status-path

**Comment by yuri-1987** [comment]
@khartahk the solution of mounting additional file works, you can verify with running this command from the container:  
`php-fpm -tt`

**Comment by J0WI** [comment]
I guess the question has been answered. We just consume the base image from https://github.com/docker-library/php, so this is not specific to the Nextcloud image.
