### ISSUE TITLE
为什么我使用https访问服务器，却有部分链接仍然使用的是http ？

### ISSUE THREAD

**Issue by kevinzu007** [nextcloud/docker#1082]
**https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm/**
我使用上面这个docker-compose配置文件测试部署nextcloud，在客户端使用 
 **https://nextcloud.zjlh.lan** 访问nextcloud，发现下面这几个链接依然使用的是**http**，并不是**https**，为啥？

1. http://nextcloud.zjlh.lan/apps/firstrunwizard/img/apps/tasks.svg
1. http://nextcloud.zjlh.lan/apps/firstrunwizard/img/apps/deck.svg
1. http://nextcloud.zjlh.lan/apps/firstrunwizard/img/apps/notes.svg
1. http://nextcloud.zjlh.lan/apps/firstrunwizard/img/apps/social.svg
1. http://nextcloud.zjlh.lan/apps/firstrunwizard/img/apps/groupfolders.svg
![image](https://user-images.githubusercontent.com/2586289/79719812-e8b3c680-8311-11ea-8d1b-c9edc0a57cc5.png)

会不会其他地方也有这个问题？
如果我不开启tcp 80端口，会不会造成使用故障？

**Comment by kesselb** [comment]
https://github.com/nextcloud/docker#using-the-apache-image-behind-a-reverse-proxy-and-auto-configure-server-host-and-protocol?

**Comment by kevinzu007** [comment]
搞定，谢谢！

**Comment by kevinzu007** [comment]
mark：
docker-compose.yml中加了下面两行
      - APACHE_DISABLE_REWRITE_IP=true
      - OVERWRITEPROTOCOL=https
