### ISSUE TITLE
Missing linux/amd64 image for 18.0.4-fpm tag

### ISSUE THREAD

**Issue by Edzilla2000** [nextcloud/docker#1089]
On docker hub, the linux/amd64 image is missing from the 18.0.4-fpm tag

**Comment by normen** [comment]
Yep, same here.

**Comment by pheiduck** [comment]
noticed this to `docker-compose pull` and then `docker-compose up -d` won't update to 18.0.4 because the build failed yesterday?

**Comment by Aurnytoraink** [comment]
All 18.0.4 amd64 version are missing in fact

**Comment by Aurnytoraink** [comment]
https://hub.docker.com/layers/nextcloud/library/nextcloud/18.0.4/images/sha256-a111841a601c81f42f08cab13f02205215096c371e965eb6b9388c7269662a82?context=explore

There is no amd64 varient

**Comment by koehn** [comment]
Thankfully there's an s390 image so I can still run it on my mainframe.

**Comment by nerrixDE** [comment]
any way to resolve this without waiting?

**Comment by herrwusel** [comment]
There is a amd64 tag now. Just updated my docker image ;)

**Comment by Aurnytoraink** [comment]
yeay!
So we can close this issue then

**Comment by tilosp** [comment]
it always takes a bit for all the images for the different architectures to get build.
You can follow the build progress here: https://doi-janky.infosiftr.net/
