### ISSUE TITLE
Error [object Object] - Probably CSP

### ISSUE THREAD

**Issue by boldt** [nextcloud/docker#1094]
# System

* Image: `nextcloud:18.0.3-apache`
* Docker version: `19.03.2, build 6a30dfc`
* Docker Compose version: `1.24.1, build 4667896b`
* Deployed behind a Traefik
* Apps:

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - bookmarks: 2.3.4
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - cookbook: 0.6.3
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - files_external
  - notifications
  - user_ldap
```

# Issue

As you can see in the following screenshot, I get the error notification "[object Object]". The network monitor shows plenty of CSP errors:

![Bildschirmfoto von 2020-04-27 14-45-08](https://user-images.githubusercontent.com/750793/80374404-e7951300-8896-11ea-9dd8-7229bfb49e87.png)

If I scroll a bit they're loaded finally:

![Bildschirmfoto von 2020-04-27 14-45-38](https://user-images.githubusercontent.com/750793/80374435-f085e480-8896-11ea-9e66-3d9749d687fd.png)

**Comment by joshtrichards** [comment]
Hi @boldt - On the surface this seems like a configuration matter and possibly something specific to Traefik. It's also possible it was a Nextcloud bug at the time. This channel is for bug specific to the official community Nextcloud Docker image. 

I'm going through old Issues in the Docker repository and trying to clean them up a bit. I hope you've found help elsewhere in the mean time. For general Nextcloud technical support, troubleshooting, and configuration assistance the best channel is the [Nextcloud Help Forum](https://help.nextcloud.com).
