### ISSUE TITLE
Improve readme regarding usage of other databases e.g. PostgreSQL

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/docker#11]
The support of PostgreSQL as alternative to MySQL seems important to me.

**Comment by SnowMB** [comment]
Nothing stops you from using a PostgreSQL database. There is an [official docker image](https://hub.docker.com/_/postgres/) you can use.

You don't even have to use a docker container. You could also run a "classic" installation of PostegreSQL on the host or another machine and use this one. 

You just have to insert the connection info in the Nextcloud setup wizard.

**Comment by Wonderfall** [comment]
The Dockerfile already provides the required extensions to use MySQL/MariaDB/PostgreSQL. As @SnowMB said, you only have to connect to a PGSQL instance during the Nextcloud setup wizard.

These explanations should be more detailed in the README.

**Comment by raimund-schluessler** [comment]
Alright, thanks for the insight.

> These explanations should be more detailed in the README.
Indeed, this should be in the readme, so people like me don't need to ask :wink: 

I changed the title to make this issue about documenting the database connection better.

**Comment by pierreozoux** [comment]
PR are welcomed :)
