### ISSUE TITLE
make kubernetes deployment more friendly or at least possible

### ISSUE THREAD

**Issue by kamikaze** [nextcloud/docker#1102]
Hi there. I'm using Traefik v2.2 with CRD. Just deploying in kubernetes doesn't make Nextcloud working and I can't find any meaningful information for such cases. Is it possible to clarify this moment with some Kubernetes YAML examples in docs? Thanks

**Comment by joshtrichards** [comment]
Hi @kamikaze - Maybe you'd find this useful: https://github.com/nextcloud/helm/

If this issue is no longer relevant, please close it here. Thanks!
