### ISSUE TITLE
Missing https urls in docker compose with-nginx-proxy

### ISSUE THREAD

**Issue by gerout7** [nextcloud/docker#1104]
When running nextcloud behind a reverse proxy with the example compose files listed here https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache all internal urls are missing https.

This has also been reported here: https://github.com/nextcloud/server/issues/20728

**Comment by ismailyenigul** [comment]
Hi @gerout7 
Try with traefik 2.0 instead of nginx proxy.
You can get full docker-compose.yml from https://gist.github.com/ismailyenigul/f03b4f5f15e5e61ac5b80905c5d2890a

**Comment by gerout7** [comment]
I think this should be fixed in all compose examples

**Comment by joshtrichards** [comment]
This may be a simple case of needing to add `OVERWRITE*`  environment variables to the examples, but I don't have time to test them all right now. So just noting for the future or if someone else wishes to pick it up.
