### ISSUE TITLE
Autoconfiguration for S3 as Primary Storage

### ISSUE THREAD

**Issue by rkilchmn** [nextcloud/docker#1124]
It would be great if S3 Primary Storage could be auto-configured similar to the database or Redis settings. Changing the primary storage in the config file after the installation step leads to some strange effects and prohibits a "serverless" deployment where there is no persistent file system other than S3. All file system extensions i looked up for docker requires root access in the container which are not given for serverless deployment options such as AWS Fargate

**Comment by MyTheValentinus** [comment]
+1 to add the possibility to configure S3 via env variable like this:
```
      - S3_KEY=xxx
      - S3_SECRET=xxxx
      - S3_BUCKET=xx-test01
      - S3_ADDRESS=xxx
      - S3_REGION=fr-par
      - S3_SSL=true
      - S3_PORT=443
      - S3_AUTOCREATE=false
```

**Comment by pankid** [comment]
Would also love to see this feature.

**Comment by rkilchmn** [comment]
Awesome! Great work and thanks for everyone who contributed
