### ISSUE TITLE
migrate helm chart to this repo (or org)?

### ISSUE THREAD

**Issue by billimek** [nextcloud/docker#1130]
Hello!  Myself and @chrisingenhaag are maintainers of the [nextcloud helm chart on the official helm 'stable' repo](https://github.com/helm/charts/tree/master/stable/nextcloud).  The helm stable repo is slated to be [deprecated in a few months](https://github.com/helm/charts#deprecation-timeline) and all charts hosted there will need to find a new home.

Would you be interested in hosting the nextcloud helm chart in this repo?  IMO it makes sense to home charts where the Dockerfile is, or at least in a co-located repo within an organization.

I would be happy to submit a pull request to add the necessary github actions to do proper linting and testing of chart changes as well as releases within the repo and 'hosting' on helm hub.  You can take a look at a [similar PR](https://github.com/munnerz/kube-plex/pull/78) I did for the kube-plex chart to see what it would look like.

Alternatively, I'm happy to host the nextcloud chart in [my charts repo](https://github.com/billimek/billimek-charts/).  I already have a couple dozen charts hosted there already with the proper chart linting/testing/releasing automation in place.

Thanks!

**Comment by pierreozoux** [comment]
@webwurst it will be here:
https://github.com/nextcloud/operator

and currently it is here:
https://lab.libreho.st/libre.sh/kubernetes/operators/nextcloud

(Sorry for the noise around the helm chart)

**Comment by pierreozoux** [comment]
@billimek I asked @skjnldsv to create  https://github.com/nextcloud/helm for you :) (I can't do it myself but he is part of Nc org)

I let you manage the details together :)

**Comment by skjnldsv** [comment]
@pierreozoux what about nextcloud/operator? Still relevant? It's unrelated?

**Comment by skjnldsv** [comment]
@billimek done

**Comment by chrisingenhaag** [comment]
Hello, 
thx @billimek and @skjnldsv for the repo migration. May I ask to be added to the repository?

**Comment by skjnldsv** [comment]
> Hello, 
> thx @billimek and @skjnldsv for the repo migration. May I ask to be added to the repository?

Ask @billimek :)

**Comment by billimek** [comment]
@chrisingenhaag added!

And with that, I think we can close this issue.  The chart has been migrated and is set for deprecation in the old helm/charts repo.
