### ISSUE TITLE
Configuring S3 (or compatible object storage) as Primary Storage

### ISSUE THREAD

**Issue by nickistre** [nextcloud/docker#1134]
A way to configure an S3 bucket as primary storage, as per [Configuring Object Storage as Primary Storage](https://docs.nextcloud.com/server/16/admin_manual/configuration_files/primary_storage.html).

I have an example project using the [18-fpm-alpine](https://github.com/nextcloud/docker/tree/master/18.0/fpm-alpine) image source, available [here](https://github.com/nickistre/nextcloud-s3-docker), including a `docker-compose.yml` and Kubernetes files that use [Minio](https://hub.docker.com/r/minio/minio/) as the S3-based back-end. 

Mainly, I'm looking to bring in the [`primary-object-storage.config.php`](https://github.com/nickistre/nextcloud-s3-docker/blob/master/fpm-alpine/config/primary-object-storage.config.php) config file I've created in my test project, update `README.md`, and optionally add an example `docker-compose.yml` that uses Minio. I can do the actual legwork of getting the PR up, but just looking for best development practices here.  Or I can just dive in and make the PR as best I can if that's fine.

**Comment by rkilchmn** [comment]
Hi,

Does this already take effect during the nextcloud installation as part of the container initialization?

Cheers Roger
