### ISSUE TITLE
Update button don't work - just redirect to main screen

### ISSUE THREAD

**Issue by iShift** [nextcloud/docker#1138]
Hi, when i push update button it redirects me to main screen, also i try to open direct: /updater/index.php and i have been redirected to home screen...

**Comment by Chartman123** [comment]
You have to update your Nextcloud using Docker mechanisms :slightly_smiling_face:

**Comment by iShift** [comment]
@Chartman123  thanks ! i think we should have some info about this in UI

**Comment by adrianmihalko** [comment]
How much should we wait until new version become available on Docker?
