### ISSUE TITLE
crashes caused by solving mysql 4-byte

### ISSUE THREAD

**Issue by richardrey** [nextcloud/docker#1139]
After applying the changes suggested by nextcloud:

MySQL is used as a database but does not support 4-byte characters

The errors indicated by the web have disappeared, but this has caused that you cannot install plugins such as: mail or ldap

not all plugins fail after installation, the ones I have detected are the ones I have mentioned

Someone can help me would like to solve the errors that nextcloud indicates to me but keeping the possibility of installing any plugins.

without applying the mysql change it allows me to install any plugin

manual that fixes errors:

https://docs.nextcloud.com/server/18/admin_manual/configuration_database/mysql_4byte_support.html

I have version 18.0.4 deployed

**Comment by joshtrichards** [comment]
Hi @richardrey - This repository is used forfiling  bug reports specific to the official community Nextcloud Docker image. It isn't for general technical support or configuration matters. This doesn't sound like it was a Docker specific issue. It also sounds like a configuration/local environment issue. I hope you found support for your matter through another channel. For future reference, the best channel for this type of situation is the [Nextcloud Help Forum](https://help.nextcloud.com).

If you agree with my assessment, please close out this Issue so we can stay focused on addressing bugs specific to the Docker image. Thanks!
