### ISSUE TITLE
Feature request: Include PHP mailparse in images

### ISSUE THREAD

**Issue by sgofferj** [nextcloud/docker#1150]
PHP mailparse is required by the files_frommail app. Installing it by hand in the container is a bit of a PITA, especially as it has to be done again after every update.

**Comment by joshtrichards** [comment]
Hi @sgofferj - Thanks for the report! 

See https://github.com/nextcloud/docker#adding-features if you wish to avoid installing it manually. 

It's not practical to add every dependency for every possible app to the default image, but it's quite possible to automate your own local customization which gets built from every official image update.

If this addresses your query, please close this Issue out. Thanks!

**Comment by sgofferj** [comment]
Apologies, I totally forgot about this issue. I am using an automated build process already for a while.
