### ISSUE TITLE
notification every 16 minutes

### ISSUE THREAD

**Issue by stefangweichinger** [nextcloud/docker#1156]
Image `nextcloud:18.0.6`, a new user was added to a group and gets a notification ala "You have been added to group X". OK so far, but that email is resent every 16 minutes ...

Why?

I recreated the container, ran "occ maintenance:repair" and even browsed the DB table `oc_notifications` for an event that maybe has to be rm-ed or so. Couldn't fix it so far.

Pls advise.

**Comment by joshtrichards** [comment]
Hi @stefangweichinger - Sorry you ran into this. As you discovered elsewhere (from the looks of it), this isn't a bug in the Docker image. I'm clearing out old Issues here. This repository is used for tracking Docker image specific bugs only.

If you agree this isn't relevant here, please close out this Issue. Thanks!

**Comment by joshtrichards** [comment]
As this matter is not related to the Docker image and already covered elsewhere, I'm closing it out.

See nextcloud/activity#459
