### ISSUE TITLE
tar: /opt/nextcloud/db/ib_logfile0: file changed as we read it

### ISSUE THREAD

**Issue by elmero1** [nextcloud/docker#1157]
I backup my docker setup with a backup script (compress the /opt directory with tar and encrypt with openssl). 
Now i got this message:
tar: /opt/nextcloud/db/ib_logfile0: file changed as we read it

Should I exclude the ib_logfile0? Or is this not a problem, when this file got changed through my backup script?

**Comment by doc75** [comment]
@elmero1 you should probably give more hint on your overall backup procedure, as it seems your DB might be modified during the backup.

It would allow to understand if you put your Nextcloud instance in maintenance mode or not for example.

**Comment by elmero1** [comment]
I have a backup script, which compress my /opt/nextcloud directory and encrypt this in a tar.gz file. docker-compose.yml, certs, backup, proxy, web are stored in the /opt/nextcloud directory.

With another backup script, I backup my nextcloud data directory (config & files) in the same way as the first one. 

Only during the first backup (/opt/nextcloud) I get the message:
tar: /opt/nextcloud/db/ib_logfile0: file changed as we read it

But Nextcloud works normally without any issues. Could the database be corrupted, should i scan the db? 

No, I don't put the Nextcloud instance in the maintenance mode. Is the maintenance mode necessary?

**Comment by doc75** [comment]
@elmero1 according to the [documentation](https://docs.nextcloud.com/server/18/admin_manual/maintenance/backup.html), it seems that this is recommended.

**Comment by doc75** [comment]
@elmero1 does the maintenance mode solved your issue ? If yes, then you should probably close this issue.

**Comment by J0WI** [comment]
This is not related to Nextcloud or Docker. You may have a look at https://stackoverflow.com/questions/20318852/tar-file-changed-as-we-read-it
