### ISSUE TITLE
Add sudo to image to run sudo -u www-data

### ISSUE THREAD

**Issue by mdupain** [nextcloud/docker#1159]
In Nextcloud sometimes you have to run the occ command on the terminal. This command can only be ran by the user www-data. In order to run it now I take the following steps:
apt update
apt install sudo
sudo -u www-data occ<somecommand>

It would be convenient if sudo was preinstalled.

**Comment by JonasAlfredsson** [comment]
Am I missing something, or can't you just run [docker exec](https://docs.docker.com/engine/reference/commandline/exec/) with `-u www-data`?

**Comment by mdupain** [comment]
I was missing something.
Normally you would not be able to run a shell using the www-data 
account. In docker apparently you can.
Thanks.

Met vriendelijke groet,
Marc Dupain

**Comment by JonasAlfredsson** [comment]
Excellent! 
Don't forget to close the issue if you are content with the solution.
