### ISSUE TITLE
how to disable update when starting up the service?

### ISSUE THREAD

**Issue by WisdomSky** [nextcloud/docker#1160]
We have a nextcloud fork with heavily modified core. Now nextcloud docker image relentlessly overwrites the core files we've modified. We're currently using version 18 and decided not to use 19.

**Comment by DatAres37** [comment]
I guess you can change the image from nextcloud:latest to a fixed version if that's what you're after?

**Comment by WisdomSky** [comment]
Hi @DatAres37 , that what I ended up doing. Thank you for your response anyway. :)
