### ISSUE TITLE
POSTGRES_USER and POSTGRES_PASSWORD are ignored

### ISSUE THREAD

**Issue by simeonschaub** [nextcloud/docker#1163]
To reproduce this, I just copied the example from `.examples/docker-compose/insecure/postgres/apache/`, filled in `POSTGRES_PASSWORD=foobar` in `db.env` and then did `docker-compose up -d`. I then opened `localhost:8080` in a browser and created a root account with username `abc`. If I now run `docker-compose exec app cat config/config.php`, I get the following output:
```php
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'ocdi90o4iymu',
  'passwordsalt' => 'jRbnJOxWaB1EPJOYrt+hnCyfPKRlog',
  'secret' => '2xX5ylw/9PacrHV0l/GFgeHHQV63wzvw/h3qMessEBhQgqfh',
  'trusted_domains' => 
  array (
    0 => 'localhost:8080',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'pgsql',
  'version' => '19.0.0.12',
  'overwrite.cli.url' => 'http://localhost:8080',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_abc',
  'dbpassword' => 'pfy6gao99be4gz175he0cfbwwyhi5i',
  'installed' => true,
);
```
So it seems like `POSTGRES_USER` and `POSTGRES_PASSWORD` get completely ignored and it tries to use a different user. This seems weird to me, since when I use `mariadb` instead of `postgresql`, `dbuser` and `dbpassword` get mapped to `MYSQL_USER` and `MYSQL_PASSWORD` just fine. Am I missing something fundamental here, or are these indeed omissions?

**Comment by doc75** [comment]
@simeonschaub I have an instance running with Postgres DB which is working fine and the `POSTGRES_USER` / `POSTGRES_PASSWORD` are not shown in the `config.php`. It seems that `POSTGRES_USER` and `POSTGRES_PASSWORD` are used for the installation procedure and then during this installation procedure a user derived from admin login is created with its own password.

**Comment by simeonschaub** [comment]
Ah, ok. Makes sense! I think I misdiagnosed an issue I had with my database container. I am using the BTRFS storage driver and I eventually fixed my problems by fixing the filesystem premissions.
