### ISSUE TITLE
Background Job not working for me.

### ISSUE THREAD

**Issue by Pushergene** [nextcloud/docker#1166]
Hey. I installed Nextcloud (apache mariadb insecure behind nginx reverse proxy). The Cron does run one time, then it doesnt (atleast it shows it so, it says "Last Job executed 2hours ago"). I already did docker-compose pull to get newest Version. The first issue with Background Job happened because i had Encryption module enabled (on VPS its important for me to have that module so please dont say that i should disable this module). The logs showed me that there are errors with /cron/  or similar, and with "nextcloud_hub.pdf (or so)". I removed all Nextcloud Files which were there before i did install the Module and i also removed them from trash. But now i get 0 log informations that (also not if there are errors). Nextcloud.log doesnt help much either. Could you fix that? Its literally a fresh reinstalled Nextcloud(first i had the fpm but because of the incompatibility with onlyoffice & collabora, i did completly purge all volumes, images  and so with system prune --volumes). So that error isnt much of my fault maybe because i enabled encryption module before removing the existing files from Nextcloud. So i think its more a general issue?

**Comment by Pushergene** [comment]
I have to mention that i have Onlyoffice with Document Server, and OnlyOffice has some trouble with AJAX Background Job(crashes).

**Comment by doc75** [comment]
@Pushergene you should probably post a docker-compose file that would enable to reproduce your issue. For me at least it is not clear how you launch the background job. So more details might help you getting an answer.

**Comment by Pushergene** [comment]
> @Pushergene you should probably post a docker-compose file that would enable to reproduce your issue. For me at least it is not clear how you launch the background job. So more details might help you getting an answer.

https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/insecure/mariadb/apache

**Comment by doc75** [comment]
@Pushergene , Any information on how you launch the background job ? It i not launched automatically in the container as far as I know.
Without more information we can only guess and your issue will probably not get any answer. Personally I am willing to try to help you, but I cannot afford to test and try without precise information on how to try to reproduce your issue.

**Comment by theniwo** [comment]
At first glance it looks like cron is not installed and thus cannot run any jobs in /var/spool/cron
