### ISSUE TITLE
w/ ONLYOFFICE Document Server

### ISSUE THREAD

**Issue by marfier** [nextcloud/docker#1173]
Could there be another option inside /.examples that sets up an ONLYOFFICE Document Server container to be used with Nextcloud using the plugin?

**Comment by edvinkuric** [comment]
Setting up an Onlyoffice Document Server is quite a task, especially if you want to run that as non-root.

NextCloud and OnlyOffice are independent setups, which require some needs to set up.

But you can check this links, maybe it helps you setting up OnlyOffice: https://github.com/ONLYOFFICE/Docker-DocumentServer

Once the OnlyOffice-Server is up and running, NC+OO can be "linked" via the nextcloud-onlyoffice-integration.

**Comment by GalacticLion7** [comment]
@edvinkuric I meant including the `onlyoffice/documentserver` Docker image in the Docker Compose configs of [.examples/docker-compose/](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose) and link them using the plugin. Yes, it will need root, but please note that you need root to run Docker at all, hence these configs.

**Comment by joshtrichards** [comment]
Currently this is outside the scope of this repository. We already have enough challenges keeping the standard examples up-to-date and applicable enough to the various ways people like to deploy things. :-)

You're always welcome to put together one and submit it has a PR for consideration for inclusion and/or post it in the How To section of the community help forum: https://help.nextcloud.com

In ~4 years this request has only had one upvote so it's not the best use of our resources at the moment. For now this is a "nice to have" so I'll close it.
