### ISSUE TITLE
When will NC 18 be moved into the production image ?

### ISSUE THREAD

**Issue by doc75** [nextcloud/docker#1174]
Hello,

Is there any rule to move to a new version in the production images ?
I thought that usually it move from stable to production around version x.0.3 or x.0.4
But for now we are at version 18.0.6 and production still contains version 17.

Any answer on the rules applied would be nice to know when this will occur.

**Comment by J0WI** [comment]
Fixed in https://github.com/nextcloud/docker/pull/1223
