### ISSUE TITLE
Versions not showing Onlyoffice changes

### ISSUE THREAD

**Issue by kowjens** [nextcloud/docker#1175]
Hi all,

I run NC with integrated Onlyoffice (documentserver_community: 0.1.7 + onlyoffice: 4.3.0 apps). Following  gives a short overview from `“settings->support->system report”`:

- Operating system: Linux 4.15.0-109-generic # 110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64
- Webserver: nginx/1.19.0 (fpm-fcgi)
- Database: mysql 10.2.14
- PHP version: 7.4.8
- Nextcloud version: 19.0.0 - 19.0.0.12

(didn’t want to blow up the topic with loaded modules/apps, but if needed I’ll add all)

However, I found two issues in NC Version 18 that still exist in V19 after updating. First if I open an office document inside the browser, change it and close it, the details button of no file in this directory is working anymore. This only happends if the file is changed. Reloading the page or folder changes back and fore make it work again. This is only a small but reproducible bug. 

More important, how I find, is that edited files are not considered in Versions at all! Under activity, it shows that the file has been changed by “remote user” after the cronjob was executed. I wonder if both, activity and versions interaction with OO could be optimized by adding an occ command after closing/ saving the file like “`occ files:scan –path=…`” or similar? But how the username can be passed to the office and back, I've no clue?

Maybe one of you faced this issue already or knows how it can be solved? Thanks in advance everybody!

Kind regards
Jens

**Comment by kowjens** [comment]
I opened this issue now at nextcloud server: [21927](https://github.com/nextcloud/server/issues/21927)
jfyi

**Comment by kesselb** [comment]
Closing in favour of #21927.
