### ISSUE TITLE
Allow specifiying admin user password as a hash

### ISSUE THREAD

**Issue by stackcoder** [nextcloud/docker#1182]
Consider specifying admin user credentials like its done with htpasswd. There should be no good reason to keep plaintext passwords inside a NextCloud container.

**Comment by J0WI** [comment]
The admin password is only used for `./occ maintenance:install --admin-pass "$NEXTCLOUD_ADMIN_PASSWORD"`. Of course Nextcloud hashes the password.

**Comment by stackcoder** [comment]
Currently the plaintext password is required to be stored within your docker deployment files (like Ansible, Terraform). I would like to hash the password before the nextcloud installer would do this.

**Comment by J0WI** [comment]
This repo is just for the Docker image. The feature you are requesting has to be implemented in https://github.com/nextcloud/server
