### ISSUE TITLE
404 when trying to update

### ISSUE THREAD

**Issue by waldner** [nextcloud/docker#1184]
Using the 19.0.0-fpm image, nginx as frontend with the recommended configuration (https://docs.nextcloud.com/server/19/admin_manual/installation/nginx.html). Going to the updater page returns a 404 error.
Is this expected?

**Comment by jheinitz** [comment]
Hello!
I faced the same issue and I simply pulled the new docker images and restarted my docker containers.
$ docker-compose pull
$ docker-compose up -d

Hopefull< this also works for you.

Regards

Jens

**Comment by waldner** [comment]
Yes, that's what I ended up doing too. However, a word on the issue from upstream to clarify what the expected behavior is would be nice.

**Comment by M4lik** [comment]
https://github.com/nextcloud/docker#update-to-a-newer-version
Just leaving this here 😉

The updated is purposely removed, so that you don't accidentally update NC without updating the actual docker image.

**Comment by andredaa** [comment]
https://github.com/nextcloud/docker/issues/1184

**Comment by BNolet** [comment]
Maybe there should be a page that goes there instead of a 404 so that folks who make issues like this, time after time, don't.
