### ISSUE TITLE
WSL: Your data directory is readable by other users  Please change the permissions to 0770 so that the directory cannot be listed by other users.

### ISSUE THREAD

**Issue by Slyke** [nextcloud/docker#1188]
I'm running NextCloud on Docker for Windows from within Ubuntu WSL. It seems that the umask is set to 0000 by default.

This means that even if I run `chmod -R 0770 ./html` on my data directory, any new file will still have the incorrect permissions.

I have tried running `chmod -R o+s ./html`, but it doesn't seem to do anything, and I have also tried `setfacl -d -m o::--- ./html`, but it errors with operation not permitted.

Is there any way to disable the permissions check, or have NextCloud automatically apply the correct permission with an env var or something?

**Comment by Slyke** [comment]
Hello, just checking if this is going to be looked at soon? It doesn't seem that complex for someone familiar with the code.

**Comment by tilosp** [comment]
there is this config option https://github.com/nextcloud/server/blob/c364b0cb193f66ad15e2950c27113b40037d1bf6/config/config.sample.php#L747-L757

**Comment by Slyke** [comment]
Nice!

**Comment by ced4568** [comment]
> there is this config option https://github.com/nextcloud/server/blob/c364b0cb193f66ad15e2950c27113b40037d1bf6/config/config.sample.php#L747-L757

so one want to point me in the direction of how to add this?

**Comment by naickercuan** [comment]
Worked, thanks!

**Comment by Welved** [comment]
I am having this exact same issue, but I have nextcloud running under docker (portainer) on a raspberrypi. I've tried chmod and chown, with chown giving me a **You are not allowed!** error, I have even tried it via the actual root user. I've also tried this solution laid out, it doesn't work.
