### ISSUE TITLE
PHP Fatal error:  Allowed memory size of x bytes exhausted

### ISSUE THREAD

**Issue by mateusz446** [nextcloud/docker#1189]
Hey, after fresh docker setup, adding a local storage with lots of images and running command on host machine:

`docker exec --user www-data nextcloud2 php occ preview:generate-all -vvv`

I can see some previews generated but after a couple of the I get en error:

`PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 12942784 bytes) in /var/www/html/lib/private/legacy/OC_Image.php on line 649`

As you can see my memory_limit is 4GB and it can't even allocate 12MB.

My docker-compose.yml:

>version: '3.7'
services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud2
    ports:
      - 889:80
    environment:
      - MYSQL_DATABASE=xxx
      - MYSQL_USER=xxx
      - MYSQL_PASSWORD=xxx
      - MYSQL_HOST=nextcloud-mariadb2
      - NEXTCLOUD_TABLE_PREFIX=oc_
      - NEXTCLOUD_ADMIN_USER=xxx
      - NEXTCLOUD_ADMIN_PASSWORD=xxx
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.0.122 nextcloud2.domain.com
      - REDIS_HOST=nextcloud-redis-bitnami2
      - REDIS_HOST_PORT=6379
      - REDIS_HOST_PASSWORD=345794761478394357
      - OVERWRITEPROTOCOL=https
      - TRUSTED_PROXIES=traefik
    volumes:
      - /mnt/2TB/nextcloud/data2:/var/www/html
      - /mnt/2TB/nextcloud/shared_photos:/media/shared_photos
      - ./php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud2.rule=Host(`nextcloud2.domain.com`)"
      - "traefik.http.routers.nextcloud2.entrypoints=websecure"
      - "traefik.http.routers.nextcloud2.tls.certresolver=myresolver"
      - "traefik.http.services.nextcloud2.loadbalancer.server.port=80"
      - "traefik.http.routers.nextcloud2.middlewares=nextcloud2-headers, nc2-rep"
    networks:
      - docker-tools_traefik
  mariadb:
    container_name: nextcloud-mariadb2
    image: mariadb:10.5.4-focal
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
      - MYSQL_PASSWORD=xxx
      - MYSQL_DATABASE=xxx
      - MYSQL_USER=xxx
    volumes:
      - /home/xxx:/var/lib/mysql
    networks:
      - docker-tools_traefik
  redis:
    image: 'bitnami/redis:6.0.5'
    container_name: nextcloud-redis-bitnami2
    restart: always
    environment:
      - REDIS_PASSWORD=xxx
    ports:
      - 6380:6379
    networks:
      - docker-tools_traefik
networks:
  docker-tools_traefik:
    external: true

My php.ini:

    memory_limit=4G
    upload_max_filesize=4G
    post_max_size=5G

Steps to reproduce

    Create docker-compose.yml from example provided with changed personal information.
    Create php.ini  from example provided.
    run on host docker-compose up
    Install nextcloud apps: external storage and preview generator.
    Mount external storage with pictures.
    run on host docker exec --user www-data nextcloud2 php occ preview:generate-all -vvv

Expected behaviour

    Previews are generated normally for all pictures.

Tell us what happens instead

    After couple of generated thumbnails I get en error:
    PHP Fatal error:  Allowed memory size of 4294967296 bytes exhausted (tried to allocate 12942784 bytes) in /var/www/html/lib/private/legacy/OC_Image.php on line 649

Server configuration

    Docker: 
    Client: Docker Engine - Community
    Version:           19.03.12
    API version:       1.40
    Go version:        go1.13.10
    Git commit:        48a66213fe
    Built:             Mon Jun 22 15:45:36 2020
    OS/Arch:           linux/amd64
    Experimental:      false

Operating system:

    Ubuntu 18.04.4 LTS

Web server:

    Default from nextcloud docker

Database:

    mariadb:10.5.4-focal

PHP version:

    Default from nextcloud docke

Nextcloud version:

    19.0.1

Updated from an older Nextcloud/ownCloud or fresh install:

    fresh install

Where did you install Nextcloud from:

    Docker

Signing status:
Signing status

List of activated apps:

    Default ones
    External storage support 1.10.0 Featured
    Preview Generator 2.3.0 

Nextcloud configuration:

    root@99ba7a7e510e:/var/www/html# cat config/config.php 
    <?php
    $CONFIG = array (
      'htaccess.RewriteBase' => '/',
      'memcache.local' => '\\OC\\Memcache\\APCu',
      'apps_paths' => 
      array (
        0 => 
        array (
          'path' => '/var/www/html/apps',
          'url' => '/apps',
          'writable' => false,
        ),
        1 => 
        array (
          'path' => '/var/www/html/custom_apps',
          'url' => '/custom_apps',
          'writable' => true,
        ),
      ),
      'memcache.distributed' => '\\OC\\Memcache\\Redis',
      'memcache.locking' => '\\OC\\Memcache\\Redis',
      'redis' => 
      array (
        'host' => 'nextcloud-redis-bitnami2',
        'password' => 'xxx',
        'port' => 6379,
      ),
      'overwriteprotocol' => 'https',
      'trusted_proxies' => 
      array (
        0 => 'traefik',
      ),
      'passwordsalt' => 'xxx',
      'secret' => 'xxx',
      'trusted_domains' => 
      array (
        0 => 'localhost',
        1 => '192.168.0.122',
        2 => 'nextcloud2.domain.com',
      ),
      'datadirectory' => '/var/www/html/data',
      'dbtype' => 'mysql',
      'version' => '19.0.1.1',
      'overwrite.cli.url' => 'https://localhost',
      'dbname' => 'nextcloud',
      'dbhost' => 'nextcloud-mariadb2',
      'dbport' => '',
      'dbtableprefix' => 'oc_',
      'mysql.utf8mb4' => true,
      'dbuser' => 'xxx',
      'dbpassword' => 'xxx',
      'installed' => true,
      'instanceid' => 'oc6cao4eved7',
    );

Are you using external storage, if yes which one: local/smb/sftp/...

    local for photos

Are you using encryption: yes/no

    no

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...

    no

Client configuration
Browser:
Operating system:

Logs

Web server error log
Web server error log
Nextcloud log (data/nextcloud.log)

        {"reqId":"s7RiP3hQEIRMD9O3yKye","level":3,"time":"2020-07-23T10:12:04+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"index","method":"GET","url":"/apps/accessibility/js/accessibility?v=0","message":{"Exception":"OCP\\Files\\NotPermittedException","Message":"Could not create folder","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Files/AppData/AppData.php","line":157,"function":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->","args":["icons"]},{"file":"/var/www/html/lib/private/Template/IconsCacher.php","line":90,"function":"newFolder","class":"OC\\Files\\AppData\\AppData","type":"->","args":["icons"]},{"function":"__construct","class":"OC\\Template\\IconsCacher","type":"->","args":[{"__class__":"OC\\Log"},{"__class__":"OC\\Files\\AppData\\Factory"},{"__class__":"OC\\URLGenerator"},{"__class__":"OC\\AppFramework\\Utility\\TimeFactory"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":84,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[[{"__class__":"OC\\Log"},{"__class__":"OC\\Files\\AppData\\Factory"},{"__class__":"OC\\URLGenerator"},{"__class__":"OC\\AppFramework\\Utility\\TimeFactory"}]]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OC\\Template\\IconsCacher","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OC\\Template\\IconsCacher"]},{"file":"/var/www/html/lib/private/ServerContainer.php","line":149,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OC\\Template\\IconsCacher",true]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":388,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OC\\Template\\IconsCacher",true]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":71,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OC\\Template\\IconsCacher",true]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Accessibility\\Controller\\AccessibilityController","__class__":"ReflectionClass"}]},{"file":"/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Accessibility\\Controller\\AccessibilityController"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":414,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Accessibility\\Controller\\AccessibilityController"]},{"file":"/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":385,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Accessibility\\Controller\\AccessibilityController"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":124,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Accessibility\\Controller\\AccessibilityController"]},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Accessibility\\Controller\\AccessibilityController","getJavascript",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"accessibility.accessibility.getJavascript"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"accessibility.accessibility.getJavascript"}]},{"file":"/var/www/html/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"accessibility.accessibility.getJavascript"}]},{"file":"/var/www/html/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/accessibility/js/accessibility"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Files/Node/Folder.php","Line":165,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":"19.0.1.1"}
    {"reqId":"f6ZPjrxSB2N1gt3doUjm","level":3,"time":"2020-07-23T10:12:27+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin_admin","app":"index","method":"GET","url":"/apps/theming/img/core/filetypes/application-pdf.svg?v=0","message":{"Exception":"OCP\\Files\\NotPermittedException","Message":"Could not create folder","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Files/AppData/AppData.php","line":157,"function":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->","args":["0"]},{"file":"/var/www/html/apps/theming/lib/ImageManager.php","line":159,"function":"newFolder","class":"OC\\Files\\AppData\\AppData","type":"->","args":["0"]},{"file":"/var/www/html/apps/theming/lib/ImageManager.php","line":174,"function":"getCacheFolder","class":"OCA\\Theming\\ImageManager","type":"->","args":[]},{"file":"/var/www/html/apps/theming/lib/Controller/IconController.php","line":91,"function":"getCachedImage","class":"OCA\\Theming\\ImageManager","type":"->","args":["icon-core-filetypes_application-pdf.svg"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"getThemedIcon","class":"OCA\\Theming\\Controller\\IconController","type":"->","args":["core","filetypes/application-pdf.svg"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Theming\\Controller\\IconController","getThemedIcon",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"app":"core","image":"filetypes/application-pdf.svg","_route":"theming.Icon.getThemedIcon"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"app":"core","image":"filetypes/application-pdf.svg","_route":"theming.Icon.getThemedIcon"}]},{"file":"/var/www/html/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"app":"core","image":"filetypes/application-pdf.svg","_route":"theming.Icon.getThemedIcon"}]},{"file":"/var/www/html/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/theming/img/core/filetypes/application-pdf.svg"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Files/Node/Folder.php","Line":165,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":"19.0.1.1"}
    {"reqId":"3jsKueD9nUzz4bfkUxhg","level":3,"time":"2020-07-23T10:12:27+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin_admin","app":"index","method":"GET","url":"/apps/theming/img/core/filetypes/folder.svg?v=0","message":{"Exception":"OCP\\Files\\NotPermittedException","Message":"Could not create folder","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Files/AppData/AppData.php","line":157,"function":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->","args":["0"]},{"file":"/var/www/html/apps/theming/lib/ImageManager.php","line":159,"function":"newFolder","class":"OC\\Files\\AppData\\AppData","type":"->","args":["0"]},{"file":"/var/www/html/apps/theming/lib/ImageManager.php","line":174,"function":"getCacheFolder","class":"OCA\\Theming\\ImageManager","type":"->","args":[]},{"file":"/var/www/html/apps/theming/lib/Controller/IconController.php","line":91,"function":"getCachedImage","class":"OCA\\Theming\\ImageManager","type":"->","args":["icon-core-filetypes_folder.svg"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"getThemedIcon","class":"OCA\\Theming\\Controller\\IconController","type":"->","args":["core","filetypes/folder.svg"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Theming\\Controller\\IconController","getThemedIcon",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"app":"core","image":"filetypes/folder.svg","_route":"theming.Icon.getThemedIcon"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"app":"core","image":"filetypes/folder.svg","_route":"theming.Icon.getThemedIcon"}]},{"file":"/var/www/html/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"app":"core","image":"filetypes/folder.svg","_route":"theming.Icon.getThemedIcon"}]},{"file":"/var/www/html/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/theming/img/core/filetypes/folder.svg"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Files/Node/Folder.php","Line":165,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":"19.0.1.1"}
    {"reqId":"sBNZegK1F7KfkXCZ98Kd","level":3,"time":"2020-07-23T10:16:47+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Allowed memory size of 4294967296 bytes exhausted (tried to allocate 12942784 bytes) at /var/www/html/lib/private/legacy/OC_Image.php#649","userAgent":"--","version":"19.0.1.1"}

Nextcloud log
Browser log
Browser log

**Comment by broetchenrackete36** [comment]
I have the same problem and there are other reports at the previewgenerator github project too ([High memory usage](https://github.com/rullzer/previewgenerator/issues/194) and [Possible memory leak](https://github.com/rullzer/previewgenerator/issues/195)). According to @rullzer it's not a problem with the previewgenerator app but nextcloud itself.

**Comment by lifesbest23** [comment]
There is a pullrequest to fix that in the nextcloud server repository.

**Comment by J0WI** [comment]
Fixed upstream
