### ISSUE TITLE
Nextcloud Image not in Storage Category on Docker Hub

### ISSUE THREAD

**Issue by tilosp** [nextcloud/docker#1191]
https://hub.docker.com/search?q=&type=image&category=storage

@tianon @yosifkit Do you have a way to edit the categories or know where the current ones come from?

cc: @nc-ruppdi

**Comment by tianon** [comment]
Unfortunately, that's not something we've had any influence in or control over -- I think https://github.com/docker/roadmap/issues/76 is the best place to add your thumbs up / subscribe.

**Comment by joshtrichards** [comment]
It's there now. I think we can close this Issue. :)
