### ISSUE TITLE
Face Recognition

### ISSUE THREAD

**Issue by iamklaus** [nextcloud/docker#1195]
Hey guys,

this docker file does not support the Face Recognition app. Any plans to integrate the dependencies here?

https://apps.nextcloud.com/apps/facerecognition

The installation of the app works, but you can't enable it because of this message:

This app cannot be installed because the following dependencies are not fulfilled:
The library pdlib is not available.
The library bz2 is not available.

Cheers,
Klaus

**Comment by JuniorJPDJ** [comment]
Just create your own Dockerfile with FROM pointing on this images.
Adding deps for every possible app to generic docker image is bad idea.

**Comment by J0WI** [comment]
Some examples for additional functionality can be found here: https://github.com/nextcloud/docker/tree/master/.examples

**Comment by spupuz** [comment]
i have the same problem of op but do not understood how to integrate face recognition

**Comment by iamklaus** [comment]
Hey guys,

try this docker file: https://github.com/iamklaus/nextcloud

I've put everything from different sources together and it work for me nicely. I hope it works for you, too.

Regards,
Klaus

**Comment by spupuz** [comment]
> Hey guys,
> 
> try this docker file: https://github.com/iamklaus/nextcloud
> 
> I've put everything from different sources together and it work for me nicely. I hope it works for you, too.
> 
> Regards,
> Klaus

Hi Klaus sorry to bother you i'm a little bit noob, can i ask you a little bit more of explaination, since i have my already deployed nextcloud container stack (no "production data" yet) how do i have to proceed?

**Comment by iamklaus** [comment]
You can use that docker hub, I have published ithere: https://hub.docker.com/r/iamklaus/nextcloud

**Comment by crywolf203** [comment]
@iamklaus Thanks! even got it to work on Unraid thanks to you!

**Comment by DevilsDesigns** [comment]
@iamklaus does this work as a docker mod. Ive been trying to implement this but theres not really any detailed instructions. Could you specify how to install and run the docker container in your github/dockerhub

**Comment by iamklaus** [comment]
@DevilsDesigns I haven't worked with docker mods, yet. So, I'm not sure if it is compatible
 with it or not.

**Comment by DevilsDesigns** [comment]
@iamklaus  I keep getting this error when writing just your github. First off of you have one working with alpine fpm installs. As well what would need to get edited to have that working. Also I keep getting this error currently trying to install your repo. It succesfully installs but I get this error in logs. https://pastebin.com/HxJz551F

**Comment by ACarolan** [comment]
> 
> 
> @iamklaus Thanks! even got it to work on Unraid thanks to you!

How did you get it to work in unraid?

**Comment by ACarolan** [comment]
> 
> 
> @iamklaus Thanks! even got it to work on Unraid thanks to you!

How did you get it to work in unraid? 

> 
> 
> > @iamklaus Thanks! even got it to work on Unraid thanks to you!
> 
> How did you get it to work in unraid?

Nevermind, got it working by installing the Official Nextcloud container from CA, letting it install, then switching the repo to my fork of iamklaus/nextcloud (for more memory, I have plenty on my Unraid server). Facial recognition, reverse proxy, and everything else working like a charm!

**Comment by mrishab** [comment]
In case a newer version is needed, I set up a new dockerfile containing the needed the dependencies: https://github.com/mrishab/anton-apps/blob/master/nextcloud/Dockerfile

This is based on the official dockerfile for docker setup provided on the [facerecognition installation doc](https://github.com/matiasdelellis/facerecognition/wiki/Docker). It needed doing bug fixes. The docker-compose is also available in the folder.

**Comment by mrishab** [comment]
Hey guys, I have recently started blogging my indie-hacker journey.. have created a post about the nextcloud docker file that includes the dependencies for setting up face recognition. Sharing it here in case somebody wants to have a deeper look: https://mrishab.io/ghost/#/editor/post/66d528bd42edd00001d3293c

**Comment by NL-TCH** [comment]
hi @mrishab can you update your repo for nextcloud 31.0.0?
