### ISSUE TITLE
Wrong installation when using NEXTCLOUD_ADMIN_USER

### ISSUE THREAD

**Issue by gwisp2** [nextcloud/docker#1204]
Automatic installation with set NEXTCLOUD_ADMIN_USER is not working properly.
Failure example: [repository](https://github.com/gwisp2/NextcloudBugEnvironment).

NEXTCLOUD_ADMIN_USER=gwisp
POSTGRES_USER=nextcloud_user

In logs it can be seen that database tables are created by _nextcloud_user_ and when handling requests they are accessed by _oc_gwisp_ user causing permission errors. In normal installation (when credentials are entered via browser) everything is ok because tables are created with _oc_gwisp_ user.

```
db_1         | 2020-08-19 22:13:35.270 GMT [58] [oc_gwisp, nextcloud_db]ERROR:  permission denied for table oc_appconfig
db_1         | 2020-08-19 22:13:35.270 GMT [58] [oc_gwisp, nextcloud_db]STATEMENT:  SELECT * FROM "oc_appconfig"
```

**Comment by JustinGuese** [comment]
Same running docker 
Works with Postgre 11, but not with the latest release

**Comment by kwisatz** [comment]
I'm seeing the same thing, but in our case, a `docker-compose down -v` didn't resolve the issue. 

We investigated and found that the user written to `config.php` is actually not the one defined by the POSTGRES_USER environment variable, but instead `oc_nextcloud`.


This is in image `d02b2bb3e283` while `c664af0d9c67` still seems to be working fine.

**Comment by kwisatz** [comment]
I'm seeing this and I'm wondering whether nextcloud isn't attempting to install the DB too early, fails and then decides to use a default username/password combination instead.

```
Initializing nextcloud 20.0.8.1 ...
Initializing finished
New nextcloud instance
Installing with PostgreSQL database
starting nextcloud installation
PostgreSQL username and/or password not valid
 -> You need to enter details of an existing account.
retrying install...
Nextcloud was successfully installed
```

**Comment by JustinGuese** [comment]
Hey,
yes it is definitely a problem with PostgreSQL, it worked way better when I used a MariaDB image. I found some other threads complaining about PostgreSQL performance with Nextcloud, even though I can't link it rn.

**Comment by gzm0** [comment]
> I'm wondering whether nextcloud isn't attempting to install the DB too early

I can confirm that for me, bringing only the DB up (`docker-compose up <db-service-name>`) waiting (look at `docker logs <db-container>`) and then the app fixed the issue for me.

**Comment by zimmertr** [comment]
Using Kubernetes I'm seeing the same issue. I have added an init-container that prevents Nextloucd from starting until pg_wait responds that the database is connectable but it is still happening.

**Comment by lumbo7332** [comment]
Any updates on this? The latest `mariadb` image is also broken with Nextcloud, so this is kind of the only option if you don't want to keep MariaDB pinned at an old version.

**Comment by goranskular** [comment]
I also struggled with this.. solution was to let DB to initialize first and then run all other containers:
```
$ docker compose up --no-start -d
$ docker compose start nextcloud-app-1
$ docker logs nextcloud-db-1 -f 
.... wait ....
$ docker compose start
```

**Comment by joshtrichards** [comment]
If this is still happening, it's an upstream (`server`) matter. If there's some scenario where the failure/retry logic in the Nextcloud Installer isn't working in a reasonable way, it'll need to get addressed there.

The POSTGRES_USER is only used by the Nextcloud installer to create the `oc_BLAH` account then the installer saves the newly created account info to the `config.php` and closes the db connection. At that point it reconnects using the newly created dedicated non-admin credentials.

https://docs.nextcloud.com/server/latest/admin_manual/installation/installation_wizard.html#database-choice

This all happens *within* the Nextcloud installer. It's not something under the Docker image's control.

The closest upstream issue I see is nextcloud/server#38749. That at least looks a bit like the situation reported by @kwisatz, @gzm0, @goranskular 

That all said, I can't reproduce this behavior. I have a test PG15 stack that seems okay.
