### ISSUE TITLE
pb of authentication when app password, 2FA and LDAP.

### ISSUE THREAD

**Issue by Sellig28** [nextcloud/docker#1229]
Hi,

I am with nextcloud 19.0.2.2 in a FPM container. with nginx, postgres and openldap in container too.

My ldap credential access is working, with 2FA when used with web browser.

But When I want ot use app password for nextcloud client it's ldap who is requesting ! see below:

{"reqId":"kenuxW2Dus6eylc3757n","level":2,"time":"2020-08-29T16:05:23+00:00","remoteAddr":"XX.XX.XX.XX","user":"--","app":"user_ldap","method":"POST","url":"/login","message":"Bind failed: 49: Invalid credentials","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36","version":"19.0.2.2"}

{"reqId":"kenuxW2Dus6eylc3757n","level":2,"time":"2020-08-29T16:05:24+00:00","remoteAddr":"XX.XX.XX.XX","user":"--","app":"no app in context","method":"POST","url":"/login","message":"Login failed: toto (Remote IP: XX.XX.XX.XX)","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36","version":"19.0.2.2"}

It seems app password is broken.

Ho,  I use TOTP for that.

I saw some persons with that problem but don't find an issue in github.

**Comment by Sellig28** [comment]
Sorry, we can close this issue. 

But it will be usefull for others. Nextcloud use flow v2 api. so nom ore password app when the app used has flow capabilities.

My android app and desktop appimage is working now by just using flow v2.

For others nomarl work is:

- I connect to app
- I put my url
- in freshly open web browser, I put my user and password
- I put my TOTP number
- then I can access to client or app.

The error was to try to put a password app for the user.

**Comment by Sellig28** [comment]
A humm too fast client desktop is no more connected. It seems that we are between app password and flow v2 but not ready yet with ldap an 2FA.

**Comment by joshtrichards** [comment]
Hi @Sellig28 - Hopefully you figured out a full solution and/or found one through another channel. 

This channel is for reporting bugs in the community Docker image. The best channel for follow-up on configuration matters and general troubleshooting assistance is the [Nextcloud Help Forum](https://help.nextcloud.com).

Since this issue is >3 years old and isn't specific to the community Docker image I'm going to close it out.
