### ISSUE TITLE
Internalization (maybe) prevent nextcloud from loading app pages/settings

### ISSUE THREAD

**Issue by tzerber** [nextcloud/docker#1237]
Hello,
after a docker-compose pull i started getting a lot of errors like this when trying to open any app (and system logs for that matter) and my browser was full of 502's on nearly all svg's and ico's

```
proxy_1                  | nginx.1    | 2020/09/04 07:20:00 [error] 111#111: *15 no live upstreams while connecting to upstream, client: MY-IP, server: SERVER_URL, request: "GET /apps/logreader/get?offset=0&count=50&levels=00111 HTTP/1.1", upstream: "http://SERVER_URL/apps/logreader/get?offset=0&count=50&levels=00111", host: "SERVER_URL"
proxy_1                  | nginx.1    | 2020/09/04 07:22:39 [error] 111#111: *49 upstream prematurely closed connection while reading response header from upstream, client: MY-IP, server: SERVER_URL, request: "GET /apps/settings/l10n/bg.js?v=2fd61271 HTTP/1.1", upstream: "http://172.26.0.3:80/apps/settings/l10n/bg.js?v=2fd61271", host: "SERVER_URL"
proxy_1                  | nginx.1    | 2020/09/04 07:23:38 [error] 111#111: *65 no live upstreams while connecting to upstream, client: MY-IP, server: SERVER_URL, request: "GET /apps/notifications/img/notifications-new.svg HTTP/1.1", upstream: "http://SERVER_URL/apps/notifications/img/notifications-new.svg", host: "SERVER_URL"
proxy_1                  | nginx.1    | 2020/09/04 07:27:08 [error] 110#110: *68 no live upstreams while connecting to upstream, client: MY-IP, server: SERVER_URL, request: "GET /core/img/clients/phone.svg HTTP/1.1", upstream: "SERVER_URL/core/img/clients/phone.svg", host: "SERVER_URL"

```
MY-IP is my real IP address and SERVER_URL is the domain name(not IP) of my server.

Running HTTPS with letsencrypt, and for the past hour debugging i can say it does this only on apps or settings pages while sync from pc/mobile and browsing files with a browser(firefox latest) works fine. With a lot of pain i managed to switch to English from the menu, and svg-s started to load and pages to function. Language i had set is Bulgarian. I can provide more logs if needed.

**Comment by joshtrichards** [comment]
Hi @tzerber - Sorry you ran into difficulties. From the looks of it this would be a Nextcloud issue, not an Docker image issue. I realize this is an older Issue, but I'm trying to clean things up a bit. If you're still experiencing this, I suggest either posting  a query on the [Nextcloud Help Forum](https://help.nextcloud.com) or checking for/submitting a bug report at https://github.com/nextcloud/server

If you agree with my assessment, please close this Issue out here. Thanks!

**Comment by tzerber** [comment]
Very well timed, but i understand. Closing this.

**Comment by tzerber** [comment]
.
