### ISSUE TITLE
Files/Settings: wrong WebDAV url suggestion

### ISSUE THREAD

**Issue by andriy-f** [nextcloud/docker#1239]
Hi,

![image](https://user-images.githubusercontent.com/1040440/92361851-ba375c00-f0f7-11ea-9590-a734b28ffa60.png)

Files/Settings/WebDAV url suggestion shows url with http instead of https even though I use https to access NC server
This is due to `fastcgi_param HTTPS on;` line commented out in https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/web/nginx.conf (and other nginx.conf files in examples)

**Comment by joshtrichards** [comment]
That config file is for the web server and is expected to be used with a reverse proxy container (where the TLS termination generally would take place). I don't believe we even have a full config file for the `proxy`. Sounds like you tried to configure the web container as a reverse proxy as well (which is fine).

In any case, this is an old issue so I'm going to close it out.
