### ISSUE TITLE
Administration/overview/Security & setup warnings about cardav/caldav

### ISSUE THREAD

**Issue by andriy-f** [nextcloud/docker#1240]
Page Administration/overview/ (<NC server>/settings/admin/overview) shows warnings in Security & setup warnings section related to caldav/cardav if port is added to https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/web/nginx.conf,

i.e: this section generates warnings:
```
 location = /.well-known/carddav {
            return 301 $scheme://$host:$server_port/remote.php/dav;
        }

        location = /.well-known/caldav {
            return 301 $scheme://$host:$server_port/remote.php/dav;
        }
```

But changing it to this (by removing :$server_port):
```
 location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
        }

        location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
        }
```

Makes warnings disappear

**Comment by joshtrichards** [comment]
Duplicate of #927 
(and since fixed)
