### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by Spilarix** [nextcloud/docker#1255]
While browsing the web interface, since 19.0.0 RC3 (not previous versions), the error log is generating issues like :
`Trying to access array offset on value of type bool at /var/www/html/console.php#69`
In log file : `"level":3,"time":"2020-10-01T09:15:24+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type bool at /var/www/html/console.php#69","userAgent":"--","version":"19.0.1.1"`

Sometimes I can see some other files referenced for the same bug like cron.php#99. I can say it's the same bug because the line of code seems identical :
	`if ($user['name'] !== $configUser['name']) {`

**Steps to reproduce**

Browse the web interface or check logs.

**Server configuration**
Docker : last version
Web server : nginx
Database: PostgreSQL

**Comment by Spilarix** [comment]
After comparisons of code between RC2 and >=RC3, it seems to be related to the upgrade of PHP-FPM from 7.3 to 7.4 and the fact that I'm using a specific user in my docker-compose, using the "user" option.
Does anyone found a workaround other than rebuilding an image with PHP-FPM 7.3 or has an idea to fix this issue ?

**Comment by M4lik** [comment]
Have you tried to use the latest patch of NC 19? I mean, is there a specific reason, why you use a release candidate, instead of the stable versions (e.g one of these tags: `19.0.3-apache, 19.0-apache, 19-apache, stable-apache, production-apache, 19.0.3`)?

**Comment by Spilarix** [comment]
> 
> 
> Have you tried to use the latest patch of NC 19? I mean, is there a specific reason, why you use a release candidate, instead of the stable versions (e.g one of these tags: `19.0.3-apache, 19.0-apache, 19-apache, stable-apache, production-apache, 19.0.3`)?

Yes of course, the problem is on all versions since 19.0.0 RC3 which is the first version with a Dockerfile using PHP FPM 7.4.
A pull request in nextcloud/server about another issue should fix the problem : #23158

However, I hoped somesone found another solution that I could use now.

**Comment by Spilarix** [comment]
Mainly fixed by https://github.com/nextcloud/server/pull/23436
