### ISSUE TITLE
Hiding index.php in URL for Nginx

### ISSUE THREAD

**Issue by kunago** [nextcloud/docker#126]
Could anyone please give me a hint how to modify the nginx.conf in examples so I am able to hide the _index.php_ in the URL when using Nginx? I tried to get some inspiration from the official Nextcloud 12 docs but could not achieve it.

**Comment by SnowMB** [comment]
That's on my list for a long time now. If you find a solution please let me know 😄

**Comment by tilosp** [comment]
Take a look at https://docs.nextcloud.com/server/12/admin_manual/installation/nginx.html

**Comment by kunago** [comment]
@tilosp Thanks, I tried that but whatever has anything to do with index.php does not hide it. So I am not sure whether the standard config file can be used. I also wonder why is the documented config so different from the one in this repo.

**Comment by kunago** [comment]
@tilosp: I rewrited all the locations according to the documented nginx.conf file and it started working. It seems the magic was in the ".php" section where there were some lines missing.

If you are interested, see this config file which is working for me: https://pastebin.com/BYeypvis
