### ISSUE TITLE
Security Check scan show wrong info

### ISSUE THREAD

**Issue by pheiduck** [nextcloud/docker#1261]
Running Nextcloud Version is wrong
And Latest Patch Level is not detected 
See screenshot 
![](https://media.discordapp.net/attachments/751529171871858788/763001722578272266/image0.jpg)

**Comment by pheiduck** [comment]
Running version ☑️

![E518379B-5A72-416E-BC7F-0CA77BA33413](https://user-images.githubusercontent.com/47042125/95302990-effc6b80-0882-11eb-8641-7f8f0d16ed24.jpeg)

**Comment by tilosp** [comment]
This is a problem with scan.nextcloud.com and unrelated to this docker image.
