### ISSUE TITLE
IRQL NOT LESS OR EQUAL (bsod error) each time on installing Docker on Windows 10 Home

### ISSUE THREAD

**Issue by debmaj2** [nextcloud/docker#1265]
I am facing a IRQL_NOT_LESS_OR_EQUAL BSOD Error each time I'm trying to install Docker on my Windows 10 Home PC.

What could be a possible reason?

P.S. I have WSL 2 and Windows 10 2004, both working without usual crashes, except the aforementioned.

**Comment by maxcodeshere** [comment]
Why would this be an issue with Nextcloud? 
A quick Google search showed me that this happens with a variety of containers on windows. Docker or Windows Support docs would be the most likely places to find help.

**Comment by M4lik** [comment]
as @maxcodeshere said, this is a docker issue. please close this issue.

@maxcodeshere : some people search for somthing like  "docker github problems" or somthing simmilar, and find this repo, and as its name is just "docker" think, that this is the repo for docker. strange SEO i guess...

**Comment by debmaj2** [comment]
I realise it now. SEO at its misleading best.

**Comment by windisklessfree** [comment]
https://windisklessfree.github.io/IRQL_NOT_LESS_OR_EQUAL/
