### ISSUE TITLE
Stable and production images should be different

### ISSUE THREAD

**Issue by doc75** [nextcloud/docker#1266]
@tilosp  you recently modified the images by merging the stable and production images (see https://github.com/nextcloud/docker/pull/1253).

I consider that it was useful, for people willing to wait for version to be quite stable, to stick to the production image which was one version behind the stable.

Would it be possible to get back to this split when stable is moving to NC20 (to avoid a step back in version for users of production image) ?

I am ready to push this as a PR, but want to be sure this will be accepted.

**Comment by tilosp** [comment]
It was not my decision, the core team discontinued the production release channel here https://github.com/nextcloud/updater_server/pull/403
And I want to keep the tags in sync with the official release channels, to avoid confusion.

> I consider that it was useful, for people willing to wait for version to be quite stable, to stick to the production image which was one version behind the stable.

Well that wasn't always the case, there where quite a few times in the past where the production and stable tag pointed to the same version.

I am sorry, but the `production` tag should point to the same version that the production release channel uses.
If you want a version older than `latest` and `stable` you can always pin to a major version of your choosing using the corresponding tags.

**Comment by doc75** [comment]
@tilosp, thanks for this clear explanation on the reason for the choice. That makes perfect sense.
