### ISSUE TITLE
desktop client lost connection during sync multiple times + possible solution

### ISSUE THREAD

**Issue by flower1024** [nextcloud/docker#1269]
Hello,

i use "https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm" + redis and got very many connection losses during sync.

i solved it by adding "fastcgi_buffering off;" to nginx.conf.

as a downside it keeps the fpm process alive longer - esp for bigger files. maybe its a good idea to raise their cound in bigger installations too.

**Comment by joshtrichards** [comment]
That would be something to take up with NC Server / NC Server Documentation since that's what the examples are modeled after:

https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

Though considerably more context would be needed to justify the change.
