### ISSUE TITLE
nextcloud is unable to access mariadb

### ISSUE THREAD

**Issue by xpseudonym** [nextcloud/docker#1271]
This seems to be a very common problem from a quick search.

If I can access the db from mysql then it seems reasonable I should be able to access the db from nextcloud with the same credentials.

Copied below output from mysql and attached login screenshot from nextcloud:
```
# mysql -u mariadb -ppassword --host=localhost --protocol=tcp --port=3306 mariadb
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 9
Server version: 5.5.5-10.5.6-MariaDB-1:10.5.6+maria~focal mariadb.org binary distribution

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit
Bye
#
```

![Screenshot_2020-10-13 Nextcloud](https://user-images.githubusercontent.com/5032475/95891707-5d296880-0d7d-11eb-984b-e6acb95ba372.png)

**Comment by M4lik** [comment]
Please provide your configuration. Without it is very hard do help you with your problem.
But what i can see, is that your mariadb host is wrong. When you use the docker image, you need to provide a, from the container's view, "external" database host, so probably your host machine.

**Comment by J0WI** [comment]
`localhost` is your nextcloud container. Just use the name of your (linked) database container.
