### ISSUE TITLE
Зависает при первом входе

### ISSUE THREAD

**Issue by extreen** [nextcloud/docker#1274]
При первом входе в браузере после ввода логина и пароля зависает.
Нажимаешь F5 и все норм, входит.
После этого все нормально, выходишь и входишь.
Но стоит сменить комп или хотя бы открыть другой браузер все повторяется.

**Comment by M4lik** [comment]
Please provide your issues in english, as not everyone can speek russian.

**Comment by extreen** [comment]
The first time you enter the browser after entering your username and password, it hangs.
You press F5 and all the rules are included.
After that, everything is fine, you go out and in.
But if you change your computer or at least open another browser, everything repeats.

**Comment by C-Magic** [comment]
https://github.com/nextcloud/docker/issues/1274
Там написано:
лечится добавлением 'overwriteprotocol' => 'https',
в config.php 
Но как єто d самом докеме поправить?

**Comment by C-Magic** [comment]
Подключил системную папку через внешнее хранилище (Local  /home/docker/cloud) и отредактировал прям в NextCloud
этот файл config.php, перезапустил контейнер - но НЕ ПОМОГЛО

**Comment by J0WI** [comment]
6d2390726fe7110b406c447d48aa345fc9d07122
