### ISSUE TITLE
Cannot access Nextcloud - 403 Forbidden

### ISSUE THREAD

**Issue by TheDuckMann** [nextcloud/docker#1279]
Hello dear Nextcloud-Community,

I had my Nextcloud running on an old PC, which wasn't performing as well as I expected. So I switched to a Raspberry Pi 4. I used my Backup of this old PC to run the nextcloud on the new host without dataloss. On my old machine everything worked fine (except overall performance), I could use my nextcloud as expected. It is running behind an Nginx Reverse Proxy.
As I said, all config and files are copied from the old host. And other containers are working as expected. But as I started my Nextcloud-Docker-Compose I got some "access forbidden by rule" Error-Messages and I am not able to access the NC through my browser.

This is the NC-web-log:
```nextcloud-web | 2020/10/18 17:27:23 [error] 22#22: *1 access forbidden by rule, client: 18.196.96.172, server: , request: "GET /.well-known/acme-challenge/SF4Uf4CVI2N28RaxeAg7kgYCSzKt1HMZcscBKxUZ938 HTTP/1.1", host: "myNC.domain.com"
nextcloud-web | 18.196.96.172 - - [18/Oct/2020:17:27:23 +0200] "GET /.well-known/acme-challenge/SF4Uf4CVI2N28RaxeAg7kgYCSzKt1HMZcscBKxUZ938 HTTP/1.1" 403 153 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "18.196.96.172"
nextcloud-web | 2020/10/18 17:27:23 [error] 22#22: *2 access forbidden by rule, client: 3.22.70.135, server: , request: "GET /.well-known/acme-challenge/SF4Uf4CVI2N28RaxeAg7kgYCSzKt1HMZcscBKxUZ938 HTTP/1.1", host: "myNC.domain.com"
nextcloud-web | 3.22.70.135 - - [18/Oct/2020:17:27:23 +0200] "GET /.well-known/acme-challenge/SF4Uf4CVI2N28RaxeAg7kgYCSzKt1HMZcscBKxUZ938 HTTP/1.1" 403 153 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "3.22.70.135"
nextcloud-web | 2020/10/18 17:27:23 [error] 22#22: *3 access forbidden by rule, client: 34.211.6.84, server: , request: "GET /.well-known/acme-challenge/SF4Uf4CVI2N28RaxeAg7kgYCSzKt1HMZcscBKxUZ938 HTTP/1.1", host: "myNC.domain.com"
nextcloud-web | 34.211.6.84 - - [18/Oct/2020:17:27:23 +0200] "GET /.well-known/acme-challenge/SF4Uf4CVI2N28RaxeAg7kgYCSzKt1HMZcscBKxUZ938 HTTP/1.1" 403 153 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "34.211.6.84"
nextcloud-web | 2020/10/18 17:27:23 [error] 22#22: *4 access forbidden by rule, client: 66.133.109.36, server: , request: "GET /.well-known/acme-challenge/SF4Uf4CVI2N28RaxeAg7kgYCSzKt1HMZcscBKxUZ938 HTTP/1.1", host: "myNC.domain.com"
nextcloud-web | 66.133.109.36 - - [18/Oct/2020:17:27:23 +0200] "GET /.well-known/acme-challenge/SF4Uf4CVI2N28RaxeAg7kgYCSzKt1HMZcscBKxUZ938 HTTP/1.1" 403 153 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "66.133.109.36"
```

I don't understand why this is happening even though it all worked on the old host and I copied everything.
I don't even know what to search for.
If you need any futher information just let me know.

So I would appreciate any help or hints.
Thank you in advance!

**Comment by joshtrichards** [comment]
Hi @TheDuckMann - I hope you got this addressed since it was quite awhile ago. Unfortunately where you posted this isn't a general technical support / troubleshooting channel. This repository is only for reporting bugs with the community Nextcloud Docker image itself. The best place for queries such as yours is the [Nextcloud Help Forum](https://help.nextcloud.com).

If you agree with my assessment of your report, please close this Issoue out. Thanks!
