### ISSUE TITLE
How to access database of nextcloud.

### ISSUE THREAD

**Issue by lafbelmonte** [nextcloud/docker#1281]
![image](https://user-images.githubusercontent.com/71109010/96802415-5adda300-143c-11eb-84b6-51490b41892b.png)

I can't seem to access or locate my database with this docker compose.
I tried exec in nextcloud but I can't locate it.
I chose postgresql in installation.

**Comment by FaMux** [comment]
Use auto configuration via environment variables as described in the readme.md or use docker volumes.
