### ISSUE TITLE
Express and docker - Serving Static files

### ISSUE THREAD

**Issue by skokonxd** [nextcloud/docker#1282]
Hello, I have nodejs bower application, im trying to deploy it to digitalocean ubuntu vps using dokku image
The problem i have is that express doesnt serve the static files, because dokku saves source as container not in directory that you can access which is a huge problem, I wasted more than 10 hours trying to figure it out but i failed
Im pretty sure the problem is because of the directory
express serve static files in localhost without any problems

Im using lastest dokku version, ubuntu

I will really appreciate any help.

**Comment by urosradosavljevic** [comment]
Can you provide reproducible example of your application?

**Comment by J0WI** [comment]
https://help.nextcloud.com/ might be a better place for your question
