### ISSUE TITLE
Updater takes you to dashboard

### ISSUE THREAD

**Issue by crazypete00** [nextcloud/docker#1287]
Trying to update Nextcloud Docker.
Current Ver 20.0.0
New version available 20.0.1

If you go to Administration > Overview
Click on Open Updater
It sends you to the Dashboard page, no way to update.

Running on Docker on Ubuntu.

**Comment by ethancedwards8** [comment]
You have to update the docker container, you don't do it through the settings like you would a normal install. 

Change the image from 20.0.0 to 20.0.01

**Comment by metroveinte** [comment]
I have the same problem in a new and clean installation 20.0.0.1 to 20.0.2, using the :latest tag
Updater takes me to the dashboard.

@crazypete00 did the solution from @ethancedwards8 solved the problem?

**Comment by ethancedwards8** [comment]
@metroveinte I don't think you understand. You can't update through the gui when running Nextcloud as docker. You have to update the container image. I'm my docker compose file I changed `image: nextcloud:20.0.0` to `image: nextcloud:20.0.1`. Or I misinterpreted your question xD.

**Comment by metroveinte** [comment]
@ethancedwards8 I asked because I have been using linexserver.io's image for more than 10 months and I was able to use the built-in updater.

Just wanted to know if this is the official update process using this image (updating the container), or if I had any configuration errors in my new deployment changing to the Nextcloud official image.
I didn't want to bother with the question

**Comment by bd8392** [comment]
Maybe there is a way to deactivate the display of the button to update inside the docker container, and instead display some text that you should update the container? As updating the container is MUCH easier and smoother than the built in updater, I would absolutely NOT RECOMMEND to turn on this internal updater again...

**Comment by bd8392** [comment]
@metroveinte I think the official way is, just switch the docker container tag to the new version...the container does EVERYTHING by itself...

**Comment by J0WI** [comment]
The updater has been disabled on purpose for the Docker image. Closing in favor of https://github.com/nextcloud/updater/pull/331
