### ISSUE TITLE
Legacy encryption in nextcloud docker 

### ISSUE THREAD

**Issue by Pushergene** [nextcloud/docker#1292]
Since nc 20 i get a message that my encryption is old. Wgat should i do? Do i have to worry that my nextcloud gets broken after some patches? The documentation of that message doesnt explain the fix for docker

**Comment by Kuphi** [comment]
Same question. What are the differences between legacy and current encryption?

Maybe this document can give some answers: https://eprint.iacr.org/2020/1439.pdf

**Comment by Kuphi** [comment]
> Since nc 20 i get a message that my encryption is old. Wgat should i do? Do i have to worry that my nextcloud gets broken after some patches? The documentation of that message doesnt explain the fix for docker

This does not only affect docker images. I created a feature request in the git of nextcloud/server:
https://github.com/nextcloud/server/issues/24240

**Comment by J0WI** [comment]
Duplicate of nextcloud/server#24240
