### ISSUE TITLE
Cron docker-compose on Azure

### ISSUE THREAD

**Issue by nickelnext** [nextcloud/docker#1295]
On Azure Web App (for containers) I am running nextcloud with the following docker-compose

`version: '3.8' 
services:
  db:
    image: mysql
    command: mysqld --sql-mode=NO_AUTO_VALUE_ON_ZERO
    environment:
      - MYSQL_ROOT_PASSWORD=*******myrootpass*******
      - MYSQL_PASSWORD=*****mypass*******
      - MYSQL_DATABASE=***mydatabase***
      - MYSQL_USER=***myuser***
    volumes:
       - ${WEBAPP_STORAGE_HOME}/mysql:/var/lib/mysql
    restart: always
  app:
    image: nextcloud:latest
    ports: 
      - 80:80
    environment:
      - MYSQL_DATABASE=***mydatabase***
      - MYSQL_USER=***myuser***
      - MYSQL_PASSWORD=*****mypass*******
      - MYSQL_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=mywebsite.azurewebsites.net
      - NEXTCLOUD_DATA_DIR=/var/www/html/data
    restart: always
    volumes:
      - HoloDentistStorageProd:/var/www/html/data
      - ${WEBAPP_STORAGE_HOME}/nextcloud/config:/var/www/html/config
      - ${WEBAPP_STORAGE_HOME}/nextcloud/apps:/var/www/html/custom_apps`

As there is no possibility to run docker commands, but only a docker-compose, how do I get the Cron/Webcron working?
Ajax seems not to be working properly, as both opening the "mywebsite.azurewebsites.net" from a non-logged in browser as well as a logged-in browser will always result in the "Some jobs didn’t execute since 4 days ago. Please consider switching to system cron"

Any ideas?

**Comment by Pushergene** [comment]
You can add cron like this example
https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb-cron-redis/apache/docker-compose.yml

that worked for me with apache

**Comment by J0WI** [comment]
Please have a look at #627 for more examples.
