### ISSUE TITLE
Setting up a cloud using docker

### ISSUE THREAD

**Issue by sabarishsubramanian** [nextcloud/docker#1298]
Hello all,

Am very new to docker and cloud.

I would like to set up a cloud with few containers in it. Could someone help me out to setting up a cloud using docker? Can someone guide me the steps to do so that i can try?

Thanks in advance

**Comment by Pushergene** [comment]
i recommend you to use the apache version in .example 
https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb/apache/docker-compose.yml
edit 
    ports:
      - 8080:80

to 
    ports:
      - 127.0.0.1:8888
you navigate to the folder with .example, so you are able to  write 
$ docker-compose up -d
if its vps u can navigate to http://yourip
but its better to make a reverse proxy with nginx with SSL
sudo apt update && sudo apt install nginx && sudo nano /etc/nginx/conf.d/nextcloud.conf
then u write this config file and modify it with your own server name and port
https://www.scaleway.com/en/docs/how-to-configure-nginx-reverse-proxy/
there u replace 127.0.0.1:8080 with 8888
and you add at beginning after server {
nameserver mydomain.com; or without semicolon not sure 
then 
$ sudo systemctl restart nginx
then you can navigate to your cloud with your domain
there the installation is automatically. 
if you want collabora i can explain it later but its more complicated... onlyoffice isnt so good with docker in my experience i had lost some files there were problems with auto saving so collabora office is better

if you want to update then you navigate to the folder with docker-compose.yml in it, for example:
$ cd docker/.examples/docker-compose/insecure/mariadb/apache/ 
$ docker-compose down && docker-compose pull && docker-compose up -d 

for better performance i recommend you to add following in your docker-compose.yml 
https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb-cron-redis/apache/docker-compose.yml
the part with cron, nothing else, just add that whats in cron. Redis is bugged with password authentication 

for SSL you can use certbot which automates it.
$ sudo apt-get update && sudo apt install certbot -y 
$ certbot --nginx --hsts 
then you follow that what it says

idk if i missed something but it should work fine with that. i can later upload my config files for apache, docker, give you tips where u can navigate and give you tips.

**Comment by sabarishsubramanian** [comment]
My prime traget is to get a application based load balancing happening between different cpus and cloud.

So for that I need a docked based cloud so will the above steps work for my target?

**Comment by J0WI** [comment]
https://help.nextcloud.com/ might be a better place for questions.
