### ISSUE TITLE
"Message":"Undefined offset: 3 at /var/www/html/lib/private/legacy/OC_Helper.php#548"

### ISSUE THREAD

**Issue by bufflu** [nextcloud/docker#1305]
docker run -d nextcloud

I can open nextcloud page，but I find many exception-message：

`{"reqId":"x89eBzMJGwCIQ3M17aEB","level":3,"time":"2020-11-14T09:45:50+00:00","remoteAddr":"","user":"","app":"PHP","method":"GET","url":"/index.php/apps/files/ajax/getstoragestats.php?dir=%2F","message":{"Exception":"Error","Message":"Undefined offset: 3 at /var/www/html/lib/private/legacy/OC_Helper.php#548","Code":0,"Trace":[{"file":"/var/www/html/lib/private/legacy/OC_Helper.php","line":548,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"Undefined offset: 3","/var/www/html/lib/private/legacy/OC_Helper.php",548,{"path":"/","rootInfo":{"__class__":"OC\\Files\\FileInfo"},"includeExtStorage":false,"used":16608274,"quota":5368709120,"mount":{"__class__":"OC\\Files\\Mount\\MountPoint"},"storage":{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"sourceStorage":{"cache":null,"scanner":{"__class__":"OC\\Files\\Cache\\Scanner"},"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"free":5352100846,"total":5368709120,"relative":0.31,"ownerId":"","ownerDisplayName":"","owner":{"__class__":"OC\\User\\User"}}]},{"file":"/var/www/html/apps/files/lib/Helper.php","line":51,"function":"getStorageInfo","class":"OC_Helper","type":"::","args":["/"]},{"file":"/var/www/html/apps/files/lib/Controller/AjaxController.php","line":47,"function":"buildFileStorageStatistics","class":"OCA\\Files\\Helper","type":"::","args":["/"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getStorageStats","class":"OCA\\Files\\Controller\\AjaxController","type":"->","args":["/"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\AjaxController"},"getStorageStats"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\AjaxController"},"getStorageStats"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\AjaxController","getStorageStats",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"_route":"files.ajax.getStorageStats"}]},{"file":"/var/www/html/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/files/ajax/getstoragestats.php"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1"}`

**Comment by hrehfeld** [comment]
I am also getting this with a postgres install.

**Comment by kesselb** [comment]
Closing in favor of https://github.com/nextcloud/server/issues/23595
