### ISSUE TITLE
Nginx blocks access from specific network

### ISSUE THREAD

**Issue by bjarnemagnussen** [nextcloud/docker#1306]
I have the following problem with a default installation using the configuration found in `.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm`:

I cannot access the server that is installed at home from my internet at home. In other words, any device connected to the same (W)LAN and accessing the server through its public internet address, cannot connect to it. Using another internet connection such as e.g. from the mobile network however does work. 

I have also run `wget nextcloud.address.com` from within the server, which works. But doing this on any other device connected to the home internet gets stuck at:

```
Resolving nextcloud.address.com (nextcloud.address.com)... a.b.c.d
Connecting to nextcloud.address.com (nextcloud.address.com)|a.b.c.d|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://nextcloud.address.com/ [following]
--2020-11-15 21:19:39--  https://nextcloud.address.com/
Connecting to nextcloud.address.com (nextcloud.address.com)|a.b.c.d|:443... connected.
HTTP request sent, awaiting response...
```

It does only show up in the `proxy` instance logs with the first 301 move:
```
proxy_1                  | nginx.1    | nextcloud.address.com a.b.c.d - - [15/Nov/2020:20:43:22 +0000] "GET / HTTP/1.1" 301 169 "-" "Wget/1.20.3 (linux-gnu)"
```

The `web` instance does not show anything in the logs.

I have tried to run the simple nginx default/demo running on port 80 on the server, which was accessible.

Any help is very much appreciated, as I have no idea what is going on.

**Comment by J0WI** [comment]
You get redirected to https which lives on port 443. Your packages are dropped on this port .

I'm closing this because your issue is not related to the Docker image.
