### ISSUE TITLE
[Question] Possible to run as another user?

### ISSUE THREAD

**Issue by smokemyshoes** [nextcloud/docker#1314]
Hi

First of all, thanks for a very nice piece of software...

I'm consolidating most of my services onto one host and thus I am transitioning a lot of stuff into docker containers. I am still pretty new to docker but I've seen that on most linuxserver images, for instance, you can specify the the user/group the container should be run as, which made me wonder:

1) What user/group does your image run as?

2) Is it possible to specify a different user/group in the compose file and if so, what's the syntax?

Thanks in advance.

**Comment by schklom** [comment]
Look [here](https://github.com/nextcloud/docker/issues/359#issuecomment-481466066) and [there](https://github.com/nextcloud/docker/issues/458#issuecomment-522273405).

Before running mine, I create an empty folder with proper owner (1001:1001 in my case) for `/var/www/html`, and another one inside for `/var/www/html/data` with same owner (you can do this at once
```
mkdir -p /path_to_nextcloud_folder/data
```
), then run my docker-compose with this bit in `nextcloud` container
```
 user: ${PUID}:${PGID}
sysctls:  # Necessary for user: ${PUID}:${PGID} # https://github.com/nextcloud/docker/issues/755
  - net.ipv4.ip_unprivileged_port_start=0 # Allow an unprivileged user to listen on any port https://github.com/nextcloud/docker/issues/359 https://github.com/nextcloud/docker/issues/458
```
and I set `PUID` and `PGID` to 1001.

**Comment by smokemyshoes** [comment]
Thanks a lot. I'll look into this.
