### ISSUE TITLE
Can't login from Android app

### ISSUE THREAD

**Issue by EgidioCaprino** [nextcloud/docker#1315]
Hi,

I used the [with-nginx-proxy-self-signed-ssl](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm) template and it works perfectly from the browser, but I get stuck on login/granting access on Android app. Do you know why is that happening?

Thank you

**Comment by danvilar** [comment]
'Yes. You have to go to your config/config.php file and add in the option `'overwriteprotocol' => 'https'`. Restart your docker image and you should be fine.

**Comment by C-Magic** [comment]
Didn't help me
 'installed' => true,
  'overwriteprotocol' => 'https',
);

**Comment by J0WI** [comment]
The initial question has been answered. Please use https://help.nextcloud.com/ for further questions with specific configurations.
