### ISSUE TITLE
stable still on 19.0.5

### ISSUE THREAD

**Issue by Thomas131** [nextcloud/docker#1323]
Hi!
Should the stable-Tags (stable-fpm-alpine in my case) be updated to 19.0.6? They are still on .5 and make Nextcloud throw notifications about updating all the time.

Thanks in advance!
Thomas

**Comment by kesselb** [comment]
cc @tilosp @J0WI

**Comment by Bleuzen** [comment]
It should be update to 20.0.4, which is now rolled out to all 19.0.6 users!

But in official updater they go 19.0.5 -> 19.0.6 -> 20.0.4.
I'm not sure if the second step to go to 19.0.6 first is really necessary.

**Comment by Fixmetal** [comment]
I came across this because I see that stable tags' latest commit is dated 23 April 2020. These includes:

- stable
- stable-fpm
- stable-fpm-alpine
- stable-apache

I might be wrong but I think this is some kind of forgetfulness :)
Might someone shed some light on the tag (github) update policy?

**Comment by ffried** [comment]
The tags on GitHub don't correlate with the tags on the Docker images. Maybe that was the case in an earlier setup of this repository, though. I don't know what the tags on this repository were used for. One of the maintainers of this repo can maybe give some insights here if necessary.

The stable tags on Docker are currently controlled by [this line](https://github.com/nextcloud/docker/blob/master/generate-stackbrew-library.sh#L4). The version referenced here will be built and tagged as 'stable' (including all the variants). Currently, this line defines 20.0.5 as stable.

Given that this repository only contains the logic to _build_ nextcloud Docker images (not the actual nextcloud source code) it makes little sense to add nextcloud version tags to this repository. 🙂
