### ISSUE TITLE
Browser access very slow on 20.0.3

### ISSUE THREAD

**Issue by danvilar** [nextcloud/docker#1326]
Hi everyone. I updated today my nextcloud instance to 20.0.3, but using it in the browser now is close to impossible. It takes 30+ seconds to load the each page. I can't find anything significant in the docker logs, where should I dig for more information? Is it happening to someone else? Thanks in advance.

**Comment by danvilar** [comment]
Adding information:

When I start the docker container, the first 15 seconds works as expected, after that starts hanging for about 30-40 seconds before switching to another page.

**Comment by er-vin** [comment]
I can confirm. Removed the app and now the server works properly again.

**Comment by j-eissler** [comment]
I can confirm this aswell. Disabling the CODE app by executing

`occ app:disable richdocumentscode` 

fixed it.

**Comment by danvilar** [comment]
I disabled it for now, but I really wanted to use the built-in CODE server

**Comment by kesselb** [comment]
Closing in favor of https://github.com/nextcloud/richdocuments/issues/1282
