### ISSUE TITLE
New NextCloud docker install stops responding after 5 seconds 

### ISSUE THREAD

**Issue by iambenmitchell** [nextcloud/docker#1348]
[Video Of Issue](https://youtu.be/M4S3zP_PpIE)

I literally just installed next cloud docker, this is the command I used:

`docker run -d --net bignet --ip xxx.xxx.xxx.xxx -v /var/ignition/ipas:/var/www/html/data nextcloud`

However, after about 5 seconds of using it, the website starts timing out. I have restarted the docker a few times and that fixes it for another 5 seconds before it crashes again.

**Comment by MrBenFTW** [comment]
I thought it was broken, but actually if you leave it for 40 seconds it will eventually load the page. This is a really long time and means every Time you press something you have to wait 40 seconds.

Any fix?

**Comment by MrBenFTW** [comment]
This seems to be caused by the `collabora online - built-in code server`

**Comment by madjoel** [comment]
I am having the same issue after upgrading from 20.0.2 to 20.0.4 via docker-compose. Disabling the _Collabora Online - Built-in CODE Server_ indeed solved the Problem for me and the loading times are back to normal, thank you!

**Comment by jcerjak** [comment]
I have the same issue (up to 1min to load a page) and disabling `Collabora Online - Built-in CODE Server` fixes the issue for me. Thanks for the hint!

Note that I'm using this docker-compose config: https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/postgres/apache

Any ideas what might be causing the issue?

**Comment by MrBenFTW** [comment]
> I have the same issue (up to 1min to load a page) and disabling `Collabora Online - Built-in CODE Server` fixes the issue for me. Thanks for the hint!
> 
> Note that I'm using this docker-compose config: https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/postgres/apache
> 
> Any ideas what might be causing the issue?

No idea, I never figured it out I just disabled collabora. Ended up making my own docker image with next cloud installed, I haven't tested the issue since, but if you're having an issue still then I can only assume it hasn't been fixed yet

**Comment by joshtrichards** [comment]
nextcloud/richdocuments#1282

Not an issue with the Docker image itself but in that app bundle.
