### ISSUE TITLE
Nextcloud setup with env-file not working

### ISSUE THREAD

**Issue by kitkittia** [nextcloud/docker#1359]
I have this env file:
```
MYSQL_ROOT_PASSWORD=mysql_root_password
MYSQL_DATABASE=nextcloud
MYSQL_USER=nc_admin
MYSQL_PASSWORD=mysql_nc_password
MYSQL_ALLOW_EMPTY_PASSWORD=no
#MYSQL_HOST=127.0.0.1
NEXTCLOUD_ADMIN_USER=nc_admin
NEXTCLOUD_ADMIN_PASSWORD=nc_password
```

If I omit `MYSQL_HOST` nextcloud appears to ignore all the other `MYSQL_*` environment variables and assumes I chose a `sqlite` database. If I however enable `M̀YSQL_HOST`, nextcloud registers that I want a `mysql` database.

Comment https://github.com/nextcloud/docker/issues/1201#issuecomment-698702665 mentions this explicitly.

Is this a bug, or is the documentation lacking?

**Comment by J0WI** [comment]
This behavior is expected:
https://github.com/nextcloud/docker/blob/d7ea12fd78f4f5a43737bd8a45be5a9a784e7844/docker-entrypoint.sh#L137

**Comment by kitkittia** [comment]
Then this must be fixed in the README

**Comment by J0WI** [comment]
Fixed in https://github.com/nextcloud/docker/pull/1361
