### ISSUE TITLE
I want to use nextcloud20.0 Ubuntu + nginx + PHP 8.0

### ISSUE THREAD

**Issue by zygds** [nextcloud/docker#1365]
But the Debian system systemctl + PHP FPM conflicts,
After installing VIM, the cursor and input position are asymmetric, and the backspace cursor does not backspace
So I want to use Ubuntu or CentOS, because I don't know much about Debian system

**Comment by J0WI** [comment]
This bug tracker is only for the Docker image. Please have a look at [the forum](https://help.nextcloud.com/t/nextcloud-and-php-8-x/99658/3) for PHP 8 and other support.
