### ISSUE TITLE
htaccess file ignored

### ISSUE THREAD

**Issue by escoand** [nextcloud/docker#1366]
Is there a reason why in the file `/etc/apache2/apache2.conf` the option `AllowOverride` for `/var/www/` is set to `None`? This is the reason why the apache container ia complaining about wrong config:

```
There are some warnings regarding your setup. 		 		

The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the security tips ↗.

Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the documentation.

Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the documentation.
```

**Comment by hakunamatata97k** [comment]
i have the same issue. please provide us with a possible solution. regarding the "Strict-Transport-Security" you can add the following line to the end of the `.htaccess` :
`Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains;

now regarding the `caldav` and the `carddav` issue: 
i edit `etc/apache2/apache2.conf` file and changed  `AllowOverride` for `/var/www/` from `none` to `all` but nextcloud still shows the same message: 

> Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the documentation.
> Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the documentation.

the nextcloud server is reached directly via the following: `exampledomain.com` without `/nextcloud/`

the server is running as a dockerized image on a raspberry pi 4 with Raspbian Os 64x and the image used is `nextcloud:apache2` and deployed using portainer.

**Comment by escoand** [comment]
I would still be interested in an upstream solution. But currently I've implemented the same options in my proxy Caddy: https://www.github.com/escoand/dockerfiles/tree/master/homeserver%2FCaddyfile

**Comment by gianpo86** [comment]
> i have the same issue. please provide us with a possible solution. regarding the "Strict-Transport-Security" you can add the following line to the end of the `.htaccess` :
> `Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains;
> 
> now regarding the `caldav` and the `carddav` issue:
> i edit `etc/apache2/apache2.conf` file and changed `AllowOverride` for `/var/www/` from `none` to `all` but nextcloud still shows the same message:
> 
> > Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the documentation.
> > Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the documentation.
> 
> the nextcloud server is reached directly via the following: `exampledomain.com` without `/nextcloud/`
> 
> the server is running as a dockerized image on a raspberry pi 4 with Raspbian Os 64x and the image used is `nextcloud:apache2` and deployed using portainer.

Hi, I have the same issue and I tried to override the .htaccess file with the configuration suggested on the [Nextcloud website ](https://docs.nextcloud.com/server/22/admin_manual/installation/harden_server.html#enable-http-strict-transport-security), which is also the solution you suggest: nothing changed. It seems to me the htaccess file is ignored by the apache instance of the container... although it is referenced in the config.... any idea?

my .htaccess:

`
# Section for Apache 2.4 to 2.6
<IfModule mod_authz_core.c>
  Require all denied
</IfModule>
<IfModule mod_access_compat.c>
  Order Allow,Deny
  Deny from all
  Satisfy All
</IfModule>

# Section for Apache 2.2
<IfModule !mod_authz_core.c>
  <IfModule !mod_access_compat.c>
    <IfModule mod_authz_host.c>
      Order Allow,Deny
      Deny from all
    </IfModule>
    Satisfy All
  </IfModule>
</IfModule>

# Section for Apache 2.2 to 2.6
<IfModule mod_autoindex.c>
  IndexIgnore *
</IfModule>

<VirtualHost *:443>
ServerName nextcloud.mydomain.synology.me
  <IfModule mod_headers.c>
    Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
  </IfModule>
</VirtualHost>

<VirtualHost *:80>
ServerName nextcloud.mydomain.synology.me
    Redirect permanent / https://nextcloud.mydomain.synology.me
</VirtualHost>

`

**Comment by erdoukki** [comment]
+1 (same issue)

**Comment by sittingbool** [comment]
Same here

**Comment by plantroon** [comment]
I also have it implemented on another reverse proxy in front of nextcloud but this wouldn't be needed if the .htaccess was read within the container. It's kind of redundant and messy. Also using official docker image as the folks above.

**Comment by joshtrichards** [comment]
Hi @escoand - Thanks for your report!

> Is there a reason why in the file /etc/apache2/apache2.conf the option AllowOverride for /var/www/ is set to None? This is the reason why the apache container ia complaining about wrong config:

That's incorrect. See `/etc/apache2/conf-enabled/docker-php.conf` where that parameter is overwritten.

If you're seeing those warnings your underlying cause is something else.

Note to folks on this thread: Just because you're seeing the same warning doesn't mean you have the same underlying cause as others in this thread. 

If you're behind a reverse proxy, the NC way is to deploy the redirects/rewrites (or equivalent) on your proxy:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html#service-discovery

Closing as this does not appear to be a bug in the Docker image.
