### ISSUE TITLE
Why docker-compose down deletes my volume? how to avoid this action done by 'down'. (Postgresql)

### ISSUE THREAD

**Issue by sapkotasuren** [nextcloud/docker#1370]
when I run docker-compose down, why my data is lost?
can anyone help?
I have created named volume seprately using this command: "docker volume create postgres "and set external to true in my compose.yaml file. But still my data is not persisted.

version: '3.9'
services:
  app:
    container_name: bsf-quiz-app
    #image: sapkotasuren/bsf-quiz #if you want it to pull from somewhere else
    #image: bsf-quiz-app #select the image from local com by building it using ./ dockerfile
    image: app
    build: ./
    ports:
      - "443:8443"
      #- "80:8080"
    #environment:
     # - "SPRING_PROFILES_ACTIVE=PROFILENAME"
    depends_on:
      - postgresqldb
  postgresqldb:
    container_name: postgres
    image: postgres:latest
    #ports:
    #  - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    #volumes:
    #  - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bsfQuiz

volumes:
  postgres:
    external: true

https://www.codepile.net/pile/MmbZkxmK

**Comment by N3bby** [comment]
I think this issue might be more at home on [docker compose's github repository](https://github.com/docker/compose/issues) 

This might not apply to your use-case, but you can always try having docker-compose automatically create the volumes for you.
```
postgresqldb:
    container_name: postgres
    image: postgres:latest
    volumes:
      - <some-path-on-the-host>:/var/lib/postgresql/data
     ...
```

**Comment by sapkotasuren** [comment]
@N3bby  Thank you!, The problem was not in docker-compose yaml file, but the problem was on my backend application where i have set **spring.jpa.hibernate.ddl-auto = create** it SHOULD NOT be create but instead update!
spring.jpa.hibernate.ddl-auto = update
