### ISSUE TITLE
HTTP 413 Request Entity Too Large on Linux Desktop only

### ISSUE THREAD

**Issue by Hursofid** [nextcloud/docker#1373]
Hello,

Today I've updated my linux desktop app to latest version (to 3.1.1) and have noticed the issue while uploading large files to the cloud: "413 Request Entity Too Large to PUT https://mycloud.example/foo/bar.jpg"

- With same server but macOS client 3.1.1 everything is okay and I'm able to upload large files.
- Uploading large files using the web interface also works as expected.

Nothing really related in nginx front proxy nor in the nginx in nextcloud_web container except for this:

```
2021/01/17 11:05:38 [warn] 22#22: *141758 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/9/30/0000000309 while reading upstream, client: 192.168.0.50, server: , request: "GET /remote.php/dav/files/constructed/foo/bar.jpg HTTP/1.0", upstream: "fastcgi://172.18.0.3:9000", host: "mycloud.example"
```

Server version is 20.0.4 and I've just tried the same with 20.0.5.2, results are the same

This is nginx-proxy vhost configuration:

```
  upstream nextcloud {
    server 192.168.0.1:8080;
  }

  server {
    listen 80;
    server_name oldurl.mycloud.example;
    return 301 http://mycloud.example;
    client_max_body_size 10G;
    client_body_buffer_size 400M;
    fastcgi_buffers 64 4K;
  }

  server {
    listen 80;
    server_name mycloud.example;
    return 301 https://$server_name:443$request_uri;
    client_max_body_size 10G;
    client_body_buffer_size 400M;
    fastcgi_buffers 64 4K;
  }

  server {
    listen 443 ssl;
    server_name oldurl.mycloud.example;
    return 301 https://mycloud.example;
    ssl_certificate  /etc/letsencrypt/live/mycloud.example/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mycloud.example/privkey.pem;
    include snippets/ssl-params-dev.conf;
    client_max_body_size 10G;
    client_body_buffer_size 400M;
    fastcgi_buffers 64 4K;
  }

  server {
    listen 443 ssl;
    server_name mycloud.example;

    ssl_certificate  /etc/letsencrypt/live/mycloud.example/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mycloud.example/privkey.pem;
    include snippets/ssl-params-dev.conf;

    client_max_body_size 10G;
    client_body_buffer_size 400M;
    fastcgi_buffers 64 4K;

    location / {
      proxy_pass http://nextcloud;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
```

/etc/nginx/nginx.conf in container nextcloud_web also has these lines:
```
        client_max_body_size 10G;
        fastcgi_buffers 64 4K;
```

**Comment by ctsrc** [comment]
I'm having this problem too when trying to upload photos and videos using the iPhone app, and despite numerous attempts at figuring it out I was unable to.

As a temporary workaround I set the chunk size in the iPhone app to 8MB, allowing me to upload files that were too big to upload all in one go.

Perhaps the desktop client has a similar setting that would allow files to be uploaded in chunks?

**Comment by joshtrichards** [comment]
Hi @Hursofid - I'm going through old Issues and attempting to clean things up a bit. Hopefully you found what you needed through another channel.

Are you still experiencing this issue?

The `413` would have been coming from one of the web/proxy/app servers in your chain. Wherever it was logged is likely where it needed to be fixed or at least will provide a big clue. Did you `nextcloud.log` contain anything? There's usually correlated errors there with the 413.

Over the years there have been some `server` bugs. Without your NC `config.php` I don't want to speculate about the underlying cause in your case.

- See https://github.com/nextcloud/server/issues?q=is%3Aissue+%22413+request+entity%22+is%3Aclosed

**Comment by Hursofid** [comment]
Hi,
No I haven't seen this issue appearing again.
