### ISSUE TITLE
How to change domains used to access nextcloud?

### ISSUE THREAD

**Issue by laurentS** [nextcloud/docker#1382]
Hi all, I've been using this docker setup for about a year now, and I love it.
However, I need to change the domain I'm using to access my instance. Let's say move from `cloud.old.com` to `cloud.new.com`. I want to keep all my data/files/etc. Just change the url.
So I went to `docker-compose.yml` and updated `VIRTUAL_HOST` and `LETSENCRYPT_HOST` to the new domain, and then `docker-compose up -d`. It complained about `TRUSTED_DOMAINS` in `config/config.php` so I renamed the file via `docker-compose exec app sh` and it then asked me to add a `CAN_INSTALL` file under `config`. I did this, but now it looks like it's going for a full reinstall from zero.
Is there a way I can update the domain and not lose all my data? (I tried reverting to the old domain, but it's doing the same thing, so now I'm worried that I've broken things for good)

Thanks for any help!
PS: I'm using the php-fpm version, in case it makes any difference

**Comment by raimund-schluessler** [comment]
Instead of renaming `config/config.php` you should adjust `TRUSTED_DOMAINS` in `config.php` to your new domain.
