### ISSUE TITLE
how to mount folder in docker container to another host

### ISSUE THREAD

**Issue by hnuhchen** [nextcloud/docker#1386]
hello everyone

i am using docker1.13.1, and i want to mount the folder of docker container to another host on the internet. So which tool should i select? It seems that `mount` commond cannot meet my expectations, what should i use?

Thank you

**Comment by supermar1010** [comment]
This is more linux question, I guess https://unix.stackexchange.com/ is the more appropriate place to ask.

**Comment by hnuhchen** [comment]
Thank you @supermar1010
