### ISSUE TITLE
Nextcloud 20.0.7 missing on hub.docker.com

### ISSUE THREAD

**Issue by hansingt** [nextcloud/docker#1398]
Nextcloud 20.0.7 is released since about a week ago. 

But, as the builders are failing, it is still missing on hub.docker.com. Could you please fix the pipeline and upload the images to the Docker-Hub?

Also: As this is the second time in short term (I think, it was 20.0.4, which was missing as well): Would it be possible, to better coordinate the releases, such, that it is assured, that the images are available as well, when a new version of Nextcloud is announced as released?

**Comment by Crocmagnon** [comment]
For reference, there is already a PR here: https://github.com/nextcloud/docker/pull/1393

**Comment by GuidoDr** [comment]
well this issue was closed 5 hours but at least for linux/amd64 it is still missing. :-(
I do only see it until now for linux/arm/v5, linux/mips64le and linux/s390x which were all pushed an hour ago to hub.docker.com
I will check it again tomorrow morning.

**Comment by hansingt** [comment]
The images are available now. 

But still remains the question, what could be done to prevent these kind of issues in future? Would it be possible, to coordinate the releases better to make sure, all sources are available at once?

**Comment by GuidoDr** [comment]
well about an hour ago some more images were pushed to hub.docker.com, but the image I do need for linux/amd64 is still missing besides the image for linux/ppc64le which is also still missing. The other images are there now.
Current images are: linux/386, linux/arm/v5, linux/arm/v7, linux/arm64/v8, linux/mips64le and linux/s390x
Let's see and wait until when the last two will be available ...
