### ISSUE TITLE
Fix docker migration instructions

### ISSUE THREAD

**Issue by martini1992** [nextcloud/docker#1405]
The docker migration instructions in the README.md are misnumbered and some are contradictory, somebody who knows the process should tidy it up.

**Comment by joshtrichards** [comment]
Hi @martini1992 - Thanks for your report. I agree there may be some cleanup overdue in that section. I think your request is covered in #1155. If you agree, can you close out this Issue since it's a duplicate? Thanks!

**Comment by martini1992** [comment]
Yeah seems to be covering the same issue, closing.
