### ISSUE TITLE
Caldav and cardav warnings

### ISSUE THREAD

**Issue by Tockra** [nextcloud/docker#1407]
Hi Guys,

I'm using a setup similar to: https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm

If I call `<mydomain>/.well-known/caldav` and `/.well-known/carddav` I see a page like:
```
This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client.
```

But my nextcloud settings show following warning (translated by google):
```
There are some warnings with your system configuration.

    Your web server is not properly set up to resolve "/.well-known/caldav". See the documentation for more information.
    Your web server is not properly configured to resolve "/.well-known/carddav". For more information see the documentation.
```

I have no idea how to fix that. My nginx.conf contains following: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm/web/nginx.conf  ...

T

**Comment by the-voidl** [comment]
I think  #927 describes a solution to your problem.
