### ISSUE TITLE
immediate logout when opening files app

### ISSUE THREAD

**Issue by lobeck** [nextcloud/docker#1419]
When I open the Files app, the spinner on the top never disappears and the popups that a error occurred appear in the top right (sometimes, so I can't post the exact phrasing).

After a bit, I'm suddenly logged out.

In the console I can see, that the first failing request is `/apps/files/ajax/getstoragestats.php?dir=%2F` with a http 412 error `CSRF check failed`

Then a few preview requests succeed, while others fail with `Current user is not logged in`.

The FPM container is run with:

    podman run -d --log-driver journald --pull=always --network mysql --network redis --network nextcloud -p 10.89.2.1:9000:9000 -v nextcloud:/var/www/html -e MYSQL_HOST=10.89.0.1 -e REDIS_HOST=10.89.1.1 --name nextcloud nextcloud:fpm

The container was just started, so it's the most recent image as of now and nextcloud 21.0.0. I can't find anything in the logs, that would indicate the root cause. Other parts like the settings page or the mobile app work without issues.

**Comment by JuniorJPDJ** [comment]
Does it work without redis?

**Comment by lobeck** [comment]
No, same issue. I removed both the REDIS_HOST and the config entry, but still the same issue.

**Comment by lobeck** [comment]
Found the cause. It was my browser cache.

It was working in a different browser so I cleared all caches, cookies and local storage and now the issue disappeared.
