### ISSUE TITLE
php-imagick SVG support in docker images

### ISSUE THREAD

**Issue by larochef** [nextcloud/docker#1420]
I have upgraded nextcloud using docker today to the `nextcloud:latest` version, and I have the following warning in the settings:

`Module php-imagick in this instance has no SVG support. For better compatibility it is recommended to install it.`

More info on the image I currently have:

```
*REPOSITORY       TAG       IMAGE ID       CREATED      SIZE
nextcloud        latest    23a40db6c36f   2 days ago   835MB
```

```
docker pull nextcloud:latest
latest: Pulling from library/nextcloud
Digest: sha256:75e1b3719ff84ce96a21eb60b519b66310c7946ef8853acfa58eeac97a8d0994
Status: Image is up to date for nextcloud:latest
docker.io/library/nextcloud:latest
```

could you see to add what's missing in the docker images?

**Comment by larochef** [comment]
Looks like there's already an issue on this

**Comment by rcdailey** [comment]
This is tracked in #1414.
