### ISSUE TITLE
Image for Nextcloud v12.0.2 not available at docker hub

### ISSUE THREAD

**Issue by smarrk** [nextcloud/docker#145]
Nextcloud v12.0.2 has been released on August 14, the latest tag on docker hub still points to 12.0.1.  
Please push v12.0.2.

Thanks.

**Comment by tilosp** [comment]
@tianon or @yosifkit please update the nextcloud image

**Comment by yosifkit** [comment]
New version will get pushed once https://github.com/docker-library/official-images/pull/3336 merges.
