### ISSUE TITLE
[stable-fpm-alpine] Doesn't support external storage using SFTP backend

### ISSUE THREAD

**Issue by LukBukkit** [nextcloud/docker#1453]
Hello,

the image [`stable-fpm-alpine`](https://github.com/nextcloud/docker/blob/f1ca6dbfab022e44b8aed9909939a4c43726d2f2/20.0/fpm-alpine/Dockerfile) doesn't include the package [`openssh-client`](https://pkgs.alpinelinux.org/package/edge/main/x86_64/openssh-client). 

In this case Nextcloud is unable to connect any external storage using the SFTP backend, but it's still possible for the user / admin to add new external storage services of this type. Nextcloud tries to connect with them and just shows the following error message to the user. You can view the full log entry of the error in [this gist](https://gist.github.com/LukBukkit/2d23cc0d16b7d28fe5c1e1f161a68978).
 ```
Cannot connect to example.com:22. Error 110. Operation timed out
```
If the required package is installed manually using the following command, everything works fine. The Buster-based Docker image already includes the equivalent package.
```sh
apk add openssh-client
```

I've got two solutions for this problem in my mind:
1. Install the package `stable-fpm-alpine` during the build process of the Docker image
2. If there is no `sftp` executable on a system, don't allow the user to create external storage services using the SFTP backend, similar to the process for a missing `smbclient`.

**Comment by J0WI** [comment]
We do not include all dependencies for all apps, please have a look at our [Dockerfile examples](https://github.com/nextcloud/docker/tree/master/.examples#dockerfiles).
