### ISSUE TITLE
BusyBox Cron Daemon does not autostart within 21.0.0 container if server reboots

### ISSUE THREAD

**Issue by avimanyu786** [nextcloud/docker#1463]
Everytime the host server is restarted, the Nextcloud container obviously starts again after boot as per the `restart: always` policy. But the BusyBox Cron Daemon inside it does not autostart. This results in the [background jobs not running](https://help.nextcloud.com/t/background-jobs-wont-run-nextcloud-15/54455) that are supposed to be executed by Cron every 5 minutes. Running `service --status-all` inside the container shows that Cron is not running.

The current workaround I'm using is to run `busybox crond` with bash that starts the Cron Daemon inside the container. Perhaps this command could be added to `~/.bashrc` for the next release(21.0.1). If there is a better approach for enabling Cron, please resolve it.

**Comment by J0WI** [comment]
Docker does not use `service` for Cron. Please see #627 for some examples.

**Comment by avimanyu786** [comment]
I tried all the suggested ways. Finally ended up adding this to the Nextcloud service to make it work:

```
command: sh -c "busybox crond && apache2-foreground"
```
