### ISSUE TITLE
Apache/PHP config: 'ServerTokens Prod' / 'expose_php = off' may be default?

### ISSUE THREAD

**Issue by jessasnoi** [nextcloud/docker#1477]
Hello,

I use the `nextcloud:production` tagged container from docker hub. Today I did a security scan of the instance and noticed that there is `ServerTokens OS` set in the default apache config of the container.

![image](https://user-images.githubusercontent.com/80790507/115126714-8f887c80-9fd1-11eb-9590-55ff71c986de.png)

Rather than chaning this manually I think it is a good Idea to set this to `ServerTokens Prod` as the default for the production tagged container? 

https://httpd.apache.org/docs/2.4/mod/core.html#servertokens

This will just expose 'Apache' as server to the world.

I use this containers for my environment:

```
$ docker image ls
REPOSITORY   TAG          IMAGE ID       CREATED       SIZE
nextcloud    production   af019cc93e89   6 days ago    826MB
haproxy      lts          d59c0ba74b7e   7 days ago    93.6MB
mariadb      latest       e76a4b2ed1b4   2 weeks ago   401MB
```

**Comment by jessasnoi** [comment]
after digging a bit around I also found 

`x-powered-by PHP/7.4.16`

in the same report. This may also lead someone who is more interested into "vulnerability management" to have a closer look at your system.

So the quick fix for this will be

```
docker exec -it nextcloud_container /bin/bash
echo 'expose_php = On' >> /usr/local/etc/php/conf.d/nextcloud.ini
sed -i 's/ServerTokens OS/ServerTokens Prod/g' /etc/apache2/conf-available/security.conf
/etc/init.d/apache2 reload
```

this will just show `Server Apache` and remove the `x-powered-by` Header.

**Comment by J0WI** [comment]
Same as in https://github.com/nextcloud/docker/issues/612#issuecomment-456101369. But hiding this header will not protect you from anything.

**Comment by jessasnoi** [comment]
Sure :-) For my personal freedom I would love to have those both things set for containers tagged "prod"!

Keep up the good work :-)

**Comment by joshtrichards** [comment]
Duplicate of #71 and #612.

Can you close this Issue out @jessasnoi to avoid confusion? Thanks!

**Comment by jessasnoi** [comment]
Duplicate of [#71](https://github.com/nextcloud/docker/issues/71) and [#612](https://github.com/nextcloud/docker/issues/612).
