### ISSUE TITLE
Certs are renewed with every docker-compose down/up cycle

### ISSUE THREAD

**Issue by Mailblocker** [nextcloud/docker#1479]
Hi everyone,
while having another problem I ran into the issue getting the follwing error from letsencrypt: 

```
letsencrypt-companion    | [Sun Apr 18 08:07:58 UTC 2021] Create new order error. Le_OrderFinalize not found. {
letsencrypt-companion    |   "type": "urn:ietf:params:acme:error:rateLimited",
letsencrypt-companion    |   "detail": "Error creating new order :: too many certificates already issued for exact set of domains: MY_DOMAIN: see https://letsencrypt.org/docs/rate-limits/",
letsencrypt-companion    |   "status": 429
letsencrypt-companion    | }
```

As stated [here](https://github.com/nginx-proxy/acme-companion/issues/216#issuecomment-770911043) the image now needs a named volume for ```/etc/acme.sh``` in order to persist ACME account keys and SSL certificates. 

Also the project renamed itself as stated [here](https://github.com/nginx-proxy/acme-companion/issues/768) which confused me since I could find the repository "jrcs/letsencrypt-nginx-proxy-companion" no more on github. New name is nginx-proxy/acme-companion.

I think these changes should be integrated into the docker-compose examples otherwise it is likely to run into the above stated error very easily. Which will end up in a not usable setup for 1 week.

**Comment by 0x47** [comment]
I found this issue described in https://github.com/nextcloud/docker/issues/1357

**Comment by Mailblocker** [comment]
@0x47 you are right.

This issue can be linked as duplicates #1357.

I really wish someone can fix the changes so the merge can be done. I would have done the same changes without anything more.

**Comment by iamunadike** [comment]
Has this issue been fixed because I experience the same is there a missing configuration, please help
