### ISSUE TITLE
docker-compose.yml Collabora don't work 

### ISSUE THREAD

**Issue by mdphoto** [nextcloud/docker#149]
Hi,

I've a VPS debian-9.
nextcloud.mydomaine.com

I try 
DOMAIN= nextcloud.mydomaine.com docker-compose up -d
I use the nginx.conf of the example just change domain of Collabora section "nextcloud.mydomaine.com:9980"
But I'have the same error #76 

Nextcloud install is ok
next I enable app/Collabora Online and admin setup collabora Online and past https://nextcloud.mydomaine.com:9980

When I edit the test.odt file the log is 

Error | index | GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to nextcloud.mydomaine.com port 9980: Connection refused

I think have a bug with proxy?

**Comment by tilosp** [comment]
There is no longer an example with collabora
