### ISSUE TITLE
Docker stable tag policy

### ISSUE THREAD

**Issue by d-vo** [nextcloud/docker#1495]
Hi Nextcloud Team, 

thx for providing the docker image. I was wondering what is the policy on moving the _stable_ tag from from 20.x to 21.x on https://hub.docker.com/_/nextcloud ? I read somewhere it would be moved, when 21.0.1 becomes available? That was released one month ago. 

Thanks and keep up the good work!

**Comment by Bleuzen** [comment]
Have a look at the official updater:
https://github.com/nextcloud/updater_server/blob/production/config/config.php

As you can see in this config, 21 is currently rolled out to only 30% of 20 users. So it still seems to be in some kind of testing phase. I guess the docker stable tag will be updated soon after 21 is rolled out to 100% of 20 users.

**Comment by floriank26** [comment]
Did you now when they update the docker stable tag? So on the offical Website NC21 is already stable

**Comment by Bleuzen** [comment]
@floriank26 For new installations they provide NC21 on the website. But in the updater they still roll out NC21 to only 30% of NC20 users. So the update seems not stable yet. Guess we will have to wait for the next NC21 update, which will be 21.0.3 and is planned to release on July 01, 2021.

**Comment by hajo62** [comment]
NC 21.0.3 is there but _stable_ still referres to 20.0.11.1

**Comment by Bleuzen** [comment]
@J0WI they roll out 21.0.3 to 70% of 20.0.11 users on the official updater now. Maybe the docker stable image can be updated to 21.0.3 now too. What do you think?

**Comment by floriank26** [comment]
The 21 version is already being rolled out to 100 percent of 20 users, according to the official updater. Only on Dockerhub is version 20 still offered as stable.

**Comment by J0WI** [comment]
Fixed in #1538
