### ISSUE TITLE
no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by Emporea** [nextcloud/docker#1500]
I get this message when trying to upgrade from 20.0.9 -> 20.0.10 via

`docker-compose pull; docker-compose up -d --build`

`no matching manifest for linux/amd64 in the manifest list entries`

I am on Ubuntu Server 18.04
Kernel 4.15

**Comment by tarioch** [comment]
Looks like they are still building and the build system is overloaded
https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/nextcloud/

**Comment by eleith** [comment]
build completed.
