### ISSUE TITLE
Arm images missing for 21.0.2 and 20.0.10

### ISSUE THREAD

**Issue by TheGreatestJannet** [nextcloud/docker#1503]
It seems that images for armv7 and armv8 are missing for 21.0.2 and 20.0.10. Is this normal or has an error happened?

**Comment by bkk87** [comment]
I am running nextcloud:**stable** on Debian Buster (arm64)/Raspberry Pi 4.

The tags at Dockerhub show new arm64 images for nextcloud:stable (which is **20.0.10** at this point in time)

> TAG
> stable
> Last pushed3 days agobydoijanky
> Digest
> OS/ARCH
> Compressed Size
> linux/arm/v5
> 260.98 MB
> 36fdcdc77174
> linux/arm/v7
> 257.28 MB
> **508b3673ec1c
> linux/arm64/v8
> 273.96 MB**

However, I am **not** getting that image tag (508b3673ec1c). Instead, I am still getting an old one:
```
docker pull nextcloud:stable
stable: Pulling from library/nextcloud
Digest: sha256:1f2962b92ef6850df0033a7d2089dc7b34aca87fb18b043df8ead7bbae870126
Status: Image is up to date for nextcloud:stable
```

which is **20.0.9**

**Comment by sleiner** [comment]
Same here for `latest`: Both on my Intel and on my Arm64 machine, when I pull `nextcloud:latest`, I get the 21.0.1 images, not 21.0.2.

Of course, on Intel I can pull the `21.0.2` tag. On Arm64 that is not possible as the tag currently does not contain any Arm64 image.

**Comment by TheGreatestJannet** [comment]
ARMV5 has appeared now but still no sign of ARM64. Maybe we will have to manually build it now.

**Comment by TheGreatestJannet** [comment]
ARMv7 is there. Hopefully ARM64 comes soon.

**Comment by TheGreatestJannet** [comment]
The ARM64 docker image is now out. Thank you!
