### ISSUE TITLE
HTTPS for images

### ISSUE THREAD

**Issue by prophet89** [nextcloud/docker#1522]
Hi,
i have an Feature Request to the Docker Apache Images of Nextcloud.

it would be nice if the image has an baked in ssl support for use attached is an draft of this feature

`
VOLUME /etc/apache2
RUN {\
	 a2enmod ssl ;\
	 a2ensite default-ssl ;\
     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
    -subj "/C=US/ST=Nextcloud/L=Nextcloud/O=IT/CN=nextcloud.local" \
    -keyout /etc/apache2/nextcloud.local.key  -out /etc/apache2/nextcloud.local.cert ;\
     sed -i s#/etc/ssl/certs/ssl-cert-snakeoil.pem#/etc/apache2/nextcloud.local.cert# /etc/apache2/sites-available/default-ssl.conf ;\
     sed -i s#/etc/ssl/certs/ssl-cert-snakeoil.key#/etc/apache2/nextcloud.local.key# /etc/apache2/sites-available/default-ssl.conf ;\
	}
`
would be really nice if you build this in 

Br,

**Comment by J0WI** [comment]
I'd rather use a proxy. You can find some examples for inspiration here: https://github.com/nextcloud/docker/tree/master/.examples#with-nginx-proxy

**Comment by prophet89** [comment]
for the password app from nextcloud you need the app server and the frontend https secured but for now it's solved for me i have done this manually by adding to the webserver config the https level with self signend certificate

**Comment by joshtrichards** [comment]
Thanks for your suggestion! :+1: 

> for the password app from nextcloud you need the app server and the frontend https secured but for now it's solved for me i have done this manually by adding to the webserver config the https level with self signend certificate

Not sure what which requirement you're referring to for "the password app" that isn't met by a properly configured HTTPS reverse proxy / TLS/SSL termination point.

In any case, sounds like you found a solution that works for you. That's great.

However, if you use one of the examples you won't have to mess with self-signing at all nor manually update certs every time expiration time arises.

Adding a self-signed cert that can't be managed appropriately into the base image seems currently out of scope for the Docker image. I'm going to close this for now on that basis.
