### ISSUE TITLE
mariadb needs to be locked to 10.5

### ISSUE THREAD

**Issue by pbek** [nextcloud/docker#1536]
Today the `mariadb:latest` [docker image](https://registry.hub.docker.com/_/mariadb) got bumped to 10.6.3. :fearful:
After an update you will run into https://help.nextcloud.com/t/update-to-next-cloud-21-0-2-has-get-an-error/117028/14 with Nextcloud 21!
Doing a `image: mariadb:10.5` helped!

I wanted to create a pull request for the documentation change in the readme (https://github.com/nextcloud/docker/commit/94a24c2385a7be70a23a1c02661ddc4c675f4c32), but I didn't realize I've write permission to the repository, so the commit went through directly into the master branch. I'm sorry.

**Comment by pbek** [comment]
Now with proper PR: https://github.com/nextcloud/docker/pull/1537

**Comment by pbek** [comment]
Maybe this also could be fixed with `--skip-innodb-read-only-compressed` in mariadb 10.6...

**Comment by Vitlik** [comment]
Can confirm.
The error was gone with `--skip-innodb-read-only-compressed`

thx!

**Comment by pbek** [comment]
Thank you for confirming!

**Comment by swiesend** [comment]
Where do I have to put this option `--skip-innodb-read-only-compressed` if I do not want to downgrade to `10.5`? I have a `docker-compose` setup.

**Comment by pbek** [comment]
I haven't tested it, but yes, I guess you need to add it to `command`. But I didn't dare to stay on 10.6, do you need anything from 10.6 (until this issue is resolved in Nextcloud itself)?

**Comment by Vitlik** [comment]
Yes, my command line looked like this:
`command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed`

**Comment by swiesend** [comment]
No not really, but I see myself running into annoying problems when staying on `10.5` and forget about updating it in my `docker-compose.yml` in the future.

**Comment by pbek** [comment]
https://mariadb.com/kb/en/changes-improvements-in-mariadb-105/ says:

MariaDB 10.5 is the current major stable version The first stable release was in June 2020, and it **will be supported until June 2025**.

**Comment by LukBukkit** [comment]
Hey, I just want to throw in a link to the issue #1492, which solves the problem for MariaDB 10.6 using the parameter `--innodb-read-only-compressed=OFF`. I guess it functions the same as `--skip-innodb-read-only-compressed`.

**Comment by x86dev** [comment]
Just got the same issue and can confirm that downgrading to 10.5 helped! Thanks!

**Comment by DukeSniper** [comment]
I don't see a need for locking nextcloud to a specific mariadb version. IMO it makes a lot more sense to remove the forced conversion to COMPRESSED rows

**Comment by x86dev** [comment]
As long as the official Dockerfile / compose does not explicitly do that I'd rather stick with 10.5 and wait for an official solution.

**Comment by DukeSniper** [comment]
I wasn't referring to a user's temporary solution. I meant that as an **official** solution, the *COMPRESSED* tables and rows should not be used. Deprecation of that feature in MariaDB has been talked about for quite a while now, and it will be completely removed sooner than later, so it kinda worries me that NextCloud still forcibly uses a feature that was basically **known** to break NextCloud installations as soon as MariaDB-10.6 was going to be declared stable.

**Comment by axllent** [comment]
I agree with @DukeSniper - the [official requirements](https://docs.nextcloud.com/server/20/admin_manual/installation/system_requirements.html) states "MariaDB 10.2+", and the latest stable [MariaDB](https://mariadb.com/downloads/) is 10.6, so yeah - Nextcloud needs to find a solution that is forwards compatible, even if it means removing compression. I was also caught out by this issue, and many others surely will too as distros progress to MariaDB 10.6. I use docker too, but not with docker-compose as my MariaDB serves more than just Nextcloud. Not everyone is necessarily in a position to downgrade or determine their MariaDB version or startup options either. MariaDB 10.6.0 (where this change was introduced) was released 3 months ago.

**Comment by DukeSniper** [comment]
> https://mariadb.com/kb/en/changes-improvements-in-mariadb-105/ says:
> 
> 
> 
> MariaDB 10.5 is the current major stable version The first stable release was in June 2020, and it **will be supported until June 2025**.

As of today, 10.5 is just **a** stable release, with 10.6 being the **latest** stable

**Comment by x86dev** [comment]
Interesting details, as I'm not too deep into database stuff. I just caught the issue by watchtower upgrading my Docker stack (to MariaDB 10.6) automatically. The rest of my stack which also uses the very same MariaDB instance was also happy running with 10.6.

**Comment by thomasmerz** [comment]
I successfully reverted to MariaDB 10.5 with these changes in my `docker-compose.yml` file and my Nextcloud is running with version 22 again 👍🏻 

```
diff --git a/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml b/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml
index b00761b..07ebf58 100644
--- a/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml
+++ b/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml
@@ -2,13 +2,13 @@ version: '3'

 services:
   db:
-    image: mariadb
+    image: mariadb:10.5
     command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
     restart: always
```

**Comment by MrReSc** [comment]
Are there any plans to solve this problem or do we always have to stay on version 10.5?

**Comment by MrReSc** [comment]
> > Are there any plans to solve this problem or do we always have to stay on version 10.5?
> 
> You don't **need** to stay on 10.5, as 10.6 still offers a compatibility setting (innodb-read-only-compressed=OFF) which reverts the behavior to 10.5 style, allowing write access to the compressed tables. However, I recommend watching the mariadb release notes closely, as this compatibility feature is deprecated and will soon be removed. Possibly already somewhere in the 10.7 series

Yes, I know this possibility too. As you mentioned, it will soon no longer work. That's why I asked whether Nextcloud will solve the problem.

**Comment by DukeSniper** [comment]
According to https://github.com/nextcloud/server/issues/25436#issuecomment-883213001 it's not about to happen any time soon 🤷‍♂️

**Comment by barqers** [comment]
> > Are there any plans to solve this problem or do we always have to stay on version 10.5?
> 
> You don't **need** to stay on 10.5, as 10.6 still offers a compatibility setting (innodb-read-only-compressed=OFF) which reverts the behavior to 10.5 style, allowing write access to the compressed tables. However, I recommend watching the mariadb release notes closely, as this compatibility feature is deprecated and will soon be removed. Possibly already somewhere in the 10.7 series

This can't be a permanent solution because running mariadb with that compatibility setting crashes mariadb for me, so it's not even an option...

**Comment by yosoufe** [comment]
Somebody needs to update the docker-compose file in the dockerhub description as well. https://hub.docker.com/_/nextcloud

**Comment by keunes** [comment]
For information: this will apparently be fixed with NC24: https://github.com/nextcloud/server/issues/25436#issuecomment-1016204995
