### ISSUE TITLE
Open Updater returns error

### ISSUE THREAD

**Issue by pcmedicaus** [nextcloud/docker#154]
When a new version is available, clicking on 'Open Updater' results in 'Could not start updater, please try the manual update'. This happened using the older docker image 12.01 attempting to go to 12.02 and also in the newer 12.02 image trying to go to 12.03rc. Running docker on Ubuntu server 16.04.

**Comment by tilosp** [comment]
The updater is intentionally disabled. We want the user to update using docker. Take a look at https://github.com/nextcloud/docker#update-to-a-newer-version
