### ISSUE TITLE
the latest docker image does not contain the correct version

### ISSUE THREAD

**Issue by paulknulst** [nextcloud/docker#1567]
the [docker image](https://hub.docker.com/_/nextcloud) was updated today but did not have the correct version.

as you can see [here](https://hub.docker.com/layers/nextcloud/library/nextcloud/latest/images/sha256-9157133520e128be91fe94b9f03a3fe162f9acf2677fb59c92b6ddfb61fd9967?context=explore ) in LINE 40 it has still the old ENV-variable.

yesterday a new patch was applied bringing nextcloud to version 22.1.1. the docker image nextcloud:latest is still 22.1.0
is this a bug within the image?

**Comment by GuidoDr** [comment]
well at least there is not yet an image with tag 22.1.1 on the server.
Nextcloud keeps informing me that I should upgrade our server to 22.1.1 but with the image I cannot upgrade yet.
I hope that Nextcloud will soon release the correct docker images.

**Comment by paulknulst** [comment]
thats exactly my problem :D

**Comment by GuidoDr** [comment]
22.1.1 is now since 5 hours on the server, so I think you can close this issue. ;-)

**Comment by paulknulst** [comment]
oh thank you. i will have a look and close this. thx

**Comment by BorussiaPlayer17** [comment]
I deaktivated the "Update notification" so you don't always get the notification that an update is available. ;-P

But yes. Update is online.
