### ISSUE TITLE
Error upgrading to 22.1.0

### ISSUE THREAD

**Issue by steveaggie** [nextcloud/docker#1569]
I'm on version 21.0.2.1 trying to upgrade to 22.1.0.  I'm using the docker image nextcloud:latest.

When I login it asks me to update the database and then says:

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Exception: Database error when running migration latest for app core

The update was unsuccessful. Please report this issue to the Nextcloud community.

**Comment by BorussiaPlayer17** [comment]
Are you using docker-compose? Check if your MariaDB is set to Version 10.5. Thats an issue at the moment. 

https://github.com/nextcloud/docker/issues/1536

**Comment by BitBernd** [comment]
Thanks a lot, saved my install. I have backup of everything including db and stuff but man I don't have time for this right now. Setting MariaDB to 10.5 worked like a charm

**Comment by steveaggie** [comment]
Yes, that fixed it for me also.  I had a post up on Nextcloud support forums b/c this forum didn't look very active.  Setting the maridb image to 10.5 helped me too.

**Comment by BorussiaPlayer17** [comment]
I'm glad I could help! :-)
