### ISSUE TITLE
image tag:22.1.1 no /etc/ldap/ldap.conf file

### ISSUE THREAD

**Issue by findlayfeng** [nextcloud/docker#1572]
Causes ldaps to be unavailable unless you choose to ignore certificate verification

**Comment by DizTortion** [comment]
Manually installing libldap-common fixed the problem. 

See: https://github.com/docker-library/php/issues/1194#issuecomment-904954896

**Comment by johnstonjs** [comment]
Thanks!  That fixed the problem for me.  Will libldap-common be installed in the next version of this image?

**Comment by steffen-kdab** [comment]
ldap/TLS stopped working for me when I updated to the latest 22-apache image. Manually creating /etc/ldap/ldap.conf with the contents `TLS_CACERT /etc/ssl/certs/ca-certificates.crt` solves it. Hope there will be an updated image soon, thanks!

**Comment by smoebody** [comment]
this issue affects 20.0.12 and 21.0.4 as well

**Comment by awlx** [comment]
Can confirm after adding `ldap.conf` via a volume it works again ...

**Comment by MohammedNoureldin** [comment]
I confirm that installting `libldap-common` seems to resolve the issue!
