### ISSUE TITLE
missing file (/etc/ldap/ldap.conf) in docker image 22.1.1

### ISSUE THREAD

**Issue by kleinundzusammen** [nextcloud/docker#1580]
The docker image 22.1.1 is missing in the image.
These commands fixed it for me:
mkdir /etc/ldap 
echo "TLS_CACERT      /etc/ssl/certs/ca-certificates.crt" >> /etc/ldap/ldap.conf

**Comment by mmasdoria** [comment]
same issue in when upgrading from 21.0.3 to 21.0.4 (debian 10 to debian 11). LDAPS don't work anymore even after addind ldap.conf.

**Comment by kleinundzusammen** [comment]
Hi, 
i also installed "ldap-utils" in the container. For me its working again.

**Comment by kleinundzusammen** [comment]
Looks like a double to https://github.com/nextcloud/docker/issues/1572

**Comment by ZaDafu** [comment]
after apt install and docker commit ，the ldap can't work yet

**Comment by lknite** [comment]
@kleinundzusammen how are you getting your additional certificate installed on the docker image?
