### ISSUE TITLE
update nextcloud to 22.1.1 no video preview

### ISSUE THREAD

**Issue by wangzhengzhen** [nextcloud/docker#1591]
Video preview cannot be generated after image upgrade
That was fine in the previous version

apt install ffmpeg imagemagick ghostscript
![image](https://user-images.githubusercontent.com/6226945/134613462-326f494e-e67c-43a0-ac68-ebc5ec13cd67.png)

![image](https://user-images.githubusercontent.com/6226945/134613530-168b3e46-5822-4436-a85c-4f46de651852.png)

**Comment by J0WI** [comment]
Maybe related to https://github.com/nextcloud/server/pull/28895
