### ISSUE TITLE
22.2.0-apache: Not available for arm64

### ISSUE THREAD

**Issue by AaronDewes** [nextcloud/docker#1598]
The version 22.2.0 of this image isn't available for `linux/arm64` (or `linux/arm64/v8`) anymore. Was this intentionally dropped?

**Comment by amiga23** [comment]
:-( Any update on this issue? Are you planning to fix it?

**Comment by amiga23** [comment]
I've moved over to https://github.com/linuxserver/docker-nextcloud
They use different directory structure. volume "data" needs to be mounted to /data, volume "config" needs to be mount to /config/www/nextcloud/config, content of volume "nextcloud" needs to be moved to www/nextloud and then mounted to /config. In your config.php you need to change the path of the datadir to /data.
Then you need to copy the updater folder into /data/www/nextcloud
PUID and PGID need to be set to 33 or you chmod the files to whatever you want.
Works like a charm and should be much simpler to upgrade.

**Comment by amiga23** [comment]
@mohammedyonusm I'm using Kubernetes. But there is a docker compose example in the readme:
https://github.com/linuxserver/docker-nextcloud#docker-compose-recommended-click-here-for-more-info
You may join their discord, they react very quick.
