### ISSUE TITLE
Nextcloud - containers as no-root 

### ISSUE THREAD

**Issue by qdupuy** [nextcloud/docker#1604]
Hello,

Currently I am in a kubernetes environment deployed with rke2 in its latest version, so I am with the containerd runtime.

Containerd doesn't allow images to run as root.

```
Warning  Failed     1s (x4 over 29s)  kubelet            Error: container has runAsNonRoot and image will run as root (pod: "x-nextcloud-67c75c879c-5jfwm_x(b77c39c1-bd87-43c5-899c-9313f96bdab3)", container: nextcloud)
```

Would it be possible to make an image that does not use the root user?

Best regards,

**Comment by RlndVt** [comment]
Nextcloud mostly works* when running as a specific non-root UID using something like `docker run --user 1000:100`.

[*] Redis and the cron job do not work.

**Comment by ducarrozb** [comment]
Hi,
There is something I don't understand (sorry for the question, I am quite new to docker and nextcloud).
When I run my container using i.ex. the command 

`docker-compose -f --user someuser /myfolder/docker-compose.yml up -d`

means this that I am running now the container as `someuser`, right?

but now when I log into my nextcloud docker container or when I try to find out the nextcloud user like this... 
`docker run --entrypoint "" <image-name> whoami`
 ... I get "root".

This means that the container itself has root privileges. 
1) Should I change this to a non-root user?
2) If so, how can I manage this? 
3) Why is the nextcloud container running as root by default? Isn't this a security issue?

I found this issue: https://github.com/nextcloud/docker/issues/458 but the proposed solution from  @rcdailey commented on 17 Aug 2019 does unfortunately not work in my case.

My entire docker-compose-file is listed in this issue: https://github.com/nextcloud/docker/issues/1641

Can someone please help me understand? - Thanks in advance.

**Comment by RlndVt** [comment]
For compose you need to specify the user in the app definition. So it isn't part of the docker-compose up command, but within the app specification.

`user: "www-data:www-data"`

By default the nextcloud container starts as root and then drops to www-data for most processes.
