### ISSUE TITLE
Nextcloud Docker image broken from time to time

### ISSUE THREAD

**Issue by Zegorax** [nextcloud/docker#1617]
From time to time, images published on Nextcloud's Docker Hub are broken.
For example, latest stable-apache image that has been published this night cannot start Nextcloud and instead throws this error :

`This version of Nextcloud is not compatible with > PHP 7.4.
You are currently running 8.0.11.`

It's really a big issues since my installations are set to auto-update using WatchTower, which will pull automatically the latest pushed image from Docker Hub.

This behavior is thrown in https://github.com/nextcloud/server/blob/732a05716719dfcb866ba14863500cfb357fe543/lib/versioncheck.php#L40

I believe the Docker images are using a PHP version that is too high.

**Comment by J0WI** [comment]
The PHP version follows the [recommendation](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#server) of Nextcloud: https://github.com/nextcloud/docker/blob/dcf058fb559e7918cd77f5f1bb0dfdbcee813571/update.sh#L4-L7

**Comment by joshtrichards** [comment]
Hi @Zegorax - It sounds to me like something is (or was) wrong with your setup/environment. At the time you reported this I believe you'd have to be running <=NC20 to get this error. At the time the most recent images would have been either NC21 or NC22 based. Somehow even though you were upgrading the base image, your Nextcloud app was not being upgraded. If you're still having this issue please post on the [Nextcloud Help Forum](https://help.nextcloud.com) to get it sorted out.

Let's close this Issue out.
