### ISSUE TITLE
Nextcloud fpm docker image with ldap support

### ISSUE THREAD

**Issue by mvarchdev** [nextcloud/docker#1618]
Hello. The nextcloud fpm docker image is not working with ldap support (users etc.) - cannot add server etc. Is this a bug or a configuration error? I cannot find any related documentation. Thanks in advance.
Maros V.

**Comment by KittyKatt** [comment]
I'm also experiencing this issue with nextcloud-fpm + nginx container on Swarm. No matter what I enter into the fields, I get "Bad base DN" when I try to test it. The "Detect port" button is also permanently grayed out.

**Comment by Sblop** [comment]
This is a problem in the nginx configuration. Add this:
```
        # Required for legacy support
        rewrite ^/(?!index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+|.+\/richdocumentscode\/proxy) /index.php$request_uri;

```
Unfortunately I cannot find where to add this in the official code...

**Comment by Sblop** [comment]
While checking further, this has been solved in this PR:
https://github.com/nextcloud/docker/pull/1635

**Comment by mvarchdev** [comment]
Thanks. Solved.
