### ISSUE TITLE
Network accessible but error "Could not connect to appstore: cURL error 28: Connection timed out" 

### ISSUE THREAD

**Issue by nodje** [nextcloud/docker#1628]
I'm not entirely sure this issue comes form the docker setup of Nextcloud, but as this is my only setup I have to make a guess.

My Nextcloud container network is fully working, I can `curl https://apps.nextcloud.com/api/v1/apps.json` manually from within it. Moreover I can send email from Nextcloud with SMTP configured.

But the GUI reports `This server has no working Internet connection` and logs warnings say `Could not connect to appstore: cURL error 28: Connection timed out`

I'm at a loss here, how could the network not work ?

NB: actually I've had this since my initial setup (probably dating back v20). I've regularly updated the image to 21, then 22, but I realize this is why I never got any apps available to install, and finally finding out why.

**Comment by nodje** [comment]
After reviewing many similar posts on the Nextcloud forum, I think I have to maintain this issue here.
Problems leading this situation are multiple, so are solutions, and they vary greatly. 
I couldn't find one that applies to my case.

Still not sure it's docker related, but I think this situation shouldn't occur on a container that has network access.
So something is amiss.

**Comment by nodje** [comment]
I realize now that connections fail with the following error:
```GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to 172.19.0.4 port 1080: Connection refused```
172.19.0.4 happens to be the IP of the container for the NC postgres database.

I find `'proxy' => '172.19.0.4',` in config/config.php. WTF?
Deleting this line just makes it work.
I never manually intervened on the `config/config.php`, only set Docker environment variables.
But none of the available variable can set the proxy asaik!

**Comment by joshtrichards** [comment]
Hi @nodje - I'm following up on older Issues in the repository. I can't think of a good reason why this happened off-hand. 

I don't think it was from the NC Docker image - I don't see anywhere that we do anything related to this  parameter. The image wouldn't even know what to do with it. But there are some circumstances where the Docker daemon can pass in proxy info and it may have gotten picked up by Nextcloud somewhere (e.g. https://docs.docker.com/network/proxy/). Of course that still doesn't explain where it came from originally. Glad you found the config entry that was causing you difficulty at least.

In the mean time, I don't think there's much to be done on this end at this point. If you agree this is no longer a matter to be dealt with here, can you close this Issue out to avoid confusion? Thanks!
