### ISSUE TITLE
Tag 22-apache: expected nextcloud 22.2.2, got 22.2.0

### ISSUE THREAD

**Issue by erikvanoosten** [nextcloud/docker#1629]
The [tag 22-apache](https://hub.docker.com/_/nextcloud?tab=tags&page=1&name=22-apache) was updated a few hours ago. I expected it to include to the latest release: 22.2.2. Instead it includes 22.2.0. Is this intentional or is this a bug?

**Comment by GuidoDr** [comment]
you are probably using docker images, right?
The docker images are always a little behind the actual version of nextcloud (mostly at least a day or two)
I do see on hub.docker.com that just 15 minutes ago the images for version 22.2.1 were published. (which has a major performance issue).
Version 22.2.2 is not yet available for docker.

**Comment by erikvanoosten** [comment]
Ah, that's how it works. Okay, thanks! I'll just be patient then!
