### ISSUE TITLE
missing documentation and patch delays on nextcloud:stable

### ISSUE THREAD

**Issue by bkk87** [nextcloud/docker#1630]
As of now, the nextcloud image with tag stable is 23 days old.
The nextcloud version for stable is 22.2.0 where the version for nextcloud:22 is 22.2.**2.**
This means that the stable tag is 2 patch versions behind.

I neither see the stable tag being mentioned on the dockerhub documentation nor here in this repo.

It is not the first time I recognized that stable does not reference the latest patch version.

As I am running my nextcloud in the internet, I am worried about this delay. 
Is the tag stable really meant for production use? Why is the tag not correctly documented like all the other tags on the main page of dockerhub?

**Comment by J0WI** [comment]
See https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what
