### ISSUE TITLE
Image for docker pull nextcloud:22.2.2

### ISSUE THREAD

**Issue by rightwayround** [nextcloud/docker#1632]
Hello

Please can someone push the latest image up to hub.docker.com?

Seems the latest is currently 22.2.1 & it's very very slow.

Thank you

**Comment by baalajimaestro** [comment]
It always happens because the images are built by Docker, the project developers do not control the way they are published.

Keep an eye on this for the builds

https://doi-janky.infosiftr.net/job/multiarch/view/images/view/nextcloud/

**Comment by fauust** [comment]
> the project developers do not control the way they are published.

It's a bit strange for a project like nextcloud to have to wait so long for new images to be available...

**Comment by bergi9** [comment]
Unraid told me there were an update of the nextcloud:latest. After apply the update it doesn't start as tells me: `Can't start Nextcloud because the version of the data (22.2.2.0) is higher than the docker image version (22.2.1.2) and downgrading is not supported. Are you sure you have pulled the newest image version?`
Before I updated the docker image nextcloud was on 22.2.1.2. How I can downgrade the data version back to 22.2.1.2?

**Comment by dayue1984** [comment]
Just updated to 22.2.1 with docker image, but found that they already called back the 22.2.1 update for performance problem, and made the 22.2.2 as a patched update, but now the latest docker version is 22.2.1, and the offical latest update is 22.2.2 ... nothing to do, just wait the new image

**Comment by fauust** [comment]
> EDIT: @baalajimaestro do you have any pointer about how the build of nextcloud containers works? I can't understand where the problem comes from. Maybe this is documented somewhere but I couldn't find it.

Found: https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what

Workaround:
```diff
diff --git a/docker/nextcloud/docker-compose.yaml b/docker/nextcloud/docker-compose.yaml
index 829fc00..47aeb90 100644
--- a/docker/nextcloud/docker-compose.yaml
+++ b/docker/nextcloud/docker-compose.yaml
@@ -14,7 +14,9 @@ services:
         tag: "nextcloud-redis"

   app:
-    image: nextcloud:fpm-alpine
+    build:
+      context: nextcloud-app/22/fpm-alpine/
+    # image: nextcloud:fpm-alpine
     restart: unless-stopped
     volumes:
       - /data/nextcloud:/var/www/html
```

**Comment by raimund-schluessler** [comment]
22.2.2. is on Docker hub now. 22.2.3 is not yet, though.

**Comment by dayue1984** [comment]
decided to build my own image on 22.2.3 with my tweaks lastnight，and it is working fine and fun

**Comment by fauust** [comment]
> decided to build my own image on 22.2.3 with my tweaks lastnight，and it is working fine and fun

yep, same here...

**Comment by raimund-schluessler** [comment]
> 22.2.3 isn't on Docker Hub because it hasn't shipped. See https://github.com/nextcloud/server/milestone/174 ... that currently says 7 open issues and 4 closed. What do y'all need that will be in 22.2.3?

The Github milestone isn't quite up-to-date. The download from the Nextcloud website gives 22.2.3: https://download.nextcloud.com/server/releases/nextcloud-22.2.3.zip

There is nothing in particular in 22.2.3 I wait for, 22.2.2 was more important.

**Comment by J0WI** [comment]
seems to be obsolete.
