### ISSUE TITLE
docker run with local volume for configdirectory  fails, named volume succesful  

### ISSUE THREAD

**Issue by hanscees** [nextcloud/docker#164]
Hi,

when I run this all works fine:

 docker run -d \
  -it \
  --name=nextcloudtest \
  -v nclconf:/etc/apache2/ \
  -v /root/dockvolumes/nextcloud_data:/var/www/html/ \
nextcloud:latest

however, when I run this:
 docker run -d \
  -it \
  --name=nextcloudtest \
  -v /root/dockvolumes/nextcloud_conf:/etc/apache2/ \
  -v /root/dockvolumes/nextcloud_data:/var/www/html/ \
nextcloud:latest

container somehow does not seem to mount the config volume and /var/log/daemon.log complains:
core 964704e00079[23475]: apache2: Could not open configuration file /etc/apache2/apache2.conf: No such file or directory

see also https://github.com/docker/compose/issues/5227

**Comment by SnowMB** [comment]
do you have a `apache2.conf` file on your host in the folder  `/root/dockvolumes/nextcloud_conf`?

**Comment by marceljd** [comment]
I think the file was missing, can be closed. The linked compose issue was also closed because of the same issue.
