### ISSUE TITLE
When will Nextcloud 23 be published?

### ISSUE THREAD

**Issue by rugk** [nextcloud/docker#1645]
[Nextcloud v23 has been release and the instance recommends to upgrade](https://nextcloud.com/blog/nextcloud-hub-2-brings-major-overhaul-introducing-nextcloud-office-p2p-backup-and-more/).

But the latest tag I can [see on Docker Hub](https://hub.docker.com/_/nextcloud?tab=tags) is v22.2.3.

So when will that Docker be available?

**Comment by arlostt** [comment]
Usually takes a few days after a release for the docker image to be updated.

**Comment by JonasToth** [comment]
docker-hub has images for 23. can be closed?
