### ISSUE TITLE
apache2 based image can not update to Nextcloud 23

### ISSUE THREAD

**Issue by JonasToth** [nextcloud/docker#1647]
- I want to update my `nextcloud` installation from `22-apache` to `23-apache`. It seems that the database migration fails.
- `docker-compose` is used, the complete file follows

Is this just a bad database migration or is my database in a bad state?
I will revert the database to its previous state and use nextcloud-22 for now. I can try a solution to this and verify if it works. The instance holds nothing mission critical or expensive.

## Executed commands

```bash
$ docker-compose down --remove-orphans
$ vim docker-compose.yml # Edit the image tag
$ docker-compose pull
$ docker-compose up -d
$ docker-compose logs -f
> Shows the error messages
```

## Database Logs

```bash
$ docker-compose logs
...
db_1   | 2021-12-02 12:27:15.786 UTC [43] ERROR:  relation "user_id" already exists
db_1   | 2021-12-02 12:27:15.786 UTC [43] STATEMENT:  CREATE UNIQUE INDEX user_id ON oc_profile_config (user_id)
....
```

## Nextcloud logs

- changing the image in used triggered the first update process, that failed
- manual upgrade using `occ`

```bash
$ docker exec -ti -u 33 <containerid-of-nextcloud-instance>
$ www-data@9b5536db89c2:~/html$ ./occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Updating database schema
Exception: Database error when running migration latest for app core
Update failed
Maintenance mode is kept active
Resetting log level
```

## Used docker-compose

This should be pretty much the example docker-compose version for apache. I changed the paths to match my local machines mounts.

```bash 
$ cat docker-compose.yml
version: '3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - /mnt/data/nextcloud-database:/var/lib/postgresql/data
    env_file:
      - db.env

  app:
    # I change the next line from 'nextcloud:22-apache' to 'nextcloud:23-apache'
    # I upgrade nextcloud 22 yesterday to its latest docker image, that went all fine
    image: nextcloud:23-apache
    restart: always
    ports:
      - 80:80
    volumes:
      - /mnt/data/nextcloud-docker:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
    env_file:
      - db.env
    depends_on:
      - db
```

**Comment by sirautj** [comment]
Related to https://github.com/nextcloud/server/issues/29986

Same problem here

**Comment by JonasToth** [comment]
Fix committed

**Comment by ChrWieg** [comment]
Same issue upgrading latest amd64/nextcloud:22-fpm to amd64/nextcloud:23-fpm. This fixed the Problem: https://github.com/nextcloud/server/issues/29986#issuecomment-983279033. PostgreSQL 12.9.

**Comment by J0WI** [comment]
Fixed according to comments
