### ISSUE TITLE
You are not tagging this repository correctly

### ISSUE THREAD

**Issue by danger89** [nextcloud/docker#1660]
The latest tag from this Docker repo comes from 2020: https://github.com/nextcloud/docker/tags

What the hell is going on here?

Your tags should be in-line with the tags used in Docker Hub: https://hub.docker.com/_/nextcloud?tab=tags

Regards,
Melroy

**Comment by cubuzz** [comment]
I'm sorry, but that's definitely not the case. Last push to docker hub was 4 hours ago.
![image](https://user-images.githubusercontent.com/30159582/147126945-b8045358-c54b-45e3-8397-b067be144a22.png)

**Comment by danger89** [comment]
> I'm sorry, but that's definitely not the case. Last push to docker hub was 4 hours ago. ![image](https://user-images.githubusercontent.com/30159582/147126945-b8045358-c54b-45e3-8397-b067be144a22.png)

You are right. I'm wrong. I didn't know what happened. Sometimes docker hub interface is buggy when a new tag is getting pushed.

**Comment by danger89** [comment]
Why the down votes? I was talking about the nextcloud on github? Github tags are very outdated!?

And github should be inline with docker hub.

**Comment by JuniorJPDJ** [comment]
There's just one branch for maintaining all currently maintained versions of images. That's why you can't just tag version of nextcloud using git.

**Comment by danger89** [comment]
Git tags can be done from the same git branch. I don't see why that can't be done to be honest.

How otherwise could be open the source code of nextcloud that is inside specific nextcloud docker image?

**Comment by martadinata666** [comment]
so here is the thing, this only generate docker image based on upstream release instead the release tag of this repo itself. Maybe it used to, with the release tag, but now it automated with upstream release. Checking the workflow maybe givin you more insight

**Comment by J0WI** [comment]
The tags in this repo are not applicable for Docker images, they are published here:
https://github.com/docker-library/official-images/blob/master/library/nextcloud
