### ISSUE TITLE
Question: Is there a simple way to change the base URL?

### ISSUE THREAD

**Issue by aanno** [nextcloud/docker#167]
Hello,

I wonder if there is a simple way to change the base URL, i.e. instead of serving nextcloud from `https://example.com/`, could I tweak the configuration to use `https://example.com/nextcloud/`? Can it be archived with apache and/or fpm?

Kind regards,

aanno

**Comment by aanno** [comment]
Based on your image, this was easy to archive. If modified the project accordingly at https://github.com/aanno/nextcloud-docker . You could also get an docker image at https://hub.docker.com/r/aanno/nextcloud/.

An complete example using that is at https://github.com/aanno/linux-config/tree/master/docker-compose/nextcloud for reference.

**Comment by h-castle** [comment]
there is a config to be set in config/config.php - 'overwritecondaddr' (like this 'overwritecondaddr' => 'nextcloud',).

**Comment by art-in** [comment]
see overwrite parameters in [reverse proxy configuration](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html#overwrite-parameters) doc.

eg. `config.php`:
```php
<?php
$CONFIG = array (
  'overwriteprotocol' => 'https',
  'overwritehost'     => 'example.com',
  'overwritewebroot'  => 'nextcloud',
);
```

probably to only change base URL `overwritewebroot` should be enough.
