### ISSUE TITLE
Example nginx conf denies access to /data but nextcloud does make a request every time

### ISSUE THREAD

**Issue by pr4xx** [nextcloud/docker#169]
Hey there,
I am using a docker-compose installation with fpm, nginx reverse proxy etc. Today I was looking at the nginx logs and found a reoccuring message:
`[error] 7#7: *213 access forbidden by rule`

This is the rule:
```
location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
        }
```
(Mind "data" at the end of the list)
When I open nextcloud in the browser and visit the admin page, my client will always do an ajax request to the following endpoint and will fail because of the deny rule:
![Firefox](https://i.imgur.com/ZjDTVOm.png)

The question is: why does nextcloud make this request and why is there a deny rule for it? Which side is "wrong" here?

**Comment by tilosp** [comment]
It's supposed to work like that.
Take a look at: https://help.nextcloud.com/t/client-denied-by-server-configuration-ocdata/13250/4
