### ISSUE TITLE
upgrade from 22 to 23 with REDIST_HOST set via docker -e fails

### ISSUE THREAD

**Issue by darena67** [nextcloud/docker#1691]
Hi if I have REDIST_HOST set in my docker run command as a -e REDIST_HOST="hostname.blah" then I get a:

Configuring Redis as session handler
/entrypoint.sh: 60: Bad substitution

removing REDIST_HOST from docker run line fixes the error and nextcloud starts up.

**Comment by mr700** [comment]
Duplicate of #1699?
