### ISSUE TITLE
PHP OPcache module is not properly configured: OPcache interned strings buffer is nearly full

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/docker#1692]
Since upgrading to 23, I'm seeing this at `/settings/admin/overview`:

* The PHP OPcache module is not properly configured:
    * The OPcache interned strings buffer is nearly full. To assure that repeating strings can be effectively cached, it is recommended to apply `opcache.interned_strings_buffer` to your PHP configuration with a value higher than 8.

I haven't changed any PHP settings, I'm just using the upstream `nextcloud` image with the tag `23`. Looks like I have version `23.0.1.2` now.

Possibly related: https://community.nethserver.org/t/nextcloud-the-php-opcache-module-is-not-properly-configured/19732/1

**Comment by floryn90** [comment]
+1
This issue is also affecting my instance - docker container

**Comment by kimbtech** [comment]
As the value is set in the Dockerfile and thus would be overwritten when pulling an updated image. 
It would be best to change the lines https://github.com/nextcloud/docker/blob/master/Dockerfile-debian.template#L96 and https://github.com/nextcloud/docker/blob/master/Dockerfile-alpine.template#L82?

**Comment by schadom** [comment]
> As the value is set in the Dockerfile and thus would be overwritten when pulling an updated image. It would be best to change the lines https://github.com/nextcloud/docker/blob/master/Dockerfile-debian.template#L96 and https://github.com/nextcloud/docker/blob/master/Dockerfile-alpine.template#L82?

Same here. Agree.

**Comment by rugk** [comment]
Okay, created a PR https://github.com/nextcloud/docker/pull/1702

**Comment by rubo77** [comment]
To solve this until the PR is added:

```
docker exec -i -t next_your_domain_app_1 bash -l
sed -i "s/;opcache.interned_strings_buffer=8/opcache.interned_strings_buffer=256/g" /usr/local/etc/php/php.ini-production | grep opcache.interned_strings_buffer
apache2ctl graceful
```

**Comment by WNYmathGuy** [comment]
I'm having this trouble after upgrading today, but setting it to 16 and rebooting the server still persists with the error message. Jacked it up to 32 and still, the error message persists after a server reboot.
