### ISSUE TITLE
Where is the new images?

### ISSUE THREAD

**Issue by kemoantemo** [nextcloud/docker#1697]
The latest tag is still 23.0.1 where is 23.0.2? On the overview page, the latest version is 23.0.2 but it's not published in the docker hub so is there is a problem on my side or what?
Ty in advance.

**Comment by rwese** [comment]
It always takes a couple of days for the docker-image version to catch up sadly.

**Comment by kemoantemo** [comment]
> It always takes a couple of days for the docker-image version to catch up sadly.
> 
> As of now the build is also failing:
> 
> https://github.com/nextcloud/docker/actions/runs/1855988508

Ty for replying wanted to ask for 1 more thing can i build the image locally or i must wait?

**Comment by SuperSandro2000** [comment]
> As of now the build is also failing:

They are failing for 23.0.2. I hope that isn't blocking 22.2.5..

**Comment by EthanLeisinger** [comment]
It would appear an retrieving i386 compatible libraries is failing on the 23.0.2 fpm-alpine build. This error is breaking the deployment of all images.

**Comment by Crocmagnon** [comment]
IMO this issue shouldn't be closed.

**Comment by kemoantemo** [comment]
> IMO this issue shouldn't be closed.

I just closed it because I didn't know that we can build the image ourselves so we don't need to wait for the hub image

**Comment by EthanLeisinger** [comment]
The builds are now completing successfully. This issue can be closed 🎉
