### ISSUE TITLE
Remove VIRTUAL_PORT env in collabora/code section

### ISSUE THREAD

**Issue by universalex** [nextcloud/docker#1707]
The example file did not work until i removed the VIRTUAL_PORT env. I guess collabora doesn't provide services on port 443 but on 9980.
https://github.com/nextcloud/docker/blob/52650497660678ef31476ade50375b833c7eae8d/.examples/docker-compose/with-nginx-proxy-self-signed-ssl-collabora-office-mariadb/docker-compose.yml#L97

**Comment by joshtrichards** [comment]
Yes, these configs became a bit dated and also operate differently depending on Docker network config, etc.

This config file has been removed from the examples so it's no longer applicable.
