### ISSUE TITLE
docker-compose/with-nginx-proxy/postgres/fpm not working

### ISSUE THREAD

**Issue by kevlar1818** [nextcloud/docker#171]
I set up a subdomain on duckdns.org, and followed the instructions in the README:

```
# ./docker-compose/with-nginx-proxy/postgres/fpm/db.env
POSTGRES_PASSWORD=i_filled_this_out
POSTGRES_DB=nextcloud
POSTGRES_USER=nextcloud
```

```
# ./docker-compose/with-nginx-proxy/postgres/fpm/docker-compose.yml
# ...
    environment:
      - VIRTUAL_HOST=not_really_my_sub.duckdns.org
      - LETSENCRYPT_HOST=not_really_my_sub.duckdns.org
      - LETSENCRYPT_EMAIL=not_really_my_email@gmail.com
# ...
```

I forwarded the following ports on my router: 80, 443 (SSL), and 5432 (Postgres).

I `docker-compose up -d` and I can access the setup screen at https://not_really_my_sub.duckdns.org as planned. However, I cannot connect to the database. I use the same credentials as in `db.env`, and I use `not_really_my_sub.duckdns.org:5432` as the database host in the Nextcloud setup UI. This looks like the relevant error in the log; it's the first log message after I submit the setup form in the web UI:

```
web_1  ... [error] 6#6: *18 access forbidden by rule, client: 172.21.0.4, server: , request: "GET /data/htaccesstest.txt HTTP/1.1", host: "not_really_my_sub.duckdns.org"
```

Any help?

**Comment by SnowMB** [comment]
Your database host is not correct. The database is not accessible from the internet, so if nextcloud tries to connect to `not_really_my_sub.duckdns.org:5432` nothing is responding. 

The database container lives in a virtual network with the nextcloud container. Use just `db` as name of the database host.

**Comment by kevlar1818** [comment]
That makes a lot more sense! It looks like it's working now. Thanks!
