### ISSUE TITLE
MySQL Group Replication: Missing primary key (or key) in oc_gluu_sso

### ISSUE THREAD

**Issue by infroger** [nextcloud/docker#172]
I'm following the "Migrating an existing installation" section of the Nexcloud Docker Readme and have an issue in step 2 (restore database from mysqldump).

I have a running instance of NC 11 and I'm trying to import the data to a new docker instance of NC 12. When I run the mysql import step, I get:

```
CREATE TABLE `oc_gluu_sso` (
  `gluu_action` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `gluu_value` text COLLATE utf8_bin,
  UNIQUE KEY `gluu_action` (`gluu_action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin

INSERT INTO `oc_gluu_sso` VALUES (...)

ERROR 3098 (HY000) at line 1486: The table does not comply with the requirements by an external plugin.
```

The error message is saying that there is a requirement missing in MySQL Group Replication plugin.

From MySQL Manual:

> 
https://dev.mysql.com/doc/refman/5.7/en/group-replication-requirements.html
Primary Keys.  Every table that is to be replicated by the group must have a defined primary key, or primary key equivalent where the equivalent is a non-null unique key. Such keys are required as a unique identifier for every row within a table, enabling the system to determine which transactions conflict by identifying exactly which rows each transaction has modified.
> 

It looks like the structure of some tables of Nextcloud are not compatible with MySQL Group Replication (MGR).

I noticed that Nextcloud Admin Manual recommends Galera Cluster for database replication. The case is that my company already has a MGR cluster homologated for other solutions and it would require substantial effort and resources to implement another MySQL cluster solution.

#1 question: is it possible that future releases of Nextcloud comply with the requirement of having primary keys in all tables and thus allow us to use MGR as a database replication method?

It seems that only three tables don't have KEY or PRIMARY KEY: 

```
+-------------------------------+
| table_name                    |
+-------------------------------+
| oc_gluu_sso                   |
| oc_spreedme_room_participants |
| oc_systemtag_object_mapping   |
+-------------------------------+

```

#2 question: I'm going to create a primary key autoincrement column in those tables. Any concerns beyond broken upgrades in the future?

**Comment by SnowMB** [comment]
That seems like an issue you should ask over at [nextcloud/server](https://github.com/nextcloud/server).

**Comment by lsyarn** [comment]
You need a primary key or a NOT NULL unique key.

**Comment by J0WI** [comment]
This seems to be an upstream issue.
