### ISSUE TITLE
23.0.3 images not available several days after release

### ISSUE THREAD

**Issue by sochotnicky** [nextcloud/docker#1721]
I suspect this is a repeat of https://github.com/nextcloud/docker/issues/1697

For one reason or another hub.docker.com has no idea about 23.0.3 NC images: https://hub.docker.com/_/nextcloud?tab=tags&page=1&name=23.0.3

Right now this is less of a problem perhaps, but next time a big security vulnerability hits I'd rather not be in a tricky position of having to redo/update the app separately.

I'd prefer if you could treat this as more of a "What can we do about the CI/CD setup to prevent this type of issues" rather than just fixing this one instance?

Thanks

**Comment by kz26** [comment]
+1. While specific tags do exist for the latest 23.0.3, the generic 23 tags (e.g. 23-fpm, 23.0-fpm) are still lagging behind on 23.0.2.

**Comment by sochotnicky** [comment]
> +1. While specific tags do exist for the latest 23.0.3, the generic 23 tags (e.g. 23-fpm, 23.0-fpm) are still lagging behind on 23.0.2.

FWIW, when I was reporting even those tags didn't exist. But you are right, now they do but the generic 23 tags haven't moved. One way or another - the delay could be pretty bad in case of a serious CVE.

Based on the comments in the previous issue, it looks like the build/tag tasks are co-dependent so that if one version fails others get aborted too (but I haven't looked too deeply to verify)

**Comment by Lesstat** [comment]
Also the 23.0.3-fpm image is not available for all architectures. Especially,  linux/amd64 and linux/386 are missing compared to 23.0.2-fpm.

**Comment by J0WI** [comment]
Please have a look at the FAQ section: https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what

Nextcloud images are provided for 3 release channels, 3 flavours and 8 platforms each. So even after https://github.com/docker-library/official-images/pull/12105 is merged, this takes some time to build and upload. You can follow the build process at https://doi-janky.infosiftr.net/

**Comment by sochotnicky** [comment]
Fair enough, so what I am taking away from this is that for people who want to be able to patch/update in a timely manner, a prebuilt docker images are not the way to go and we should just roll our own. Or perhaps I'll test the update script within console (not sure it will work within the container context or get wiped on restart).

I don't have a problem with this, but I think it would be good to have this made more obvious in the [README file ](https://github.com/nextcloud/docker/blob/master/README.md).

**Comment by GuidoDr** [comment]
> Or perhaps I'll test the update script within console (not sure it will work within the container context or get wiped on restart).

that would not be a good idea. I made that error in the past. ;-)
Because you will end up with the data migrated to the new version but the docker container itself will remain on the old version.
If you then have to restart your docker container for whatever reasion you will end up with a crash of the container due to the fact the container version does not match the data version.
So I would propose to always be patient until the correct docker container is released by the nextcloud people.

**Comment by J0WI** [comment]
> I don't feel comfortable with a multi-day delay that I can't "speed up" if I feel like my exposure to some CVE is high enough.

I'm not aware of any CVE in 23.0.2. You can open a PR in https://github.com/docker-library/official-images as I do.

**Comment by sochotnicky** [comment]
> > I don't feel comfortable with a multi-day delay that I can't "speed up" if I feel like my exposure to some CVE is high enough.
> 
> I'm not aware of any CVE in 23.0.2. You can open a PR in https://github.com/docker-library/official-images as I do.

Sorry if I wasn't clear - I didn't mean to suggest that there *is* a CVE currently. Just that if there was one - people running docker images are at a mercy of a (IMO) slow update process that leaves them exposed and they won't have many options.

This can be somewhat mitigated by a layered image/Dockerfile that just runs `apt-get update`. That still leaves CVEs that are directly in nextcloud code (and not underlying packages such as openssl).

Anyway - knowing what the situation is, I'll consider what I'll do about this for myself (if anything).
