### ISSUE TITLE
All data gone

### ISSUE THREAD

**Issue by fampla** [nextcloud/docker#1722]
Hello,
I have (or had) all data not in var/www/data but in var/www/backup/data.
Why I did that is quickly explained, pure laziness after a server move. After an update from 22.0.2 to 22.0.3 the folder completely disappeared.
Even if I don't put my data in the right folder, Nextcloud should just not delete data by itself.

the problem was already described here once, which of course I had found only now.

**Comment by guycalledseven** [comment]
@Slevin7 I don't think this is docker related. I think this question should be addressed towards the nextcloud/server repo maybe?

My experience with newer version is slightly different than yours.

I was doing the update yesterday from 23 to 24 and automatic update was failing, web update was failing. Finally I run terminal update and found out why it was failing:  I had backed config/ dir to another dir. The installation did not delete it - actually this halted my updater with error:

```
[14:18](https://nivas.slack.com/archives/DEWLK68KH/p1654085923144309)
[✘] Check for expected files failed
The following extra files have been found:
    config.backup
```
