### ISSUE TITLE
NC24 Beta image required

### ISSUE THREAD

**Issue by oneWaveAdrian** [nextcloud/docker#1731]
I cannot seem to find the latest V24 beta image for docker.
Can someone please provide a beta docker image/ how do we keep the beta updated?
Would be very helpful in order to help develop nextcloud apps locally and keep them current/switch fast between envs.

Thanks community!

**Comment by J0WI** [comment]
There where too many issues with beta images in the past (like #1220) and the prereleases change too frequently. For local development I'd suggest to mount the sources directly into the container or build it from source.

**Comment by Emporea** [comment]
For everyone wanting to test betabuilds via Docker:

I just build the Dockerfile from https://github.com/nextcloud/docker/tree/master/24/apache myself and changed the two Nextcloud links to the latest beta from https://download.nextcloud.com/server/prereleases/

**Comment by jld3103** [comment]
I would also like to have beta images for testing. The issue is still relevant so it should be re-opened?

**Comment by Emporea** [comment]
@jld3103 
As i stated above you can build the Dockerfile yourself when changing the two Nextcloud links to the latest source from https://download.nextcloud.com/server/prereleases/

**Comment by jld3103** [comment]
Yes I understood that, but I just think having official images would be a good idea. Some deployments use docker and building the images on your own might not be an option.
