### ISSUE TITLE
Encryption not working and mariadb user has no permission in example with encryption

### ISSUE THREAD

**Issue by topas-rec** [nextcloud/docker#175]
Hello dev team,

I tried the encrypted example again after its rework in the past and noticed two problems I cannot some on my own.
1. Database user (I use mariadb) has no permission. Nextcloud web setup reports no permission for user nextcloud. (Using root as user works)
2. Encryption does not work. Connecting to port 443 or via https does not connect to anything. (I use a DNS name here from a machine on the local network) Port 80 works fine.

Can you please help me troubleshooting?

**Comment by topas-rec** [comment]
I found out that the error message is originated by the mariadb container. (Found the exact same error in the output of the container)
The message states: access denied for user "nextcloud" @<domain name> (using password: yes)

The container seems not to restart and runs fine(found this behaviour in similar issues)

From the output of the container I can see that a root account is created - nothing shows that a user nextcloud is created. I assume the user is not created and therefore the permission is denied.

**Comment by tilosp** [comment]
@topas-rec Have you set the password for the nextcloud database user in the [`db.env`](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/db.env) file?

**Comment by topas-rec** [comment]
I initially wanted to answer no, because it is already set in the compose file. I took a closer look now and saw it is a different environmental variable. I think that might be the issue.
I'll test this as soon as possible.
Thanks!

**Comment by topas-rec** [comment]
Tested your suggestion and it solved the (problem). Thank you.
