### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by Huarong** [nextcloud/docker#176]
when uploading file size > 1M, there will be a error "Request Entity Too Large".

This will occur both in latest and fpm image.

I am using the latest version and docker-compose

**Comment by cropse** [comment]
Hi:
I figured out the problem, It seen like docker volumes mount append the dockerfile `COPY uploadsize.conf`
If you know the basic linux shell, copy the `uploadsize.conf` to `data/conf.d/uploadsize.conf` aka docker volumes of `conf.d`, otherwise, I'm commit the pull request to fix it.

**Comment by Huarong** [comment]
I figured out it is because my nextcloud server is behind a Nginx proxy.  The proxy need to modify the config too.

**Comment by cropse** [comment]
If you don't mind, try #183, It might fix the problem, and no need to set `letsencrypt-companion`
