### ISSUE TITLE
Enable PHP-FPM Unix socket for nextcloud:fpm

### ISSUE THREAD

**Issue by kawaii** [nextcloud/docker#177]
To eliminate some of the TCP overhead I like to use Unix sockets where possible. Is there a way for you to enable the `docker-php-ext-install sockets` from the official PHP Docker images? That way I'd be able to mount the FPM Unix socket into my nginx container and use that as the 'upstream' instead of my current way which is `nextcloud:9000`. :slightly_smiling_face:

**Comment by kawaii** [comment]
Seems that I was mistaken - `docker-php-ext-install sockets` enables the PHP sockets extension, it does not create and enable connection to the PHP API via Unix socket. This has to be done within the `www.conf` FPM pool configuration file from what I can tell.

**Comment by J0WI** [comment]
Your current way is the way how Docker works. I don't see any benefits to mount unix sockets in other containers.

**Comment by ethrgeist** [comment]
Can this be discussed?

For segregation i would always prefer passing around a socket through volumes rather then having ingress proxy and app containers coupled via networks.

Why not offer both?

"how docker works" i find rather flimsy as argument against it.

**Comment by joshtrichards** [comment]
You can easily override the default `listen` in the image. It's located in `/use/local/etc`:

https://github.com/docker-library/php/blob/a53c65198c669682fb8e5c4581ecaf759fd4c309/8.2/bookworm/fpm/Dockerfile#L266-L267
