### ISSUE TITLE
Is a separate container required for cron jobs?

### ISSUE THREAD

**Issue by tacticz** [nextcloud/docker#1771]
Hello,

While exploring how to deploy a Nextcloud instance using docker, I based my configuration on the [`docker-compose/insecure/mariadb/apache/docker-compose.yml`](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb/apache/docker-compose.yml) example file. This file includes two instance of the `nextcloud:apache` image (`app` and `cron`), both accessing the same docker volume.

While further experimenting, I started using the [`dockerfiles/full/apache/Dockerfile`](https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/full/apache/Dockerfile) and thus modified the `docker-compose.yml` file, replacing 
```yml
  app:
    image: nextcloud:apache
```
with
```yml
  app:
    build: .
```

Keeping the:
```yml
  cron:
    image: nextcloud:apache
```

As a result, the configuration now requires two different images, and having two different containers running the Nexcloud app with slightly different (build) options. I realize I could of course use the same image for the `cron` container, but my real question is:

**Is there no way to run the cron jobs straight withing the main Nextcloud container?**
**And if not, could someone be kind enough to give some explanation as why another container is required?**
**Also am I right thinking that running two instances of the Nexcloud image does have an impact on the global system performances?**

Thank you very much for helping me figure this out.

Best,

**Comment by martadinata666** [comment]
The full image [full/Dockerfile](https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/full/apache/Dockerfile) , will also implement cron, because it is using `supervisor` to start programs. The default image  need separate cron because the differences on how it build, as it only start `apache`. So the cron need created/run separately, no differences about performance, just design.

**Comment by tacticz** [comment]
Thank you for your answer, I think I got it!

Since `supervisord.conf` contains a section that starts the `cron.sh` script, it becomes unnecessary to have a dedicated Nextcloud container that runs the cron job.
```
[program:cron]
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
command=/cron.sh
```

Thanks again.
