### ISSUE TITLE
Nextcloud 24.0.2 image is absent in dockerhub

### ISSUE THREAD

**Issue by DeniGam** [nextcloud/docker#1774]
Nextcloud 24.0.2 released yesterday but last docker image update wes done 11 days ago. 
![chrome_cZbNKvHG2N](https://user-images.githubusercontent.com/22942374/174725830-7a03b5a7-cbf2-4376-92b0-9586a055f968.png)

**Comment by xorbital** [comment]
The change has been commited already #1773 
This issue has been discussed multiple times, e.g. here https://github.com/nextcloud/docker/issues/1721#issuecomment-1077605280
Basically you'll have to wait for [steps 1-6](https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what) to complete, it seems it's currently somewhat [stuck](https://github.com/docker-library/official-images/pull/12663) at step 3 or 4.

**Comment by DeniGam** [comment]
Now image is updated
