### ISSUE TITLE
recreate docker containers result in relation oc_appconfig not found error

### ISSUE THREAD

**Issue by pessimo** [nextcloud/docker#1780]
I tried some research, it seems volumes and containers are linked together.
so if my process is
```
docker-compose down
docker-compose up -d
```

docker will remove all containers and result in an internal server error.
which is directly caused by database relation oc_appconfig not found error.

I could only use 
```
docker-compose stop
```
this command won't remove docker containers.
I guess it has something to do with container hash, those volumes and containers are connected together.

_Originally posted by @pessimo in https://github.com/nextcloud/docker/issues/1727#issuecomment-1169634882_

**Comment by Gamechiefx** [comment]
I just did a recreate on my docker container to do an upgrade to 24 and it broke my server. It would appear that the containers have a volume dependency. How do we fix this?

**Comment by pessimo** [comment]
If it's the same error, I guess you should backup your db and restore it.

**Comment by joshtrichards** [comment]
Hi @pessimo - Thanks for your report, but it lacks important context. Can you provide your Docker Compose file?

@Gamechiefx - Are you getting the `oc_appconfig` error or just an internal server error? The former is a very specific error, while the latter is just a generic one.

**Comment by joshtrichards** [comment]
Closing due to "needs info" >90 days.
