### ISSUE TITLE
CIFS/Samba -v issue

### ISSUE THREAD

**Issue by VOCCTQ** [nextcloud/docker#179]
Hello -
I've a problem to parse directory to docker via -v option if directory is a mount from CIFS Nextclouad homepage isnt loading.

docker run -d -p 80:80 --name=NextCloud -v /mnt/MyDataStorage:/var/www/html/data nextcloud

Samba Conf:
[MyDataStorage]
  comment = NextCloud
  path = /opt/MyDataStorage
  valid users = @www-data
  force group = www-data
  create mask = 0775
  directory mask = 0775
  writable = yes

Mount it  also as www-data:www-data

Any ideas?

**Comment by VOCCTQ** [comment]
No idea?

**Comment by Greek64** [comment]
Just brainstorming here, but could it be that you are forcing the permissions to www-data:www-data through Samba, but the nextcloud container expects www-data:root?

**Comment by marceljd** [comment]
Can you access the mount/MyDataStorage through the Linux command line and create a file there? Try as root and as the www-data user.

**Comment by J0WI** [comment]
Closing due inactivity.
