### ISSUE TITLE
[HELP] cURL error 77: error setting certificate verify locations

### ISSUE THREAD

**Issue by boi-doingthings** [nextcloud/docker#1815]
Trying to setup nextcloud in a docker container. Post seemingly successful login setup, I am facing the below issue when I try to install some applications in the installation.

![image](https://user-images.githubusercontent.com/111463360/188308098-e6b4a55c-e0ee-4bbb-9ad6-e6a9af5dbdf6.png)

Have tried looking aroung in nextcloud discussion forums and related stack-overflow, but couldn't find a clear solution to mitigate the problem, hence putting it up here.

If anyone can help me with a solution or some resource that addresses the issue, it would be really kind.

**Comment by boi-doingthings** [comment]
If it helps, when I restarted my container, I can no longer see the names  of the apps.

**Comment by joshtrichards** [comment]
Hi @boi-doingthings - Unfortunately it's hard to help without more info:

- What version of Nextcloud Server?
- Please post your Docker Compose file
- The output of `ls -l /var/www/data/files_external/rootcerts.crt` from your app container 
- Confirm have *outbound* connectivity from within the app container

**Comment by joshtrichards** [comment]
My best guess is this is a config matter (Compose file/run command, data volumes mixed up, permissions on bind directories, or similar). Particularly if the app names disappeared after restarting.

Without a way to reproduce this issue that suggests it's a bug, I'm going to close this. Please post some of that information on the Nextcloud Help Forum - https://help.nextcloud.com - to get some analysis of your configuration if you're still having this issue.
