### ISSUE TITLE
Recurrent integrity check fails on 24 subversions

### ISSUE THREAD

**Issue by leolivier** [nextcloud/docker#1820]
Hi
At least for the 2 latest new minor versions 24.0.4, 24.0.5 there is an error on integrity checks in the mail application for the HTML Purifier
With 24.0.4, I physically removed the files but they are back again with 24.0.5. I was told in another issue that it was a packaging problem, so I opened this issue...
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- mail
	- EXTRA_FILE
		- vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer/URI/4.14.0,3478238e680361cd87bf880f5b3cc50a1e7abc6c,1.ser
		- vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer/HTML/4.14.0,100a0d442686872045400b774dcb082c945a1908,2019080701.ser

Raw output
==========
Array
(
    [mail] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer/URI/4.14.0,3478238e680361cd87bf880f5b3cc50a1e7abc6c,1.ser] => Array
                        (
                            [expected] => 
                            [current] => ab08a13c9d6765c71769c6d2940ec65ad0752b8772da219d427bb34c6a35872c664379ea00285d855f84330e0665fe28dbb5b216251259f3efa32bb7cc70b697
                        )

                    [vendor/ezyang/htmlpurifier/library/HTMLPurifier/DefinitionCache/Serializer/HTML/4.14.0,100a0d442686872045400b774dcb082c945a1908,2019080701.ser] => Array
                        (
                            [expected] => 
                            [current] => 540a367e60974a65ddc6db7481eeb141077ba7275caa4c1d478ab76baa8381a865983319035a324109709bb5dafcf92f621837c480458ab84765f7d874174006
                        )

                )

        )
)

```

**Comment by joshtrichards** [comment]
Hi @leolivier - Thanks for the report. This would be an issue in the `mail` app and/or its packaging. It wouldn't have anything to do with the community NC Docker image itself. This repository is for reporting bugs in the Docker image. The mail app doesn't come installed in the Docker image. It's just an app like any other NC app that can optionally be installed within NC. 

It's also a little weird but AFAIK the `mail` isn't signed at the moment: https://github.com/nextcloud/mail/issues/7465. If it's still occurring I'd suggest checking the open/closed issues at https://github.com/nextcloud/mail.

If you agree with my assessment of your report, please close this Issue out. Thanks!

**Comment by leolivier** [comment]
Ok, I'll open an issue in the mail app itself
