### ISSUE TITLE
Cant load documents - fuse2 error - missing dependency?

### ISSUE THREAD

**Issue by NotGovernor** [nextcloud/docker#1823]
Fresh install. Latest docker image. Latest Ubuntu server version. All clean installs.

NextCloud installation all working well.

Browse to files and inside the default Documents folder I choose the Welcome to Nextcloud Hub.docx file. It shows the loading page and I see the following error in the console for the docker.

Best guess: Has the image moved on to a version of linux that has fuse3 in it and not fuse2 so this is breaking now?

```
app_1  | IP - - [13/Sep/2022:23:36:04 +0000] "PROPFIND /remote.php/dav/files/USER/Documents/Welcome%20to%20Nextcloud%20Hub.docx HTTP/1.1" 207 1417 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
app_1  | dlopen(): error loading libfuse.so.2
app_1  |
app_1  | AppImages require FUSE to run.
app_1  | You might still be able to extract the contents of this AppImage
app_1  | if you run it with the --appimage-extract option.
app_1  | See https://github.com/AppImage/AppImageKit/wiki/FUSE
app_1  | for more information
```

Thanks for your assistance.

**Comment by projx** [comment]
Did you find a solution to this?

**Comment by martadinata666** [comment]
https://github.com/nextcloud/docker/issues/1896

**Comment by kacperpaczos** [comment]
I have the same problem.
I will test my own Dockerfile for Nextcloud to try to resolve the issue.
Related information at this link:
https://github.com/AppImage/AppImageKit/wiki/FUSE

**Comment by joshtrichards** [comment]
`richdocumentscode` does **not** require `libfuse.so.2` (see [Requirements](https://github.com/CollaboraOnline/richdocumentscode#system-requirements)). That warning is normal when running in the Docker container. When libfuse.so.2 isn't found, `richdochmentscode` falls back on extracting and running.

If the *Collabora Online - Built-in CODE Server* app isn't functioning for you, the lack of fuse is not the reason. I suggest checking:

https://github.com/CollaboraOnline/richdocumentscode
&
https://github.com/nextcloud/richdocuments
