### ISSUE TITLE
Unable to start nextcloud using secure example (with-nginx-proxy/mariadb-cron-redis/apache)

### ISSUE THREAD

**Issue by atkulp** [nextcloud/docker#184]
I'm new to Ubuntu/Linux and Docker, so please bear with me.  I've cloned the repo locally and changed to this example dir:
.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache

From there, I've edited the docker-compose.yml file based on the instructions (with-nginx-proxy section):

- services/db/environment/MYSQL_ROOT_PASSWORD
- services/app/environment/VIRTUAL_HOST
- services/app/environment/LETSENCRYPT_HOST
- services/app/environment/LETSENCRYPT_EMAIL

In db.env, I set MYSQL_PASSWORD.

Then I ran "docker-compose build --pull" and "docker-compose up -d".

For images I have:
```
REPOSITORY                               TAG                 IMAGE ID            CREATED             SIZE
apache_proxy                             latest              5dc507f7ce63        11 hours ago        51.3MB
apache_app                               latest              1bbd0cde41cf        11 hours ago        637MB
apache_cron                              latest              1bbd0cde41cf        11 hours ago        637MB
mariadb                                  latest              abcee1d29aac        19 hours ago        396MB
jwilder/nginx-proxy                      latest              0c76c7469f53        2 days ago          148MB
jwilder/nginx-proxy                      alpine              d5ad788a0788        2 days ago          51.3MB
jrcs/letsencrypt-nginx-proxy-companion   latest              5efa1f628e32        7 days ago          79.7MB
nextcloud                                apache              38eab7366bdc        11 days ago         637MB
redis                                    latest              8f2e175b3bd1        12 days ago         107MB
```

For containers, I have:
```
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS              PORTS                                      NAMES
ddd8345970bf        jrcs/letsencrypt-nginx-proxy-companion   "/bin/bash /app/en..."   29 minutes ago      Up 29 minutes                                                  apache_letsencrypt-companion_1
bd05ec36e7b0        apache_cron                              "bash -c 'bash -s ..."   29 minutes ago      Up 29 minutes       80/tcp                                     apache_cron_1
410e9bc9b246        apache_app                               "/entrypoint.sh ap..."   29 minutes ago      Up 29 minutes       80/tcp                                     apache_app_1
8e5db605c9d0        apache_proxy                             "/app/docker-entry..."   29 minutes ago      Up 29 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   apache_proxy_1
4ba7e63f90ae        mariadb                                  "docker-entrypoint..."   29 minutes ago      Up 29 minutes       3306/tcp                                   apache_db_1
d2f4e084ce43        redis                                    "docker-entrypoint..."   29 minutes ago      Up 29 minutes       6379/tcp                                   apache_redis_1
```
Are there other steps I should be doing from another section?  Why don't I actually see nextcloud in the containers list?

Thanks!

**Comment by atkulp** [comment]
Well, after messing around more, it appears that nextcloud is actually part of the apache_app_1 container (not intuitive!).  I'm running on an Azure Ubuntu virtual machine, and have exposed ports 80 and 443, but it only responds on port 80.  The apache_proxy_1 container (as seen above) appears to expose both ports.  At least I'm closer...

**Comment by SnowMB** [comment]
Try going through the logs 
```
docker-compose logs <NAME_FROM_COMPOSE_FILE>
```

So for example 
```
docker-compose logs app
```

The names for your containers are automatically generated. In your setup your folder name is `apache` and in the compose file the services are called `app`, `db`, `redis` and so on. Together you get `apache_app_1`, `apache_db_1`, `apache_redis_1`.

**Comment by atkulp** [comment]
The only things that look like an error is the Apache message about not determining the server's fully-qualified host name.  Everything I've read said not to worry about that.  Is there anything I should look for specifically?

On a side note, isn't it way aggressive to renew our SSL cert so often?  I thought it was more like 30 days valid, so wouldn't a daily renew be better to keep load off their servers?

**Comment by SnowMB** [comment]
Can you please explain in more detail, what error you are facing? From what you posted it looks like your container is up and running. 

Is the container stopping itself? Do you face problems with the certificate generation? Are you unable to open nextcloud with your browser? Do you get error messages from docker-compose?

It would be helpfull if you could post the files you made changes to and the logs. But keep in mind to leave out sensitive data.

**Comment by atkulp** [comment]
In case this helps, I tried connecting directly to the SSL endpoint using curl, and I get the following response:

`curl: (35) gnutls_handshake() failed: The TLS connection was non-properly terminated.`

The container is definitely running.  I have no problem hitting things on port 80.  I posted all of my file changes in the first comment.  Let me know what log to include (and the command to get it) and I can attach that too.

Thanks!

**Comment by SnowMB** [comment]
Look at the logs for the letsencrypt container. Are the certificates properly generated?

**Comment by atkulp** [comment]
no.  the docker image for letsencrypt is [using the wrong hash](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion/issues/277).  I thought I had it fixed, but the log is showing errors again.  I'm still working on that...

I'm not getting a cert issue though anyway, it's like the port isn't even open.  My first post shows what the containers look like for ports.  Though I know you can't help troubleshoot Azure, I'm also including the image that shows I'm opening the ports properly there too.  It seems like it should be such a simple thing!

![image](https://user-images.githubusercontent.com/3195410/33781268-bb23f04e-dc08-11e7-89c3-2cee0085f139.png)

**Comment by atkulp** [comment]
updated letsencrypt and cert is generating fine now and I can access the cloud with SSL.  ARGH!  That was pretty infuriating.  Thanks for your help anyway, it's working now!

```
[0m 2017-12-08 19:45:07,987:INFO:simp_le:1538: Retrieving Let's Encrypt latest Terms of Service.
[0m 2017-12-08 19:45:09,005:INFO:simp_le:1356: Generating new account key
[0m 2017-12-08 19:45:12,986:INFO:simp_le:1455: Generating new certificate private key
[0m 2017-12-08 19:45:13,864:INFO:simp_le:463: Saving account_key.json
[0m 2017-12-08 19:45:13,866:INFO:simp_le:463: Saving key.pem
[0m 2017-12-08 19:45:13,867:INFO:simp_le:463: Saving chain.pem
[0m 2017-12-08 19:45:13,867:INFO:simp_le:463: Saving fullchain.pem
[0m 2017-12-08 19:45:13,867:INFO:simp_le:463: Saving cert.pem
```
