### ISSUE TITLE
security guidance instruction is not met: open_basedir is not configured for /dev/urandom

### ISSUE THREAD

**Issue by dimonf** [nextcloud/docker#185]
docker exec -it nextcloud /bin/bash

> php -i | grep open_basedir
> open_basedir => no value => no value

**Comment by tilosp** [comment]
The security guidance is met. They only say that if `open_basedir` is configured it needs to contain `/dev/urandom`. But is is not configured which means that php can access `/dev/urandom`
https://docs.nextcloud.com/server/12/admin_manual/configuration_server/harden_server.html?highlight=enabledpreviewproviders#give-php-read-access-to-dev-urandom
