### ISSUE TITLE
swapped user and group permission after run my container

### ISSUE THREAD

**Issue by cocodrino** [nextcloud/docker#188]
Hi, good day, I'm running my nextcloud container, something than it's a bit confuse about the folder permission for my /var/www/html folder is than the permission seems to be swapped...

```bash

drwxr-xr-x  6 www-data root  4096 Nov 21 20:19 lib
-rwxr-xr-x  1 www-data root   283 Nov 21 20:19 occ
drwxr-xr-x  2 www-data root  4096 Nov 21 20:19 ocs
drwxr-xr-x  2 www-data root  4096 Nov 21 20:19 ocs-provider
-rw-r--r--  1 www-data root  3152 Nov 21 20:19 public.php
-rw-r--r--  1 www-data root  5323 Nov 21 20:19 remote.php
drwxr-xr-x  4 www-data root  4096 Nov 21 20:19 resources
-rw-r--r--  1 www-data root    26 Nov 21 20:19 robots.txt
drwxr-xr-x 14 www-data root  4096 Nov 21 20:19 settings
-rw-r--r--  1 www-data root  2110 Nov 21 20:19 status.php
drwxr-xr-x  3 www-data root  4096 Nov 21 20:19 themes
-rw-r--r--  1 www-data root   435 Nov 21 20:19 version.php


```

so it's the user www-data for the group root....very weird for me...why could this happening???

I'm running ubuntu server and docker as root, the command is the very standart way, I'm storing the data in a folder where originally has permission <ubuntu-user>:www-data and it's a classic domain folder created by plesk...

docker change all the permission inside this folder to www-data root...

```shell
docker run -d --name containerNextcloudD -p 8085:80 -v DataUS:/var/www/html/data -v /var/www/vhosts/<my-url>/<ubuntu-user>/var/www/html nextcloud
```

I'd like could mount this container as <ubuntu-user>:www-data but I've not problems with than it can be root www-data....now a user www-data it's not ok for me...

thank you so much...hope you can understand my question and know the issue, please let me know if you need more details...thanks!!!......

**Comment by Greek64** [comment]
This is expected behavior.
It is done by the "chown -R www-data:root /var/www/html" command run before the "VOLUME" command in the dockerfile.
This was added in a PR closing issue #107 for OpenShift support (running docker containers as non-root)

**Comment by J0WI** [comment]
Assuming that the question has been answered.
