### ISSUE TITLE
Database update is not working

### ISSUE THREAD

**Issue by Unfaehig** [nextcloud/docker#1880]
Got this error today after watchtower update. Not sure if it is some issue with Postgre Container, but till it worked before the last update and only the Nextcloud was updated, i guess it is related to the upgrade process.

I'm using Postgresql 15 latest as DB
and latest Nextcloud fpm image 

```Configuring Redis as session handler
Initializing nextcloud 25.0.2.3 ...
Upgrading nextcloud from 25.0.1.1 ...
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: extract
Updating <photos> ...
Exception: Database error when running migration 20003Date20221102170153 for app photos
An exception occurred while executing a query: SQLSTATE[42501]: Insufficient privilege: 7 ERROR:  permission denied for schema public
LINE 1: CREATE TABLE oc_photos_albums_collabs (id BIGSERIAL NOT NULL...```

**Comment by joshtrichards** [comment]
Hi @Unfaehig - Glad you found a solution.

The Nextcloud Admin Manual was reworked (see nextcloud/documentation#9227) around the same time as your original report. Similar GRANTs/etc were added to [the docs](https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/linux_database_configuration.html#postgresql-database) then.

> would be nice, if we get a notification after an upgraded DB is detected. Something like: warning we detect your have upgraded to Postgres 15 please be sure you grant permissions to all on public schema to your admin user!

This is out-of-scope for the Docker image. If anywhere, it would perhaps belong the Nextcloud Server level.
