### ISSUE TITLE
Place the data folder outside of www/html

### ISSUE THREAD

**Issue by etokheim** [nextcloud/docker#1889]
Hi, and thanks for all the good work!

I was wondering why the `data` folder is located inside `var/www/html`, when this is not the recommended practice according to the docs?
> It is highly recommended to place your data directory outside of the Web root (i.e. outside of /var/www).
([Hardening and security guidance](https://docs.nextcloud.com/server/25/admin_manual/installation/harden_server.html#place-data-directory-outside-of-the-web-root))

Wouldn't it be easy to fix this in the build process? Could you say anything about why it's not done, if there was any reasoning behind it - and also how this impacts security?

**Comment by etokheim** [comment]
Why can't you just set it to ie. `/data`?

It doesn't have to be customizable, so why would you have to predict it?

**Comment by obel1x** [comment]
@jowi i would also think of adding a volume nextcloud_data, mount it to a different location than /var/www/html and use that location per default. What do you mean with "undefine volumes"?

**Comment by obel1x** [comment]
> > What do you mean with "undefine volumes"?
> > https://docs.docker.com/engine/reference/builder/#volume
> 
> You can only declare multiple volumes in the Dockerfile but users or child images cannot overwrite or disable them. Every `VOLUME` will get registered on startup.

Yes, but why not use nextcloud_data:/var/www/nextcloud_data and use it?

**Comment by joshtrichards** [comment]
@obel1x I haven't thought much about this particular matter, but I think the answer is: because we'd have to accommodate *both* VOLUMEs no matter what from then on... We can't just change things without dealing with backwards compatibility of existing installations too...

**Comment by joshtrichards** [comment]
This can already be done at install time (using `NEXTCLOUD_DATA_DIR`).

@obel1x Keep in mind we're referring to the volume definitions in the image build file (`Dockerfile`), not what user/admin does in their Docker Compose or equivalent.
