### ISSUE TITLE
Cron Setup

### ISSUE THREAD

**Issue by pietru2004** [nextcloud/docker#1894]
I want to ask about
https://github.com/nextcloud/docker/blob/de77074a55a7d181276de5cddf9fbdb5b9e56f3e/.examples/docker-compose/insecure/mariadb/apache/docker-compose.yml

To run cron task with nextcloud do I need both app and cron containers or would just setting entrypoint of my existing setup to `/cron.sh` suffice (1 container)

**Comment by Japhys** [comment]
Not what you asked but you can also do this on your host machine. Works perfect for me and very easy

`sudo crontab -e`

`*/5 * * * * docker exec -u www-data nextcloud-app php -f /var/www/html/cron.php`

**Comment by pietru2004** [comment]
I asked how many docker containers are required for cron.php - without counting adding something to host machine

**Comment by Japhys** [comment]
0

**Comment by Japhys** [comment]
You obviously need one for the app and one for the db, but you don't need anything else for cron to work if you do docker exec

**Comment by pietru2004** [comment]
you just don't get the question. point is if there is 1 container can it host page and run it own cron tasks

**Comment by Japhys** [comment]
You are right, I did not get that. Never tried it that way

**Comment by martadinata666** [comment]
using default setup you need two the `nextcloud` itself and the `cron`. if you proficient enough you can get away with single container by some modification `self build docker image` with the Dockerfile provided in `.example` path

**Comment by pietru2004** [comment]
Ok thank you for answer :-)
