### ISSUE TITLE
db service complains my password has expired

### ISSUE THREAD

**Issue by dehuszar** [nextcloud/docker#190]
I'm trying to migrate my nextcloud configuration from the old indiehosters/nextcloud image.  But I'm seeing this error on boot.

```Your password has expired. To log in you must change it using a client that supports expired passwords.```

I'm not sure how to resolve this in a way that persists across multiple docker-compose ups/downs, nor could I find any supported environment variables for MYSQL's `disconnect_on_expired_password=false` param that I could pass the db service.

Is there a recommended way I should be approaching this?

**Comment by J0WI** [comment]
See https://dev.mysql.com/doc/refman/8.0/en/expired-password-handling.html
