### ISSUE TITLE
Nextcloud :fpm image blank page

### ISSUE THREAD

**Issue by reinoldus** [nextcloud/docker#191]
Hi,

When I am running the docker-compose file for the secure nginx with redis I just get a blank page.
I did some digging and if you uncomment the following line in the lib/base.php. It works, but only for the first initial page, after that it's blank page again.:

`                if (!self::$CLI) {
//                      self::initSession();
                }
`

It is at line 675.

Anybody else having this issue?

Regards
isset

**Comment by J0WI** [comment]
Please open a new issue with more details if you still have this problem.
It would be helpful to know what version and what configuration you are using.
