### ISSUE TITLE
Nextcloud forgets its already been set up on container wake/recreate

### ISSUE THREAD

**Issue by amancevice** [nextcloud/docker#193]
I have a deployment of Nextcloud on the Heroku Container platform. Because I'm using the free tier, my container gets spun down after the web dyno goes to sleep and spun back up when a request wakes it up.

My container is configured to use the heroku postgres plugin via the `POSTGRES_*` ENV variables.

Everything works wonderfully when I first set up the admin user, but once the dyno goes to sleep and I spin up a new instance, the Nextcloud container gets confused and thinks it needs to set up the admin user, even though this has already been done and the information is in the postgres DB.

How can I inform the container that setup is not needed when it wakes up?

**Comment by SnowMB** [comment]
To me that sounds like your storage is not persistant. How are your volumes configured?

**Comment by amancevice** [comment]
ah, I thought all that was driven entirely by the database. Are there particular volumes I should be looking at here?

**Comment by amancevice** [comment]
It looks like Heroku's volumes are ephemeral so probably not a great long-term solution for me.

**Comment by evertramos** [comment]
Hello @amancevice, you will find the settings as of Oficial Docs under `./config/config.php` file, so @SnowMB probably is right and your Nextcloud config data did not persist. I think if you configure a volume for some local folder you could fix this issue. Here is an example with some persistent data using *docker-compose* - https://github.com/evertramos/docker-nextcloud-letsencrypt. 

Hope it helps!
