### ISSUE TITLE
Can I setup redis via env var ? 

### ISSUE THREAD

**Issue by rgarrigue** [nextcloud/docker#194]
Hello

I'ld like to setup a redis via docker-compose. Do I have no other choice than writing myself the config.php file and mount it? I've been looking for something like this

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

But no example found so far, I guess I can't ?

Best regards,

**Comment by SnowMB** [comment]
It's not possible at the moment.

**Comment by adriengibrat** [comment]
There is [an example how to configure redis](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/app/Dockerfile): copy the config file in `/usr/src/nextcloud/config/redis.config.php`

**Comment by rgarrigue** [comment]
Thanks @adriengibrat . I came up with something similar, I'm leaving this issue open as a feature / enhancement request.

**Comment by marceljd** [comment]
#525

**Comment by marceljd** [comment]
#525

**Comment by marceljd** [comment]
#525

**Comment by r2evans** [comment]
I recognize that memory caching [is not strictly a requirement in NC](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/caching_configuration.html), though it seems to be a reasonable expectation and (I believe) a performance improvement. There have been a couple of PRs for this (#292 and #522), both closed (rejected?) for unclear reasons. The latter seemed a reasonable (small) patch to me, though I'm not a regular nextcloud code maintainer.

It is likely acceptable (for now) to not automate this, for simple configurations. I'm guessing we are "assured" that `config.php` parameters not explicitly changed in the `docker-compose.yml` env-vars will not be over-written. **Is this a safe assumption?**

**Comment by marceljd** [comment]
can be closed via #600
