### ISSUE TITLE
Add Nextcloud 26

### ISSUE THREAD

**Issue by aentwist** [nextcloud/docker#1950]
Not sure what this involves past just running the update.sh action. For example, maybe upgrade the PHP version on the images.

> PHP 8.2 is now supported.

See https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_26.html

**Comment by MartinSchmidt123** [comment]
The release failed one check and was rejected:
https://github.com/docker-library/official-images/actions/runs/4484535415/jobs/7885150358?pr=14304
