### ISSUE TITLE
Build images with AVIF support

### ISSUE THREAD

**Issue by aentwist** [nextcloud/docker#1959]
Related to https://github.com/juliushaertl/nextcloud-docker-dev/issues/177

## User Story

I am considering working on adding AVIF preview support to Nextcloud https://github.com/nextcloud/server/issues/13552. I'd like to start the discussion with getting AVIF into the images.

## Proposed Solution

Install AVIF in the images that have a PHP GD version that supports it.

Requirements should just be:

- install `libavif-dev libaom-dev libdav1d-dev`
- configure GD `--with-avif`

## Alternative Considerations

- Have users build it in themselves by using their own images built on top of official images
- [docker-php-extension-installer](https://github.com/mlocati/docker-php-extension-installer)

**Comment by aentwist** [comment]
`aom-dev dav1d-dev` appear to both be for AV1 video. Don't think we need these, although they might be required as peer deps for specific functionality?

**Comment by aentwist** [comment]
> `libaom-dev libdav1d-dev` appear to both be for AV1 video. Don't think we need these

We need these.

See https://github.com/juliushaertl/nextcloud-docker-dev/issues/182

**Comment by joshtrichards** [comment]
When/if upstream (`server`) suggests this officially in their documentation/requirements we can do so. Since that's not the case today, I'll close this out.
