### ISSUE TITLE
Update base image to php 7.2 (Nextcloud 13)

### ISSUE THREAD

**Issue by ovidiub13** [nextcloud/docker#196]
The current base image `php:7.1-fpm` manifests this bug: https://github.com/nextcloud/server/issues/7380

Please update the base image to one with `php:7.1-fpm`. This can be somewhat problematic as I see none of the `7.2` images are based on Debian anymore.

Any plans to move this image to be based on alpine or other common lightweight bases?

**Comment by tilosp** [comment]
We can't upgrade to 7.2 because nextcloud doesn't support it (https://github.com/nextcloud/server/issues/7384). We have to wait for php 7.1.13

**Comment by thiesschneider** [comment]
This could work now, right?

**Comment by jlelse** [comment]
Any updates on this?

**Comment by tilosp** [comment]
This should be possible now for nextcloud 13
