### ISSUE TITLE
PHP OPcache module is not properly configured: OPcache buffer is nearly full

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/docker#1965]
First I've seen this one. In the past I've seen warnings about string buffers (mentioned in other issues).

## Security & setup warnings

It's important for the security and performance of your instance that everything is configured correctly. To  help you with that we are doing some automatic checks. Please see the  linked documentation for more information.

There are some warnings regarding your setup.

* The PHP OPcache module is not properly configured. See the [documentation ↗](https://docs.nextcloud.com/server/25/go.php?to=admin-php-opcache) for more information. 
  * The OPcache buffer is nearly full. To assure that all scripts can be hold in cache, it is recommended to apply `opcache.memory_consumption` to your PHP configuration with a value higher than `128`.

Please double check the [installation guides ↗](https://docs.nextcloud.com/server/25/go.php?to=admin-install), and check for any errors or warnings in the [log](https://nextcloud.twobulb.com/settings/admin/logging).

Check the security of your Nextcloud over [our security scan ↗](https://scan.nextcloud.com).

![Screenshot from 2023-04-08 17-12-51](https://user-images.githubusercontent.com/50639/230747779-648b28e3-cf89-4ad6-b686-0dbfe88745b2.png)

I'm using:

* version 25.0.5.1
* image tag: `nextcloud:25.0.5-apache`
* image SHA256 checksum: `1dd8f331fb758655eb3b2e6388b7cff26f2a90dc0bec25f8d2af1dbdbf538234`

**Comment by meonkeys** [comment]
I destroyed and re-created my Nextcloud app container and the warning went away. I don't have a repro. Maybe it was running for a long time?

**Comment by meonkeys** [comment]
Still seeing this, but the server seems to be working fine. No other symptoms that I can tell.

**Comment by R7JANV1** [comment]
Will the problem be fixed or is there a solution for this error?

**Comment by meonkeys** [comment]
@R7JANV1 are you seeing this warning?

**Comment by R7JANV1** [comment]
> @R7JANV1 are you seeing this warning?

Yes!

**Comment by meonkeys** [comment]
Ok. @R7JANV1 , can you add any details about your setup, what you've tried or researched already?

The obvious solution (as rawtaz pointed out in \#nextcloud on LiberaChat IRC) is to increase the value. But I have questions--I just added them to the description. I'd like to know the root cause and if the default value should be increased.

https://www.saotn.org/optimize-php-opcache-configuration/ might help us figure this out.

**Comment by R7JANV1** [comment]
I recently migrated my Nextcloud All in One instance from my Ubuntu Server to TrueNAS.  There I linked a Nextcloud container and a database container using the built-in Kubernetes Docker function and migrated the data and database of the old instance to the new instance on TrueNAS.

**Comment by meonkeys** [comment]
Have you tried changing the value of `opcache.memory_consumption`?

**Comment by AlterDepp** [comment]
Warning still exists on NC 27.1.1

**Comment by nikbpetrov** [comment]
For me, it's an error - NC 28.0.8.

Interestingly - maybe due to my own ignorance - I don't have a php.ini files in /usr/local/etc but I do have `/usr/local/etc/php/php.truenas.ini`, which I believe is the same (although would be excited to be corrected if this is not the case).

My config is:
```
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=512
opcache.interned_strings_buffer=32
opcache.max_accelerated_files=10000
opcache.revalidate_freq=1
opcache.save_comments=1
```

The opcache thing used to be a warning but since some time (idk when or why) it has become an error.

**Comment by meonkeys** [comment]
folks still seeing this error, note new container env var `PHP_OPCACHE_MEMORY_CONSUMPTION`. See #2090
