### ISSUE TITLE
Image for v26.0.2 not on Dockerhub

### ISSUE THREAD

**Issue by lazaroblanc** [nextcloud/docker#1991]
I got the notification that 26.0.2 is available and I can see the Dockerfile in the repo here is already up-to-date, but it's not available as a a tagged image on Dockerhub. Please check.

![image](https://github.com/nextcloud/docker/assets/40198445/8b6ee063-0e30-403c-9a12-cd914569514a)

**Comment by t-lo** [comment]
25.0.7 is missing too, and my instance (on 25.0.6) keeps nagging me to update as "a new version is available".

Anything we can do to help?

**Comment by ppkhoa** [comment]
Maybe file an issue here instead? https://github.com/docker-library/official-images/issues?q=label%3Alibrary%2Fnextcloud

**Comment by Strit** [comment]
The Action for building and publishing images is failing. That's why there are no new images on Dockerhub.

**Comment by pfuhrmann** [comment]
Related to https://github.com/nextcloud/helm/pull/402.

**Comment by pfuhrmann** [comment]
FYI, the image is available now: https://hub.docker.com/layers/library/nextcloud/26.0.2/images/sha256-69c8f46e049e72d8433e2ec4a59589aa6296c84d09b3dbcac8c16906a2bf6d4c?context=explore

**Comment by pReya** [comment]
@pfuhrmann @tcitworld The new releases from today (25.0.8) are missing again :(

**Comment by provokateurin** [comment]
You always have to wait a little bit. The docker image is done by the community, please be easy on the people putting in their hard work here :)
