### ISSUE TITLE
No version tags

### ISSUE THREAD

**Issue by cyphar** [nextcloud/docker#20]
Currently this repo (and the [associated repo on the Docker Hub]()) doesn't have any version tags. This means that users can't pin their install to a particular version. The best way of handling this would be to have different branches of this repo with different `nextcloud` versions pinned in each Dockerfile. AFAIK it should be possible to configure the Docker hub to handle this.

Also, are there any plans to get this integrated into the _actual_ `docker-library/`, like `owncloud` is? You could always emails @tianon and similar maintainers of that project to see if they'd be open to having `nextcloud` hosted in [a similar way to `owncloud`](https://github.com/docker-library/owncloud).

**Comment by cyphar** [comment]
Yeah, there's an option for this when creating an automated build image (and can be configured after you create it).

**Comment by cyphar** [comment]
Also, we really should provide `-apache` tags for Apache-based images (`php:5.6-apache`).

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/pull/2185 for where this is proposed for inclusion as an official image. :smile: :+1: (with version tags, but not an Apache variant)

**Comment by cyphar** [comment]
Alright, I'll make PRs against this project to add Apache variants as well as subdirectories for each major/minor version.

**Comment by cyphar** [comment]
#21 has my changes.
