### ISSUE TITLE
Upgrading docker container from 26.0.1 to 26.0.2 or to 27

### ISSUE THREAD

**Issue by servoronine** [nextcloud/docker#2002]
After upgrading the docker container (nextcloud:fpm) from 26.0.1 to 26.0.2, it does not start any more. The error message is very strange. It states that retrofitting from version 26.0.1 to 26.0.2 is not allowed, so clearly thinking that the upgraded version 26.0.2 is lower than the version 26.0.1...

**Comment by krillin666** [comment]
I'm also experiencing this error on Raspbian 32 bit

Any solution till now ?

**Comment by meonkeys** [comment]
That upgrade went fine for me. What error message do you get? What have you tried so far?

**Comment by servoronine** [comment]
I have not really tried anything beyong trying to upgrade once. As mentioned in the original message, I got an error stating that hte new version 26.0.2 was older than the original... I have then explicitly used version 26.0.1 in my docker-compose file and nextcloud launched without any issues - so clearly nothing was upgraded when I pulled the latest fpm version...

**Comment by hankjordan** [comment]
This upgrade is causing issues for me too:

```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

I have only seen this issue on my mariadb/mysql instances, my postgres instances are fine. Though I have not tried it yet, [migrating from mysql to postgres](https://blog.jeanbruenn.info/2022/11/25/nextcloud-migrate-to-postgresql/) may be a workaround for this issue.

**Comment by t3easy** [comment]
Maybe first fix the PHP warning by setting PHP_MEMORY_LIMIT to 1536M https://www.php.net/manual/en/faq.using.php#faq.using.shorthandbytes

**Comment by omhaal** [comment]
I also could not upgrade from 25 to 26. Got the warning:
```
nextcloud        | Can't start Nextcloud because the version of the data (                     
nextcloud        | Warning: Invalid "upload_max_filesize" setting. Invalid quantity "2048M": value is out of range, using overflow result for backwards compatibility in Unknown on line 0
nextcloud        |                                                                             
nextcloud        | Warning: Invalid "post_max_size" setting. Invalid quantity "2048M": value is out of range, using overflow result for backwards compatibility in Unknown on line 0
nextcloud        | 25.0.9.2) is higher than the docker image version (                         
nextcloud        | Warning: Invalid "upload_max_filesize" setting. Invalid quantity "2048M": value is out of range, using overflow result for backwards compatibility in Unknown on line 0
nextcloud        |                                                                             
nextcloud        | Warning: Invalid "post_max_size" setting. Invalid quantity "2048M": value is out of range, using overflow result for backwards compatibility in Unknown on line 0
nextcloud        | 26.0.4.2) and downgrading is not supported. Are you sure you have pulled the newest image version?
nextcloud        
```
Although `2048M` conforms to the article @t3easy linked to, I the environment variable `PHP_UPLOAD_LIMIT` to `1024M` and retried and the problem went away. 

So thanks @t3easy for pointing me in the right direction. The error about the current version being greater than the image version is a red herring, though :sweat: 

[From the Docker documentation](https://hub.docker.com/_/nextcloud):

> PHP_UPLOAD_LIMIT (default 512M) This sets the upload limit (post_max_size and upload_max_filesize) for big files. Note that you may have to change other limits depending on your client, webserver or operating system. Check the [Nextcloud documentation](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html) for more information.

**Comment by t3easy** [comment]
The Docker image update from 26.0.1 to 26.0.2 also upgrades PHP from 8.1.19 to 8.2.7

https://hub.docker.com/layers/library/nextcloud/26.0.1-fpm/images/sha256-95de6bb5a11626028d541594f793fabe43afb10599400fa7d8512c03d7531cf0?context=explore
https://hub.docker.com/layers/library/nextcloud/26.0.2-fpm/images/sha256-889342e791a819f0cb090c5cb95ea6863377176d7f7622c19efc2544f5623705?context=explore

I guess there is a bug in PHP itself.

**Comment by normen** [comment]
Things changed in the php image, yes. I also had to do some `chmod`ing for PHP as I don't run my docker image as root.

**Comment by tyculus** [comment]
I am experiencing something very similar, my nextcloud seems to think that 26.0.3.2 > 26.0.5.1 and therefore won't let me upgrade. I am using the stable-apache tag and get the following message:

```
nextcloud_1  | Can't start Nextcloud because the version of the data (
nextcloud_1  | Warning: PHP Startup: Unable to load dynamic library 'imap.so' (tried: /usr/local/lib/php/extensions/no-debug-non-
zts-20220829/imap.so (libc-client.so.2007e: cannot open shared object file: No such file or directory), /usr/local/lib/php/extens
ions/no-debug-non-zts-20220829/imap.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/imap.so.so: cannot open shared
 object file: No such file or directory)) in Unknown on line 0
nextcloud_1  | 26.0.3.2) is higher than the docker image version (
nextcloud_1  | Warning: PHP Startup: Unable to load dynamic library 'imap.so' (tried: /usr/local/lib/php/extensions/no-debug-non-
zts-20220829/imap.so (libc-client.so.2007e: cannot open shared object file: No such file or directory), /usr/local/lib/php/extens
ions/no-debug-non-zts-20220829/imap.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/imap.so.so: cannot open shared
 object file: No such file or directory)) in Unknown on line 0
nextcloud_1  | 26.0.5.1) and downgrading is not supported. Are you sure you have pulled the newest image version?
nextcloud_nextcloud_1 exited with code 1
```

I have temporarily revived my nextcloud by stopping my containers, reverting the on-disk files to  a snapshot I made just before the update (in a stopped state) and fixing the image to nextcloud:26.0.3-apache. It works now, but it seems that I'm stuck on this version now. I retried the update and even tried to go directly to 27 from a fresh & reverted stage, but nothing changed. I still get the same error. Every update has been smooth sailing so far, so this comes as a bit of a surprise.

I am running a derived image. Here is my docker-compose in case I am mssing something. This was completely fine for many versions in a row now.
```
# Taken & modified from:
# https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/full/apache/Dockerfile


FROM nextcloud:26.0.3-apache


RUN set -ex; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        libmagickcore-6.q16-6-extra \
        procps \
        smbclient \
        supervisor \
#       libreoffice \
    ; \
    rm -rf /var/lib/apt/lists/*

RUN set -ex; \
    \
    savedAptMark="$(apt-mark showmanual)"; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libbz2-dev \
        libc-client-dev \
        libkrb5-dev \
        libsmbclient-dev \
    ; \
    \
    docker-php-ext-configure imap --with-kerberos --with-imap-ssl; \
    docker-php-ext-install \
        bz2 \
        imap \
    ; \
    pecl install smbclient; \
    docker-php-ext-enable smbclient; \
    \
# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
    apt-mark auto '.*' > /dev/null; \
    apt-mark manual $savedAptMark; \
    ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
        | awk '/=>/ { print $3 }' \
        | sort -u \
        | xargs -r dpkg-query -S \
        | cut -d: -f1 \
        | sort -u \
        | xargs -rt apt-mark manual; \
    \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p \
    /var/log/supervisord \
    /var/run/supervisord \
;

COPY supervisord.conf /

ENV NEXTCLOUD_UPDATE=1


### CUSTOM: additional cron entries
RUN echo '0 3 * * * php /var/www/html/occ preview:pre-generate' >> /var/spool/cron/crontabs/www-data && \
    echo '0 2 * * * php /var/www/html/occ app:update --all' >> /var/spool/cron/crontabs/www-data
    
###

CMD ["/usr/bin/supervisord", "-c", "/supervisord.conf"]
```

**Comment by omhaal** [comment]
@tyculus If you look at the source of the script, you'll see that the error about version y < x (where y is larger than x) is a red herring. During the version check, an error occurs. The error causes the version check to fail and say that the new version is less than the new version, regardless of the actual values compared. So what you need to do is figure out how to solve this actual error:

```
Warning: PHP Startup: Unable to load dynamic library 'imap.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20220829/imap.so (libc-client.so.2007e: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20220829/imap.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20220829/imap.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
``` 

Fix that, and the version comparison function will once again work properly.

**Comment by tyculus** [comment]
@omhaal Thank you so much for your reply. It led me in the right direction and I was able to fix the error in my custom Dockerfile by commenting out the purge of recommended and seemingly unused packages. I am neither strapped for disk space, nor do I have to distribute my image to thousands of servers so a little extra image size is a good enough fix for me.

**Comment by joshtrichards** [comment]
The hint about the cause of the problem in each of these reports is the*weirdness* of this line:

>  Can't start Nextcloud because the version of the data (

It comes from here:

https://github.com/nextcloud/docker/blob/37ee8cfdab231703b1adb5fa20abaeceec1b95cc/27/fpm/entrypoint.sh#L153

The error messages about things like the below are messing up the version check and getting placed in the $installed_version variable (which breaks the version check):

> Warning: Invalid "upload_max_filesize" setting. Invalid quantity "2048M": value is out of range, using overflow result for backwards compatibility in Unknown on line 0

> Warning: PHP Startup: Unable to load dynamic library 'imap.so' (tried: /usr/local/lib/php/extensions/no-debug-non-

etc.

As long as you fix, in your environment, whatever is causing whatever error shows up there then you'll be golden. Basically what @omhaal said here: https://github.com/nextcloud/docker/issues/2002#issuecomment-1695055979

@omhaal: My best guess why 2048M didn't work for you, but 1024M did is that maybe you're on a 32-bit platform (i.e. see https://www.php.net/manual/en/ini.core.php#ini.post-max-size)
