### ISSUE TITLE
PHP Version is 8.2.6 on nextcloud:26.0.2-fpm

### ISSUE THREAD

**Issue by JackBailey** [nextcloud/docker#2005]
I'm using nextcloud:26.0.2-fpm with the following Dockerfile:

```Dockerfile
FROM nextcloud:26.0.2-fpm
USER root
RUN apt-get update && apt-get install -y ffmpeg

USER www-data
```

However, when nextcloud starts I get the following error:
```
This version of Nextcloud is not compatible with PHP>=8.2.
You are currently running 8.2.6.
```

How do I resolve this? I haven't changed anything except going from 26.0.1 to 26.0.2 and it appears to have this issue with either version.

**Comment by pganansia** [comment]
I have also the same problem with linuxserver/nextcloud:latest
Is there someone who has an idea or a solution ?
Rgds

**Comment by JackBailey** [comment]
It's weird as version 8.2.6 _does match_ PHP>=8.2

**Comment by pganansia** [comment]
It is written "This version of Nextcloud **is not** compatible with PHP>=8.2."
It means Next cloud has to use a php version < 8.2

**Comment by JackBailey** [comment]
Oh yep oops, ignore my message lol

**Comment by jmigual** [comment]
I've checked my `/var/www/html/version.php` and it has the following content:

```php
<?php
$OC_Version = array(25,0,6,1);
$OC_VersionString = '25.0.6';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array (
  'nextcloud' =>
  array (
    '24.0' => true,
    '25.0' => true,
  ),
  'owncloud' =>
  array (
    '10.11' => true,
  ),
);
$OC_Build = '2023-04-19T15:56:33+00:00 df9a14d1d63ad8f46d65c19c67736ef922bdbdfe';
$vendor = 'nextcloud';
```

So, somehow the upgrade process is never triggered.

**Comment by jmigual** [comment]
Okay I solved it by adding the following to the docker call: `NEXTCLOUD_UPDATE=1` this forces the update

**Comment by JackBailey** [comment]
Yep looks like nextcloud just needed an update either ran by that flag or `docker exec -it nextcloud updater.phar`, fixed it for me.

**Comment by LoveIsGrief** [comment]
This problem still presents itself for me on `26.0.5-fpm`

```
/var/www/html $ ./occ 
This version of Nextcloud is not compatible with PHP>=8.2.<br/>You are currently running 8.2.10./var/www/html $ 
```

The env var is also set. I'll just stick to nextcloud v25 for now and abort the update
```
/var/www/html $ echo $NEXTCLOUD_UPDATE
1
```
