### ISSUE TITLE
OCC doesn't work on v27

### ISSUE THREAD

**Issue by hutcheon** [nextcloud/docker#2022]
Since the upgrade to v27, occ commands have not worked.  Gives error:

```
www-data@2c2a44bd69f4:~/html$ /usr/src/nextcloud/occ
Cannot write into "config" directory!
This can usually be fixed by giving the web server write access to the config directory.

But, if you prefer to keep config.php file read only, set the option "config_is_read_only" to true in it.
```

The problem seems to be that occ tries to use a config file at /usr/src/nextcloud/config/config.php instead of /var/www/html/config

I can see this if I install strace (as root), then running /usr/src/nextcloud/occ as www-data:
```
access("/usr/src/nextcloud/config//config.php", F_OK) = 0
access("/usr/src/nextcloud/config//config.php", W_OK) = -1 EACCES (Permission denied)
```

**Comment by joshtrichards** [comment]
`./occ`

Or even:

`/var/www/html/occ`

Don't use the one in /usr/src/nextcloud :-)
