### ISSUE TITLE
Installing redis and executing redis.config.php does not enable filelocking

### ISSUE THREAD

**Issue by yevon** [nextcloud/docker#2024]
Installing redis and executing redis.config.php doesn't seem to enable filelocking.

[https://github.com/nextcloud/docker/blob/master/27/apache/config/redis.config.php](https://github.com/nextcloud/docker/blob/master/27/apache/config/redis.config.php)

It should contain 'filelocking.enabled' => true isn't it?
[https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html#:~:text=Nextcloud's%20Transactional%20File%20Locking%20mechanism,a%20filesystem%20that%20supports%20locking](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/files_locking_transactional.html#:~:text=Nextcloud's%20Transactional%20File%20Locking%20mechanism,a%20filesystem%20that%20supports%20locking)

The helm chart states that when redis is installed, file locking is enabled:
<html>
<body>

redis.enabled | Whether to install/use redis for locking | false
-- | -- | --

</body>
</html>

But the config file doesn't enable it, and I cannot edit the php config directly with docker as it get overwritten on every restart isn't it?.

**Comment by joshtrichards** [comment]
Hi @yevon - 

`filelocking.enabled` is enabled by default by Nextcloud. There's no need to set it there.

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#filelocking-enabled

And setting `memcache.locking` to use Redis is all that's needed to not rely on the db for file locking (which gets done there).

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#memcache-locking

**Comment by yevon** [comment]
Thnaks! Closing this
