### ISSUE TITLE
Cannot pass the first page

### ISSUE THREAD

**Issue by t18n** [nextcloud/docker#2025]
I am trying to set up NextCloud with Traefik. SSL and domain has been working great. But when I try to create the admin account, it always show this error
![image](https://github.com/nextcloud/docker/assets/14198542/ff1e0ff7-97d2-4cb1-9bc6-d396775429fb)

My docker-compose
![image](https://github.com/nextcloud/docker/assets/14198542/f639f2af-8fd5-4e1f-85c4-91a9cc9f0491)

**Comment by joshtrichards** [comment]
Hi @t18n - I'm sorry to hear you're running into some challenges. This is a configuration matter. Please post it over at the [Nextcloud Help Forum](https://help.nextcloud.com). This channel is for bug reports and enhancement requests.

**Comment by t18n** [comment]
Thanks @joshtrichards, I am not sure what I've tried, I think I gave the volume that holds the nextcloud volume more generous permission and the problem is resolved for now :)
