### ISSUE TITLE
Container could not bind port 80 to itself

### ISSUE THREAD

**Issue by frequency403** [nextcloud/docker#2027]
As i recently pulled the new version of the nextcloud:latest Image, a weird problem occured.

Snippet from docker-compose.yaml:

nextcloud:  
        image: nextcloud:latest  
        container_name: nextcloud  
        ports: 
            - 5555:80

And it says in the logs:

2023-07-11T08:11:47.955103382Z => Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/before-starting
2023-07-11T08:11:47.959283385Z ==> but the hook folder "before-starting" is empty, so nothing to do
2023-07-11T08:11:48.082631557Z AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.4. Set the 'ServerName' directive globally to suppress this message
2023-07-11T08:11:48.096065765Z (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
2023-07-11T08:11:48.096131865Z no listening sockets available, shutting down
2023-07-11T08:11:48.096157065Z AH00015: Unable to open logs

I tried to disable any connections from outside to the container (proxy) - but the Error still exists.

--EDIT--
Even if the container doesnt bind to the host, the error occures

**Comment by ashwaq06** [comment]
I have no prior experience in Contribution for opensource but I have knowledge in this area, which I believe will be valuable in resolving this issue. If you think it's suitable, I'd be grateful for the opportunity to work on this and contribute to the project . I will be providing my suggestions on the issue down below.

The error message you're encountering suggests that there is a conflict with port 80, which is already in use by another process on your system. Additionally, there is a warning about the server's fully qualified domain name (FQDN) not being set.
To address these issues, you can take the following steps:

1. Addressing Port Conflict:

- Ensure that you don't have any other service or process already running on port 80 of your host machine.
- Check for any other containers or applications using port 80 and stop or reconfigure them to use a different port.
- If you have any reverse proxies or other networking configurations, make sure they are not conflicting with the port binding of the Nextcloud container.

2. Setting ServerName Directive:

- In your Apache configuration file (httpd.conf or a virtual host configuration file), add the ServerName directive globally.
- Set the ServerName to the desired FQDN or IP address. For example:
`ServerName example.com
`

- Restart the Apache service within the Nextcloud container to apply the changes.

3. Checking Docker Networking:

- Confirm that there are no networking issues within your Docker setup. Ensure that Docker is properly configured and running, and that there are no conflicts with networking settings or port mappings.


By addressing the port conflict and setting the ServerName directive, you should be able to resolve the issues you're facing with the Nextcloud container. If the problem persists, check the Nextcloud documentation or the project's issue tracker for specific troubleshooting steps related to this error.
