### ISSUE TITLE
`PHP_MEMORY_LIMIT` doesn't seem to work

### ISSUE THREAD

**Issue by kagstrom2100** [nextcloud/docker#2040]
So I've just set up Nextcloud in docker and been trying to pre-generate photos. I keep running in to the memory limit though.
Seen a few similar issue on here  (#1648) , but non of their workarounds worked in my case.

**Image:** nextcloud:latest (2023-07-26)
**Version:** Nextcloud Hub 5 (27.0.1)

**Config.php:**

```
<?php
$CONFIG = array (
  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Movie',
    1 => 'OC\\Preview\\PNG',
    2 => 'OC\\Preview\\JPEG',
    3 => 'OC\\Preview\\GIF',
    4 => 'OC\\Preview\\BMP',
    5 => 'OC\\Preview\\MP3',
    6 => 'OC\\Preview\\MP4',
    7 => 'OC\\Preview\\AVI',
    8 => 'OC\\Preview\\MKV',
    9 => 'OC\\Preview\\MOV',
  ),
  'htaccess.RewriteBase' => '/',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'redis',
    'password' => 'REDACTED',
    'port' => 6379,
  ),
  'trusted_proxies' =>
  array (
    0 => '192.168.224.0/20',
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'REDACTED',
  'mail_smtpport' => 465,
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'REDACTED',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'REDACTED',
  'mail_smtppassword' => 'REDACTED',
  'instanceid' => 'REDACTED',
  'passwordsalt' => 'REDACTED',
  'secret' => 'REDACTED',
  'trusted_domains' =>
  array (
    0 => 'REDACTED',
  ),
  'datadirectory' => '/mnt/cloud_data',
  'dbtype' => 'pgsql',
  'version' => '27.0.1.2',
  'overwrite.cli.url' => 'REDACTED',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'REDACTED',
  'dbpassword' => 'REDACTED',
  'installed' => true,
  'allow_local_remote_servers' => true,
  'default_phone_region' => 'REDACTED',
  'maintenance' => false,
  'loglevel' => 2,
  'memories.exiftool' => '/var/www/html/custom_apps/memories/exiftool-bin/exiftool-amd64-glibc',
  'memories.vod.path' => '/var/www/html/custom_apps/memories/exiftool-bin/go-vod-amd64',
  'memories.vod.ffmpeg' => '/usr/bin/ffmpeg',
  'memories.vod.ffprobe' => '/usr/bin/ffprobe',
);
```
**PHP Memory Limit:**
```
Version: 8.2.8
Memory limit: 536,9 MB
Max execution time: 3600
Upload max size: 536,9 MB 
```

**Command:**
`sudo docker exec Nextcloud-App su -p www-data -s /bin/bash -c '/var/www/html/occ preview:generate-all -vvv'`

**The command runs for a good while, but eventually stops with the following error:**
`PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 28672 bytes) in /var/www/html/lib/private/legacy/OC_Image.php on line 533
`

**Comment by kagstrom2100** [comment]
> What exactly did you try from #1648? Your command should look like this: `sudo docker exec -u $DOCKER_WWW_UID Nextcloud-App /var/www/html/occ preview:generate-all -vvv` and you need to set a higher for the `PHP_MEMORY_LIMIT` environment variable when you create the container with `docker run` or `docker create`.

Tried all the different commands that was suggested on that issue, also tried running the command you suggest, but all gives the same results.

I did also try and increase the `PHP_MEMORY_LIMIT` by setting it as an environment variable in the .env file. This dosn't seem to do anything though, looking at the Administration -> System -> System gives me this: 
```
Version: 8.2.8
Memory limit: 536,9 MB
Max execution time: 3600
Upload max size: 536,9 MB

Extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, session, PDO, pdo_sqlite, standard, posix, random, Reflection, Phar, SimpleXML, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, sysvsem, zip, Zend OPcache
```
Do I have to mount the php.ini file and change it manually maybe?

About the last suggest solution @szaimen says you have to run `sudo -E -u www-data php occ` but this omits the docker command?

**Comment by kagstrom2100** [comment]
Tried increasing the PHP_MEMORY_LIMIT using the environment variable (default is 500 MB) by creating "upload-max-filesize.ini" in /usr/local/etc/php/conf.d and added PHP_MEMORY_LIMIT = 8G, but this still doesn't change the value shown in the info panel on Nextcloud.

Found here: https://www.reddit.com/r/NextCloud/comments/ffdx4y/nextcloud_max_file_size_2mb_in_docker/fuxr9wf/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by joshtrichards** [comment]
The `PHP_MEMORY_LIMIT` environment variable needs.to be passed to Docker when you *create* your container. 

So either put in your Docker Compose file or as a `-e` parameter if not using Compose. If the variable is in place, the php ini file will be updated with the appropriate parameters and values whenever you recreate the container.

(Btw: The reason your manual addition of it to `/usr/local/etc/php/conf.d/` didn't work is because the environment variable is a parameter for the Docker image, but the PHP parameters it ultimately adds are not literally the same name).

I'm going to close this out since it appears to be a configuration matter. The [Nextcloud Help Forum](https://help.nextcloud.com) is  the best spot to follow-up if you need further help: this channel here is for reporting bugs in the image.
