### ISSUE TITLE
Nextcloud fpm INVALID_HASH after update

### ISSUE THREAD

**Issue by Randerspl** [nextcloud/docker#2058]
Hello,
i just did update from 27.0.1-fpm to 27.0.2-fpm.
Installation completed normally (i think) but on admin panel it shows that one file has invalid hash.

```
Results
=======
- provisioning_api
	- INVALID_HASH
		- composer/composer/InstalledVersions.php

Raw output
==========
Array
(
    [provisioning_api] => Array
        (
            [INVALID_HASH] => Array
                (
                    [composer/composer/InstalledVersions.php] => Array
                        (
                            [expected] => 733e68c171cb9e44868bb0f105850fbd0e4f225c67235bf30fb2ac5c3443c6edfb722d4b33aa91c82bb600e937cb6392eb1883694d41616e66969d7d42e23b4f
                            [current] => 4b9a7eeaedc3f73c7320bef284fb36136d03d3b37a3247e444d08b434edfaada3937bb35d60ca63303cd89d48cbe7344bc6f68607b3922d62020202de53b76c1
                        )

                )

        )

)
```

Im building using docker compose and using simple dockerfile for ffmpeg installation.

```
FROM nextcloud:27.0.2-fpm

RUN apt-get update && apt-get install -y ffmpeg && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*
```

On logs i didn't find any error outputs, only Info or Debug levels.
I removed container images and then did second build and this error shows again.

Should i do anything more or it is just some minor bug (looking on filename  it seems like file containing application version?)

**Comment by joshtrichards** [comment]
If it is a bug, it's an upstream matter in https://github.com/nextcloud/server rather than the community Docker image. But:

- that file hasn't changed in months and has been the same since v27.0.0.
- it would be impacting basically everyone since that's a shipped app. 
-  I haven't run across anyone else with the same issue so far.

For what it's worth, I'm unable reproduce this situation. 

Any chance you have more than one `provisioning_api` app installed across your various `app_paths` directories from your `config.php`?

The one in my image matches:
```
x@x:~/html/apps/provisioning_api/composer/composer$ sha512sum InstalledVersions.php 
733e68c171cb9e44868bb0f105850fbd0e4f225c67235bf30fb2ac5c3443c6edfb722d4b33aa91c82bb600e937cb6392eb1883694d41616e66969d7d42e23b4f  InstalledVersions.php
x@x:~/html/apps/provisioning_api/composer/composer$ 
```

And the one in the `server` repository matches:

```
x@node2:~/src/infrastructure/test/test-nc27$ wget https://raw.githubusercontent.com/nextcloud/server/stable27/apps/provisioning_api/composer/composer/InstalledVersions.php
[...]
Saving to: ‘InstalledVersions.php’
[...]
2023-08-13 13:42:26 (28.0 MB/s) - ‘InstalledVersions.php’ saved [16143/16143]

x@node2:~/src/infrastructure/test/test-nc27$ sha512sum InstalledVersions.php 
733e68c171cb9e44868bb0f105850fbd0e4f225c67235bf30fb2ac5c3443c6edfb722d4b33aa91c82bb600e937cb6392eb1883694d41616e66969d7d42e23b4f  InstalledVersions.php
```

**Comment by Randerspl** [comment]
Thank you very much @joshtrichards, because of your commands i got knowledge where this file is (i didn't know before).

After my investigation i downloaded file from github server and from my instance and then did comparison.
The difference was very simple and looks like a human error.
![image](https://github.com/nextcloud/docker/assets/9450923/b9b99bba-a5af-425a-b378-8e81c4195ef0)
I don't have any idea how `s` was changed to `3`. And i didn't even get close to this file before (i didn't even entered this folder).
One thing it is in my mind is that after i changed version in docker compose i didn't removed images from machine and did docker compose [...] --build. But this was not working because my instance started as 27.0.1 and didn't do update in logs (but docker compose downloaded files and was looking like building new image).

After i manually fixed this file now nextcloud is saying everything is ok.

**Comment by Randerspl** [comment]
I can close this issue because my problem got resolved.
