### ISSUE TITLE
Docker image entrypoint issue

### ISSUE THREAD

**Issue by viggy96** [nextcloud/docker#2059]
I'm encountering a bug in the entrypoint script. I get the following message.
```
  => Searching for scripts (*.sh) to run, located in the folder: /docker-entrypoint-hooks.d/before-starting
==> but the hook folder "before-starting" is empty, so nothing to do
```
I believe its from here: https://github.com/nextcloud/docker/blob/74d33d0020000f3a955e14119f0d7592982e7a31/docker-entrypoint.sh#L29

Nextcloud fails to start, I get no web GUI, or anything.

**Comment by viggy96** [comment]
Turned out to be networking issue.

**Comment by Dreytac** [comment]
I've just updated to the latest Docker image pushed half an hour ago and I'm getting this error now. I haven't changed any configuration and everything else is working as expected.

**Comment by KptnKMan** [comment]
> Oh okay never mind I think I figured out the issue.
> 
> I made a change to the address of the DB in the Helm chart I use to configure Nextcloud, but for some reason that didn't update the config file. Updating the config file to the correct DB address got Nextcloud loading again. No idea why this is the only message that shows and nothing about how it's unable to connect to the DB pops up 🤔

Im getting this error, can you elaborate on what you did to solve the problem?
What was the network issue, and what did you update in your config?
