### ISSUE TITLE
missing config option 'allow_local_remote_servers' 

### ISSUE THREAD

**Issue by coelner** [nextcloud/docker#2060]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=allow_local_remote_servers%20true#proxy-configurations

> 'allow_local_remote_servers' => true,
> Allow remote servers with local addresses e.g. in federated shares, webcal services and more
> Defaults to false`

I tried to mount a webdav share from a different docker container, but this container is only available on the internal network.
It is not possible to create a predefined option, so there is the `busybox vi config/config.php` way to add this.

**Comment by coelner** [comment]
Thanks, the `NC_` - prefix does the trick.

**Comment by Ziris85** [comment]
Hello! I'm finding myself faced with a similar issue, with nextcloud being ornery about connecting to my collabora instance. It doesn't look like the `NC_ALLOW_LOCAL_REMOTE_SERVERS` env var works (anymore? ever?). I did ultimately end up just creating a custom `*.config.php` file with that enabled, but I get the feeling that this kind of connectivity is common enough that it warrants it's own, documented, env var. A quick Google search for "Host violates local access rules" turns up endless questions and discussions that all ultimately suggest enabling this config as the fix.

So just commenting on this bug report to throw my vote behind that notion.

**Comment by brlin-tw** [comment]
I've checked the entrypoint script, and it indeed does not act on the `NC_ALLOW_LOCAL_REMOTE_SERVERS` environment variable.

**Comment by joshtrichards** [comment]
@brlin-tw It's not in the entrypoint because `NC_*` variables are handled internally by Nextcloud Server itself.

See #2226

@Ziris85 Also see #2231
