### ISSUE TITLE
Mount additional local storage as external does not work - red exclamation mark

### ISSUE THREAD

**Issue by Sorwrath** [nextcloud/docker#2066]
Hello all,

As per my post in Nextcloud https://help.nextcloud.com/t/red-exclamation-mark-on-local-storage-docker-portainer-multiple-ssds/170057 (and having no response whatsoever), i will try my luck here! 

I will copy what i wrote already to save you some time :)

-------------------------------------------
I am bit stuck the last 3 days. I have read through forums for a solution but i am still getting a red exclamation mark when i add a local storage. My setup is Docker with Portainer to manage, and i have 5 data folders for Nextcloud. Data is the one i setup initially, this works fine, data2 and data3 is part of the same SSD as data but on different partitions. Data4 and data 5 have each their own SSD. I changed the permission with chown to match the settings of the first data folder but it did not helped.

Here are some information. From the permissions.

$ ls -l /srv/dockerdata/nextcloud_data/config/www/nextcloud/config/config.php
-rw-r----- 1 fileserveradmin fileserveradmin 802 Sep 13 12:16 /srv/dockerdata/nextcloud_data/config/www/nextcloud/config/config.php

$ ls -l /srv/dockerdata/nextcloud_data
total 8
drwxr-xr-x 8 fileserveradmin fileserveradmin 4096 Sep 12 13:30 config
drwxrwx— 6 fileserveradmin fileserveradmin 4096 Sep 12 14:37 data

From the rest of the folders in different partitions/SSDs

total 4
drwxrwx— 2 fileserveradmin fileserveradmin 4096 Sep 13 12:16 data2

total 4
drwxrwx— 2 fileserveradmin fileserveradmin 4096 Sep 12 18:38 data3

total 4
drwxrwxr-x 2 fileserveradmin fileserveradmin 4096 Sep 12 18:39 data4

total 4
drwxrwxr-x 2 fileserveradmin fileserveradmin 4096 Sep 12 18:40 data5

![quickshot_230913_130525](https://github.com/nextcloud/docker/assets/123364832/15975f0c-c42e-4bb7-a45c-d4546cbcd258)

I can add them as bind mounts through Portainer/docker when i edit and redeploy the container but unfortunately i can not control which folder is assigned to each drive/mount, at least 1 folder would be sufficient for me. It looks that Nextcloud waits to fill the first drive and then go to the next one, from what the floating tool-tips suggests, but i am not sure.

To make things even more interesting, if i use only the /media/ i get a green check mark! If use a /media/sda4 for example, as expected i get the error again. The weird is also the /media/ is part of the root group and not the fileserveradmin group. But also the sda4 is part of the root group.

![quickshot_230913_163430](https://github.com/nextcloud/docker/assets/123364832/f99cfc92-e563-4e88-a135-1eaaa892c713)

Here are their permissions.

drwxr-xr-x 7 root root 4096 Sep 12 18:13 media

$ ls -l /media/
total 20
drwxr-x—+ 2 root root 4096 Sep 7 21:08 fileserveradmin
drwxr-xr-x 4 root root 4096 Sep 13 11:51 sda4
drwxr-xr-x 4 root root 4096 Sep 12 18:37 sda5
drwxr-xr-x 4 root root 4096 Sep 12 18:38 sdb1
drwxr-xr-x 4 root root 4096 Sep 12 18:39 sdc1

Also when i go and check the /media/ there is no folder or files there, but i get them on web GUI of nextcloud

![quickshot_230913_164359](https://github.com/nextcloud/docker/assets/123364832/2cd72d9d-445b-4095-ab6f-dc4f1af0c49b)

from root search for the ‘Nextcloud intro.mp4’ that does not appear inside the test folder.

/srv/dockerdata/nextcloud_data/data/omitted-admin/files/Nextcloud intro.mp4

/var/lib/docker/overlay2/12916fb1f09cd962288192b3ebe2499428cb42d3bb324dbcfd42dcb820c87696/diff/app/www/public/core/skeleton/Nextcloud intro.mp4

/var/lib/docker/overlay2/12916fb1f09cd962288192b3ebe2499428cb42d3bb324dbcfd42dcb820c87696/merged/app/www/public/core/skeleton/Nextcloud intro.mp4

/var/lib/docker/overlay2/12916fb1f09cd962288192b3ebe2499428cb42d3bb324dbcfd42dcb820c87696/merged/app/www/src/core/skeleton/Nextcloud intro.mp4

/var/lib/docker/overlay2/ba8c9edb0139f867b44dac321707a1af1ba8af26565f5f85ce9e6731a1ccc2ff/diff/app/www/src/core/skeleton/Nextcloud intro.mp4

/timeshift/snapshots/2023-09-13_13-00-01/localhost/srv/dockerdata/nextcloud_data/data/omitted-admin/files/Nextcloud intro.mp4

I am suspecting that there is a line in the config files that causing this.

-------------------------------------

Additionally tried the "check_data_directory_permissions' => false," and the "sudo chmod u+rwx /mnt/data" from this page 
https://github.com/nextcloud/docker/issues/236 - but unfortunately no joy, same issue. 99% of the time i stop the Nextcloud container, make changes and start it again.

If anyone can help i will appreciate it!!

**Comment by joshtrichards** [comment]
Hi @Sorwrath: I'll try to help you out a bit on the forum since that's a more appropriate place for this (since this is more a channel for reporting bugs or enhancement ideas with the official Nextcloud Docker image). In addition, based on your forum post you're actually not using the official Nextcloud Docker image handled by us here in this repository. You're using the LinuxServer.io one - which is a solid image, but definitely not us here. :)

To that end, I'm going to close this issue here for now since there isn't anything for us to fix per se.
