### ISSUE TITLE
[Bug]: Upgrade dilemma 25 to 27

### ISSUE THREAD

**Issue by xeruf** [nextcloud/docker#2079]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am trying to upgrade from Nextcloud 25 to 27, accidentally ending up with a skipped version in my kubernetes cluster.
I tried to run `occ upgrade` in version 27 and got:

Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed

Then I tried to go back to Nextcloud 26, but that failed too:

Can't start Nextcloud because the version of the data (27.0.2.1) is higher than the docker image version (26.0.2.1) and downgrading is not supported. Are you sure you have pulled the newest image version?

So I cannot run at 26 because the data is supposedly at 27 but I cannot upgrade it to 27 because the data is supposedly at 25. What the heck?

### Steps to reproduce

good question

### Expected behavior

Either the data is at 25 or 27, not both at once?

### Installation method

Stackspin Kubernetes Cluster

**Comment by wetneb** [comment]
I have recently made a change which intended to address exactly this issue (https://github.com/nextcloud/docker/pull/2018).
I wonder if this change was already included in the Docker image of NextCloud 27 that you used. Can you tell us about the exact name of the Docker image you used, and when you pulled it?

For workarounds about how to restore your instance, see #1809, #1129, #616 and #617.

**Comment by isdnfan** [comment]
IMHO this [comment](https://github.com/nextcloud/docker/issues/617#issuecomment-742750405) resolves the problem at 99% success rate

**Comment by joshtrichards** [comment]
Closing since this has been addressed.
