### ISSUE TITLE
Apache: X-Forwarded-For not applied

### ISSUE THREAD

**Issue by UltraBlackLinux** [nextcloud/docker#2081]
So I have tried a lot but I just cannot get this to work at all.

Every time I access my nextcloud interface on the apache image, I see the IP of the local proxy in the console. Until I set the trusted_proxies variable to the IP that the requests are proxied through, I saw a warning in the web UI about that. Brute force throttling did work, at least to some extent.
Since I set that variable, there is no brute force throttling and I still see that proxy IP in the logs.

I even went as far as creating a custom apache config file which explicitly specified the headers, but to no avail.

Why is this not working by default? How do you make it work? I'm tired of trying to debug something that I have practically no knowledge about (apache) so I need some help here.

I just want this to be safe and I'm surprised that the provided configuration is not working as it should

After checking /etc/apache2/conf-enabled/remoteip.conf I even changed the nextcloud config variable for the header to "X-Real-IP" since that's what it's using, but to no avail again

**Comment by melle2** [comment]
In general the approach how to configure reverse proxy is described here https://github.com/nextcloud/docker#using-the-apache-image-behind-a-reverse-proxy-and-auto-configure-server-host-and-protocol
This is not an issue with the Nextcloud docker image but with the configuration of your Apache reverse proxy.

> Why is this not working by default?

It is working by default! You only have to configure your reverse proxy and your Nextcloud in the right way.
> I'm tired of trying to debug something that I have practically no knowledge about (apache) so I need some help here.

Sorry to say, but irrespective if you're setting up Nextcloud with a Docker image or using Nextcloud with a http server. It is essential to understand how it works. Keep in mind, Apache != Nextcloud.
In my view, the easiest way for you would be to follow a howto without a Docker container which is described [here](https://www.howtoforge.com/tutorial/ubuntu-nginx-nextcloud/). Then you don't need to worry about a reverse proxy, which adds additional complexity.
I don't know your setup, and based on the missing information about your setup, I'd guess that no one would be able to help you.

However, to give you a hint, you should verify if you have considered the following config in your reverse proxy setup

```
        RemoteIPHeader X-Forwarded-For
        RequestHeader set X-Forwarded-Proto 'https'
        RemoteIPInternalProxy YOUR_CIDR_OR_IP
        ProxyPreserveHost On
```
Good luck!

**Comment by UltraBlackLinux** [comment]
>  Keep in mind, Apache != Nextcloud.
Yeah I'm aware of that. I'm asking here because the provided docker image should work, which it doesn't currently.

I'm just now realizing something. I have this docker container running behind caddy: `Caddy -> [ Apache -> Nextcloud ]`
Is it possible that apache doesn't read the X-Forwarded-For header provided by Caddy? I'm using this setup so I'm not introducing security flaws into my setup and I haven't really had any issues with cascading proxies like this.

**Comment by UltraBlackLinux** [comment]
> `RemoteIPInternalProxy YOUR_CIDR_OR_IP`

I just did what I should have done for quite a while now. I checked the docs on what this does instead of assuming how it works. I had this set to the IP that I saw in the nextcloud logs. I read the docs and set it to the hostname of my caddy instance. Now it works. Thank you for guiding me here, I guess I need to remember that reading helps
