### ISSUE TITLE
Update docker compose examples to move way from deprecated `--link`

### ISSUE THREAD

**Issue by tippexs** [nextcloud/docker#2087]
First of all this repository contains awesome examples and getting started configuration! Well done!

I was just working on a issue https://github.com/nextcloud/docker/issues/1063 and updated my docker compose files to the latest API Version 3 and removed the deprecated `--link` option. As it is still supported in Version 2, Docker recommends the ussage of `networks`. See: https://docs.docker.com/compose/compose-file/compose-file-v2/#links

Before creating a PR I just want to be sure they are welcome and an update to compose V3 is appropriate! Happy to drop a PR to update the README.md docker compose exmaples.

https://github.com/nextcloud/docker/blob/master/README.md#base-version---apache

Keep up the great work!
Cheers Timo

**Comment by tippexs** [comment]
@joshtrichards thanks for adding the labels and sorry for my late response! I will work on the PR and submit it once I am back in my office. Currently in transit over the atlantic ocean. ✈️

**Comment by joshtrichards** [comment]
Closing since other PRs have now eliminated the `--link` usage. :)
