### ISSUE TITLE
BYOS - Bring your own SSL Certificates

### ISSUE THREAD

**Issue by robclay** [nextcloud/docker#210]
I bought some SSL certificates (My ISP does not allow Port 80 and I needed to get up and running quickly) so that I can access my qnap remotely using docker.  
I used the example [here](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/insecure/mariadb-cron-redis/fpm).  
I have it working - I am interested in knowing if I am creating a future problem:
In the web portion of the docker-compose file, 
I added a volume:
`volumes:`
`  -  /share/ncssl:/srv`
I then added the following in the nginx.conf
`       ssl_certificate      /srv/ssl_cert.crt;`
`        ssl_certificate_key  /srv/Key-File.key;`
I choose the 'srv' folder from the container because it was empty.  I then copied my ssl certs into the /share/ncssl folder.  
Like I mentioned, this is working, and I can access remotely.  But was using `/srv` okay?  Dumb?  Is there a better practice? 

Thanks for any guidance!

**Comment by SnowMB** [comment]
You don't have to use an existing folder. You can specify any path you want.

If you're unsure use something self explanatory like `/ssl` or `/certs`.

**Comment by robclay** [comment]
Ha!  I had bin/sh'd into the container to look for a folder to use.  Didn't realize I could do it that easily!  Thanks!
