### ISSUE TITLE
flaky tests prevent pushing images - latest Dockerfile does NOT reflect latest Nextcloud Update from 27.1.3 to 27.1.4 

### ISSUE THREAD

**Issue by henningsieh** [nextcloud/docker#2104]
Hi.

The latest master branch only contains the previous version 27.1.3
=> see master Dockerfile here: https://github.com/nextcloud/docker/commit/4c24a2ae8ed0b1c6dff7aeddb6fb2d8e07d87f3e#diff-ba531c54643576be3aab1b9c8dd47b669d4a27f024512ecb1506cae5ec6b61bf

The Update has been commited yesterday.
=> see commited/updated Dockerfile here: https://github.com/nextcloud/docker/commit/44e01e1eab2160bce02686797a51f81a3a021551#diff-ba531c54643576be3aab1b9c8dd47b669d4a27f024512ecb1506cae5ec6b61bf

So, the commited update hasn't found its way into the master branch and/or is NOT included in the official [Nextcloud Image on Docker Hub](https://hub.docker.com/_/nextcloud).

So docker-compse does no _nextcloud-27.1.4_ update, because 'latest' still refers to _27.1.3_.

Do I miss or missunderstand somthing in general here?

Thanks in advance (and sorry, if it's not an issue but a noob question!)

**Comment by martadinata666** [comment]
Because it has flaky test https://github.com/nextcloud/docker/actions/runs/6985847840 that prevent pushing images.

**Comment by henningsieh** [comment]
> Because it has flaky test ...

Hey, thanks for pointing that out to me.... My research didn't go that far. 🙏

**Comment by l0drex** [comment]
I just tried to update Nextcloud through the web ui, but got a 404 when trying to open the updater. Is that expected? Am I supposed to only do updates with docker compose?

**Comment by henningsieh** [comment]
> just tried to update Nextcloud through the web ui, but got a 404 when trying to open the updater

Yes, here too. 

If I remember correctly, this seems to be the NORMAL BEHAVIOR when running Nextcloud as a Docker image.

In the past, I could always use the "docker-compose" routines to start an updated Nextcloud after deleting the old image and container. (Or in my case use the Portainer frontend [as you can see here](https://prikatschik.de/nextcloud-docker-container-update-mit-portainer/)).

I wonder, if waiting "is enough" in this case and if someone is fixing the flaky tests in CI/CD, so that the updated images get shipped? 🤔

**Comment by henningsieh** [comment]
Hello.

I really don't know what's going on here (sorry!), but as of now there's only one faulty test left: [27.1.4-apache (i386) failed](https://github.com/nextcloud/docker/actions/runs/7012426462)

```
27.1.4-apache (i386)
Process completed with exit code 1.
```

Hopefully all images get pushed to Docker Hub after the next run, if all tests went fine!?

**Comment by Strit** [comment]
It's been a couple of months since the action has completed successfully. I hope someone is looking into fixing what's wrong.

**Comment by martadinata666** [comment]
So curious about previous image updates like this one https://github.com/nextcloud/docker/actions/runs/6979766289/job/18993721739 all green but the log success, technically I don't know what is success criteria is, I thought triple database installation/deployment test. But seems not it or intended too but not really working.

**Comment by donkeyDau** [comment]
27.1.4 is available now. Even though it does not show up on the README but on the recent tags:

![image](https://github.com/nextcloud/docker/assets/17231336/01c4aa21-8813-449e-af68-9ebbf1cb358d)
