### ISSUE TITLE
Upgrade 27.1.3 to 27.1.4 no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by m0rph2k** [nextcloud/docker#2105]
Hi

I can not upgrade from nextcloud:27.1.3-apache to nextcloud:27.1.4-apache error --> no matching manifest for linux/amd64 in the manifest list entries

**Comment by meonkeys** [comment]
Have you searched for similar issues? I feel like this comes up often.

I vaguely recall it takes a while for upstream to update official Docker images. Something like that. Whatever it is, when we figure it out we should make a PR to update the top-level readme.
