### ISSUE TITLE
Use docker apache under subdir with reverse proxy

### ISSUE THREAD

**Issue by akralj** [nextcloud/docker#211]
Hi,
since days i'm trying to get the default apache docker image 12.04 to work under http://mydomain.com/api/cloud, but with no avail.
I tried all documented settings in config.php and also changing apache2.conf.

#### docker config
`docker run --name nextcloud --restart=always -d -v /apps/nextcloud/html:/var/www/html -v /apps/nextcloud/apache2:/etc/apache2 -p 7070:80 nextcloud`
#### config.php
```
'trusted_domains' =>
  array (
    0 => 'mydomain.com:7070',
    1 => 'mydomain.com:7060',
  ),

  'htaccess.RewriteBase' => '/',
  'overwrite.cli.url' => 'http://mydomain.com:7060',
  'overwritehost' => 'mydomain.com:7060',
  'overwritewebroot' => '/api/cloud',
```
This config works as long a user was logged on beforehand at the root domain without the above custom settings in config.php.  When trying to login in a private window at this url:
http://mydomain.com:7060/api/cloud/login

I get the following javascript errros in chrome console:
```
Uncaught ReferenceError: oc_appconfig is not defined
    at merged-share-backend.js?v=4312c8c4cdfe10ec7e0a9c65160aa6c0-0:24
    at merged-share-backend.js?v=4312c8c4cdfe10ec7e0a9c65160aa6c0-0:80
Uncaught TypeError: Cannot read property 'substring' of undefined
    at Object.filePath (merged-template-prepend.js?v=4312c8c4cdfe10ec7e0a9c65160aa6c0-0:1349)
    at viewer.js?v=4312c8c4cdfe10ec7e0a9c65160aa6c0-0:15
```
and this browser html:
````
Interner Serverfehler

Der Server hat einen internen Fehler und konnte Deine Anfrage nicht vervollständigen.
Bitte wende dich an den Serveradministrator, wenn dieser Fehler mehrfach auftritt, gebe bitte die, unten stehenden, technischen Details in Deinem Bericht mit an.
Weitere Details können im Server-Protokoll gefunden werden.

Technische Details

Entfernte Adresse: 172.17.0.1
Anfragekennung: PgnC74i4ti2HzMSNNTGi
````

So it seems my proxy is basically working, but i cant do an logins.

Do you have an working example of a docker image (i don't care which one) and a reverse proxy on the host machine, which proxies to a subdir.
thanks so much for your help
andrej

**Comment by tilosp** [comment]
Take a look at https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html#pretty-urls
You need to set `htaccess.RewriteBase` to `/api/cloud`

**Comment by akralj** [comment]
thanks for your help, but it is still not working.
I added you suggestion to config.php, but no luck. still get the above javascript errors on login.
```
'trusted_domains' =>
  array (
    0 => 'mydomain.com:7070',
    1 => 'mydomain.com:7060',
  ),

  'htaccess.RewriteBase' => '/api/cloud',
  'overwrite.cli.url' => 'http://mydomain.com:7060',
  'overwritehost' => 'mydomain.com:7060',
  'overwritewebroot' => '/api/cloud',
```
and again. i tried all sorts of combinations, but not working. any suggestion, how i could at least get the docker image run under a subdir, without a proxy. please be so kind and post a complete config.php.
thanks a lot

**Comment by marceljd** [comment]
If you look at the examples tilosp gave you you should replace 2 things:
'overwrite.cli.url' => 'https://example.org/api/cloud:7060',
'htaccess.RewriteBase' => '/api/cloud',

I think the webroot is an internal server rewrite and should be removed. You problably installed in /var/www/html and not in /var/www/html/api/cloud. I don't know why you added the overwritehost, can't you remove that too?

**Comment by akralj** [comment]
thank you for your suggestion, but i'm giving up.
I spent hours trying all possible combinations, but no luck.
It just does not seem to work in a subfolder with this docker image. if someone has a working config.php, please post it. 
otherwise i just assume it is not possible.
thanks

**Comment by GregorB54321** [comment]
Anybody got it to run with subdir? I've also spend hours with no luck so far...

**Comment by zavodnyuk** [comment]
I have the same issue, any luck with solving it?
Should be pretty common config, though not obvious how to configure it
