### ISSUE TITLE
Destktop client seems to be unable to sync big files

### ISSUE THREAD

**Issue by Julianoe** [nextcloud/docker#212]
Nextcloud client 2.3.3
(Client) Ubuntu 17.10
(server) Ubuntu 16.04
Nextcloud server 12

I'm using Nextcloud with a Docker image in a [docker-nginx-reverse-proxy-companion-letsencrypt](https://github.com/evertramos/docker-nextcloud-letsencrypt/) type of environment. 

My problem is 

```

03/01/2018 05:03:58,           Notes/evernotes/attachments/1888597437. 2014 11:43:46,                     Nextcloud,L'opération est annulée [ _operation cancelled_ ]
03/01/2018 05:03:58,                     Notes/evernotes/attachments/1620875799.docx,                     Nextcloud,L'opération est annulée  [ _operation cancelled_ ]
03/01/2018 05:03:58,                      Notes/evernotes/attachments/1674516874.pdf,                     Nextcloud,Connexion fermée  [ _connexion closed_ ]
03/01/2018 05:03:27,                             Notes/Archive/media/1897464188.jpeg,                     Nextcloud,Cet élément n'a pas été synchronisé en raison des erreurs précédentes : Error transferring https://mydomain/remote.php/dav/files/julien/Notes/Archive/media/1897464188.jpeg - server replied: Request Entity Too Large
03/01/2018 05:03:27,                                                .Contacts-Backup,                     Nextcloud,Le fichier ou dossier a été ignoré car il est masqué.


```

In my admin parameters the max file size is set to the default value though (511mb). How can i debug that? 
All the files that cause a problem in the syncing process seem to be heavier than 1mo. (my folder is made of .md files notes and a bunch of images. Small ones work. Big ones cause me problems. Same for pdf and other type of files biggest than ~1.2mo or something.) Is this a known issue?

**Comment by SnowMB** [comment]
Are you sure your proxy is configured to handle large files?

See our [examples](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache)

**Comment by Julianoe** [comment]
I've seen nothing related to this in @evertramos provided docker files https://github.com/evertramos/docker-nextcloud-letsencrypt/. Do you have any issue like this mate?

@SnowMB i'm looking into the link you provided and will update here soon

**Comment by evertramos** [comment]
Yes!

@SnowMB is right!

You must add the file [uploadsize.conf](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache/proxy/uploadsize.conf) to your `./data/conf.d` folder and you should be good to go.

**Comment by Julianoe** [comment]
Seems to be working like a charm! Thanks to both of you i'm rocking a cloud :+1: and will for a few friends.

**Comment by evertramos** [comment]
Just for reference... I have updated our webproxy so you could have your special conf files as optional. 

Just pull the latest version of our [webproxy](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion), set the option `USE_NGINX_CONF_FILES=true` at your .env file and run our start script.

Cheers!
