### ISSUE TITLE
errors in the logs since

### ISSUE THREAD

**Issue by snakwu** [nextcloud/docker#2131]
errors in the logs since
![Screenshot_20231227_194531](https://github.com/nextcloud/docker/assets/5343595/fc04e7c9-e108-42d5-9940-2fe33bd30cc5)

Could you tell me how to solve the problem?

**Comment by joshtrichards** [comment]
This repository is for bug reports specific to the Docker image and not general support or troubleshooting. Please post your query at the Nextcloud Help Forum - https://help.nextcloud.com.
