### ISSUE TITLE
Q: Which folders to keep in sync for failover? 

### ISSUE THREAD

**Issue by MarcS1975** [nextcloud/docker#2137]
I am looking to create a failover solution for my Docker Nextcloud server. NC1 is configured and live and NC2 should stay in sync, so in case NC1 goes down, I can easily switch over to NC2. Which folders on NC1 would I need to keep in sync with NC2 so all data is always up to date, including NC configuration (installed apps etc), user accounts, user passwords?

**Comment by joshtrichards** [comment]
Hi @MarcS1975 - As this seems to be a configuration question, please post your query to the Nextcloud Help Forum - https://help.nextcloud.com and/or review the Admin Manual - https://docs.nextcloud.com

The repository Issues are for bug reports in the image.
