### ISSUE TITLE
External storage not writable unless manual permission change

### ISSUE THREAD

**Issue by MarcS1975** [nextcloud/docker#2140]
When mounting data folders via External storage option 'local', there is always a permission problem that causes NC to block uploads/writing to those folders. Only when manually loging into the container and changing the permissions is it possible to use those External Storage options.

Process: 
1) new installation using docker compose, file extract below
```volumes:
      - /srv/2T_JBOD/DockerappsHot/NC/NC_app:/var/www/html
      - /srv/BTRFS27/dataX:/var/www/html/data/dataX```

2) Inside NC, add app "External Storage"
3) In External Storage, link the mounted folder as storage type 'local'

Expected bahaviour:
The folder dataX should show up in NC as folder and the user should have r/w permissions.

Actual behaviour:
The folder dataX does show up in NC but user has **NO write permissions**.

When checking inside the container the 2 folders are owned by root:root.
The NC user cannot write to that folder.

Only by manually doing
```sudo chown -R www-data:www-data dataX
$ sudo chmod -R 0750 dataX
```
can the folders be made usable.

**Comment by martadinata666** [comment]
Well, "local" mean it will use whatever the docker container user run for to read/write permission to folder `in this case "www-data" uid "33"` *cmiiw, other way is set 755 on folder. Samba it best bet on granuled permissions.

**Comment by joshtrichards** [comment]
You're using bind mounts. The permissions, when using bind mounts, aren't even under the Docker Engine's control let alone Nextcloud. That's one of the downside to using bind mounts - permissions are your problem. :-)

I'm not sure what you expect either Nextcloud Server or the Nextcloud Docker image to do about this. 

If you want to avoid this, use Docker named volumes, just as most of the examples in our README do. :)

Please follow-up at the Nextcloud Help Forum - https://help.nextcloud.com/ - or the Docker Community Forum - https://forums.docker.com/ since this is more a general configuration and/or Docker Engine matter.

**Comment by MarcS1975** [comment]
I am not using bind mounts.I believe my compose defines my exiting data
folders (LIVE180) as volumes.

volumes:
      - /srv/MyLocalPath/LIVE180:/var/www/html/data/nmax/live

I think the compose file needs some parameters to amend user permissions. I
am not an expert but there might be a solution via PUID and GUID that
should be in the compose file.

**Comment by MarcS1975** [comment]
> Samba it best bet on granuled permissions.

Unfortunately the smbclient in Nextcloud does not work. It has been buggy for years and although there are many [issue reports ](https://github.com/nextcloud/server/issues/41114#issuecomment-1738740358)by users about smbclient, its never been fixed (at least not in the NC community container). That's the whole reason I had to revert to the Nextcloud "local" solution.

**Comment by MarcS1975** [comment]
> this is more a general configuration and/or Docker Engine matter

I actually think its very specific to Nextcloud docker as NC is a file sharing system and currently mounting External data sources is inherently buggy, i.e. smbclient doesnt work and 'local' causes permission problems. It would be great if NC could be fixed to work for its main purpose (file sharing). :)

**Comment by MarcS1975** [comment]
just quickly closing tickets doesn't help improve the application for sure

**Comment by joshtrichards** [comment]
> volumes:
>     - /srv/MyLocalPath/LIVE180:/var/www/html/data/nmax/live

The left side has a slash in front - that means the source is an actual folder on your underlying host rather than a Docker Engine managed volume.

https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-3

**Comment by MarcS1975** [comment]
But how else should I integrate my existing data? I need to somehow bring in that path. That path holds 1TB of existing files which I want to utilise, share and manage in Nextcloud.

**Comment by joshtrichards** [comment]
> I actually think its very specific to Nextcloud docker as NC is a file sharing system and currently mounting External data sources is inherently buggy, i.e. smbclient doesnt work and 'local' causes permission problems. It would be great if NC inside Docker could be fixed to work for its main purpose (file sharing). :)

I'm not sure what smbclient has to do with this Issue you opened about mounting a local host folder and expecting the image to fix the permissions.

I'm merely suggesting maybe getting some feedback from the forums before you assume things are a bug. :)

**Comment by MarcS1975** [comment]
Well NC has several ways of integrating existing data via the External Storage app. One option in that app is SMB which requires smbclient to run inside the container. This is not working (as reported). An alternative to bring in data is via the type "local" which requires a path into the container as per my volume. That caused the permission errors so its also not working. Bug or not bug, both ways are not fully implemented.

**Comment by martadinata666** [comment]
Technically docker or not, the "local" will use the permission of the Apache user. What ever it is. 
Then there is docker image issue about SMB that is not working ootb, thus require user to rebuild the image themselves. https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles

**Comment by MarcS1975** [comment]
> Technically docker or not, the "local" will use the permission of the Apache user. What ever it is. Then there is docker image issue about SMB that is not working ootb, thus require user to rebuild the image themselves.

Yes, local will use the existing permissions but that does not work for a file sharing application. Thus, I think there should be a permanent fix, possible via PUID/PGID (see below). The fix is not smbclient because it does not work. Even the rebuild or manual installation of smbclient inside the container does not work and fiddling with packages inside the container is totally against the concept of a container. After installing smbclient , there a plenty of errors in the NC log files and this has been reported many times by many users. Smbclient is not a stable solution to share files in NC Docker with.

> * https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles
> * https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage/local.html

Yes, that is the fix that I described in my initial post. But again, its a manual workaround and should not be part of a docker container (IMHO). The real solution could maybe be implemented with PUID and PGID seetings in the compose file, but I am not a Docker expert to know exactly how that works. Apparently setting PUID/PGID to the values of the host user will ensure that files are accessible inside the container. Some Docker experts may be able to validate if this makes sense.

**Comment by martadinata666** [comment]
Yes, there are many of tedious talk of this smb thing or other thing that not supported ootb as expected to be, then there is also https://github.com/nextcloud/all-in-one, that call for "the complete" ultimate nextcloud docker image. Maybe you want to try that.

**Comment by MarcS1975** [comment]
I did try that. It's a very bloated distribution and very very slow.

**Comment by joshtrichards** [comment]
> The real solution could maybe be implemented with PUID and PGID settings as described here, but I am not a Docker expert to know exactly how that works. If this is really the solution to the permission problems, then should these settings not be part of every NC Docker container.

We already support this and we do it in the Docker way: using `--user` (run) / `user` (Compose): 

https://docs.docker.com/reference/compose-file/services/#user

Even LSIO has a note at the top of the page you linked to,  regarding their PUID/PGID mapping support, mentioning the same approach we already support as an alternative.

I'm closing this out at this point since what you're requesting is either already achievable or outside the capability of the image itself (e.g. a container platform matter).

**Comment by ewenjc** [comment]
@MarcS1975 did you ever resolve this issue?
I'm trying to setup External Storage; shared folder on NAS, Nextcloud in docker on NAS.  Only solution I've seen involves changing the ownership of the shared_folder to www-data but that break other struff.

**Comment by MarcS1975** [comment]
No solution. I do chmod 777 on the folder tree to make it work.
