### ISSUE TITLE
After updating to Nextcloud 28.0.2 Security message: 32bit in use

### ISSUE THREAD

**Issue by cablesky** [nextcloud/docker#2153]
After I updated my Nextcloud Docker container to 28.0.2, the following security warning appears in Nextcloud's administrator settings: "It appears you are using a 32-bit PHP version. Nextcloud requires 64-bit to run well."
I use Ubuntu 22.04 with Docker 24.0.2.
Can someone give me a hint?

**Comment by koelle25** [comment]
It seems the amd64 image variant is not available yet, see #2154 
Your Linux system automatically falls back to the i386 image if amd64 is not available (because 64-bit OS can run 32-bit programs without an issue).

**Comment by cablesky** [comment]
@koelle25: Thank you! Then i will wait.. :-)

**Comment by elhossary** [comment]
I have the same issue too

**Comment by elhossary** [comment]
I think it is solved a minute ago, just pull the latest image and run it

**Comment by henningsieh** [comment]
> It seems the amd64 image variant is not available yet, see #2154 Your Linux system automatically falls back to the i386 image if amd64 is not available (because 64-bit OS can run 32-bit programs without an issue).

Great, this did work!

The error which says "Apparently you are using a 32-bit PHP version..." has gone. ✅

**Comment by joshtrichards** [comment]
You all were just a bit *too* quick for the build process. :-)
