### ISSUE TITLE
28.0.2 is missing amd64 version

### ISSUE THREAD

**Issue by zephyros-dev** [nextcloud/docker#2154]
As the name suggest, all variants of the 28.0.2 version is missing amd64 architecture. https://hub.docker.com/layers/library/nextcloud/28.0.2/images/sha256-9e8d4ff261335f8022004a56619df71424e7bdec2eba73903b102fd5c21f9191

**Comment by calvinbui** [comment]
this is breaking my deployment as I have set `PHP_UPLOAD_LIMIT` and `PHP_MEMORY_LIMIT` > `1024M` which is the limit of 32-bit deployments.

**Comment by koelle25** [comment]
It seems the build job for the amd64 variant is hanging:
https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/nextcloud/

Can a maintainer please check and maybe restart the build job?

**Comment by elhossary** [comment]
I have the same issue

**Comment by elhossary** [comment]
I think it is solved a minute ago, just pull the latest image and run it
