### ISSUE TITLE
Nextcloud won't pick up changes on my external unionfs storage.

### ISSUE THREAD

**Issue by Nottt** [nextcloud/docker#216]
### Steps to reproduce

1. Add a external unionfs folder as external storage
2. Delete or add files, move stuff around
3. NextCloud won't reflect this even after a long time of waiting, and even restarting the docker container

### Expected behaviour
The web interface should reflect the changes made on the folder, in real time or in a reasonable time. 

### Actual behaviour
Web interface does not reflect changes in the folder. 

### Server configuration

**Operating system**: Ubuntu Server 16.04

**Web server:** Nginx 

**Database:** Mariadb latest docker

**PHP version:** PHP 7.1.9 

**Nextcloud version:** Nextcloud 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** No

**Where did you install Nextcloud from:** Docker*

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Could not retrieve on my docker
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
Could not find a way to retrieve it on my docker
or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** Yes, a unionfs folder joining a read-only folder with a read-write folder, path being /mnt/unionfs/

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** Not sure. 

### Client configuration
**Browser:** Version 63.0.3239.84 (Official Build) (64-bit)

**Operating system:** Windows 7

#### Web server error log
<details>
<summary>Web server error log</summary>

[error.log](https://github.com/nextcloud/server/files/1580307/error.log)

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

[nextcloud.log](https://github.com/nextcloud/server/files/1580302/nextcloud.log)
</details>

I have many other docker applications that uses the same /unionfs folder, and none has issues dealing with changes in real time so I'm not sure why this is happening only with nextcloud.

Any help is appreciated! Thanks,

**Comment by DenSA-Inc** [comment]
AFAIK nextcloud does not automatically reflect the changes in the file system, files have to be added to the database first (or something like that). Anyway, just as in this [nextcloud forum question](https://help.nextcloud.com/t/adding-files-to-nextcloud-without-uploading/2847/2) you have to use `occ files:scan` to update nextcloud's knowledge of the file system.

I don't know how fast you want the file-system-changes to appear in nextcloud, but running the discovery-command via crontab every 5 minutes should suffice.

**Comment by schliflo** [comment]
There is also a config option that tells nextcloud to automatically scan the filesystem for changes: ```'filesystem_check_changes' => 1,```

**Comment by Nottt** [comment]
Thanks dude! How can i change that configuration? Sorry I'm a noob. I just
use the docker and it just "works" ( well except the keep it updated part)

**Comment by schliflo** [comment]
If you have mounted your config (like [this](https://github.com/schliflo/nas-docker/blob/master/docker-compose.yml#L107)), just add this line in your config.php

**Comment by J0WI** [comment]
Assuming that the question has been answered.
