### ISSUE TITLE
Redirect stderr output to stdout (or disable access log) with nextcloud:fpm

### ISSUE THREAD

**Issue by witchent** [nextcloud/docker#2164]
I hope this is the right place (if it belongs to nextcloud/server let me know).
The nextcloud:fpm image apparently puts the access log to stderr. Therefore, podman writes a lot of lines like ``nextcloud[6638]: - - username 21/Feb/2024:09:21:45 +0000 "PROPFIND /remote.php" 207`` to the error level of journald.
This makes debugging real errors a lot harder.

The only thing I was able to find is https://github.com/nextcloud/docker/issues/1667, but it is using the apache image where apparently there are symlinks in ``/var/log/apache2/``, but that folder doesn't even exist in the fpm image. Is there anything else I can do to get rid of those logs?

**Comment by joshtrichards** [comment]
Likely comes from this in our upstream's image:

https://github.com/docker-library/php/blob/ba61c23b327ad937a335906439cc3b72e1eb9687/8.1/bookworm/fpm/Dockerfile#L247-L254

Further context:

https://github.com/docker-library/php/issues/358#issuecomment-271033464

**Comment by witchent** [comment]
Alright, awesome, thanks a lot for the input. I redirected it to a file for now because I couldn't get the trick from the last comment to work. Seems it's not a bug of the docker image though so sorry for asking here (at least the next person can find it hopefully)
