### ISSUE TITLE
 mariaDB errors: “Aborted connection 5 to db: ‘unconnected’ user: ‘unauthenticated’ host: ‘172.21.0.3’ (This connection closed normally without authentication)”

### ISSUE THREAD

**Issue by lhoupert** [nextcloud/docker#2165]
Since the recent update or MariaDb (11.3.2) the connectivity broke down between nextcloud and mariadb.

This can be fixed by adding addition flag to the mariadb command `--character-set-server=utf8`

A solution would be to update the example docker compose file with these arguments
```
    image: mariadb:11.3.2
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --character-set-server=utf8
```

_All credits for this solution go to [Gypertena's reply on the nextcloud discourse](https://help.nextcloud.com/t/nextcloud-broken-on-docker-zimaboard/182378/3?u=lhoupert)_ .

**Comment by lhoupert** [comment]
I just raised a PR to edit the docker-compose files given as example. Let me know if I missed something.

**Comment by zackmuc** [comment]
Thx helped me also is in another docker container with the same problem

**Comment by Kitt3120** [comment]
Thanks, helped me. Can confirm that it works with your changes.

**Comment by sloniupl** [comment]
Thanks a lo! Fixed also my issue with nextcloud that after update was just showing Internal Server Error in the browser.

**Comment by CooperBarrett** [comment]
Thank you so much, you've just saved me hours of headaches!
Well done

**Comment by lhoupert** [comment]
It took me a couple of hours to understand what was happening until I found a post on a discourse (unfortunately I don't have the link anymore). The author of the post is the one to thank :-)

**Comment by celevra** [comment]
thank you very much!

i add the nextcloud log error message so that more people can find this solution through google:

```
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers in /var/www/html/lib/private/DB/Connection.php:140
```

**Comment by joshtrichards** [comment]
Glad you all found a solution but:

- 11.3.x is a short-term release series
- good practice is to stick with LTS release trees of MariaDB unless you have a good reason not to
- Nextcloud Server has specific DB version requirements already, and 11.3 is definitely not on that list: https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#server

In other words, this shouldn't occur if you stick with supported DB versions. :-)

**Comment by joshtrichards** [comment]
FYI: MariaDB reverted the change in their image so new pulls already have it fixed there: https://github.com/MariaDB/mariadb-docker/pull/565

**Comment by logopk** [comment]
> Glad you all found a solution but:
> 
> * 11.3.x is a short-term release series
> * good practice is to stick with LTS release trees of MariaDB unless you have a good reason not to
> * Nextcloud Server has specific DB version requirements already, and 11.3 is definitely not on that list: https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html#server
> 
> In other words, this shouldn't occur if you stick with supported DB versions. :-)

unfortunately the default docker-compose solutions (that I use for more than 3 years) had mariadb:latest in them. So now I'm already on 11.3 and there is no easy way back to LTS...

:-(

**Comment by joshtrichards** [comment]
https://mariadb.org/post-mortem-php-and-mariadb-docker-issue/

**Comment by joshtrichards** [comment]
Closing since there's nothing to be done here in the Docker image. Also, all references to mariadb in our example Composer files are tagged with a specific version (10.6.) presently.
