### ISSUE TITLE
How do I remove a device stored in 'Sign in with Device,' for example, this 23ultra?

### ISSUE THREAD

**Issue by williamcanon1** [nextcloud/docker#2167]
![屏幕截图 2024-02-27 224711](https://github.com/nextcloud/docker/assets/95892193/250a8f65-0ba6-48e0-a49b-f5b153a0b188)

I have already replaced my phone. I didn't find any option to delete this device.

**Comment by joshtrichards** [comment]
This is not a Docker image matter. 

Post your query to the help forum - https://help.nextcloud.com - or review the documentation - https://docs.nextcloud.com.
