### ISSUE TITLE
setting up docker-compose example with nginx and lets encrypt in local network

### ISSUE THREAD

**Issue by divramod** [nextcloud/docker#217]
Hey, 

i am trying to setup the docker-compose example shown here:
https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/postgres/fpm/docker-compose.yml

I adapted everything (passwords) said in the example-section documentation (with-nginx-proxy) but i am stuck with what i should write as VIRTUAL_HOST and LETSENCRYPT_HOST. should i use the servers (my laptops) ip?

      - VIRTUAL_HOST=192.168.178.23
      - LETSENCRYPT_HOST=192.168.178.23

do i have to change something in the nginx.conf?
what will be the url i can reach the nextcloud server with?

thx in advance for helping me.

after pulling and starting i get the following messages

> $ docker-compose up                                                                                                                              
Starting fpm_db_1
Starting fpm_proxy_1
Starting fpm_letsencrypt-companion_1
Starting fpm_app_1
Starting fpm_web_1
Attaching to fpm_proxy_1, fpm_db_1, fpm_letsencrypt-companion_1, fpm_app_1, fpm_web_1
db_1                     | 2018-01-10 22:09:16.385 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1                     | 2018-01-10 22:09:16.385 UTC [1] LOG:  listening on IPv6 address "::", port 5432
proxy_1                  | Custom dhparam.pem file found, generation skipped
db_1                     | 2018-01-10 22:09:16.390 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
app_1                    | [10-Jan-2018 22:09:17] NOTICE: fpm is running, pid 1
db_1                     | 2018-01-10 22:09:16.404 UTC [24] LOG:  database system was shut down at 2018-01-10 22:08:47 UTC
proxy_1                  | forego     | starting dockergen.1 on port 5000
db_1                     | 2018-01-10 22:09:16.409 UTC [1] LOG:  database system is ready to accept connections
proxy_1                  | forego     | starting nginx.1 on port 5100
proxy_1                  | dockergen.1 | 2018/01/10 22:09:17 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
letsencrypt-companion_1  | Sleep for 3600s
proxy_1                  | dockergen.1 | 2018/01/10 22:09:17 Watching docker events
app_1                    | [10-Jan-2018 22:09:17] NOTICE: ready to handle connections
proxy_1                  | dockergen.1 | 2018/01/10 22:09:18 Generated '/etc/nginx/conf.d/default.conf' from 16 containers
proxy_1                  | dockergen.1 | 2018/01/10 22:09:18 Running 'nginx -s reload'
proxy_1                  | dockergen.1 | 2018/01/10 22:09:18 Received event start for container 9a57eab0403b
letsencrypt-companion_1  | 2018/01/10 22:09:18 Generated '/app/letsencrypt_service_data' from 16 containers
letsencrypt-companion_1  | 2018/01/10 22:09:18 Running '/app/update_certs'
letsencrypt-companion_1  | 2018/01/10 22:09:18 Watching docker events
letsencrypt-companion_1  | /etc/nginx/certs/192.168.178.23 /app
letsencrypt-companion_1  | Reloading nginx proxy (b05aadf8d5e21765273212924c2706621b7f3bd71f595277bec03bbd3c407c0c)...
proxy_1                  | dockergen.1 | 2018/01/10 22:09:18 Generated '/etc/nginx/conf.d/default.conf' from 16 containers
proxy_1                  | dockergen.1 | 2018/01/10 22:09:18 Running 'nginx -s reload'
letsencrypt-companion_1  | 2018/01/10 22:09:18 Contents of /app/letsencrypt_service_data did not change. Skipping notification '/app/update_certs'
letsencrypt-companion_1  | R2018/01/10 22:09:18 Generated '/etc/nginx/conf.d/default.conf' from 16 containers
letsencrypt-companion_1  | ;2018/01/10 22:09:18 [notice] 82#82: signal process started
letsencrypt-companion_1  | Creating/renewal 192.168.178.23 certificates... (192.168.178.23)
letsencrypt-companion_1  | 2018-01-10 22:09:18,611:INFO:simp_le:1538: Retrieving Let's Encrypt latest Terms of Service.
letsencrypt-companion_1  | 2018-01-10 22:09:20,413:INFO:simp_le:1356: Generating new account key
letsencrypt-companion_1  | ACME server returned an error: urn:acme:error:malformed :: The request message was malformed :: Error creating new authz :: Issuance for IP addresses not supported
letsencrypt-companion_1  |
letsencrypt-companion_1  |
letsencrypt-companion_1  | Debugging tips: -v improves output verbosity. Help is available under --help.
letsencrypt-companion_1  | /app
letsencrypt-companion_1  | Sleep for 3600s

**Comment by SnowMB** [comment]
Does not work this way. Let's encrypt requires you to have a valid domain name and a server that is publicly reachable under that name.

For local deployments you have to use self signed certificates or ditch https encryption completely.

**Comment by topas-rec** [comment]
As a workaround:
Is it possible to make a dynamic DNS URL (really publicly reachable through your router - that's how I setup my local docker based nextcloud), then generate the certificate and containers, then abandon or delete the dynamic DNS URL and set your server locally to the previously used URL? Some routers allow DNS in local networks. Maybe you can set your DNS to the global URL used to generate the certificate.

Otherwise, why not using dynamic DNS?

**Comment by romanar** [comment]
if you want to access nextcloud only from you local network than you can follow my `docker-compose` instruction [here](https://github.com/nextcloud/docker/issues/202).
