### ISSUE TITLE
Missing php-bz2 module

### ISSUE THREAD

**Issue by d3xt3r01** [nextcloud/docker#2172]
Default simple install yells this:

This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them: bz2. For more details see the [documentation ↗](https://docs.nextcloud.com/server/28/go.php?to=admin-php-modules).

Can we add this so we get rid of this warning?

**Comment by joshtrichards** [comment]
Duplicate of #2118
