### ISSUE TITLE
Server has no maintenance window start time configured

### ISSUE THREAD

**Issue by d3xt3r01** [nextcloud/docker#2173]
Default image install yells this:

Can we add it to the default config?

Server has no maintenance window start time configured. This means resource intensive daily background jobs will also be executed during your main usage time. We recommend to set it to a time of low usage, so users are less impacted by the load caused from these heavy tasks. For more details see the [documentation ↗](https://docs.nextcloud.com/server/28/go.php?to=admin-background-jobs).

**Comment by bonsje** [comment]
I had this issue also when setting up the nextcloud:latest (28.0.2), i hacked it away to give it the command in the docker directly. If read the documentation correctly yesterday you must give it a number for the starttime of the maintenance window to start. I can image that this could be a little difficult bc everybody is in different timezones and it was recommended to do this window in the night if i recall correctly (depends also on your size of the instance too). Maybe we could get an Environment Variable to get the maintenance window when we spin up the container? or maybe i read over it, but to my knowledge an maintenance window  Environment Variable does not exist atm.

**Comment by d3xt3r01** [comment]
So we have some `NEXTCLOUD_` variables, some `NC_` variables and some that don't have anything ( like `TRUSTED_PROXIES`) ?

**Comment by d3xt3r01** [comment]
Also, if there isn't a cron daemon running in the container, is there a reason for `maintenance_window_start` to exist?

**Comment by mattvisa** [comment]
Same. I get this error code on a default install of NextCloud in TrueNas Scale. If there is an update that can fix this by setting a default as described above for it to run at 3am based on local timezone, that would be great. I don't want to shell into the system and update if you will be pushing an update to fix.

**Comment by joshtrichards** [comment]
This is an upstream matter (`server`). It doesn't make sense for us to do anything fancy merely in the Docker container for this parameter.

**Comment by joshtrichards** [comment]
@d3xt3r01 

> Some can be seen in sudo -u www-data php occ config:list (mainly NEXTCLOUD_ and TRUSTED_PROXIES) because they end up in the config file... but not the NC_ ones.

FYI, the `NC_` handling has now been fixed upstream: nextcloud/server#46140
