### ISSUE TITLE
Cronjob do nothing

### ISSUE THREAD

**Issue by Saphyel** [nextcloud/docker#2181]
I tried the apache image and the fpm-alpine and after waiting more than 5 mins several times the admin page says cronjob hasn't run yet. Checking the logs seems like it did run in both cases

Also the permission system is a bit of a hell probably worth consider to make run with the option [USER](https://docs.docker.com/compose/compose-file/compose-file-v3/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir)?

**Comment by joshtrichards** [comment]
Please share your Compose file. There are multiple ways of running cron. It's not clear which approach you're using.

**Comment by isdnfan** [comment]
Cron usage is not self-explaining. both Apache and fpm image require additional *sidecar* container running cron by default (see [Dockerfiles](https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles/cron)). Look at [this support forum post](https://help.nextcloud.com/t/nextcloud-docker-compose-setup-with-notify-push-2024/186721) for advanced and polished example.

**Comment by joshtrichards** [comment]
Closing due to lack of follow-up info.
