### ISSUE TITLE
Error cd occUnable to write to the “config” directory!

### ISSUE THREAD

**Issue by josephfeussi** [nextcloud/docker#2183]
I deployed nextCloud on docker Desktop on my windows computer
After starting , everything worked fine. 
Opon trying to access the installation via another computer on the network, i got an error asking to add url of my host computer inside the var/www/html and config.php

as soon as i did that, now have a general error 

===============================================================

Error
Unable to write to the “config” directory!

This problem is usually resolved by giving the web server write access to the configuration directory. Or, if you prefer to keep the config.php file read-only, set the "config_is_read_only" option to true. See https://docs.nextcloud.com/server/28/go.php?to=admin-config

=====================================================================

Please community, need assistance

**Comment by joshtrichards** [comment]
Hi @josephfeussi - As this seems to be a configuration/troubleshooting matter (not a bug in the image), please post your query to the Nextcloud Help Forum - https://help.nextcloud.com. I also suggest you include your Compose file.
