### ISSUE TITLE
Missing python dependencies

### ISSUE THREAD

**Issue by pabloeisenhut** [nextcloud/docker#2186]
Some AI functions in Nextcloud require python3.11-venv.

`occ maintenance:repair` output
     
```
ERROR: Failed to install python dependencies: Failed to create python venv: python3 -m venv ./python returned The virtual environment was not created successfully because ensurepip is not available.  On Debian/Ubuntu systems, you need to install the python3-venv package using the following command.

    apt install python3.11-venv

You may need to use sudo with that command.  After installing the python3-venv package, recreate your virtual environment.

Failing command: /var/www/html/custom_apps/llm/python/bin/python3
```

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/docker#adding-features

**Comment by sbe-arg** [comment]
@joshtrichards https://github.com/nextcloud/docker#adding-features is okay but in truenas app you cannot do this customization.

it would be ideal to have python3.11-venv installed as it will allow LLM app to work in truenas as well.

**Comment by sbe-arg** [comment]
as workaround I'm manually installing on the running pods python3-env XD lol so sad

**Comment by sbe-arg** [comment]
In truenas scale UI cinsole i open the pods for ssh and run the apt install command... Nothing else

**Comment by joshtrichards** [comment]
You may want to try `llm2` which uses a different deployment architecture: https://docs.nextcloud.com/server/latest/admin_manual/ai/app_llm2.html
