### ISSUE TITLE
new env for auto configuration via environment variables for ldapUserCleanupInterval

### ISSUE THREAD

**Issue by ederator** [nextcloud/docker#2198]
Hi all,

there are some env variables for the configuration of config.php
https://hub.docker.com/_/nextcloud "Auto configuration via environment variables" . Would it be possible to use the
https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap_cleanup.html setting more precisely the option "ldapUserCleanupInterval" to be controllable via env in the docker env?

**Comment by joshtrichards** [comment]
You can use post-installation auto-config hooks to run `occ` commands. This allows you to set any Nextcloud parameter desired at installation time (and during some other events):

https://github.com/nextcloud/docker?tab=readme-ov-file#auto-configuration-via-hook-folders

**Comment by joshtrichards** [comment]
We'll expand the examples in the docs so it's more obvious. Tracking #2231
