### ISSUE TITLE
arm64/v8 non-existant?

### ISSUE THREAD

**Issue by Dracks** [nextcloud/docker#2208]
Hello, 

I'm not sure it's the correct place, but today I tried to update my nextcloud in my rpi4, and I've found that from the 28.0.4 to 28.0.5 the linux/arm64/v8 version is not there anymore. 

What's the problem? Is it definitive?

Thanks!
Dracks.

**Comment by davidzx** [comment]
the stable got an update but, but still has ENV NEXTCLOUD_VERSION=28.0.4

**Comment by Dracks** [comment]
> the stable got an update but, but still has ENV NEXTCLOUD_VERSION=28.0.4

yes, it get updated all images except the arm64/v8, when you look for the hash was still the same.

**Comment by JuniorJPDJ** [comment]
probably the reason for #2210

**Comment by JuniorJPDJ** [comment]
looks like it got fixed
