### ISSUE TITLE
Could not update user information!

### ISSUE THREAD

**Issue by baiwei0703** [nextcloud/docker#2240]
Recently, I found user managment could not update user information. Including email, password or group. Add user is ok, but add group does not working.  No error alert. Docker image version is 'lasest', pulled about 11 months before ago. docker-compose file and system information has added in attachment. Waitting for answer. Thank you.
[system_info.txt](https://github.com/user-attachments/files/15881345/system_info.txt)
[system_info.txt](https://github.com/user-attachments/files/15881352/system_info.txt)
[docker-compose.txt](https://github.com/user-attachments/files/15881353/docker-compose.txt)

**Comment by Strit** [comment]
Pulled 11 months ago.....?

Then please update your install. You are running an unsupported version.

**Comment by baiwei0703** [comment]
> Pulled 11 months ago.....?
> 
> Then please update your install. You are running an unsupported version.

Thank you for your answering.

**Comment by joshtrichards** [comment]
This channel is only for reporting bugs in the images. Since this seems to be a support request, please take it to the help forum: https://help.nextcloud.com

Thanks!
