### ISSUE TITLE
question: why server itself have to be installed after start container (aka. why server itself have to be persistenced)

### ISSUE THREAD

**Issue by bonjour-py** [nextcloud/docker#2241]
i have a s3fs mountpoint to persistence data for my server , it makes the nextcloud server runs pretty slowly because lots of  IO reads.

if i just mount /var/www/html/data , it can not be reused after rebuild container

so i have this question writen in title  

and is there any possible to just mount /var/www/html/data

**Comment by joshtrichards** [comment]
Duplicate of #2044
