### ISSUE TITLE
Where to find Docker 26 version

### ISSUE THREAD

**Issue by luckydogxf** [nextcloud/docker#2259]
I'm running nextcloud version 25.03, and I'm going to upgrade to 29. 
But I have to follow the upgrade path 25--->26--->27--->28---29. 
Turns out Dockerfile 26 is removed from github. Any way to find the old archive ?

Thanks.

**Comment by fuse314** [comment]
The Nextcloud docker images are still available on docker hub:
http://hub.docker.com/_/nextcloud/tags?page=&page_size=&ordering=&name=26

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/docker/tree/bc172f8dd22a648d5c166b854dceef958a2d4425/26
