### ISSUE TITLE
Cannot run container - no matching manifest for windows/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/docker#227]
When I try to run
```
docker run -d -p 8080:80 nextcloud
```
I get the following error
```
C:\Program Files\Docker\docker.exe: no matching manifest for windows/amd64 in the manifest list entries.
```
On Windows Server 2016 DataCenter Version 10.0.14393 Build 14393
Processor	AMD Phenom(tm) II X4 965 Processor, 3400 Mhz, 4 Core(s), 4 Logical Processor(s)

**Comment by marceljd** [comment]
Does `docker run hello-world` work?
Seems like a Docker installation problem and not a Nextcloud problem. Besides that: this is a bug reporting site, for general help issues you can visit other sites (or use google).

**Comment by BetaLeaf** [comment]
yea ```docker run hello-world``` worked just fine.

**Comment by marceljd** [comment]
https://github.com/docker/for-win/issues/1100

Seems that reinstalling Docker on Windows helps, this is not Nextcloud related. Please use Google and do not post questions here, this is for bug reporting.

**Comment by BetaLeaf** [comment]
I reinstalled Docker but I'm still having the same issue.

**Comment by tilosp** [comment]
@BetaLeaf Docker does not find the image for windows because there is no nextcloud image for windows.

If you take a look at the docker hub page you will see that windows-amd64 is not listed under supported architectures.

The nextcloud image is based on the php image and supports every architecture that the php image supports.

**Comment by BetaLeaf** [comment]
I expected docker to use linux php so nextcloud would work properly. 
https://help.nextcloud.com/t/windows-10-server/23052

also on the official website:
https://nextcloud.com/install/#instructions-server
"Nextcloud Server does not support Microsoft Windows. We recommend using a virtual machine or docker image on Windows Server."

**Comment by tilosp** [comment]
On docker for windows you can switch between running windows containers and Linux containers.
