### ISSUE TITLE
Nextcloud 30 image already considered production ready?

### ISSUE THREAD

**Issue by pbek** [nextcloud/docker#2296]
I wanted to ask if the Nextcloud 30 image already is considered production ready.
Because there is no image on Docker Hub, so I built my own from [30](https://github.com/nextcloud/docker/tree/master/30) on https://github.com/digital-blueprint/nextcloud-docker/pkgs/container/nextcloud-docker-pre-apache for testing our Nextcloud Apps.

I ran into an error 500 when using `Storage::getUidAndFilename($source)`:
https://help.nextcloud.com/t/storage-getuidandfilename-source-not-working-in-nextcloud-30-anymore/204168/2
🤔

**Comment by joshtrichards** [comment]
> I wanted to ask if the Nextcloud 30 image already is considered production ready.

There isn't anything specific about 30 and the Docker image. So any judgement about "production ready" is an upstream matter (`server` and associated apps) for the most part. We'll publish a 30 image momentarily. No v30 image, however, will be associated with the `stable` Docker tag until the Nextcloud update_server is pushing v30 to 100% of installations (as is our normal policy - i.e. see #2265).

> Because there is no image on Docker Hub, so I built my own from 30

Yeah we need to get on bumping up all the images. Unfortunately, release publishing has mostly been falling on one person. We need to work on spreading the load around a bit.

**Comment by pbek** [comment]
Thank you for your work, your answers and letting me know about the policy!
So the 30.0.0.14 version from https://github.com/nextcloud/docker/blob/0ffd24170f863f302dfb74fe3a63b6c41f82a4fa/30/apache/Dockerfile#L153 will go into the v30 image.

I really am puzzled why I'm having those issues with `Storage::getUidAndFilename($source)`...
