### ISSUE TITLE
Nextcloud fail to startup!

### ISSUE THREAD

**Issue by AbuShaihab** [nextcloud/docker#2306]
Hi everyone,

I'm using portainer to install nextcloud on my OMV7 server
I used the following composer code:

[
---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    depends_on:
      - nextcloud-mariadb
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Riyadh
    volumes:
      - /srv/dev-disk-by-uuid-91073136-5843-4551-9d1f-48c77b3c0377/D_Files/nextcloud/Config:/config
      - /srv/dev-disk-by-uuid-91073136-5843-4551-9d1f-48c77b3c0377/SC_Project/The Financial District:/data
    ports:
      - 4443:443
    restart: unless-stopped

  nextcloud-mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: nextcloud-mariadb
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Riyadh
      - MYSQL_ROOT_PASSWORD=#I entered a complicated password#
      - MYSQL_DATABASE=nextcloud_database
      - MYSQL_USER=nextclouddb-user
      - MYSQL_PASSWORD=#I entered same complicated password#
    volumes:
      - /srv/dev-disk-by-uuid-91073136-5843-4551-9d1f-48c77b3c0377/D_Files/nextcloud-mariadb/Config:/config
    ports:
      - 3306:3306
    restart: unless-stopped
]

and then I open my port (4443), so the nextcloud startup on GUI

![Image](https://github.com/user-attachments/assets/057ad67a-f200-4155-8c0c-d591e0813157)

But as appearing in the image, despite inputting all variables as in the compose code, nextcloud won't start!

Can any buddy help please?

**Comment by joshtrichards** [comment]
> `image: lscr.io/linuxserver/nextcloud:latest`

This is not our image. Try:

https://docs.linuxserver.io/images/docker-nextcloud/

https://github.com/linuxserver/docker-nextcloud

**Comment by AbuShaihab** [comment]
I used this code in portainer:

" ---
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Asia/Riyadh
    volumes:
      - /srv/dev-disk-by-uuid-91073136-5843-4551-9d1f-48c77b3c0377/D_Files/nextcloud/Config:/config
      - /srv/dev-disk-by-uuid-91073136-5843-4551-9d1f-48c77b3c0377/SC_Project:/data
    ports:
      - 558:443
    restart: unless-stopped "

At first it works good with no problem
But I had to remove the nextcloud container and again reinstalled it
But it didn't work again

Every time I try to open it throught the port 558 - or any other port i assign - I got this screen:

![Image](https://github.com/user-attachments/assets/034a0dc6-42ba-42ed-9df5-8b591b16b366)

Please help how I can restore nextcloud fully functional?

**Comment by joshtrichards** [comment]
Again. You are *not* using our Docker image. You're using the LinuxServer one. Use the links I provided in my prior response.

Also, this is not a help channel. Use the help forum for troubleshooting assistance (also linked in my last response).
