### ISSUE TITLE
renderD128 access not correct

### ISSUE THREAD

**Issue by wangruiqi-git** [nextcloud/docker#2326]
I deploy my nextcloud like this
`docker run -d --restart=always --device=/dev/dri:/dev/dri:rw --name nextcloud2  -p 7680:80 -p 7681:443 -v /app/nextcloud:/var/www/html  -v /media/app/nextcloud_data/data:/var/www/html/data m.daocloud.io/docker.io/nextcloud`
then， every time I restart my container，renderD128 is reseted like this：
`www-data@60323fcdb204:/dev/dri$ ls -al
crw-rw---- 1 root   103 226, 128 Oct 24 16:40 renderD128`
application “memories” have no access to renderD128.
so， I need to 
`docker exec -it -u 33 nextcloud30 /bin/bash`
and chmod 777
I wonder if I use in a wrong way，anyway to solve it simply
![Image](https://github.com/user-attachments/assets/4cd41beb-e3f6-46de-8254-99d6ab5d69fc)

**Comment by joshtrichards** [comment]
This channel is for reporting bugs in the image. This sounds like a general support matter so I'm going to close this. Please post your query on the [Nextcloud help forum](https://help.nextcloud.com) or the [Memories Discord community](https://memories.gallery/faq/#getting-help). Thank you!

P.S. Note there are *two* approaches to integrating hardware transcoding. The newer (external) one may be more to your liking, particularly if you prefer not to use a custom `Dockerfile`: https://memories.gallery/hw-transcoding/
