### ISSUE TITLE
docker-compose examples: Command "app:list" is not defined.

### ISSUE THREAD

**Issue by churib** [nextcloud/docker#233]
Hi folks,

I get the following error
```
app_1  |                                                                   
app_1  |   [Symfony\Component\Console\Exception\CommandNotFoundException]  
app_1  |   Command "app:list" is not defined.                              
app_1  |   Did you mean this?                                              
app_1  |       app:check-code                                              
app_1  |                                                                   
app_1  | 
apache_app_1 exited with code 1
```
when running `docker-compose up` with the customized examples in

- `.examples/docker-compose/insecure/mariadb/apache` or
- `.examples/docker-compose/with-nginx-proxy/mariadb/apache` .

Any idea?

**Comment by SnowMB** [comment]
Can't reproduce the error. Are you running a fresh install, or is there an old installation in place?

Could you try running `docker-compose down -v` before trying again? (WARNING: this removes the volume and all existing data!!!!)

**Comment by churib** [comment]
@SnowMB That helped, thank you, my fault.
