### ISSUE TITLE
The `Strict-Transport-Security` HTTP header is not set

### ISSUE THREAD

**Issue by tsjordan-eng** [nextcloud/docker#2348]
I get the following warning when running `nextcloud:30` under Administration->Overview->Security & setup warnings in the web GUI:
> Some headers are not set correctly on your instance - The `Strict-Transport-Security` HTTP header is not set (should be at least `15552000` seconds). For enhanced security, it is recommended to enable HSTS. For more details see the [documentation ↗](https://docs.nextcloud.com/server/30/go.php?to=admin-security).
[Documentation is here](https://docs.nextcloud.com/server/30/admin_manual/installation/harden_server.html#enable-http-strict-transport-security)
 
It seems that this is part of the nextcloud apache image and not due to any of my volume mounts or configuration, however, my container is set up through [ansible-nas](https://github.com/davestephens/ansible-nas/blob/main/roles/nextcloud/tasks/main.yml). `nextcloud_image_name=nextcloud`, `nextcloud_image_version=30`.

**Comment by joshtrichards** [comment]
Hi @tsjordan-eng!

Did you follow the documentation link mentioned in the warning message?

That is a setting/header you add on your HTTPS server/service (i.e reverse proxy or HTTPS terminator):

https://docs.nextcloud.com/server/30/admin_manual/installation/harden_server.html#use-https

Also see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

If still stuck, please use the help forum: https://help.nextcloud.com

Hope that helps.
