### ISSUE TITLE
nextcloud:30.0.3-apache - change required to make element/riotchat  work

### ISSUE THREAD

**Issue by nowatbuer** [nextcloud/docker#2349]
I upgraded my nextcloud docker installation from nextcloud:29.0.10-apache to nextcloud:30.0.3-apache. 
Everything worked after that upgrade, except element/riotchat:

**Dein Element ist falsch konfiguriert
Failed to construct 'Worker': Access to the script at 'https://cloud.xx.de/apps/riotchat/riot/bundles/1c4a7dc1375053e9cf63/playback.worker.js' is denied by the document's Content Security Policy.**

It turned out, that I had to change one line in /etc/apache2/conf-enabled/security.conf to make it work again:
change 
#Header set Content-Security-Policy "frame-ancestors 'self';"
to
Header set Content-Security-Policy "frame-ancestors 'self';"

After that change, also element/riotchat started working again.
Maybe this change can make it into future version of nextcloud:xxxxx-apache

**Comment by joshtrichards** [comment]
CSP is managed by Nextcloud Server itself + individual apps modifying the CSP policy.

The default policy in Nextcloud already includes `self` for `frame-ancestors`. I see `self` as well as my own URL in the test instances I checked.

You may want to do some debugging by seeing what you're actually getting in your CSP header(s). You can use your browser inspector or `curl -I` to do so. Something like:

```
curl -I https://domain.tld/apps/riochat/ -u USERNAME:PASSWORD
```

Or check it for another app like the `settings` app:

```
curl -I https://domain.tld/apps/settings/ -u USERNAME:PASSWORD
```

I don't know why you encountered this with v30, but if there is a bug the fix needs to happen in the app itself (or maybe in Server):

https://github.com/gary-kim/riotchat/blob/b42534282c9b59730edbc3b102b6afefa5a1fd4b/lib/Controller/AppController.php#L66
https://github.com/gary-kim/riotchat/blob/b42534282c9b59730edbc3b102b6afefa5a1fd4b/lib/Controller/StaticController.php#L171

Or it's possible it's a config matter (in the app or server or reverse proxy config). 

It looks like riotchat sets the policy here:

https://github.com/gary-kim/riotchat/blob/b42534282c9b59730edbc3b102b6afefa5a1fd4b/lib/Controller/StaticController.php#L183

Yes, you can always add headers via the web server/reverse proxy config, but it's unsupported and will create conflicting policies (which will break numerous other things in Nextcloud).

**Comment by joshtrichards** [comment]
Closing since whatever this is, it will ultimately end up being one of:

- an app matter
- a `server` matter
- a config matter

We don't do anything in the image (nor should we) related to CSP.
