### ISSUE TITLE
Update .htaccess and .user.ini during start of a Container

### ISSUE THREAD

**Issue by RGregat** [nextcloud/docker#237]
Hey me again. 
I'm trying now for a couple of days to increase the upload limit through my start.sh which executes during the starting process of my nextcloud container. 
My Problem is, that it is not working and I also get a integrity failure from nextcloud because of the modified files (.htaccess and .user.ini). I found a way which should fix this issue `php /var/www/html/occ maintenance:update:htaccess`, but even this has no effect for the integrity message. 
I also read that a php.ini should fix the problem, but for that I have to comment out all entries regards the upload limits in the .htaccess and .user.ini files which again leeds to the integrity issue. So I'm sorry guys, but I don't get my head around it. In theory it should be so easy, but in practice I could rage like hell

Oh an another thing, I have to explicity log in as the www-data user to my nextcloud container, because this `su - www-data php /var/www/html/occ maintenance:update:htaccess` is not working. If I execute this command `su` tells me, that the user account does not exist.

**Comment by usharf** [comment]
Same here. Very frustrating.

**Comment by pierreozoux** [comment]
Looks like there is an example on how to proceed here:
https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/proxy/uploadsize.conf

**Comment by pierreozoux** [comment]
I'll then close, thanks :)
