### ISSUE TITLE
Add a License (AGPLv3)

### ISSUE THREAD

**Issue by tilosp** [nextcloud/docker#238]
We should add a license to this repo.

I would either use MIT because the docker library uses it for the [docs](https://github.com/docker-library/docs) repo (Which contains the readme of this repo).
Or use AGPL3 because the nextcloud server uses it.

@pierreozoux and @SnowMB what do you think?

**Comment by SnowMB** [comment]
Personally I've got no preference on this one. But I think sticking to nextcloud would make more sense.

**Comment by pierreozoux** [comment]
AGPLv3 like Nextcloud I'd say.
@jancborchardt or somebody from Nextcloud can you help us on that?

**Comment by tilosp** [comment]
ping @jancborchardt

**Comment by pierreozoux** [comment]
@tilosp I don't think we need to wait them on that, just go ahead with AGPLv3

**Comment by tilosp** [comment]
@pierreozoux but i am not sure how to do it right. 
Isn't adding a License is like re-licensing, which means that everyone how has contributed has to agree?
And i think we should enforce [signing](https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md#sign-your-work) for new commits.

**Comment by pierreozoux** [comment]
It is already AGPLv3 https://github.com/nextcloud/docker/blob/master/license.md/

About signing, I didn

**Comment by pierreozoux** [comment]
Mobile.. sorry.. about signing, maybe let's point a Contribute.md to the official one then we are.always up to date?

**Comment by jancborchardt** [comment]
Just for the record: AGPLv3+ sounds good, yes. :)

**Comment by SnowMB** [comment]
Ok then, can we just do it? Or do we have to consider what @tilsop mentioned?
