### ISSUE TITLE
Update process fails (12.0.4 to latest)

### ISSUE THREAD

**Issue by D3luxee** [nextcloud/docker#239]
Hello everyone,

The upgrade "docker-compose pull && docker-compose up -d" fails, im using the official image together with the official postgres image.

[Compose File](https://pastebin.com/GyYA0Hyy)
[Pull Output](https://pastebin.com/nXr3hKxw)
[Full Upgrade Output](https://pastebin.com/ADBCtTHc)
[Active Apps](https://pastebin.com/9tBFcSWc)

Let me know if you need any further information.

> db_1   | 2018-02-01 18:07:29.988 UTC [1] LOG:  database system is ready to accept connections
app_1  | Nextcloud or one of the apps require upgrade - only a limited number of commands are available
app_1  | You may use your browser or the occ upgrade command to do the upgrade
app_1  | Set log level to debug
app_1  | Turned on maintenance mode
db_1   | 2018-02-01 18:09:58.909 UTC [31] ERROR:  column "min_value" does not exist at character 8
db_1   | 2018-02-01 18:09:58.909 UTC [31] STATEMENT:  SELECT min_value, increment_by FROM "storages_numeric_id_seq"
app_1  | Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "storages_numeric_id_seq"':
app_1  | 
app_1  | SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
app_1  | LINE 1: SELECT min_value, increment_by FROM "storages_numeric_id_seq...
app_1  |                ^
app_1  | Update failed
app_1  | Maintenance mode is kept active
app_1  | Reset log level

**Comment by tilosp** [comment]
Nextcloud 12 is incompatible with PostgreSQL 10.
Nextcloud 13 will be compatible with PostgreSQL 10.

See: https://github.com/nextcloud/server/issues/5930

**Comment by D3luxee** [comment]
The new nextcloud/docker image (Nextcloud 13) solved this issue

**Comment by juniorz** [comment]
I had the same error while upgrading the Notes app to the latest version on a Nextcloud 12 running on PostgreSQL 10:

```
Preparing update
Set log level to debug
Turned on maintenance mode
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "storages_numeric_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "storages_numeric_id_seq... ^
```

I never had any problem before. So, as recommended, I updated docker-nextcloud to version 13. But the error persists, and I am stuck in an upgrade loop:  Also, there is no way to disable the Notes app via `occ apps:disable`.
