### ISSUE TITLE
Update Failed

### ISSUE THREAD

**Issue by elmero1** [nextcloud/docker#24]
Hi i use the snowmb docker-compose file and updated nextcloud with the WebUpdater (maybe the problem). After the update and a restart i have the following message:
Downgrading is not supported and is likely to cause unpredictable issues (from 9.1.2.2 to 9.1.1.5)

When i change the version in the config file to 10.0.2 the i have the following message:
Downgrading is not supported and is likely to cause unpredictable issues (from 10.0.2 to 9.1.1.5)

Thanks for your support.

**Comment by elmero1** [comment]
The problem is the that config and database are on 10.0.2 and the container is on 10.0.1. Can you update the conatiner to 10.0.2 or give me the possibility to manual set the version with a environment variable?
Thanks a lot.

**Comment by pierreozoux** [comment]
Hello!

Just change this line: https://github.com/nextcloud/docker/blob/master/Dockerfile#L40

And then, run `docker build mytag .` :)

Cheers!

**Comment by pierreozoux** [comment]
It looks like it has been solved, please reopen if you still  have an issue.
