### ISSUE TITLE
No tag for Nextcloud version 13.0.0

### ISSUE THREAD

**Issue by SireneKatze5872** [nextcloud/docker#246]
The new Nextcloud version 13.0 got added manually to the repository but there is no tag on the docker hub page.

**Comment by tilosp** [comment]
This is normal. The docker library team has to review and build test the changes (See https://github.com/docker-library/official-images/pull/3982). And after that is done the images get build which can take a bit depending on the cpu architecture and how busy the build sever is (See https://doi-janky.infosiftr.net).
