### ISSUE TITLE
13.0 Missing FreeType Support - nextcloud:latest

### ISSUE THREAD

**Issue by ShoGinn** [nextcloud/docker#248]
Your PHP does not have freetype support. This will result in broken profile pictures and settings interface.

Not much more to say. Using the vanilla all inclusive docker.

**Comment by k1ngf15h3r** [comment]
Can confirm this. Updated docker container to 13.0 and get this message in the backend

**Comment by ShoGinn** [comment]
fixed the docker file in #249 
I tested it on my local machine and no problems.
