### ISSUE TITLE
NC13, PHP freetype not enabled

### ISSUE THREAD

**Issue by abmurksi** [nextcloud/docker#252]
Just upgraded to NC13 apache with supervisord & redis.
Get this error in the Admin-Panel:
Your PHP does not have freetype support. This will result in broken profile pictures and settings interface.

It appears that PHP Freetype GD is not enabled in this release yet, although I see it being installed (Line 20 in Dockerfile) and configured (Line 32).

https://github.com/nextcloud/docker/blob/master/13.0/apache/Dockerfile

**Comment by tilosp** [comment]
Duplicate of #248

**Comment by abmurksi** [comment]
Right, sorry for that
