### ISSUE TITLE
Cannot start service web: invalid header field value "oci runtime error: container_linux.go:247

### ISSUE THREAD

**Issue by abradshaw** [nextcloud/docker#256]
Cant get the docker-compose to work, I get the following error

```
ERROR: for web  Cannot start service web: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:364: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/home/adrian/nextcloud/nginx.conf\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/devicemapper/mnt/9b0b2e0786f7bb39ace13c4cba75ee9fe39ff879f3808d87d195f713da19947b/rootfs\\\\\\\" at \\\\\\\"/var/lib/docker/devicemapper/mnt/9b0b2e0786f7bb39ace13c4cba75ee9fe39ff879f3808d87d195f713da19947b/rootfs/etc/nginx/nginx.conf\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\"\n"
ERROR: Encountered errors while bringing up the project.
```

**Comment by SnowMB** [comment]
In your compose file you use './nginx.conf' as volume. This file doesn't exist.

**Comment by Greek64** [comment]
Why is nginx.conf listed as a directory? 
It should be a file.

**Comment by abradshaw** [comment]
@Greek64 well it didnt exist before, so docker.compose must have created it. Anyway, I removed the dir and touched a file of the same name, now I get 

`web_1  | container_linux.go:247: starting container process caused "process_linux.go:364: container init caused \"rootfs_linux.go:54: mounting \\\"/root/docker/nginx.conf\\\" to rootfs \\\"/var/lib/docker/devicemapper/mnt/ceaa1017170e3bc6cfdcafca27728599f741cf3bf92d7a7210bb1842b900fae5/rootfs\\\" at \\\"/var/lib/docker/devicemapper/mnt/ceaa1017170e3bc6cfdcafca27728599f741cf3bf92d7a7210bb1842b900fae5/rootfs/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\""
`

**Comment by SnowMB** [comment]
Of course you need a valid nginx configuration. An empty file will not work. Have a look at 

https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb/fpm/web/nginx.conf

**Comment by J0WI** [comment]
Assuming that the question has been answered.
