### ISSUE TITLE
For big installations, chown of data folder is taking a looong time

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/docker#26]
This line has to be optimised:
https://github.com/nextcloud/docker/blob/master/docker-entrypoint.sh#L6

**Comment by arnaudmm** [comment]
Hello, same probleme here, why the entrypoint.sh does a "tar -C |tar xf" by the way ?

As used here, we don't mount entire /var/www/html, but apps/ config/ and data/ separatly, so this system is not useful I think, and source could be moved to the right place at build time (in Dockerfile)

correct me if i'm wrong

**Comment by SnowMB** [comment]
Yeah we have been discussing this matter a little bit. See here https://github.com/nextcloud/docker/pull/23

**Comment by tilosp** [comment]
Fixed in #65
