### ISSUE TITLE
RESTAPI support with docker-compose(kubernetes) of nextcloud

### ISSUE THREAD

**Issue by jmjoo** [nextcloud/docker#260]
I want to use my object storage for storage of nextcloud in kubernetes env.
Is there the way to implement nextcloud using yaml file for connecting object storage(interface=RESTAPI)

**Comment by cuppett** [comment]
For existing object storage drivers (Swift/S3), you can configure those with environment variables via upcoming and merged PRs: #1243 #1227. In the nextcloud docs, you can find information on the configuration of [object storage].

For a unique type of object storage, it is likely you will need to create either an official or private extension to nextcloud. You may find the [developer guide] helpful in getting started extending nextcloud and then this repository as a basis for creating a custom container image with that work.

This kind of enhancement above/beyond the included nextcloud functionality is likely beyond the scope of this project.

[object storage]: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/primary_storage.html
[developer guide]: https://docs.nextcloud.com/server/19/developer_manual/
