### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by dennybrandes** [nextcloud/docker#261]
I tried to upload a file with ~3Mb, but as response i get 413 Request Entity Too Large.
I updated already to last version. I'm using nextcloud 13.0.

**Comment by schliflo** [comment]
make sure your maximum allowed upload size is set correctly. see this: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/web/nginx.conf#L76 for example

**Comment by etibamecus** [comment]
Hello, 

First thanks a lot for all this, this is so nice and easy to use.

I must alter my congratulations by saying that I have the same problem, i checked everything, 

nginx.conf is set as the example (i copy/pasted it)

i went inside the nextcloud interface, in settings / additional settings and changed the "file handling" to 10 GB

I changed the write permissions for the data folder with chmod command to 777

but still i get the same 413 error on every devices.

I'm running the latest nextcloud using docker-compose of this link https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm

Thanks for helping, and for everything (again)

Have a nice day!

**Comment by kevenwyld** [comment]
Maybe this is related to the recent virtualbox issue (change) when vagrant creates vms?  Are you on mac? I think docker for mac uses vagrant to create vms. https://github.com/hashicorp/vagrant/issues/9524

**Comment by bhansley** [comment]
For anyone else who run across this issue, in addition to setting upload size in the Nextcloud UI, I had to tweak my upstream Nginx proxy to allow bigger uploads.

```
client_max_body_size        10G;
client_body_buffer_size     400M;
```

**Comment by bilyboy785** [comment]
@bhansley thank's for the tips ! Solved my issue with Jwilder Nginx Proxy in vhost.d/domain.tld

**Comment by samoylenkodmitry** [comment]
> For anyone else who run across this issue, in addition to setting upload size in the Nextcloud UI, I had to tweak my upstream Nginx proxy to allow bigger uploads.
> 
> ```
> client_max_body_size        10G;
> client_body_buffer_size     400M;
> ```

Please tell where is to place this if I run nextcloud with docker compose?

**Comment by AkioSarkiz** [comment]
@samoylenkodmitry it's for proxy, your docker-compose already setup
