### ISSUE TITLE
Add ImageMagick PHP extension to support "Theming of icons"

### ISSUE THREAD

**Issue by suntorytimed** [nextcloud/docker#263]
The current docker image doesn't provide the dependencies for "Theming of icons":

https://docs.nextcloud.com/server/13/admin_manual/configuration_server/theming.html#theming-of-icons

Please add the ImageMagick PHP extension and ImageMagick SVG support to the container to support custom favicons in settings/admin/theming of Nextcloud.

**Comment by phlegx** [comment]
Here our Dockerfile code to add Imagemagick.

```
RUN set -ex; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libmagickwand-dev \
        libmagickcore-extra \
    ; \
    pecl install imagick; \
    docker-php-ext-enable imagick
```

**Comment by suntorytimed** [comment]
Don't forget to cleanup the dpkg cache after the installation of the packages.

**Comment by phlegx** [comment]
@suntorytimed please add the cleanup Dockerfile code.

**Comment by seblu** [comment]
What could make this be added to official images? Do you expect a merge request?

**Comment by lupa18** [comment]
Hello, I'm getting this error: 

`E: Package 'libmagickcore-extra' has no installation candidate`

**Comment by rubo77** [comment]
maybe try `libmagickcore-6.q16-3-extra` instead?

**Comment by lupa18** [comment]
@rubo77 work with libmagickcore-6.q16-3-extra

thanks!

**Comment by rubo77** [comment]
What is the extra package for?

Should we add it to the "full" docker file?

**Comment by lupa18** [comment]
As I can understand, this package is a dependence for compiling imagick's php extension: docker-php-ext-enable imagick

**Comment by seblu** [comment]
It seems that it does not work. Tested with nextcloud 15.0.2.

**Comment by fuse314** [comment]
The "extra" package (for svg support) is still missing in the official images.
#575 only added imagick (supports "most used" image file types like png,jpg,bmp for previews).
See #594 .

**Comment by seblu** [comment]
Thanks! I didn't notice the second MR.

I think this should not be closed until theming of icons is complete.

**Comment by abdulocracy** [comment]
This issue still isn't resolved (16.0.4) so shouldn't be closed. The SVG support is missing, as @fuse314 mentioned.

**Comment by J0WI** [comment]
Please see #759 and https://github.com/nextcloud/docker/issues/594#issuecomment-459859737.

**Comment by pgassmann** [comment]
In nextcloud 17, imagemagick svg support is used to convert various elements like folder icons. the package is missing in the official nextcloud:17-fpm image. The folders and my logo were black after the upgrade to 17.

my workaround:

```
docker-compose exec nextcloud bash
apt install libmagickcore-6.q16-6-extra
./occ repair # clean frontend caches
docker-compose restart
```
