### ISSUE TITLE
Connecting to SQL on host?

### ISSUE THREAD

**Issue by mforcer** [nextcloud/docker#266]
Is it possible to connect to a host's SQL server?

I'm running this Docker image in Container Station on my QNAP NAS which has an SQL server on the host. I've entered the host's database user, password, and database name. I have confirmed that remote connections are granted and can connect through the command line.

`mysql -u dbuser -h <QNAP Public IP> -p`

It works fine I am able to connect and use the database.

When I try with same credentials through NextCloud setup screen, I get an error:

`Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] Connection refused`

I've tried lots of different hostnames: localhost, 127.0.0.1, public IP, 192.168.0.20 (NAS internal IP), nothing works. I have also tried appending port :3306.

Any ideas?

**Comment by marceljd** [comment]
SQL standard port is 3306, typo or could that be the problem?

**Comment by gdbytes** [comment]
@marceljd Unfortunately not it was just a typo.

I've fixed my main post, thanks for pointing that out.

**Comment by poVoq** [comment]
Probably doesn't make a difference but did you try adding the container to the "host" network?
https://docs.docker.com/network/host/

**Comment by qdii** [comment]
I have the same issue

marceljd: In my case, I can establish a connection using the CLI from within the nextcloud container, but nextcloud itself cannot. So it's not a networking or a firewall problem. I suppose gdbytes has the same problem.

poVoq: I would rather not, that would lower isolation and not root-cause the problem.
