### ISSUE TITLE
freetype issue

### ISSUE THREAD

**Issue by loderunner84** [nextcloud/docker#268]
please replace docker-php-ext-configure gd --with-freetype-dir=/usr --with-png-dir=/usr --with-jpeg-dir=/usr;
with docker-php-ext-configure gd --enable-gd-native-ttf --with-freetype-dir=/usr --with-png-dir=/usr --with-jpeg-dir=/usr;

**Comment by tilosp** [comment]
According to http://php.net/manual/en/image.installation.php is `--enable-gd-native-ttf` effectless.
