### ISSUE TITLE
Update to 11

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/docker#27]
Hello,

I would to ask when the image will be update to 11? Now version 11.0.1 of Nextcloud is available but docker version stay an 10. If it will take some days I will think about clone it and try to update it by my own or are there problems to do this?

Thank you and best regards
Wolfgang

**Comment by SnowMB** [comment]
It's easy to do on your own. Just fork the repo and change this line: 
https://github.com/nextcloud/docker/blob/master/Dockerfile#L40

Then you can build the container on your own: 

```
docker build .
```

**Comment by CordlessWool** [comment]
Ok, but is there a reason why it is not done by the nextcloud team if it is so easy?

Thank you

**Comment by SnowMB** [comment]
Actually this docker container is not contained by the team. It's maintained by the community, mainly by @pierreozoux. He's done quite some work to get this container into the official docker repository. And there are some great pull requests open from other contributors. But to get things rolling we would need at least another person to stand up and take care of the repository. Pierre can't do anything on his own. 

The nextcloud team is very open and will be grateful for anybody wanting to participate in the development and maintaining of the docker image. If someone is interested he could just leave them a message and ask for access to the repository.

**Comment by pierreozoux** [comment]
Yes, sorry, I was a bit under water lately, but well, yes, it is a "community" contribution, and would be glad if somebody could step in to help :)

Anyway, I accepted a contribution that set the route to 11, it will come soon.

**Comment by pierreozoux** [comment]
just waiting this PR: https://github.com/docker-library/official-images/pull/2560

**Comment by pierreozoux** [comment]
The PR landed, so I close here (meaning, you have access to version 11)
