### ISSUE TITLE
Can't upgrade from version 11.x

### ISSUE THREAD

**Issue by dehuszar** [nextcloud/docker#271]
I am trying to migrate from a non-official docker image.  I have gotten almost everything in place, and am getting prompted to update to version 13.  I am currently on version 11.0.2.7.  I have attempted to set the app build to the 12.0/apache path made available by the repo, but am still prompted to update to version 13 even after deleting the nextcloud_app_1 container.

Is there anything else I have to do in order to upgrade from 11 to 12, short of manually hacking and slashing the app container contents?

**Comment by pierreozoux** [comment]
You still have the old versions here:
https://hub.docker.com/r/library/nextcloud/

If you use dokcer-compose, be sure to `docker-compose rm` in between.
And how do you separate the data from the app?
(maybe you have app code persisted?)

**Comment by dehuszar** [comment]
Thanks for responding, I have been deleting all containers except for the db container where I've bootstrapped the previous db dump.

I am persisting a few volumes, but none that should contain the app/ folder.  The volumes I _am_ persisting are the same from the examples:
db:
```
- db: /var/lib/mysql
```
app:
```
- ./data/apps:/var/www/html/apps
- ./data/config:/var/www/html/config
- ./data/data:/var/www/html/data
```
cron:
```
- nextcloud:/var/www/html
```
I _presume_ apps is for the installed sub-apps, not the main app code, but maybe I'm mistaken.  I would figure that apps would get upgraded along with the primary app code.

Pointing the app container build to (no image is defined) to the repo's 12.0/apache/docker file should load v12 code, no?

**Comment by dehuszar** [comment]
Looks like using the `build` method wasn't working.  Pointing to `image: nextcloud:12.0.5-apache` got me to the next step

**Comment by pierreozoux** [comment]
Yes, it should:
https://github.com/nextcloud/docker/blob/master/12.0/apache/Dockerfile#L73

There is something strange, but I can't see it.
