### ISSUE TITLE
Not upgrading to NC 13

### ISSUE THREAD

**Issue by jkalousek** [nextcloud/docker#272]
Yesterday I updated/pulled last version and to my surprise it didn't upgrade NC to 13. I'm still on 12.0.5.
Is there any reason for that? Everywhere I look (dockerhub...) latest version of docker container should contain NC 13.

```
docker-compose pull nextcloud
...
Pulling nextcloud (nextcloud:latest)...
latest: Pulling from library/nextcloud
Digest: sha256:06af39ea8ed1f5b285e5bcf7f0ab9048c3a086a2793b3cf04ea9cde566db1aac
Status: Image is up to date for nextcloud:latest
```

```
docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:53 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by mr-bolle** [comment]
You run the current container with the old version.

If your data storage, and database are mounted to the host, you can remove this old container, with follow command. 

$ docker pull nextcloud $ docker stop <your_nextcloud_container> $ docker rm <your_nextcloud_container> $ docker run <OPTIONS> -d nextcloud

**Comment by jkalousek** [comment]
@mr-bolle I use docker compose... It should do all these steps automatically (or not?)... 
Anyway... I solved the problem by doing weir magic...
I changed image from nextcloud to nextcloud:fpm
Which did update to NC 13 but gave me Bad Gateway which I fixed by repeating steps from #195 and finally a changed image back to just nexcoud and everything is working again with NC13...

**Comment by jkalousek** [comment]
Now I'm not sure if it worked because if I hit Allow on NC Talk App it gives me `App "Video calls" cannot be installed because it is not compatible with this version of the server.`

**Comment by jkalousek** [comment]
Ok scratch that, NC just didn't update Video calls app and also didn't notify me that it need to be updated so I did it manually and now it's working...

**Comment by mr-bolle** [comment]
Sorry, that you use docker-compose i dont read.
With docker-compose down && docker-compose pull && docker-compose -up -d you should get the current verstion.
