### ISSUE TITLE
Run Apache as a different user/group

### ISSUE THREAD

**Issue by mzamot** [nextcloud/docker#274]
Apache and/or PHP_FPM can't be run as a different user than www-data, because the user and group is hardcoded into the Dockerfile.
Base image already has a mechanism to do so, using variable APACHE_RUN_USER and APACHE_RUN_GROUP. 
An option could be to use "${APACHE_RUN_USER:-www-data}" and "${APACHE_RUN_GROUP:-www-data}" instead of www-data.

**Comment by tilosp** [comment]
Closing this in favour of #359
