### ISSUE TITLE
using other port than 80 in combination with reverser proxy for ssl

### ISSUE THREAD

**Issue by worksasintended** [nextcloud/docker#275]
Hi there, 
thank you first for the nice container. Sadly I have problems getting it working on my system. 
I try to get it tunneld through a reverse proxy using port 18080 (port 80 and 443 already taken on that server). Every time I go to myurl:18080 I get redirected to myurl/apps/files instead of myurl:18080/apps/files. Any idea where to fix that?
My docker compose: 

`version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - /home/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nottherealpass
      - MYSQL_PASSWORD=nottherealpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    links:
      - db
    environment:
      - ServerName=https://myurl.com:18080
    volumes:
      - /home/nextcloud/app:/var/www/html
    restart: always

  ssl-proxy:
    image: justsml/ssl-proxy:latest
    environment:
    - HTTPS_PORT=18080
    - SERVER_NAME=myurl.com18080
    - UPSTREAM_TARGET=app:80
    - CERT_PUBLIC_PATH=/certs/fullchain.pem
    - CERT_PRIVATE_PATH=/certs/privkey.pem
    volumes:
    - /home/nextcloud/certs:/certs:ro
    links:
    - app
    ports: ['18080:18080']

`

**Comment by SnowMB** [comment]
Be sure to set `'overwritehost' => '', ` in your `config.php`  accordingly.

See https://docs.nextcloud.com/server/13.0.0/admin_manual/configuration_server/config_sample_php_parameters.html#proxy_configurations

**Comment by worksasintended** [comment]
Ah, thank you! I falsly put that into 
htaccess.RewriteBase
My very bad that I overlooked that in the docu!

**Comment by digitalkram** [comment]
I am in the same scenario (running behind non-443 ssl reverse proxy).
Is there a way of setting overwriteprotocol/overwritehost during first start of the nextcloud docker container (without extending the base image) via an environment variable by any chance?
