### ISSUE TITLE
service unavailable 503 in random time

### ISSUE THREAD

**Issue by Ciangi** [nextcloud/docker#278]
Hello,

as in topic, i got in random time "service unavailable 503" error. No informations in nextcloud/apache logs.
I use nextcloud:latest image. when i type ps -ef all apache background processes works... When i restart docker container everything works back fine.
Could anyone help me?

**Comment by AlbertJean** [comment]
I encounter the same problem following the previous update of nextcloud, 503 errors permanently, nextcloud is unusable.

**Comment by flycloudOne** [comment]
i found the same problem and many service is very slow, like file_favorites eg.

**Comment by pierreozoux** [comment]
Do you use only apache version, or do you have some sort of reverse proxy in front?

**Comment by mapolone** [comment]
I'm having the same issue, using Apache. The only difference is that I'm running it in a Kubernetes cluster.

**Comment by pierreozoux** [comment]
You should check your reverse proxy logs, you have to trace from the user to the edge until the container. It looks like external issue, especially if it is 503, it means that the apache is not available, but it doesn't mean apache is down.

**Comment by Ciangi** [comment]
Yep i found the problem.
I have QNAP and inside of apache qnap i debug log i found log like:
SSL Proxy connect failed

Everytime when this above line appears the proccess of  proxy https qnap ports to https cloud port just disappear.

I think that the problem became when i updated qnap - new docker version and new apache version. Helpdesk of QNAP till today don't know how to help me...
