### ISSUE TITLE
Add this repo to the list of auto updated repos

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/docker#28]
@SnowMB Could you add @tianon to the collaborators, then he can update this repo automatically with the `update.sh` script.

Thanks!

related to https://github.com/docker-library/official-images/issues/1321

**Comment by tianon** [comment]
You should throw in @docker-library-bot too :+1:

**Comment by SnowMB** [comment]
Would love to, but I have no access.

I summon @jospoortvliet . It's your time to shine 😁

**Comment by pierreozoux** [comment]
@SnowMB can you pressure  @jospoortvliet to do it please?
I'll send him an email again :)

**Comment by jospoortvliet** [comment]
Guys, sorry it took so long. I did:

* create a 'Docker' team: @nextcloud/docker 
* add @pierreozoux as team maintainer
* add @tianon @SnowMB and @docker-library-bot ;-)

Hope this works. And yeah, I'm behind on my github notifications, you have no idea...  :-1:

**Comment by tianon** [comment]
@jospoortvliet thanks!  I'll get some automation set up today :+1:

(I can definitely relate to being behind on GitHub notifications -- 23k unread conversations in my inbox and counting! :sweat_smile:)

**Comment by jospoortvliet** [comment]
23K? Ok, that is far beyond me. I feel I shouldn't even complain... hehe

**Comment by tianon** [comment]
https://doi-janky.infosiftr.net/job/update.sh/job/nextcloud/ :+1:

**Comment by tianon** [comment]
Also, https://github.com/docker-library/official-images/pull/2742

**Comment by pierreozoux** [comment]
Thanks everyone \o/
