### ISSUE TITLE
entrypoint.sh fails for fpm:alpine due to unsupported find option in BusyBox

### ISSUE THREAD

**Issue by wintamute** [nextcloud/docker#282]
When running the fpm:alpine image on a new installation, the entrypoint.sh tries to rsync some files. This fails as the script uses a find option which the find in busybox in alpine does not support.

The error then is:
```
find: unrecognized: -empty
BusyBox v1.24.2 (2017-11-23 08:52:33 GMT) multi-call binary.
```
This can be fixed by adding findutils in the Dockerfile for fpm:alpine:
```
RUN apk --no-cache add findutils && \
    rm -rf /var/cache/apk/*
```

**Comment by anshulsri12** [comment]
@wintamute thank you so much. I was struggling with find command in alpine.
