### ISSUE TITLE
Unable to pull image from docker hub

### ISSUE THREAD

**Issue by romanar** [nextcloud/docker#285]
`docker-compose up -d `
```
Pulling nextcloud (nextcloud:latest)...                                                                                                                       
latest: Pulling from library/nextcloud                                                                                                                        
ERROR: no matching manifest for linux/amd64 in the manifest list entries
```
`docker pull nextcloud`
```
Using default tag: latest                                                                                                                                     
latest: Pulling from library/nextcloud                                                                                                                        
no matching manifest for linux/amd64 in the manifest list entries
```
I also tried pulling the image using other tags and on different machines.

**Comment by cescobarf** [comment]
Just had this same problem trying to upgrade

**Comment by axel-kummer** [comment]
I am also unable to pull nextcloud images:
```
Pulling nextcloud (nextcloud:13-fpm)...
13-fpm: Pulling from library/nextcloud
no matching manifest for linux/amd64 in the manifest list entries
```
tested on Ubuntu 16.04 and Linux Mint 18.2

**Comment by SnowMB** [comment]
As quick workaround you can use the images under [amd64/nextcloud](https://hub.docker.com/r/amd64/nextcloud/).

ping @tilosp @tianon

**Comment by tilosp** [comment]
See: https://github.com/docker-library/official-images/issues/3835

**Comment by CleverUnderDog** [comment]
> As quick workaround you can use the images under amd64/nextcloud.


@SnowMB its seems to work but could you explain to me why?
I mean isn't nextcloud:latest a simple reference to amd64/nextcloud based on which arch you running?

**Comment by tilosp** [comment]
@CleverUnderDog the latest tag in amd64/nextcloud points to version 13.0.0 beacuse 13.0.1 is not build for amd64 yet. But the latest tag in nextcloud points to 13.0.1 because 13.0.1 is already build on some cpu architectures.

**Comment by tilosp** [comment]
and btw it is not a simple reference it gets updated every hour by this Jenkins job: https://doi-janky.infosiftr.net/job/put-shared/job/light/

**Comment by CleverUnderDog** [comment]
@tilosp Thanks, this totally makes sense :)

**Comment by CleverUnderDog** [comment]
Is there a way to get notified if the build is done?

**Comment by tilosp** [comment]
Once it is up on docker hub i will close this issue.

It looks like its alrady build: https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/nextcloud/
This means it up on [amd64/nextcloud](https://hub.docker.com/r/amd64/nextcloud/)
And once https://doi-janky.infosiftr.net/job/put-shared/job/light/ runs again it should be up on [nextcloud](https://hub.docker.com/_/nextcloud/).

**Comment by tilosp** [comment]
The image is no up on  [nextcloud](https://hub.docker.com/_/nextcloud/)
