### ISSUE TITLE
configuration reset

### ISSUE THREAD

**Issue by othcorp** [nextcloud/docker#286]
Hi,

I did some changes and am now not able to recover.

I did have setup docker image with separate mariadb container.
It was working until I started to play with adding letsencrypt proxy.

Is there a way to reset configuration of nextcloud, so I would connect to the same database, with the same user and password. Same admin user and password for nextcloud too.

It is all in order to use the same volume and addons etc as before, without the need to redo all I did.
I did copy quite a lot of data already so I would like to use it too, if possible.

I will be thankful for any suggestions as right now, I feel I exhausted all my knowledge.

**Comment by J0WI** [comment]
You basically need to backup these folders: https://github.com/nextcloud/docker/blob/master/upgrade.exclude
From your `config.php` you should keep `instanceid`, `passwordsalt` and `secret`. The databse can be set with environment variables.
