### ISSUE TITLE
App (files_pdfviewer) update do not work properly

### ISSUE THREAD

**Issue by tobiasbaehr** [nextcloud/docker#288]
When I try to update the app via UI, then the app will be downloaded to /custom_apps but not moved /apps.

I reload the page it shows again an update for files_pdfviewer is available.

Nextcloud image: nextcloud:13.0.1-apache
DB-Image: mariadb:10.3.5

The update on a nextcloud without docker works.

**Comment by tilosp** [comment]
cc @nextcloud/server-triage 
seems to be a problem with not writable app paths

**Comment by tobiasbaehr** [comment]
The owner of all directories/files is www-data.

**Comment by tilosp** [comment]
@tobiasbaehr the problem is that the apps dir is configured to bet not writable
See: https://github.com/nextcloud/docker/blob/master/.config/apps.config.php

**Comment by MorrisJobke** [comment]
Just for the context: yesterday we shipped an update of files_pdfviewer (which is usually a shipped app) to mitigate some bugs in it. cc @rullzer 

That also means, that it should be possible to overwrite the app in `apps/` itself.

**Comment by mr-bolle** [comment]
Hi, 

do you have set into your config.php a array for 'apps_paths'?
in my case it is like that, and i have the app files_pdfviewer into both. If you delete the folder into apps/files_pdfviewer and refresh the admin page. The update is installed into the custom_apps path, and the update refresh the app into that one.

I don't know why this default apps are into both path installed. 

> 'apps_paths' => 
>   array (
>     0 => 
>     array (
>       'path' => '/var/www/html/apps',
>       'url' => '/apps',
>       'writable' => false,
>     ),
>     1 => 
>     array (
>       'path' => '/var/www/html/custom_apps',
>       'url' => '/custom_apps',
>       'writable' => true,
>     ),
>   ),

**Comment by MorrisJobke** [comment]
> I don't know why this default apps are into both path installed.

I guess because the second one is writable. Nextcloud only installs into the writable apps dir. During the upgrade it will check the App Store and may have noticed that there is an update available and tries to install it -> custom_apps, but it loads it from the first one and thus is not showing the updated version. :/ We need to detect this in the server properly.

**Comment by MorrisJobke** [comment]
Let's try to tackle the underlying problem in https://github.com/nextcloud/server/issues/8929

**Comment by mr-bolle** [comment]
Hi, 

now I try one my test environment this issue again. And found out that the permissions of  /var/www/html/apps are www-data:root, and now I change it to www-data:www-data. After that the upgrade of the App works properly.
