### ISSUE TITLE
SMTP error when configuring email settings

### ISSUE THREAD

**Issue by graffen** [nextcloud/docker#290]
I'm running NC 13.0.1 in docker behind nginx-proxy and nginx-proxy-companion. 

When I try to configure SMTP settings, I get an error in NextCloud: 
`A problem occurred while sending the email. Please revise your settings. (Error: Unable to connect with TLS encryption)`

On the mail server, postfix throws this in the log
`Mar 22 10:16:26 mail postfix/submission/smtpd[21308]: warning: TLS library problem: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1399:SSL alert number 48:`

To me this looks like the NextCloud docker is using its own, untrusted/self-signed TLS cert to create the connection to my mail server, and since this isn't trusted, the mail server won't accept the connection. This makes sense, since the LetsEncrypt certs live in the reverse proxy, so NextCloud doesn't know anything about them. 

- Is there a way I can export this certificate from the docker container so that I can add it to the trusted cert store on my mail server? 
- Will this certificate stick, or does it get re-generated every time I download the latest image and run from that?

**Comment by J0WI** [comment]
As long as you mailserver doesn't require client cert authentication NextCloud does not use/need any certificate.
The issue seems to be on your mail servers side (or your configuration). Please make sure that the certificate chain of your mailserver is correct and valid.
