### ISSUE TITLE
Avoid generating a new mariadb docker image

### ISSUE THREAD

**Issue by rodrigoaguilera** [nextcloud/docker#291]
I realized the this PR introduced a change that builds a custom mariadb image
https://github.com/nextcloud/docker/pull/258
I feel that if the purpose is just changing a configuration value it can be done as part of the "command" section when you run a container as a flag:

 --transaction-isolation=READ_COMMITED

That is what I read from
https://hub.docker.com/_/mariadb/

But I have to really try it.

This will allow people to just copy the docker-compose.yml file and not the dockerfile and the specific structure that comes with it.

**Comment by rubdevton** [comment]
I made some changes that also add the --binlog-format=ROW argument needed for the READ-COMMITED isolation level (according to docs: https://mariadb.com/kb/en/library/set-transaction/).
I have not had a chance to test anything yet, but I plan to do so unless someone else does it before me.

https://github.com/rubdevton/docker/commit/d905503a6e705c92538f2b9069b7674ef99b9e53
