### ISSUE TITLE
Error logs for nextcloud:latest

### ISSUE THREAD

**Issue by gcleaves** [nextcloud/docker#295]
Hello,

I'm having terrible trouble uploading files using the :latest images behind an nginx SSL proxy. Sometimes the upload works for very small files, other times the uploader executes but the file doesn't appear, and most of the time the uploader doesn't even start. Dragging a file onto Nextcloud does nothing - no client-side JS errors, no apparent network activity in Chrome dev console. I don't know where to find the error log. docker logs -f shows nothing. /var/log/apache2/error.log is empty.

Please let me know how to troubleshoot. And if anybody has a proven nginx proxy config, that would be nice, too. I've found a few examples but they all have different settings.

Geoff

**Comment by mr-bolle** [comment]
Hi, the nextcloud log files you can find `nextcloud/data/nextcloud.log`
If you use a ngnix webserver you have to add follow file, into you ngnix container.

/etc/nginx/conf.d/uploadsize.conf
client_max_body_size 10G;

**Comment by gcleaves** [comment]
Thanks @mr-bolle , you're absolutely right. The trouble I was having is that I'm using the https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion image for the SSL reverse proxy and I was setting client_max_body_size in the wrong image. I've set it in all the images I can think of and things are now working as expected.
