### ISSUE TITLE
Persistent nginx config

### ISSUE THREAD

**Issue by Eriton33** [nextcloud/docker#304]
Hi,

I'm using the docker compose exampkle with nginx as proxy. 
https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache/docker-compose.yml
However it seems there is no way to persist the config for nginx as all changes are overwritten on the volumes after the container is restarted.

Also, with the last commit https://github.com/nextcloud/docker/commit/bb42fcfaed366007a941d8bc190864d601d11bdd#diff-d1599375ef161681939ba62830644a1a
the volume for the ginx confic was removed as well even though the changes I made to files in that volume did not persist anyway. However if I am not mistaken volumes exist especially for that purpose (persistent data) which makes me wonder if I have overlooked something or if this is a bug.

As things are now there is not way to configure the nginx proxy or is there?

**Comment by pierreozoux** [comment]
This example doesn't look like to make nginx tuning possible.

If you want to tune such things, I recommend forking this example, and tune it your way.

This is what I do here for instance: https://github.com/libresh/compose-nextcloud

**Comment by J0WI** [comment]
Assuming that the question has been answered.
