### ISSUE TITLE
[NC 13.0.1] Missing dependencies for Grauphel: Tomboy app

### ISSUE THREAD

**Issue by nRaecheR** [nextcloud/docker#305]
The current version of the Docker image is missing the dependencies for the Nextcloud App Grauphel: Tomboy. 
While trying to install it on a Docker Nextcloud instance, one get the error message 

```App "Grauphel: Tomboy note server" cannot be installed because the following dependencies are not fulfilled: The library OAuth is not available.```

and the installation fails because of that.

**Comment by J0WI** [comment]
The image can't cover all dependencies of all extensions. Feel free to extend it:
```Dockerfile
FROM nextcloud:$VARIANT

RUN set -ex; \
# Install required dependencies
#...
    pecl install oauth-$VERSION; \
    docker-php-ext-enable oauth-$VERSION

CMD ["$CMD"]
```

**Comment by nRaecheR** [comment]
Why can't it cover all dependencies, at least it should try to support the apps from the official store. I know that I can extend the Dockerfile with my the extension and rebuild it on my own. But this means a manual step each time the original image gets updated.

**Comment by J0WI** [comment]
See also related discussion in https://github.com/docker-library/owncloud/pull/79#issuecomment-284113915

**Comment by pierreozoux** [comment]
Yes, we want to keep the base image light and clean, so that everybody can extend on top.
