### ISSUE TITLE
Cannot upgrade Nextcloud Onlyoffice integration app

### ISSUE THREAD

**Issue by rollanders** [nextcloud/docker#309]
I have NC 13.0 in docker with Onlyoffice, nginx and MariaDB. Works well. I get a notification that there is a new version 1.3 of the integration app. Click on that - it shows upgrading. But when I get back no upgrade has taken place.

Maybe same issue as  #288

I have also posted this on Onlyoffice github as I do no know if this is a Docker or Onlyoffice issue

https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/175

**Comment by rollanders** [comment]
Solved by doing chown -R www-data:www-data /apps where /apps is the folder where var/www/onlyoffice/documentserver/web-apps/apps is located

**Comment by rollanders** [comment]
Sorry the solution above did not work

**Comment by tconnard** [comment]
I have had the same issue except with the PDF viewer.
