### ISSUE TITLE
TTFB is very high

### ISSUE THREAD

**Issue by bantocn** [nextcloud/docker#310]
Hello

The container is what I just installed, but all Ajax requests are very slow. In particular, the login page reached 30 seconds, and other pages also had about 4 seconds.

I try to turn off brute force protection but it has no effect

**Comment by buyi998** [comment]
This problem is similar to what I have encountered but it does not solve my problem #31

**Comment by buyi998** [comment]
I am sorry to write the title wrong

**Comment by J0WI** [comment]
I can't reproduce and the mentioned version is EOL.
