### ISSUE TITLE
Environment variable to disable frontend upgrade/update button

### ISSUE THREAD

**Issue by kawaii** [nextcloud/docker#315]
I propose for some way of disabling the button to update to the next version to be implimented into Nextcloud. This is not necessarily Docker specific but for my own use case is why I've chosen to open the issue here and not in the main repository. We manage Nextcloud installations (or Docker 'instances') for our clients, some of which have admin control over their installation. We'd like to prevent them from just arbitrarily clicking the update button in the frontend [and potentially breaking their installation due to a dodgy module](https://github.com/nextcloud/server/issues/9193) or some other unknown variable.

For Docker specifically, an environment variable would be perfect, but if this were to be a Nextcloud setting in general then I suppose the configuration file would be the best place for it.

Thoughts?

**Comment by tilosp** [comment]
we already disable the updater in the `Dockerfile` see: https://github.com/nextcloud/docker/blob/01ad4658abe6add2ee6282432b0d3d3e5d22d135/Dockerfile-debian.template#L112
Have you tried clicking the update button? It shouldn't work.

**Comment by tilosp** [comment]
there is also this config option: https://github.com/nextcloud/server/blob/13d21f5989a3dfba417a506cbe5bac9e794c3fdd/config/config.sample.php#L1544

**Comment by kawaii** [comment]
@pierreozoux yes, apps.
See this issue for more reason why:
https://github.com/nextcloud/server/issues/9193

**Comment by J0WI** [comment]
You could use `'appstoreenabled' => false,` or `'has_internet_connection' => false,`

https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html
