### ISSUE TITLE
Ajax cron.php is a noop

### ISSUE THREAD

**Issue by ghost** [nextcloud/docker#318]
Because of a [Nextcloud 13.0.1 bug](https://github.com/nextcloud/server/issues/9050) the Ajax version of cron.php does not do anything. Since it is the default, e-mail notification, file expiration etc. do not work as expected.

**Comment by dachary** [comment]
A possible solution would be to replace `13.0/apache/Dockerfile` with something similar to `.examples/dockerfiles/cron/apache/Dockerfile`, i.e. always run the daemon (apache or npm) via supervisord together with cron.php instead of not running cron.php by default.

**Comment by dachary** [comment]
For the record, here is what I did as a temporary measure

* sudo docker build -t nextcloud:apache-cron .examples/dockerfiles/cron/apache
* cd /home/debian/docker/.examples/docker-compose/with-nginx-proxy/postgres/apache
* patch
```
diff --git a/.examples/docker-compose/with-nginx-proxy/postgres/apache/docker-compose.yml b/.examples/docker-compose/with-nginx-proxy/post
gres/apache/docker-compose.yml
index febd740..97d49d5 100644
--- a/.examples/docker-compose/with-nginx-proxy/postgres/apache/docker-compose.yml
+++ b/.examples/docker-compose/with-nginx-proxy/postgres/apache/docker-compose.yml
@@ -10,14 +10,14 @@ services:
       - db.env

   app:
-    image: nextcloud:apache
+    image: nextcloud:apache-cron
     restart: always
     volumes:
       - nextcloud:/var/www/html
```
* sudo docker-compose up -d

**Comment by dachary** [comment]
Would you like me to propose a pull request based on this or do you think there is a better way?

**Comment by J0WI** [comment]
I would recommend to execute `docker exec -u www-data my-nextcloud php cron.php` periodically from your host.
