### ISSUE TITLE
Request Entity Too Large

### ISSUE THREAD

**Issue by ARMistice** [nextcloud/docker#32]
I get errors when using Nextcloud Image over https (nginx-proxy), but works fine with http:

Error Downloading https://.../remote.php/webdav/...... - server replied: Request Entity Too Large.

Possibly something to do with the PHP-Settings in the container?

**Comment by cl3m3nt666** [comment]
I have the same error. 
I solved the error by modifying my configuration of my nginx proxy 

If you use JrCs/docker-letsencrypt-nginx-proxy-companion
Change configuration in `/etc/docker-gen/templates/nginx.tmpl` or specific template
```
 server {
....
        client_max_body_size 20M;
....
    }
```
And restart :) 
http://www.daveperrett.com/articles/2009/11/18/nginx-error-413-request-entity-too-large/

**Comment by ARMistice** [comment]
Many thanks,
you are right it was a "fault" in JrCs/docker-letsencrypt-nginx-proxy-companion which created this Problem. I solved it by adding the client_max_body_size to the "/etc/nginx/vhost.d/default" config. Which worked. For me the special config for the domain wasnt loaded :(

**Comment by pierreozoux** [comment]
Looks solved :)

**Comment by tjscomics** [comment]
Thanks, you saved my life!
