### ISSUE TITLE
nextcloud:13.0.2 ?

### ISSUE THREAD

**Issue by christophetd** [nextcloud/docker#323]
Hi, 

I'm currently running `nextcloud:13.0.1` and would like to update to `nextcloud:13.0.2`, but the tag doesn't exist (only `13.0.2-rc`). I assume it's maybe too early, generally how much time after the nextcloud code does the corresponding docker image gets released?

Thank you!

**Comment by tilosp** [comment]
The tag exists now. 

After we change something in this repo, a review and merge is required in the [docker-library/official-images](https://github.com/docker-library/official-images) repo. After that is done the images get build by a [jenkins server](https://doi-janky.infosiftr.net/) which can take some time depending on how busy the build server is.
