### ISSUE TITLE
separate application code from data

### ISSUE THREAD

**Issue by rdxmb** [nextcloud/docker#326]
Hello,

with https://github.com/nextcloud/docker/issues/251 there was a problem with missing files in `/var/www/html`

I don't know if I understand it the right way - but it would be the best to separate appliation code from personal data. This could be done , e.g. , via symlinks.

What about https://github.com/nextcloud/docker/commit/5ddd03aa501a53d609ec4f8de3add575fc10f5ce ? Is this a step for that? The folder seems to be empty after an update from 12.7 to 13.0.2

**Comment by skjnldsv** [comment]
Please read the readme about persistent data: https://github.com/nextcloud/docker#persistent-data

**Comment by rdxmb** [comment]
I did. As I use this in Docker SwarmMode, `/var/www/html` is not a docker volume, but a bind mount like

`/mnt/shared/nextcloud:/var/www/html`

Is this not supported with this image? If files in the image within /var/www/html were added with a new version, with a bind mount they will not appear - for they will be "covered" by the mounted files. With docker volumes they get "merged", as long as `nocopy: true` is not set in the compose- or stack-file.

**Comment by skjnldsv** [comment]
you want persistent data or persistent nextcloud instance?
Because I use the bind mount with /data:/var/www/html/data and it works fine :)

**Comment by rdxmb** [comment]
@skjnldsv What do you mean with "persistent nextcloud instance"?

I just want to be able to upgrade nextcloud with changing the image - and have the data, configs, apps persistent.

When changing the image from 12.x to 12.7 there were application files missing in /var/www/html , as reported in https://github.com/nextcloud/docker/issues/251 . I have had a look at the Dockerfiles and have seen that there were files `rsync`-ed with `--delete` to `/var/www/html` when running supervisord . I think there is the problem.

**Comment by rdxmb** [comment]
Maybe I did not get the real meaning of the docs. Is it enough to mount

> /var/www/html/custom_apps installed / modified apps
> /var/www/html/config local configuration
> /var/www/html/data the actual data of your Nextcloud
> /var/www/html/themes/<YOU_CUSTOM_THEME> theming/branding

?

What does

> /var/www/html Main folder, needed for updating

really mean?

 Main folder, needed for updating 

mean?


/var/www/html/custom_apps installed / modified apps
/var/www/html/config local configuration
/var/www/html/data the actual data of your Nextcloud
/var/www/html/themes/<YOU_CUSTOM_THEME> theming/branding

**Comment by rdxmb** [comment]
If this really is the right way, the docs should be edited for this best practise, for this is not documented in that way here.

IS

> To make your data persistent to upgrading and get access for backups is using named docker volume or mount a host folder. To achieve this you need one volume for your database container and Nextcloud.
> 
> Nextcloud:
> 
>     /var/www/html/ 

...

SHOULD BE

To make your data persistent to upgrading and get access for backups is using named docker volumes or mount host folders. [...]

Nextcloud:

/var/www/html/custom_apps installed / modified apps
/var/www/html/config local configuration
/var/www/html/data the actual data of your Nextcloud
/var/www/html/themes/<YOU_CUSTOM_THEME> theming/branding

**Comment by skjnldsv** [comment]
@rdxmb could you create a pull request? :)

**Comment by rdxmb** [comment]
here we go ...
