### ISSUE TITLE
FeatureRequest: write docker logs when migrating data

### ISSUE THREAD

**Issue by rdxmb** [nextcloud/docker#327]
When upgrading from 12.07 to 13.0.2 the web-container is not reachable for minutes. 
`docker logs` seems empty.

When checking `ps xa` within the container, there are running some `rsync`-processes.

Could you please write some output to the docker logs (stdout)? Echoing `'migrating data. This could take some time...'` would be enough for the first step.

**Comment by pierreozoux** [comment]
Would you like to make a PR? The script is [here](https://github.com/nextcloud/docker/blob/master/docker-entrypoint.sh)
