### ISSUE TITLE
SSL Required

### ISSUE THREAD

**Issue by doodlemania2** [nextcloud/docker#33]
Hi there - the Docker image seems to be having an issue when attempting to connect to MySQL (remote) if remote requires SSL, is there a way to support that (my server is set to require SSL).

**Comment by pierreozoux** [comment]
Indeed, maybe mysql ssl support is not build in.
I don't use it, so I can't really help you, but if you PR, I'd be more than happy to merge!

**Comment by ambis** [comment]
PR #34 updated the mysql library to mysqli (with an i). 

mysql doesn't support SSL on any level, but mysqli does. I believe nextcloud does not support config keys for mysqli SSL config (which I think it should).

**Comment by pierreozoux** [comment]
@doodlemania2 then if mysqli supports SSL, you should be good to go with version 11 :)

Please reopen if needed.
