### ISSUE TITLE
APCu apparently not running

### ISSUE THREAD

**Issue by y0va** [nextcloud/docker#336]
I still have these messages in the log:

```
{"reqId":"M8GVPAOoFTXpYCokElcT","level":1,"time":"2018-05-14T21:21:49+00:00","remoteAddr":"","user":"--","app":"cli","method":"--","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for local cache","userAgent":"--","version":"13.0.2.1"}
{"reqId":"M8GVPAOoFTXpYCokElcT","level":1,"time":"2018-05-14T21:21:49+00:00","remoteAddr":"","user":"--","app":"cli","method":"--","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","userAgent":"--","version":"13.0.2.1"}
```
acpu configuration looks like:
```
apcu                                                                     
                                                                         
APCu Support => Enabled                                                  
Version => 5.1.11                                                        
APCu Debugging => Disabled                                               
MMAP Support => Enabled                
MMAP File Mask =>                                                        
Serialization Support => php                                   
Build Date => May 10 2018 18:49:49      
                                                          
Directive => Local Value => Master Value          
apc.coredump_unmap => Off => Off                 
apc.enable_cli => On => On                      
apc.enabled => On => On
apc.entries_hint => 4096 => 4096
apc.gc_ttl => 3600 => 3600
apc.mmap_file_mask => no value => no value
apc.preload_path => no value => no value
apc.serializer => php => php
apc.shm_segments => 1 => 1
apc.shm_size => 32M => 32M
apc.slam_defense => On => On
apc.smart => 0 => 0
apc.ttl => 0 => 0
apc.use_request_time => On => On
apc.writable => /tmp => /tmp
```

After manually enabling APCu Features:
```
root@02e0442acb2b:/var/www/html# cat /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini
extension=apcu.so
apc.enable_cli=1
```
https://github.com/krakjoe/apcu/issues/99
( Is this necessary? Any way to automate it in docker environment?)

config.php contains:

```
  'memcache.local' => '\OC\Memcache\APCu',
  'memcache.locking' => '\OC\Memcache\Redis',
  'redis' =>
  array (
    'host' => 'redis',
    'port' => 6379,
  ),
```

In the Admin Interface the tests for caching pass, everything looks ok, also redis, but still these errors appear in the logs.

**Comment by godfuture** [comment]
Same here. APCu is configured but getting this error log:
> Info | cli | Memcache \OC\Memcache\APCu not available for local cache

I tried to get more information and went into the container:
```
docker exec -it nextcloud /bin/bash
php -r \@phpinfo\(\)\; | grep apcu
Additional .ini files parsed => /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini,
apcu
```
But I couldn't really find out something. Interesting is that when I had configured Redis to be used as local cache, this log appeared as well...

What is going wrong?

**Comment by kimsyversen** [comment]
My Dockerfile is shown below. Maybe this helps.

I had the same issue as you. After I added the `echo "apc.enable_cli=1" >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini`. Now I dont see any error messages related to apcu anymore.


```
FROM nextcloud:fpm

RUN apt-get update && apt-get install -y \
    supervisor \
    libc-client-dev libkrb5-dev \
  && rm -rf /var/lib/apt/lists/* \
  && docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
  && docker-php-ext-install imap \
  && mkdir /var/log/supervisord /var/run/supervisord \
  && echo "apc.enable_cli=1" >> /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini

COPY supervisord.conf /etc/supervisor/supervisord.conf

CMD ["/usr/bin/supervisord"]
```

**Comment by biva** [comment]
I quote @michalng in https://help.nextcloud.com/t/cli-apcu-not-available/26194/2

> Add apc.enable_cli=1 to your /etc/php/7.0/mods-available/apcu.ini or similar one, depending on your PHP version. Then restart PHP/webserver
> 
> APCu is by default not active for CLI calls, e.g. cron or occ command.

@nickvergessen : shouldn't it be added to the Nextcloud documentation?https://docs.nextcloud.com/server/13/admin_manual/configuration_server/caching_configuration.html

**Comment by nickvergessen** [comment]
Feel free to add it :wink: 
Send a PR to https://github.com/nextcloud/documentation/

**Comment by biva** [comment]
@nickvergessen I'd love to do it, but I'm just copy-pasting that from other blogs/websites, and I don't understand all what I'm doing. 

Where should we put `apc.enable_cli=1` ?
- `/etc/php/7.2/cli/php.ini` as I see in @riegercloud (https://www.c-rieger.de/nextcloud-installation-guide-debian-stretch/) ?
- `/etc/php/7.2/mods-available/apcu.ini` ?
- Or in both?

In addition, I understand opcache should be configured correctly (https://docs.nextcloud.com/server/13/admin_manual/configuration_server/server_tuning.html?highlight=opcache#enable-php-opcache), where should it be configured?
- `/etc/php/7.2/fpm/php.ini` ?
- `/etc/php/7.2/apache2/php.ini` ?
- Or should it be in both?

Last question: I see in https://www.c-rieger.de/nextcloud-installation-guide-debian-stretch/#c03 that a lot more parameters are added about `apc`: are they optional, or should I include them in the documentation?

Thanks @nickvergessen

**Comment by biva** [comment]
I opened a pull request here: https://github.com/nextcloud/documentation/pull/830
@nickvergessen and/or @tilosp, could you help me?
Thanks
