### ISSUE TITLE
PR: Add in `.examples` an example for LAN solutions with HTTPS without letsencrypt

### ISSUE THREAD

**Issue by lil5** [nextcloud/docker#337]
I've written one with [paulczar/omgwtfssl](https://hub.docker.com/r/paulczar/omgwtfssl/).

https://gist.github.com/lil5/b7263a59f385f1296fcfdb5fbf816a4b

**Comment by pierreozoux** [comment]
Do you want to PR?

**Comment by lil5** [comment]
@pierreozoux yeah sure
