### ISSUE TITLE
this content failed to load

### ISSUE THREAD

**Issue by aristosv** [nextcloud/docker#339]
I get this on first login and it keeps reloading every 5 seconds.

![2018-05-17 06_34_50-files - nextcloud](https://user-images.githubusercontent.com/528302/40155471-94b46530-599c-11e8-8db1-11c1de59b7c0.png)

this is how I installed it.

docker run -d --restart always --name=nextcloud -p 8080:80 -e PUID=1001 -e PGID=1001 -v nextcloud:/var/www/html -e TZ=Asia/Nicosia nextcloud

**Comment by KyleTryon** [comment]
I just did a simple `docker run -d -p 8080:80 nextcloud` and I am unable to load the page.

**Comment by aristosv** [comment]
No support for the container really.

**Comment by tilosp** [comment]
We currently do not support changing of the UID/GID. (see: #359)

**Comment by tstackhouse** [comment]
I'm seeing the same issue and also did the same as @KyleTryon running completely isolated and the current stable container does the same thing.

**Comment by changchichung** [comment]
I have the same situation , after login , the page always refresh with error loading the content..any solutions ?
