### ISSUE TITLE
Do not switch to older alpine repositories for nextcloud:fpm-alpine

### ISSUE THREAD

**Issue by Drugoy** [nextcloud/docker#347]
On `nextcloud:fpm-alpine` image command `cat /etc/alpine-release` returns `3.4.6` and `cat /etc/apk/repositories` returns `http://dl-cdn.alpinelinux.org/alpine/v3.4/main`, but the parental image is `php:7.1-fpm-alpine3.7`, which is based on alpine v3.7 with repositories from alpine v3.7.

**Comment by J0WI** [comment]
I cannot reproduce using `docker pull nextcloud:fpm-alpine && docker run --rm nextcloud:fpm-alpine cat /etc/issue /etc/apk/repositories`.

**Comment by Drugoy** [comment]
Thanks, I see it is fixed now.
