### ISSUE TITLE
Restore deleted volumes

### ISSUE THREAD

**Issue by churib** [nextcloud/docker#348]
Hi,

I accidently deleted my docker volumes via `docker-compose down -v`.
I use docker-compose from the example section with apache and mariadb.
I do nighlty backups of the host system, so i still have the /var/lib/docker/volumes folders.

Okay, I dont have much knowlodge about neither docker nor nextcloud, but here is how i tried to restore my data:
I copied back (via rsync - ownership and permissions should be intact) the volume folders und started nextcloud `docker-compose up`, but I got some strange behavior:
- my two user accounts are there
- the files of the users are there
- the calendar app is installed but disabled
- when I enable it, my previously calendars are not there
- I cannot login as admin

I tried to create the admin user via occ
`docker exec -e OC_PASS=xxx --user www-data apache_app_1 php occ user:add admin --password-from-env --group=admin`
but the user does not seem to be created.

Any idea how to restore my data? 

Most important for me are the calender entries. My last resort is to dump them from the old database and import them.

**Comment by mr-bolle** [comment]
Hi, 

could you login into your mariadb container? If yes you can create a mysqldump your whole database or only from calender tables

edit before you run _DB_CONTAINER_NAME_ and _NEXTCLOUD_DB_NAME_ 
example 1 table (oc_users): `docker exec DB_CONTAINER_NAME sh -c 'exec mysql -u root -p"$MYSQL_ROOT_PASSWORD"  NEXTCLOUD_DB_NAME oc_users' > /var/lib/mysql/oc_users.sql`

**Comment by churib** [comment]
Hi @mr-bolle,
yes, that would be my last resort.

My understanding was: There are stateless containers, all state is written to volumes.
To rebuild my setup i hoped to just restore the volumes and fire up the containers.

My backup strategy relies on this understanding. 
Any ideas what I may have missed?

**Comment by mr-bolle** [comment]
You can mount the container volume on your host, and all changes will be available after updating the image.

volumes:  
Just specify a path and let the Engine create a volume 
`- /var/lib/mysql`

Specify an absolute path mapping 
`- /opt/data:/var/lib/mysql`

Path on the host, relative to the Compose file 
`- ./cache:/tmp/cache` 

User-relative path 
`- ~/configs:/etc/configs/:ro`

Named volume 
`- datavolume:/var/lib/mysql`

https://docs.docker.com/compose/compose-file/#long-syntax-3

**Comment by churib** [comment]
Hi @mr-bolle,

i tried to myspldump my databases and got strange errors, that some tables are missing.

I concluded that my restored db volume is corrupt and I rsynced it again to my server.

Now it works as I assumed before. So it 's most likely that I did some mistakes at  restoring tbe volume via rsync before.

Thanks for your help!

This issue can be closed!
