### ISSUE TITLE
Missing "server_name example.com;"

### ISSUE THREAD

**Issue by scurrie18** [nextcloud/docker#350]
https://github.com/nextcloud/docker/blob/e833d8a4b7e78aef863e1841f780fbe1f73f3a0c/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf#L41

LetsEncrypt keeps failing with "ERROR:simp_le:1272: CA marked some of the authorizations as invalid" because it relies on finding the server name in nginx.conf in order to add the required code to complete the initial verification. Adding `server_name example.com` fixed it. Perhaps there is a better way than to hard code it in.

**Comment by J0WI** [comment]
The example lacks of https completely. I would refer to https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx.rst

**Comment by Fribb** [comment]
I have the same problem but with the mariadb apache version. In that example there is no nginx,conf available (nor can I find it in the container), so I'm not sure how I would resolve this in my case.

**Comment by J0WI** [comment]
You can customize apache as described here:
https://hub.docker.com/_/httpd/#configuration
