### ISSUE TITLE
Updater does not open

### ISSUE THREAD

**Issue by topas-rec** [nextcloud/docker#352]
I've installed NC 13.0.1 from examples section without doing an update so far through the NC admin panel. (Just installed via docker-compose) (Installation ran perfectly for months with just some file locking errors at the beginning - they never appeared again)
Now there is an update to NC 13.0.2 available through the internal updater in NC admin basic setings.
![screenshot from 2018-05-28 20-30-38](https://user-images.githubusercontent.com/20391449/40626039-629bfd38-62b6-11e8-9eaa-bbbd9835d533.png)

I tried to do the update by clicking on "Open Updater" but NC only changed to an empty main frame - with decorating NC environment (Menu on the left and Main menu on top)
![screenshot from 2018-05-28 20-30-54](https://user-images.githubusercontent.com/20391449/40626047-7209d312-62b6-11e8-8c17-dc0c5bbdb191.png)

My questions are:
1. What is the preferred way to upgrade? (I know that the suggestions from examples section is to do a `docker-compose build --pull` and then `docker-compose up -d` - but should the internal updater also work?)
2. If the internal updater should work - how can I debug the issue frome above? (There is no entry in the native NC logs and no entry in the NC app container logs and not in the proxy container logs. Only firefox console shows:
`Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/
core.js:4:14346`
`Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://mydomain.ddns.net/core/vendor/core.js?v=7d781b9c-0
Source Map URL: purify.min.js.map[Learn More]`
)
Replaced my domain name with mydomain in the Firefox console output.

**Comment by x86dev** [comment]
Experienced the exact same here with the just released 13.0.3.

**Comment by tilosp** [comment]
This is no a bug. We disabled the internal updater because we want people to update by pulling the new docker image. This way the php dependencies get also updated.

@x86dev the image for 13.0.3 is not jet available. 
Currently we are waiting for this PR to get merged: https://github.com/docker-library/official-images/pull/4440

**Comment by noplanman** [comment]
@tilosp Just ran into this as well. Would be nice to have a message or something at least.
Landing on a seemingly broken page feels kinda weird :grin:

**Comment by tilosp** [comment]
Yes this would be a nice improvement. But i am not sure how to best accomplish that.
Maybe a config option for the server to disable the updater. Or simply showing a message that the updater is not available if the updater files are missing.

@pierreozoux any ideas?

**Comment by topas-rec** [comment]
> This is no a bug. We disabled the internal updater because we want people to update by pulling the new docker image. This way the php dependencies get also updated.

Point that out on the explanation page of the examples. Update via following docker commands and NOT using the update button. (Button is there - but disabled) I read that page carefully and remembered the way nextcloud has to to be updated when using the docker images. That is why I asked for:

> What is the preferred way to upgrade? (I know that the suggestions from examples section is to do a docker-compose build --pull and then docker-compose up -d - but should the internal updater also work?)

If I'd have found this on that page everything would have been clear to me. (If you find a way to make the button disappear or make a dialogue box that would make it perfect)

**Comment by x86dev** [comment]
@tilosp The upgrade path also is fine with me and makes sense.

The "Update" button needs to be disabled with a hint in Docker image documentation ... I guess that should be easily doable via a NextCloud configuration setting. Otherwise people will get into this again, wondering why they can update their instance.
