### ISSUE TITLE
Nextcloud page doesnt load after reboot when using LDAP

### ISSUE THREAD

**Issue by domnoble** [nextcloud/docker#356]
i am running nextcloud with docker-compose, if i reboot the server while im still logged in via LDAP in the browser when the server comes back up i get a 504 page from my reverse proxy. when i look through the nextcloud.log in data i can see there is a problem with the LDAP connection, first i thought it might be because the requests go to the external IP rather than straight to the internal one so i set explicitly the LDAP IP in /etc/hosts, which had no effect page still blank no matter how many times i reloaded. so then i thought possibly it might be down to the credentials from LDAP still being active in the browser session and some sort of CSRF protection that might be stopping it, so i flushed the browser cache and surely enough nextcloud came back up

**Comment by pierreozoux** [comment]
This issue looks related to LDAP, and not necessarily the docker image by itself (that doesn't ship ldap at all)
I'm closing this, I think you would have better luck in the ldap repo.
Feel free to reopen if you feel it is related to docker.
