### ISSUE TITLE
Web login broken after update to nc13

### ISSUE THREAD

**Issue by MPK1** [nextcloud/docker#364]
Hi there,
since i did the update to Nextcloud 13, i cannot login to the Webinterface any more. I can use Nextcloud on the PC's I am already logged in, Android Client and Windows Sync also work as normal, but with any new Browser I cannot log in. If I wait for my current sessions to expire, I cannot use it any more. 
When I type in username and password and hit the login button, nextcloud just refreshes the page and doesn't show any errormsg, even if I type a wrong password...
Do you know what could went wrong?
Thank you.

**Comment by tilosp** [comment]
This is a bug of the server see: https://github.com/nextcloud/server/pull/9802#issuecomment-395780141
