### ISSUE TITLE
There was no plugin in the system that was willing to handle this SEARCH method.

### ISSUE THREAD

**Issue by upsala** [nextcloud/docker#369]
I'm trying to search with curl like in this [documentation](https://docs.nextcloud.com/server/13/developer_manual/client_apis/WebDAV/search.html):

```
curl -X SEARCH http://192.168.1.68:8080/remote.php/webdav/files/admin/ -u admin:admin -H "content-Type: text/xml" --data '<?xml version="1.0"?>
 <d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:basicsearch>
      <d:select>
          <d:prop>
              <oc:fileid/>
              <d:getcontenttype/>
              <d:getetag/>
              <oc:size/>
          </d:prop>
      </d:select>
      <d:from>
          <d:scope>
              <d:href>/files/</d:href>
              <d:depth>1</d:depth>
          </d:scope>
      </d:from>
      <d:where>
          <d:like>
              <d:prop>
                  <d:getcontenttype/>
              </d:prop>
              <d:literal>text/%</d:literal>
          </d:like>
      </d:where>
      <d:orderby/>
  </d:basicsearch>
</d:searchrequest>'
```

But I'm always getting an error-message:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotImplemented</s:exception>
  <s:message>There was no plugin in the system that was willing to handle this SEARCH method.</s:message>
</d:error>
```

What I'm making wrong.

**Comment by ChrisHaPunkt** [comment]
The example in the documentation is incorrect. The request needs to point to the `/dav/`-root and the scope property in the payload needs to be `files/<user>` .
The corrected one should be (in your case)
`curl -X SEARCH http://192.168.1.68:8080/remote.php/dav/ -u admin:admin -H "content-Type: text/xml" --data '<?xml version="1.0"?>
 <d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:basicsearch>
      <d:select>
          <d:prop>
              <oc:fileid/>
              <d:getcontenttype/>
              <d:getetag/>
              <oc:size/>
          </d:prop>
      </d:select>
      <d:from>
          <d:scope>
              <d:href>/files/admin</d:href>
              <d:depth>1</d:depth>
          </d:scope>
      </d:from>
      <d:where>
          <d:like>
              <d:prop>
                  <d:getcontenttype/>
              </d:prop>
              <d:literal>text/%</d:literal>
          </d:like>
      </d:where>
      <d:orderby/>
  </d:basicsearch>
</d:searchrequest>'`
Thanks to @gameldar
[#9347](https://github.com/nextcloud/server/issues/9347#issuecomment-389227418)

**Comment by chichivica** [comment]
in my case I just missed 
```
-H "content-Type: text/xml"
```
