### ISSUE TITLE
Official nextcloud docker-compose

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/docker#37]
It would make sense to ship an official docker-compose from Nextcloud with the following features:
 - TLS
 - Cron
 - collabora

What do you think @SnowMB ?

**Comment by SnowMB** [comment]
I looked through the discussion and your comments and I like the ideas in https://github.com/docker-library/owncloud/pull/79.

It would be great to keep our base images (apache + fpm) simple and don't overcomplicate things by adding a million different tags. (e.g. If you would like to add a 'heavy' tag, you would have to do apache, fpm, apache-heavy, fpm-heavy multiplied by the number of versions we're offering.) 
Instead we could document the possibility to build on the base images and add what the user needs via derived dockerfiles.

For example something like:
```
FROM nextcloud:apache
RUN apt-get update && apt-get install -y smbclient && rm -rf /var/lib/apt/lists/*
```

Or for cron something like:
```
FROM nextcloud:fpm

RUN apt-get update && apt-get install -y \
  supervisor \
  cron \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir /var/log/supervisord /var/run/supervisord && \ 
  echo "*/15 * * * * su - www-data -s /bin/bash -c \"php -f /var/www/html/cron.php\""| crontab -

COPY supervisord.conf /etc/supervisor/supervisord.conf

CMD ["/usr/bin/supervisord"]
```

This would be a great way to let the user choose what he needs. (Personally I use exactly this method now, I was just to lazy to update my github repo ;) )

For the official compose part:
After working with diffrent installations (at work and at home), I think it's not feasible. There are so many possibilities to configure even the simplest nextcloud installtion and it's depending heavily on the server architechture used (proxies, databases, ect.). We surely should add more examples (and I strongly agree that our documentation of how to use the fpm image must get better), but marking a docker-compose solution as "official" might be misleading and a bad idea. We should focus on giving the right examples so anyone can build the setup that suits him.

PS: any idea on the /var/www/html volume part? ;)

https://github.com/nextcloud/docker/pull/23

**Comment by ambis** [comment]
> It would be great to keep our base images (apache + fpm) simple 

@SnowMB Spot on. Happy to see Nextcloud docker images are in good hands.

**Comment by pierreozoux** [comment]
@SnowMB you are right, closing in favor of #57
