### ISSUE TITLE
problems using: docker-compose with-nginx-proxy/mariadb/fpm/

### ISSUE THREAD

**Issue by VladDrakul1986** [nextcloud/docker#373]
i edit as explained the docker-compose.yml and db.env and start everythink with

`docker-compose up -d`

5 times done but my nextcloud is not avaiable if i check the logs all looks fine besides letsencrypt-companion here i got an error as anyone a idea how to fix this?

`2018-06-20 20:06:54,774:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: ....,`

**Comment by amarmadhavan** [comment]
I'm having the exact same problem. Did you ever find a fix for this?

**Comment by VladDrakul1986** [comment]
not really i test out the apache .examples/docker-compose/with-nginx-proxy/mariadb/apache
and only change the volumes section to
`volumes:
  db:
    driver_opts:
      type: none
      device: /yourPath/db
      o: bind
  nextcloud:
    driver_opts:
      type: none
      device: /yourPath/nextcloud
      o: bind
  certs:
  vhost.d:
  html:
`
now the containers are running fine iam not sure what was really the problem why its failed
