### ISSUE TITLE
Error send mail with php

### ISSUE THREAD

**Issue by jeferro** [nextcloud/docker#375]
Hello,

I am trying the installation of Nextcloud with Docker. I copied the docker-composer from Docker Hub and the installation was fine. But when I tried to send a email with default configuration (php mode), it is failed. I tryed to solve myself, but I couldn't. I have ufw disabled. My docker-compose file is:

version: '2'
services:
  db:
    image: mariadb:10.3.7
    container_name: nextcloud_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    ports:
      - 3306:3306
    volumes:
      - ./storage/db/data:/var/lib/mysql

  webserver:
    image: nextcloud:13.0.4
    container_name: nextcloud_webserver
    restart: always
    environment:      
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    ports:
      - 80:80
      - 25:25
    volumes:
      - ./storage/webserver/html:/var/www/html
      - ./storage/webserver/logs:/var/log/apache2
    links:
      - db

**Comment by robinleander** [comment]
The `nextcloud:fpm` container does not come with sendmail resulting in the following error messages:

```
A problem occurred while sending the email. Please revise your settings. (Error: Email could not be sent. Check your mail server log)
```

```
app_1  | [10-Jul-2018 19:42:13] WARNING: [pool www] child 21 said into stderr: "sh: 1: "
app_1  | [10-Jul-2018 19:42:13] WARNING: [pool www] child 21 said into stderr: "-t: not found"
app_1  | [10-Jul-2018 19:42:13] WARNING: [pool www] child 21 said into stderr: ""
```

Which according to [this](http://axiac.ro/blog/sh-1-t-not-found/) is related to a sendmail issue.

If sendmail is added to the image, I suggest installing it during the first run, since it appears to generate a private key and certificate.

**Comment by J0WI** [comment]
Only SMTP mode is supported in Docker.

**Comment by J0WI** [comment]
To clarify: there is no mail transfer agent installed in the container. You can use any external MTA or a MTA container.
