### ISSUE TITLE
Package "LibreOffice" in Dockerfile-Examples

### ISSUE THREAD

**Issue by TheMiller2015** [nextcloud/docker#379]
Hello there! Something might have been changed and I wanted to inform you quickly about that. In all of your "Dockerfile (build)"-examples, the commented package "LibreOffice" can be uncommented in order to build/install an instace with nextcloud enabled. **But this doesn't work anymore**, as the packagenames are case-sensitve, so you have to uncomment the line "LibreOffice" as stated in the README.md and to change the name to lowercase completely. I can't do a pull-request because I ran out of time, but I hope someone will do that for the community.

Thanks for nextcloud, docker repos, examples and your great work. I hope, I could also help someone.

Have a nice day.

**Comment by SnowMB** [comment]
Duplicate #380
