### ISSUE TITLE
Upgrade issue from 12.0.4 to 13.0.1 with docker image

### ISSUE THREAD

**Issue by meons** [nextcloud/docker#389]
I have tried to upgrade from nextcloud 12.0.4 to 13.0.1 by using the new image and keeping same mounts and data but it fails because of an invalid datetime format as you can see on the attached screen shot.

Need I to perform some changes manually before upgrading ?

### Steps to reproduce
https://github.com/nextcloud/docker#update-to-a-newer-version

### Expected behaviour
Upgrade should be performed

### Actual behaviour
![error](https://user-images.githubusercontent.com/5362939/37665293-3446047c-2c5d-11e8-8a91-e7ed2ce030e3.png)

### Server configuration

**Operating system**:
SLES12SP2, Docker version 17.04.0-ce, build 78d1802

**Web server:**
nextcloud:12.0.4-apache -> nextcloud:13.0.1-apache

**Database:**
10.2.7-MariaDB

**PHP version:**
nextcloud:12.0.4-apache -> nextcloud:13.0.1-apache
**Nextcloud version:** (see Nextcloud admin page)
nextcloud:12.0.4-apache -> nextcloud:13.0.1-apache
**Updated from an older Nextcloud/ownCloud or fresh install:**
nextcloud:12.0.4-apache -> nextcloud:13.0.1-apache

**Comment by J0WI** [comment]
Closing since the version is EOL.
