### ISSUE TITLE
all apps does not work on example docker-compose (fpm+nginx)

### ISSUE THREAD

**Issue by allustin** [nextcloud/docker#391]
steps to reproduce

* get https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/postgres/fpm/docker-compose.yml
* docker-compose build
* docke-compose up
* login and register
* install random app (for example mail, calendar, mind,map, etc

and you get

> Refused to execute script from localhost:8080
> because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
> 

in Chrome Dev Console

and icon for apps will be disabled

![default](https://user-images.githubusercontent.com/55323/42716300-870036f0-8703-11e8-9ee6-e191fae2c2b5.png)

**Comment by claudiobianco** [comment]
We had a similar issue.
I'm still not sure which part is to blame (probably me).

Our setup was a bit different though. We mounted the `custom_apps` folder explicitly which resulted in it being outside the root folder from nginx.
When nginx could not find the file it redirected to the index.php file (hence the html MIME type).

Anyway I just followed your steps and it works for me (on Ubuntu 18.04).
Can you check, that your `custom_apps` folder is writable and whether the installed app is in there?

For me it is in `ls -la /var/lib/docker/volumes/nextcloud_nextcloud/_data/custom_apps`

**Comment by allustin** [comment]
@claudiobianco all installed app is in there (in the mount folder) and it writable, for example

> ls -al custom_apps/mindmaps/img/
total 48
drwxr-xr-x 2 www-data www-data 4096 Jul 13 21:48 .
drwxr-xr-x 9 www-data www-data 4096 Jul 13 21:48 ..
-rw-r--r-- 1 www-data www-data 5461 Jul 13 21:48 app.svg
-rw-r--r-- 1 www-data www-data 4995 Jul 13 21:48 favicon-touch.png
-rw-r--r-- 1 www-data www-data 4072 Jul 13 21:48 favicon-touch.svg
-rw-r--r-- 1 www-data www-data 4286 Jul 13 21:48 favicon.ico
-rw-r--r-- 1 www-data www-data 1294 Jul 13 21:48 favicon.png
-rw-r--r-- 1 www-data www-data 5582 Jul 13 21:48 favicon.svg

i think it is nginx issue 

i find this https://help.nextcloud.com/t/solved-all-extra-apps-fails-to-load-due-to-mime-type-mismatch/21111

still work to find fix for that issue ;-)

**Comment by allustin** [comment]
i found what wrong - docker volumes !!!

if you use multi-volume https://github.com/nextcloud/docker#persistent-data for each dir

* you must mount volume in nginx similar like in app
* full data dir must be last in mount order

@claudiobianco thanks for idea
