### ISSUE TITLE
USE_ZEND_ALLOC=0 to mitigate SIGSEGV in zend_hash_str_find()

### ISSUE THREAD

**Issue by ghost** [nextcloud/docker#393]
A [known php allocator bug](https://bugs.php.net/bug.php?id=75375) causes occasional crashes of PHP unless USE_ZEND_ALLOC=0 is set in the environment. A [reproducer was provided yesterday](https://github.com/nextcloud/server/issues/10241) and will hopefully allow this rather old problem to be fixed.

In the meantime I suggest USE_ZEND_ALLOC=0 is set to mitigate the problem.

**Comment by pierreozoux** [comment]
Could you try to report the bug on the upstream php base image? We use the base php image, and I have the feeling that this could be part of the default php image.
