### ISSUE TITLE
Deploying Nextcloud via AWS (Fargate + S3 + RDS)

### ISSUE THREAD

**Issue by mtimyself** [nextcloud/docker#394]
I have only used NC on a classic bare metal or VM setup so far.
Now I am looking to deploy another environment and I am revisiting my choices in this regard as this seems somewhat antiquated with the possibilities that AWS holds.

In my current use case I do not see an argument for a dockerized setup that is still hosted on a VM, such as a simple EC2 instance. If I want to make use of this technology it needs to make that instance obsolete as capsuling applications on a multi-tenant server is not a concern and I can not see any other reason or advantage of using docker images.
Judging by the documentation I can foresee that there will be the question of proxy'ing the actual webserver requests and HTTPS setup.
What I am wondering about most of all though is the actual practical implication of using AWS ECS to not deploy docker images to an EC2 instance but rather to AWS Fargate in order to make it a "stand-alone" setup, detached from the need for an EC2 instance which could host the entire shebang anyway.

How would I provide it with a DB and Storage mount point?
Can I utilize AWS RDS to provide the DB?
Can I use AWS EBS to mount the Storage? Would there be a way to utilize S3 (Object Storage) as the primary storage location (on an EC2 instance I could for example mount it via "S3FS")?

If this is not possible to execute could anyone please point me to a best practice scenario of how to setup your NC environment in 2018 with cost efficiency and scalability in mind.

**Comment by pierreozoux** [comment]
Hehe, this looks like a cool setup :)

But to be honest, I'm not sure you'll find a lot of people hosting Nc on AWS (but maybe I'm wrong). I think that because of privacy reasons.

For your setup, I'd advise  using cloud formation, with aurora, and s3, and I'm sure you can use cloudfront in front of it for the https part.

If you make a cloud formation template, ping me here, and I'm sure Nc will like to share your work with others.

If you need help specific to docker, please ask here.

In the mean time, I close this issue, as not directly related to docker.

**Comment by jverhoeks** [comment]
We have researched this idea. But Nextcloud needs a persistence storage for /var/www/html. 
And that's not yet possible in Fargate. Also, it's not possible to use nfs-client or s3fs from inside the container as they require CAP_SYSADMIN, which is also blocked by fargate.

**Comment by pierreozoux** [comment]
I think it is not an issue.
Modify the docker image to remove the need for persistent storage.
And configure Nextcloud to use s3.
https://docs.nextcloud.com/server/12/admin_manual/configuration_files/external_storage/amazons3.html

**Comment by mtimyself** [comment]
How would I go about disabling the need for persistent storage in the docker image?
I have experienced no issues running NC on an EC2 instance using S3 as storage backend and Aurora as the DB. The last component missing is the ability to rid myself of the EC2 entirely as host nginx via Fargate.
This means that all components would be compartmentalized and not bound to a "classic" VM.

**Comment by pierreozoux** [comment]
You could use the Apache Version instead of nginx. If not, you'll have to put assets (css, js..) in nginx container.

**Comment by markuman** [comment]
> I think it is not an issue.
> Modify the docker image to remove the need for persistent storage.
> And configure Nextcloud to use s3.
> https://docs.nextcloud.com/server/12/admin_manual/configuration_files/external_storage/amazons3.html

that's wrong! What you want is to change the primary storage to use S3.
https://docs.nextcloud.com/server/13/admin_manual/configuration_files/primary_storage.html

you need to edit the `config/config.php` in the docker container. that might be work using fargate. next to S3 and fargate, consider to use mysql aurora serverless and you're 100% serverless.

But that might be nor the cheapest setup nor the best for your privacy (just my two cents).

**Comment by pierreozoux** [comment]
> you need to edit the config/config.php
comfigmap looks like a good candidate for that job
