### ISSUE TITLE
Nextcloud database exception after update

### ISSUE THREAD

**Issue by steglicd** [nextcloud/docker#395]
I have set up my nextcloud like this:
```
docker network create extern
docker run --name nginxproxy --network=extern -v /var/run/docker.sock:/tmp/docker.sock:ro -p 80:80 -p 443:443 -v dhparam:/etc/nginx/dhparam -v nginxproxy_certs:/etc/nginx/certs:ro -v nginxproxy_vhosts:/etc/nginx/vhost.d -v nginxproxy_html:/usr/share/nginx/html --label com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true -d  jwilder/nginx-proxy
docker run --name ngnix_le_comp -v /var/run/docker.sock:/var/run/docker.sock:ro -v nginxproxy_certs:/etc/nginx/certs:rw --volumes-from nginxproxy -d jrcs/letsencrypt-nginx-proxy-companion 
docker run --name cloudsql --network=extern -v cloudsql:/var/lib/mysql -e "MYSQL_ROOT_PASSWORD=****" -e "MYSQL_DATABASE=****" -e "MYSQL_USER=****" -e "MYSQL_PASSWORD=****" -d  mysql
docker run --name nextcloud --network=extern -v cloudstorge:/var/www/html -e "VIRTUAL_HOST=example.com" -e "LETSENCRYPT_HOST=example.com" -e "LETSENCRYPT_EMAIL=foo@example.com" -d nextcloud
```

Now I keep the container up-to-date with watchtower. Yesterday the container was restarted by watchtower for an update.

Now Nextcloud doesn't work anymore:
```
[Sun Jul 22 09:58:10.618581 2018] [php7:error] [pid 32] [client 1.2.3.4:43910] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2006] MySQL server has gone away in /var/www/html/lib/private/DB/Connection.php:64\nStack trace:\n#0 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/html/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Configuration),  in /var/www/html/lib/private/DB/Connection.php on line 64
```

**Comment by steglicd** [comment]
Commandline isn't working either:
```
php occ help
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2006] MySQL server has gone away in /var/www/html/lib/private/DB/Connection.php:64
Stack trace:
#0 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/html/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/html/lib/private/DB/ConnectionFactory.php(152): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/html/lib/private/Server.php(628): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OCP\\IDBConnecti...')
#10 /var/www/html/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IDBConnecti...')
#11 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(164): OC\ServerContainer->query('OCP\\IDBConnecti...')
#12 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#13 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('DatabaseConnect...')
#14 /var/www/html/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#15 /var/www/html/lib/private/Server.php(1511): OC\ServerContainer->query('DatabaseConnect...')
#16 /var/www/html/lib/private/Server.php(332): OC\Server->getDatabaseConnection()
#17 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#18 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OC\\Authenticati...')
#19 /var/www/html/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#20 /var/www/html/lib/private/Server.php(336): OC\ServerContainer->query('OC\\Authenticati...')
#21 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#22 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OC\\Authenticati...')
#23 /var/www/html/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#24 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(164): OC\ServerContainer->query('OC\\Authenticati...')
#25 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#26 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OC\\Authenticati...')
#27 /var/www/html/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#28 /var/www/html/lib/private/Server.php(352): OC\ServerContainer->query('OC\\Authenticati...')
#29 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#30 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OCP\\IUserSessio...')
#31 /var/www/html/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OCP\\IUserSessio...')
#32 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(164): OC\ServerContainer->query('OCP\\IUserSessio...')
#33 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#34 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('UserSession')
#35 /var/www/html/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#36 /var/www/html/lib/private/Server.php(1380): OC\ServerContainer->query('UserSession')
#37 /var/www/html/lib/private/Server.php(688): OC\Server->getUserSession()
#38 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#39 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('OC\\App\\AppManag...')
#40 /var/www/html/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\App\\AppManag...')
#41 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(164): OC\ServerContainer->query('OC\\App\\AppManag...')
#42 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#43 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): Pimple\Container->offsetGet('AppManager')
#44 /var/www/html/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#45 /var/www/html/lib/private/Server.php(1684): OC\ServerContainer->query('AppManager')
#46 /var/www/html/lib/private/legacy/app.php(332): OC\Server->getAppManager()
#47 /var/www/html/lib/private/legacy/app.php(113): OC_App::getEnabledApps()
#48 /var/www/html/lib/base.php(662): OC_App::loadApps(Array)
#49 /var/www/html/lib/base.php(1081): OC::init()
#50 /var/www/html/console.php(46): require_once('/var/www/html/l...')
#51 /var/www/html/occ(11): require_once('/var/www/html/c...')
#52 {main}PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2006] MySQL server has gone away in /var/www/html/lib/private/DB/Connection.php:64
Stack trace:
#0 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/html/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration),  in /var/www/html/lib/private/DB/Connection.php on line 64
root@038aa4694baa:/var/www/html# 
```

I also tried with older versions of nextcloud and mysql. Nothing seems to work. If I set up a fresh nextcloud, the GUI shows up. If I copy my config.php from the non-working nextcloud instance - it stops working.

**Comment by ChessSpider** [comment]
lol they're pushing updates now like crazy. they just pushed another image 7 minutes ago.

**Comment by nextgen-networks** [comment]
... hmm repo update is not yet pullable

PS C:\Program Files\Docker\Kitematic> docker pull nextcloud
Using default tag: latest
latest: Pulling from library/nextcloud
Digest: sha256:9343f3dc8a15112d498fef2516a6adc423a7b51c70095c9aac77b87642c90435
Status: Image is up to date for nextcloud:latest
PS C:\Program Files\Docker\Kitematic> docker image ls
REPOSITORY                               TAG                 IMAGE ID            CREATED             SIZE
nextcloud                                latest              ce02f682625c        13 hours ago        544MB

**Comment by nextgen-networks** [comment]
Hmm - no watchtower has pulled latest updates tonight.

An "FrankenCloud" is not the workaround i prefer ;-)
... i'm young - i can wait for fixed images :-D

The latest updates also seem completely off the problem we discussed here - the're introducing Debian 9 Update 5 and nextcloud 13.0.5 only but no bugfix for the database connection problem.

**Comment by ChessSpider** [comment]
Haha it actually is less frankencloud than you might expect, due to the way
volumes are used within nextcloud. But preferable, it is not.
Let's hope they fix it soon.


Op di 24 jul. 2018 12:51 schreef Nextgen-Networks <notifications@github.com

**Comment by nextgen-networks** [comment]
.. some more info why php could not be updated/reinstalled in standard config:
https://github.com/docker-library/docs/pull/1111/commits/aab8b5b1dce19e7d2459a908f1f130d56a14807b

... was not aware of this setting.

**Comment by tilosp** [comment]
To me this looks like https://github.com/nextcloud/server/issues/8863 and not directly related to the docker image.

**Comment by nextgen-networks** [comment]
@tilosp 
But why does it connect to database when using it with an older nextcloud image (e.g. 13.0.3)?
It also worked on 13.0.4 until an update of the container 2 days ago.

**Comment by ChessSpider** [comment]
@tilosp I can assure it is an issue with the image. Downgrading to the 13.0.3-fpm  base image with the source code of 13.0.5 fixed it for me immediately. 

**I am currently running Nextcloud (or FrankenCloud) 13.0.5 with the base-image (and thus their PHP-version+dependencies of) version of 13.0.3-fpm.**. I am able to run 13.0.5 as I started the 13.0.5 image earlier, which copies its source-code into the docker volume using the entrypoint.sh script. So the source-code in the volume was already 13.0.5, and the webgui then prompted me to upgrade to 13.0.5 (it was on 13.0.4 before). 

Unfortunately I don't know what it could be specifically. My stack trace is basically the same:

``
app_1    | [24-Jul-2018 08:28:51] WARNING: [pool www] child 77 said into stderr: "Stack trace:"
app_1    | [24-Jul-2018 08:28:51] WARNING: [pool www] child 77 said into stderr: "#0 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()"
app_1    | [24-Jul-2018 08:28:51] WARNING: [pool www] child 77 said into stderr: "#1 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()"
app_1    | [24-Jul-2018 08:28:51] WARNING: [pool www] child 77 said into stderr: "#2 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()"
app_1    | [24-Jul-2018 08:28:51] WARNING: [pool www] child 77 said into stderr: "#3 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()"
app_1    | [24-Jul-2018 08:28:51] WARNING: [pool www] child 77 said into stderr: "#4 /var/www/html/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)"
app_1    | [24-Jul-2018 08:28:51] WARNING: [pool www] child 77 said into stderr: "#5 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(173): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Dri..."
``

I am running MySQL 8.0.11. 

I am 99,99% certain it hangs on the ``connect()`` call. Not on any queries or anything.

**Comment by tilosp** [comment]
The update 2 days ago was caused by and update to the php base image. See: https://github.com/docker-library/official-images/pull/4622

And the only thing that was changed was the php version form `7.1.19` to `7.1.20`. See: https://github.com/docker-library/php/compare/b599d7375c12ff69e4d11ea10c3dea56dd670eb9...d6b950cc18b2977a96f472345024bed00cd07814

**Comment by ChessSpider** [comment]
From my limited knowledge it seems that PHP is the most likely culprit; I followed the stacktrace of Doctrine DBAL and I didn't see anything weird. I commented out the logic create a Transaction, only to have it fail on the first ``select * from oc_apps`` or whatever table it was. A query which, when I ran it manually on the DB, took 0.00s to complete. 

With fail I mean that it was running that specific query twice, hanging for 10 seconds each, and then it failed. It always failed consistently after 20 seconds. 

Interesting.

**Comment by nextgen-networks** [comment]
... ma stack trace looks absolutely similar to ChessSpider's:
```
Tue Jul 24 13:03:35.163663 2018] [php7:error] [pid 30] [client 172.18.0.xx:xxxxx] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2006] MySQL server has gone away in /var/www/html/lib/private/DB/Connection.php:64
Stack trace:
#0 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()
#1 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()
#2 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()
#3 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()
#4 /var/www/html/lib/private/DB/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)
#5 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Configuration),  in /var/www/html/lib/private/DB/Connection.php on line 64
```

**Comment by tilosp** [comment]
@nextgen-networks what version of mysql are you running

**Comment by nextgen-networks** [comment]
@tilosp I'm running 8.0.11 too
(docker run --name nextgen-mysql01 --network=le_ext -e MYSQL_ROOT_PASSWORD=*** --mount source=nextgen-mysql01_db,target=/var/lib/mysql --restart always -d mysql:latest)

**Comment by ChessSpider** [comment]
oh by the way, docker tag mysql:8.0.11 was only added 2 days ago. One might think it could also be mysql related.

However, mysql:latest and mysql:8 were both pushed 7 days. These are the versions nextgen-networks and I are running, so the failure weren't introduced by the latest mysql image.

**Comment by nextgen-networks** [comment]
I'm using mysql 8.0.11 since 2018-07-17T 23:26:42Z without any problems.

**Comment by tilosp** [comment]
This seems to be caused by the combination of php 7.1.20 and mysql. 
If i try to setup a new instance with the current image and mysql i get an error. If i try the same with mariadb it works fine.

But there is currently not much i can do about this.
The examples use mariadb or postgres, both working just fine.

**Comment by nextgen-networks** [comment]
@tilosp followed your "hint" and created an MariaDB container, imported the database and got the exact same connection errors like with MySQL.

Could you create an test setup to verify this db is also affected?

Thanks!

**Comment by ChessSpider** [comment]
For solution, see https://help.nextcloud.com/t/nextcloud-13-php-7-1-mysql-8-error-500/34443/4

aka

> Spot on glycoknob !!!
> 
> ``` 
> [mysqld]
>  default_authentication_plugin=mysql_native_password
> ```
> 
> That fixed my setup.
> 
> Thank you very much indeed !!!

**Comment by steglicd** [comment]
Unfortunately I've set up a fresh environment from scratch (by using a older version of the mysql container) and migrated the data to the new nextcloud. So I cannot test the solution but if anyone can confirm the solution I would propose to close this issue. Thanks to @ChessSpider

**Comment by ChessSpider** [comment]
The solution they provided works for me :) 
I am back on Nextcloud docker latest

**Comment by jmccoy555** [comment]
Worked for me, added the below to my mysql compose file;

`command: --default_authentication_plugin=mysql_native_password`
