### ISSUE TITLE
Unable to update - Nextcloud stays at 13.0.2

### ISSUE THREAD

**Issue by monreal** [nextcloud/docker#396]
My setup is based on docker/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/

It works great but I am unable to update to newer Nextcloud releases beyond the currently running 13.0.2. The Dockerfile for "app" references "FROM nextcloud:fpm" which should - as far as I can see - pull in 13.0.4 right now. I even changed this to "FROM nextcloud:13.0.4-fpm" and ran the usual "docker-compose build --pull". It pulls in updates to the image but after Nextcloud is started I can see it is still at 13.0.2.

Any idea what could be wrong? Are there any manual steps required to actually update the Nextcloud version?

**Comment by tilosp** [comment]
```bash
$ docker-compose pull
$ docker-compose build --pull
$ docker-compose up -d
```
have you run these 3 commands?

**Comment by monreal** [comment]
I was missing the "docker-compose up -d"... as my script ends with a full system reboot and the containers are started automatically I assumed incorrectly the "up -d" was not needed. Thanks for pointing out!
