### ISSUE TITLE
Example docker-compose and with-nginx-proxy and mariadb and fpm doesn't work for me

### ISSUE THREAD

**Issue by freeroot** [nextcloud/docker#409]
I followed https://github.com/nextcloud/docker/tree/master/.examples#with-nginx-proxy with files in .examples/docker-compose/with-nginx-proxy/mariadb/fpm

VIRTUAL_HOST=localhost
LETSENCRYPT_HOST=localhost
LETSENCRYPT_EMAIL= I enter a valid email
MYSQL_ROOT_PASSWORD= I enter the valid password
MYSQL_PASSWORD=I  choose a password for the database user nextcloud in db.env

On http://localhost/ I can install nextcloud by creating an admin user and connect with it.
but 
https://localhost/ doesn't work and Firefox display "Secure Connection Failed"

I tried then to connect from my phone with the nextcloud app on lan with ip adress but alert something like "server maintenance".

How can I fix it ?

**Comment by SnowMB** [comment]
The nginx proxy + letsencrypt companion does not work for a local setup. You need a domain and your server must be reachable by that domain name to get your certificates automatically. If you want a local setup, you have to ditch letsencrypt. 

Use examples from [insecure](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/insecure) instead.

**Comment by SnowMB** [comment]
There is not really a practical way. HTTPS requires a trusted CA (Certificate Authority) to sign your certificate. In theory you can always use self-signed certificates, but modern browsers will warn their users that the certificates are not trusted. 

If you have no internet access you can either ditch https (and live with the insecure connection warning) or use self signed certificates and live with another warning (untrusted).

The only (but not in any way recommended) way would be to install your certificates in the os or browser certificate storage of each client. But this imposes a huge security risk and is not practical at all. 

So I would stick to either using just http or self-signed https and ignore the warnings.

**Comment by freeroot** [comment]
Thx.

Still with insecure example, I tried to connect from my phone on LAN by firefox instead of by the app and it displays an error message with the way to succeed to connect : add "trusted_domains" (for me "ip:port") in config/config.php. So, now, I can connect with the app on LAN too.

Still insecure, I prefer to not use https no properly and stay at LAN step for the moment because a domain name is required to have a certificate signed by a CA, what I didn't know.

Thanks for your many advice and informations.

**Comment by hlvs44** [comment]
Hi,
I'd found a solution duplicating docker container: one called "nextcloud" and one "nextlocal", sharing some volumes:

---------------

version: "2"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1002 #change PUID if needed (valori di docker1!)
      - PGID=100  #change PGID if needed (id docker1)
      - TZ=Europe/Rome #change Time Zone if needed
    volumes:
      - /srv/disk1/appdata/nextcloud/config:/config #<----------------!!!!!
      - /srv/disk1/appdata/nextcloud/data:/data
      - /srv/disk1/appdata/nextcloud/apps:/apps
      - /srv/disk1/appdata/nextcloud/theme:/theme
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: nextclouddb
    environment:
      - PUID=1002 #change PUID if needed
      - PGID=100  #change PGID if needed
      - MYSQL_ROOT_PASSWORD=dfjk6jiI8  #change password
      - TZ=Europe/Rome #Change Time Zone if needed
    volumes:
      - /srv/disk1/appdata/nextclouddb:/config    #/srv/dev-disk-by-label-disk1 needs to be adjusted
    restart: unless-stopped
  nextlocal:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextlocal
    environment:
      - PUID=1002 #change PUID if needed (valori di docker1!)
      - PGID=100  #change PGID if needed (id docker1)
      - TZ=Europe/Rome #change Time Zone if needed
    volumes:
      - /srv/disk1/appdata/nextlocal/config:/config #<----------------!!!!!
      - /srv/disk1/appdata/nextcloud/data:/data
      - /srv/disk1/appdata/nextcloud/apps:/apps
      - /srv/disk1/appdata/nextcloud/theme:/theme
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: nextclouddb
    environment:
      - PUID=1002 #change PUID if needed
      - PGID=100  #change PGID if needed
      - MYSQL_ROOT_PASSWORD=xxxxxx  #change password
      - TZ=Europe/Rome #Change Time Zone if needed
    volumes:
      - /srv/disk1/appdata/nextclouddb:/config    #/srv/dev-disk-by-label-disk1 needs to be adjusted
    restart: unless-stopped

  swag:
    image: linuxserver/swag         #swag is the replacement for letsencrypt (see link below)
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1002 #change PUID if needed
      - PGID=100  #change PGID if needed
      - TZ=Europe/Rome # change Time Zone if needed
      - URL=xxxxxxxxxxxxxxx #insert your domain name - yourdomain.url
      - SUBDOMAINS=
      - VALIDATION=http
      - EMAIL=xxxxxxxxxx # define email; required to renew certificate
    volumes:
      - /srv/disk1/appdata/swag:/config  #/srv/dev-disk-by-label-disk1 needs to be adjusted
    ports:
      - 453:443
      - 90:80
    restart: unless-stopped


----------

**swag/nginx/proxy-confs:**


location = /.well-known/carddav {
    return 301 $scheme://$host/nextcloud/remote.php/dav;
}

location = /.well-known/caldav {
    return 301 $scheme://$host/nextcloud/remote.php/dav;
}

location /nextcloud {
    return 301 $scheme://$host/nextcloud/;
}

location ^~ /nextcloud/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app nextcloud;
    set $upstream_port 443;
    set $upstream_proto https;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;

    rewrite /nextcloud(.*) $1 break;
    proxy_max_temp_file_size 2048m;
    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;
    proxy_redirect off;
    proxy_ssl_session_reuse off;
}

location ^~ /nextlocal/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app nextlocal;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;

    rewrite /nextlocal(.*) $1 break;
    proxy_max_temp_file_size 2048m;
    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;
    proxy_redirect off;
    proxy_ssl_session_reuse off;
}

---------------

**Ando so I have two different "config.php" in two different containers; the one referred to "nextcloud" container with "trusted_proxies" and "trusted_domains" and one with no such directives:**

  'trusted_proxies' => 
  array (
    0 => 'swag',
  ),

  'trusted_domains' => 
  array (
    0 => 'xxxxx.xxxx.xxx',
  ),
`

**Comment by hlvs44** [comment]
Hi,
I'd found a solution duplicating docker container: one called "nextcloud" and one "nextlocal", sharing some volumes:

---------------

version: "2"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1002 #change PUID if needed (valori di docker1!)
      - PGID=100  #change PGID if needed (id docker1)
      - TZ=Europe/Rome #change Time Zone if needed
    volumes:
      - /srv/disk1/appdata/nextcloud/config:/config
      - /srv/disk1/appdata/nextcloud/data:/data
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: nextclouddb
    environment:
      - PUID=1002 #change PUID if needed
      - PGID=100  #change PGID if needed
      - MYSQL_ROOT_PASSWORD=dfjk6jiI8  #change password
      - TZ=Europe/Rome #Change Time Zone if needed
    volumes:
      - /srv/disk1/appdata/nextclouddb:/config    #/srv/dev-disk-by-label-disk1 needs to be adjusted
    restart: unless-stopped
  nextlocal:
    image: ghcr.io/linuxserver/nextcloud
    container_name: nextlocal
    environment:
      - PUID=1002 #change PUID if needed (valori di docker1!)
      - PGID=100  #change PGID if needed (id docker1)
      - TZ=Europe/Rome #change Time Zone if needed
    volumes:
      - /srv/disk1/appdata/nextlocal/config:/config
      - /srv/disk1/appdata/nextlocal/data:/data
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: nextclouddb
    environment:
      - PUID=1002 #change PUID if needed
      - PGID=100  #change PGID if needed
      - MYSQL_ROOT_PASSWORD=xxxxxx  #change password
      - TZ=Europe/Rome #Change Time Zone if needed
    volumes:
      - /srv/disk1/appdata/nextclouddb:/config    #/srv/dev-disk-by-label-disk1 needs to be adjusted
    restart: unless-stopped

  swag:
    image: linuxserver/swag         #swag is the replacement for letsencrypt (see link below)
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1002 #change PUID if needed
      - PGID=100  #change PGID if needed
      - TZ=Europe/Rome # change Time Zone if needed
      - URL=xxxxxxxxxxxxxxx #insert your domain name - yourdomain.url
      - SUBDOMAINS=
      - VALIDATION=http
      - EMAIL=xxxxxxxxxx # define email; required to renew certificate
    volumes:
      - /srv/disk1/appdata/swag:/config  #/srv/dev-disk-by-label-disk1 needs to be adjusted
    ports:
      - 453:443
      - 90:80
    restart: unless-stopped


----------

**swag/nginx/proxy-confs:**


location = /.well-known/carddav {
    return 301 $scheme://$host/nextcloud/remote.php/dav;
}

location = /.well-known/caldav {
    return 301 $scheme://$host/nextcloud/remote.php/dav;
}

location /nextcloud {
    return 301 $scheme://$host/nextcloud/;
}

location ^~ /nextcloud/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app nextcloud;
    set $upstream_port 443;
    set $upstream_proto https;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;

    rewrite /nextcloud(.*) $1 break;
    proxy_max_temp_file_size 2048m;
    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;
    proxy_redirect off;
    proxy_ssl_session_reuse off;
}

location ^~ /nextlocal/ {
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;
    set $upstream_app nextlocal;
    set $upstream_port 80;
    set $upstream_proto http;
    proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    proxy_set_header        X-Real-IP $remote_addr;
    proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header        X-Forwarded-Proto $scheme;

    rewrite /nextlocal(.*) $1 break;
    proxy_max_temp_file_size 2048m;
    proxy_set_header Range $http_range;
    proxy_set_header If-Range $http_if_range;
    proxy_redirect off;
    proxy_ssl_session_reuse off;
}

---------------

**Ando so I have two different "config.php" in two different containers; the one referred to "nextcloud" container with "trusted_proxies" and "trusted_domains" and one with no such directives:**

  'trusted_proxies' => 
  array (
    0 => 'swag',
  ),

  'trusted_domains' => 
  array (
    0 => 'xxxxx.xxxx.xxx',
  ),
`

Indicating the same DB name documents and users settings should be shared.

from localhost you can access pointing the browser to the "nextlocal" container ip (172.18.0.6 in my case).

First time you must indicate a different new nextcloud user name for the second container.
