### ISSUE TITLE
docker-compose error, no ssl, no db connection 

### ISSUE THREAD

**Issue by rinik1** [nextcloud/docker#410]
Hi guys,

I am using the selfsigned docker-compose example.

When I run the compose I get following error:
`nextcloud2_omgwtfssl_1 exited with code 0
db_1         | 2018-08-03 22:21:53 0 [Note] InnoDB: Buffer pool(s) load completed at 180803 22:21:53
proxy_1      | dockergen.1 | 2018/08/03 22:21:53 Received event start for container 0566a8550ac7
proxy_1      | dockergen.1 | 2018/08/03 22:21:53 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
`
Do I need to change anything else besides password and VIRTUAL_HOST= ?

I can reach nextcloud by 'localhost' without https. But there I get an error with the db connection:
`[Warning] Access denied for user 'nextcloud'@'172.18.0.3' (using password: YES)`

**Comment by SnowMB** [comment]
What is the domain name you used? Make sure that it is an actual domain you own and the server is reachable via this name.

For more detailed information it would be helpful if you post the `docker-compose.yml` you have used (without your personal information).

You can also have a look at #409

**Comment by rinik1** [comment]
@SnowMB Thanks.

To my understanding the ''with-nginx-proxy-self-signed-ssl/mariadb/fpm/" should work without a domain. Am I wrong? When using 'localhost' I can reach the app but without https. If I enter a random IP it doesn't work.

`version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
    env_file:
      - db.env

  app:  
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/media/nextcloud
    environment:
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db

  web:
    build: ./web
    restart: always
    volumes:
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=localhost
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - omgwtfssl

  omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=servhostname.local
      - CA_SUBJECT=my@example.com
      - SSL_KEY=/certs/servhostname.local.key
      - SSL_CSR=/certs/servhostname.local.csr
      - SSL_CERT=/certs/servhostname.local.cert
    networks:
      - proxy-tier

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:`

**Comment by SnowMB** [comment]
OK now i know what you are trying to do 😁 . 

The nginx proxy needs to know which are the certificates. It is done by simple name matching. You have to change their names accordingly.  (see https://github.com/jwilder/nginx-proxy#ssl-support)

So try this: (it might be better to use a network name instead of localhost)

```yaml
omgwtfssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=servhostname.local
      - CA_SUBJECT=my@example.com
      - SSL_KEY=/certs/localhost.key
      - SSL_CSR=/certs/localhost.csr
      - SSL_CERT=/certs/localhost.crt
    networks:
      - proxy-tier
```

**Comment by rinik1** [comment]
@SnowMB 
That was indeed the missing piece. Works now with https. Thanks a lot.
