### ISSUE TITLE
Let's Encrypt certificate expiration notice 

### ISSUE THREAD

**Issue by kowjens** [nextcloud/docker#411]
Lately I received a mail saying my “Let’s encrypt” certificate is running out in a few days.

“Your certificate (or certificates) for the names listed below will expire in 10 days (on 08 Aug 18 14:07 +0000). Please make sure to renew your certificate before then, or visitors to your website will encounter errors.”

I set up my nextcloud according to following link and up to now everything was working quiet well:
[nginx-mariadb-cron-redis](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml)

Is it going to renew automatically or do I have to or can I do something to renew manually in cases the auto-renew doesn’t work? 

Thanks everybody in advance for hints.

**Comment by SnowMB** [comment]
They should be automatically renewed. However in the past I experienced some bugs with the letsencrypt companion, so depending on how old your image is you could check for certificate status or manually trigger a renewal:

```shell
docker-compose exec letsencrypt-companion /app/cert_status

docker-compose exec letsencrypt-companion /app/force_renew
```

See the [here](https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion#force-certificates-renewal) for additional information.

**Comment by kowjens** [comment]
Hey SnowMB,
thanks a lot for the help and link. Makes my day :) That looks exactly like what I’ve been looking for. I’ll try this in the evening and leave a comment if and what worked for me. For now I’ll close this as solved.
Thanks und enjoy the day
cheers
