### ISSUE TITLE
APCu not enabled?

### ISSUE THREAD

**Issue by ksala** [nextcloud/docker#415]
Okay, this might be a dumb question, so sorry in advance.
On my installation (using the Apache docker image) I still have the warning about no cache being configured in the "Security & setup warnings" section of the admin page.  

I know [this](https://github.com/nextcloud/docker/blob/master/.config/apcu.config.php) is supposed to enable APCu, and it's copied into `/usr/src/nextcloud/config/` from the [Dockerfile](https://github.com/nextcloud/docker/blob/master/13.0/apache/Dockerfile#L136).

But is that the correct path? I just copied it into `/var/www/html/config` and the warning went away. Nextcloud also feels faster, but it could be just placebo effect.

**Comment by SnowMB** [comment]
Yeah it is correct. For new instances we add an additional config file with the same lines in it, but if you have migrated your nextcloud or started with an early version of the image, it could be missing. You have to insert the lines by hand.

See https://github.com/nextcloud/docker/blob/master/.config/apcu.config.php

**Comment by ksala** [comment]
Yeah, that must be it. I just tried bringing up really quick a fresh instance and it worked great out of the box.
Thanks!
