### ISSUE TITLE
Stuck in maintenance mode after switching to 14

### ISSUE THREAD

**Issue by schliflo** [nextcloud/docker#417]
After switching to 14 and running `occ upgrade` in the container I'm stuck in maintenance mode with the following error:
```
InvalidArgumentException: Index name "oc_notes_meta"."notes_meta_file_id_user_id_index" is too long.
```

I wasn't sure where to report this (server, notes or here?)

**Comment by tilosp** [comment]
Duplicate of nextcloud/server#10518
