### ISSUE TITLE
HTTPS not working in self signed example

### ISSUE THREAD

**Issue by skvl** [nextcloud/docker#419]
Hello.

I have tried to build an [example](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm) (commit `c82c9fb70547228db1d8e245dd26dd00db0e671a`).

HTTP works just fine. But there is no HTTPS page (`Unable to connect` in Firefox).

The most strange thing to me is that there is no SSL section in `nginx.conf`.

Thank you.

**Comment by tilosp** [comment]
It works if you set all the vars and replace `servhostname.local` with your domain.
