### ISSUE TITLE
Strict-Transport-Security

### ISSUE THREAD

**Issue by umardraz** [nextcloud/docker#421]
Hello,

The basic setting indicating that **Strict-Transport-Security** header is not set in apache configuration, is it possible we can define this through environment variable or any other way?

> The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the security tips.

**Comment by GammaPi** [comment]
Hi, I'm here to help.
This HSTS is just a header, so if you are using nginx like me, you can solve this simply by adding the following code into nextcloud nginx configruation

add_header Strict-Transport-Security "max-age=15552000";

**Comment by tilosp** [comment]
If you use [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) the header should be present (See: https://github.com/jwilder/nginx-proxy#ssl-support)

**Comment by umardraz** [comment]
I think my question was how I can set environment variable for this HSTS header while creating my docker container.

I know about this HSTS and also knows how and where to set

**Comment by tilosp** [comment]
No there is no such environment variable. All existing environment variables are listed in the [README.md](https://github.com/nextcloud/docker/blob/master/README.md)

**Comment by hannut** [comment]
Anyone know how to do this with the apache -image?
