### ISSUE TITLE
Could not resolve host: www.github/google/nextcloud.com in logger

### ISSUE THREAD

**Issue by harkor** [nextcloud/docker#425]
Hi,

I installed nextcloud:apache with docker-compose yesterday.
NextCloud 13.0.5.

I saw that in the logger section and it's weird.

![image](https://user-images.githubusercontent.com/1044182/44252148-854bca00-a1fb-11e8-8c32-a6698ebd58b9.png)

> This server has no working Internet connection: Multiple endpoints could not be reached. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. Establish a connection from this server to the Internet to enjoy all features.

I can access to nextcloud from outside and inside network without problem.

Any clue ?

**Comment by harkor** [comment]
Mmmh if I understand, I need to have SSL configuration.

But I can't have nextcloud on port 80 & 443, In my setup I have 1563 (random port) and in my real apache server, I have a proxypass 80 > 1563 and 443 > 1564

I'm a beginner with docker and with examples, I don't understand how to do to make it work.

`version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=coucouhiboucoucou
    env_file:
      - db.env

  app:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./data:/var/www/html/data
    environment:
      - VIRTUAL_HOST=nextcloud.harkor.be
      - LETSENCRYPT_HOST=nextcloud.harkor.be
      - LETSENCRYPT_EMAIL=julien@harkor.be
      - MYSQL_HOST=db
    env_file:
      - db.env
    depends_on:
      - db
    ports:
      - 1565:80
      - 1566:443
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 1563:1565
      - 1564:1566
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
`

**Comment by harkor** [comment]
I found solution, it was a problem with resolv.conf.

I added on docker-compose.yml

dns:
  - 8.8.8.8

and all is fine :)

**Comment by bitdegree67** [comment]
Cause you're using Ubuntu 18.04, right ?

**Comment by harkor** [comment]
No the computer run on Arch.
