### ISSUE TITLE
use the same storage for temp files

### ISSUE THREAD

**Issue by Redsandro** [nextcloud/docker#430]
In the docs, you can read:

> Your temp file or partition has to be big enough to hold multiple parallel uploads from multiple users; 

So when [a volume is mounted](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml#L19) like so:

```
    volumes:
      - nextcloud:/var/www/html
```

I assume that means uploads first go to the containers `/tmp` located on docker's main storage, and then it is moved to the named volume (which might be on a different disk) creating overhead.

What directory is used for temp files in the default docker image?

**Comment by J0WI** [comment]
You can also use `docker inspect` to see the attached volumes.
