### ISSUE TITLE
Plain setup page

### ISSUE THREAD

**Issue by marvink87** [nextcloud/docker#44]
Hi there,

Sorry for bothering you guys but I've been trying to solve this on my own but I can't seem to find anything I'm doing wrong. Nor anyone who ran into a similar problem.

I've followed the example from indiehosters/nextcloud but made a few tweaks and it's booting nicely, but when I go to the web page I see the following:
![image](https://cloud.githubusercontent.com/assets/12583709/23773396/4bbc949c-051f-11e7-9baa-cd63809980f3.png)
I get the same screen with IE, chrome and chrome incognito (with extensions disabled). I verified that it wasn't my reversed proxy as when I bypass it I have the same issue.

Do you have any idea what could be the issue or what info do you need?

**Comment by ambis** [comment]
In case you are using nginx and docker compose, add volumes_from: - your-nc-fpm-name

This happens (probably) because nginx doesn't see the static files it should be serving.

**Comment by marvink87** [comment]
..., that should've been so obvious! I can't believe somewhere along the track that wouldn't be necessary. Thanks for your help, you saved me a lot of time, even though it was a moronic thing of me to do.
