### ISSUE TITLE
PROPFIND requests for /remote.php/dav/files/user

### ISSUE THREAD

**Issue by ukos-git** [nextcloud/docker#441]
I have a docker container in a kubernetes environement that is initializing in current `nextcloud:14-beta` container. One nginx proxy load balancer (here `192.168.178.100`) is pointing from "nextcloud.myserver" to  the docker host (here `192.168.178.101:port`). The docker host is then directing to the containers in `10.42.1.0`.

On the main node which is accepting the connections on port 80, I am seeing a lot of messages like this:

```
192.168.178.101 - user2 [28/Aug/2018:19:22:40 +0000] "PROPFIND /remote.php/dav/files/user2/ HTTP/1.0" 207 1092 "-" "Mozilla/5.0 (Linux) mirall/2.3.3 (Nextcloud)"
10.42.1.0 - user1 [28/Aug/2018:19:22:55 +0000] "PROPFIND /remote.php/dav/files/user1/ HTTP/1.0" 207 1071 "-" "Mozilla/5.0 (Linux) mirall/2.3.3 (Nextcloud)"
(...)
192.168.178.101 - user1 [28/Aug/2018:19:23:25 +0000] "PROPFIND /remote.php/dav/files/user1/ HTTP/1.0" 207 1071 "-" "Mozilla/5.0 (Linux) mirall/2.3.3 (Nextcloud)"
10.42.1.0 - user2 [28/Aug/2018:19:23:34 +0000] "PROPFIND /remote.php/dav/files/user2/ HTTP/1.0" 207 1130 "-" "Mozilla/5.0 (Linux) mirall/2.3.3 (Nextcloud)"
```

Is it a wanted behavior to flood the k8 log with those requests or is there something not configured correctly in my nginx?

I was thinking about making those `PROPFINDS` disappear by replying directly at the load balancer that the calendar or dav exists for certain users so that it doesn't even get directed to the main container.

Another option I can think of would be to direct those requests to a separate container in my k8 namespace that is running the another nextcloud instance that catches the requests. This would have them separated so that it doesn't influence the logs of my main app container but that seems like a workaround to me.

I'm posting this in the container section as I am targetting the k8 logs and my setup container-based.

**Comment by kevinfaguiar** [comment]
DId you find a solution to this problem?

**Comment by ukos-git** [comment]
I dropped k8.
I am currently running nextcloud on a bhyve instance and I am not looking too much into the logs anymore. Probably not the solution, you are looking for.

**Comment by godfuture** [comment]
I am interested to get these statements out of my log. Any solution?

**Comment by ukos-git** [comment]
sed 😂
