### ISSUE TITLE
Can I install ocdownloader within this docker image?

### ISSUE THREAD

**Issue by seonghobae** [nextcloud/docker#444]
Hello, I want to add the ocdownloader within this docker image. However, I could not find out how to add the youtube-dl and aria2 or curl module. How can I make it?

Seongho

**Comment by marceljd** [comment]
You have to take the Nextcloud/docker image and create a new Dockerfile. In that file you can add everything you need. See [https://github.com/nextcloud/docker/blob/master/README.md#adding-features](https://github.com/nextcloud/docker/blob/master/README.md#adding-features).

**Comment by J0WI** [comment]
Assuming that the question has been answered.
