### ISSUE TITLE
Cannot switch to /cron.sh

### ISSUE THREAD

**Issue by all-the-good-ones-are-gone** [nextcloud/docker#445]
I've had Nextcloud through docker since the examples were complete enough for me to caveman my way through it.

Recently I've been wanting to get cron to scan external media, and to that end I'm seeing tickets here where the "solution" they found were linked to [here](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml) and [here](https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/cron/fpm/supervisord.conf).
The differences I find there are:

MY docker-compose.yml:
`  cron:`
`...`
`    entrypoint: |`
`      bash -c 'bash -s <<EOF`
`        trap "break;exit" SIGHUP SIGINT SIGTERM`
`        while [ ! -f /var/www/html/config/config.php ]; do`
`          sleep 1`
`        done`
`        while true; do`
`          php -f /var/www/html/cron.php`
`          sleep 15m`
`        done`
`      EOF'`
`...`

ONLINE:
`  cron:`
`...`
`entrypoint: /cron.sh`
`...`

and 

MY supervisord.conf:
`command=cron -f`

ONLINE:
`command=/cron.sh`

I made the above changes, stopped and restarted the containers; stopped, deleted all images, and `docker-compose build --pull`; and I end up with a docker_cron_1 that constantly restarts. I also cannot locate any file named cron.sh anywhere.

Are you supposed to manually create this file? If so, where would it belong? I cannot find anything specifying.

My overall goal is to get a job into the containerized cron to run a scan on external media every `1-46/15 * * * *`.

Any ideas? I've got docker_cron_1 back to its old state for now.

**Comment by J0WI** [comment]
A better solution for you might be running `docker exec -u [user] [continer] [cmd]` from crond or systemd on your host.

**Comment by all-the-good-ones-are-gone** [comment]
Ended up starting from scratch.
