### ISSUE TITLE
PHP memory limit to 128 ?

### ISSUE THREAD

**Issue by bitdegree67** [nextcloud/docker#447]
Hello, i'm using the latest image (with nextcloud 14)
 and when i run any php occ command. i get this message
`The current PHP memory limit is below the recommended value of 512MB.`
i haven't touch the image. it's the official image from docker hub vanilla (with clean installation to mariadb)

**Comment by bitdegree67** [comment]
It's a good idea to PR this ?
RUN echo 'memory_limit = 512M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini;
in Dockerfile of NC14 ?

**Comment by bitdegree67** [comment]
@J0WI No, as i said. i've just run
docker run nextcloud
and then in this new nextcloud run "php occ" then i get the message of warning 128MB

**Comment by xXZaretXx** [comment]
@bitdegree67 
You can change it with 
`echo 'memory_limit = 512M' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini;`
inside the docker container 
but i think its temporary and hacky

**Comment by bitdegree67** [comment]
@xXZaretXx I myself proposed this solution

**Comment by xXZaretXx** [comment]
@bitdegree67  ups yes you are right , i'm blind

**Comment by ixinshang** [comment]
Hello,
i have the same problem ,someone  who can slove it. thanks.

**Comment by J0WI** [comment]
Thanks for providing the details. I can now reproduce the issue.
@tilosp since this has been added in https://github.com/nextcloud/server/pull/10539 (NC 14), should we change the defaults for the container?

**Comment by bitdegree67** [comment]
The question is why .htaccess isn't used by "php occ"

**Comment by cynecx** [comment]
@bitdegree67 It apparently still an issue with the php-fpm variant. My current solution is to have my own derived Dockerfile which simply increases the mem limit, but I think this should really be included in upstream (php-fpm and the alpine alt).

**Comment by J0WI** [comment]
There are two different checks in NextCloud:

* One is in the setting page, served through Apache or PHP-FPM and using `.htaccess` or `.user.ini`
* Another one is in the `occ` cli util (since NextCloud 14), which uses PHP defaults

You can always mount a custom `my-config.ini` file, that contains e.g. `memory_limit = 512M`, into `/usr/local/etc/php/conf.d/`.
I've created #460 to ship this setting by default.

**Comment by githubworkwork** [comment]
> pora

Thank you
