### ISSUE TITLE
Can't access the nextcloud php-fpm Container from Apache on host

### ISSUE THREAD

**Issue by MBurchard** [nextcloud/docker#45]
I hope you can help me getting the official Nextcloud container running on my ubuntu 16.04 host.

The documentation does not tell much about how to set up the reverse proxy and thus I set it up like I found it on the net. But it does not work.

Details can be found at [Stackoverflow][1]

[1]: http://stackoverflow.com/questions/42761076/cant-access-php-fpm-container-from-apache

**Comment by ambis** [comment]
I believe you don't need to map port 9000 in any way if you are using the apache version.

Only: `-p 80:80 -p 443:443`

**Comment by ambis** [comment]
Hmm. If you want to run apache locally and only run the nextcloud as PHP-FPM, you are using the wrong tag. `nextcloud:latest` is bundled with apache. See my comment above.

Use tag `nextcloud:11.0-fpm` if you setup apache/nginx yourself.

**Comment by MBurchard** [comment]
Oh, this was a misunderstanding from my site. From the docu it sounds that I have to use Port 9000 and mod_proxy_fcgi.  
Instead I now use mod_proxy_http  

        ProxyPreserveHost On
        ProxyPass "/cld" "http://127.0.0.1:8080"
        ProxyPassReverse "/cld" "http://127.0.0.1:8080"

It works fine.

Last question: If I would start not latest but 11-fpm the fcgi proxy should work?

**Comment by ambis** [comment]
>  If I would start not latest but 11-fpm the fcgi proxy should work?

PHP-FPM is a Fast CGI (fcgi) backend so... at least theorethically yes. 

I have never setup Apache with FPM so can't help you other than that, sorry.

**Comment by MBurchard** [comment]
Thank you for pointing to this information. It helped my get it running. I'm not on fcgi, so running the Apache is fine :)
