### ISSUE TITLE
Nextcloud 14.0 missing php-ldap?

### ISSUE THREAD

**Issue by ICANSEEYOU7687** [nextcloud/docker#454]
I upgraded my container, and ldap no longer works.  I think that perhaps php-ldap is missing?

**Comment by MaxNoe** [comment]
ldap works for me using `14-apache`

**Comment by ICANSEEYOU7687** [comment]
Thank you the quick reply.  The console says "Could not connect to LDAP".  However the logs say something different.

Error	no app in context	Exception: LDAP Operations error
Error	PHP	ldap_control_paged_result_response(): Result is: Operations error (1) at /var/www/html/apps/user_ldap/lib/LDAP.php#74
Warning	user_ldap	Bind failed: 49: Invalid credentials

However the credentials are correct, and account is not locked.  Something odd is going on here.  I am trying to go back to 13.0.5 by pulling it manually in docker, but the container fails to start.  Ithink 14 must have updated something in the config file.

**Comment by ICANSEEYOU7687** [comment]
This is resolved.  I am an idiot.  Password was expired, dunno how i missed that.
