### ISSUE TITLE
Fatal error: Class OC\Server contains 2 abstract methods after upgrade to 14 from version 13

### ISSUE THREAD

**Issue by hubermi** [nextcloud/docker#457]
Fatal error: Class OC\Server contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (OCP\IServerContainer::getHelper, OCP\IServerContainer::getHTTPHelper) in /var/www/html/lib/private/Server.php on line 162

**Comment by J0WI** [comment]
Closing since this version is EOL and can not be reproduced.
