### ISSUE TITLE
hub.docker.com out of sync?

### ISSUE THREAD

**Issue by mxjeff** [nextcloud/docker#46]
The git repo has been updated more than a week ago but hub.docker.com still provides n-1 version of nextcloud.

Not sure this is the right place to report it, please forward or tell where to request an update.

Cheers and thanks for the work on nextcloud docker images

**Comment by ambis** [comment]
Have been checking the same thing every day now for the last week or two.

Is the process of releasing new versions to docker hub documented anywhere?

**Comment by pierreozoux** [comment]
Fix #28, and this repo will be great again!

**Comment by jospoortvliet** [comment]
So our repo will soon be great again ;-)

I invited everyone who committed to be a collaborator/team member. @mxjeff - @ambis - do a PR, get it merged, and join the club ;-)
