### ISSUE TITLE
Missing Referrer-Policy header

### ISSUE THREAD

**Issue by k1ngf15h3r** [nextcloud/docker#461]
I think the recommended Referrer-Policy header should be added by default in the Webserver config inside the Docker image

**Comment by tilosp** [comment]
See: #450

**Comment by J0WI** [comment]
This should be fixed in the upcoming 14.0.4 release: https://github.com/nextcloud/server/pull/11798

**Comment by J0WI** [comment]
The header is now present in NC 15.
