### ISSUE TITLE
pretty urls broken after 13 -> 14 update, apache -image

### ISSUE THREAD

**Issue by hannut** [nextcloud/docker#462]
"docker-compose logs" gives the following:

AH01276: Cannot serve directory /var/www/html/apps/files/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive

**Comment by Clasko** [comment]
Append a / to your overwrite.cli.url and run "php occ maintenance:update:htaccess".
See also https://github.com/nextcloud/server/issues/10678

**Comment by hannut** [comment]
that did the trick. Thank you!

**Comment by b3** [comment]
That did not do the trick for an upragde from 13.0.6 to 14.0.1.1.
