### ISSUE TITLE
Cron example: need to make cron.sh runnable

### ISSUE THREAD

**Issue by ItalyPaleAle** [nextcloud/docker#463]
In the cron examples, it's necessary to add a command that runs `chmod +x /cron.sh`, or cron won't work.

**Comment by ItalyPaleAle** [comment]
Oh, makes sense then.

Essentially, I created my Dockerfile by forking the one in this repo because I needed to make some changes. When I created the `cron.sh` file, I didn't check the permissions of the file in the repo, and just copied the content.

May I suggest adding a comment in the Dockerfile template saying that the files have 755 permissions? I understand mine is an edge case, but it took me ~1hr to debug this :)

**Comment by J0WI** [comment]
Assuming that the questions is answered. Feel free to open a PR to enhance our docs.
