### ISSUE TITLE
Upgrade from 13 to 14 unable to login

### ISSUE THREAD

**Issue by johansmitsnl** [nextcloud/docker#465]
When upgraded from 13 to 14 it disabled many modules.
I wan unable to login with the admin account due to missing a special character. I opened the console and reset the admin password but still not able to login.
When I enabled the modules and tried to login with ldap also no luck. When I enter a wrong password it says that the password is wrong (so ldap seems ok).

`sudo -u www-data ./occ ldap:check-user myusername` says: `The given user is not a recognized LDAP user`

Logging does not show a clear error message. how to debug this issue?

Did a rollback to 13.

**Comment by J0WI** [comment]
Meanwhile both versions are EOL
