### ISSUE TITLE
Add postfix/sendmail example in docker section

### ISSUE THREAD

**Issue by Split7fire** [nextcloud/docker#467]
I'm using docker-compose on debian. With recent update to Nextcloud 14, I've got an warning regarding mail server: php method of sending no longer supported. 
So, it would be wise to add example section about using smtp server.

**Comment by J0WI** [comment]
There are some docs here: https://docs.nextcloud.com/server/14/admin_manual/configuration_server/email_configuration.html#configuring-an-smtp-server

See also #292

**Comment by J0WI** [comment]
Since Docker follows the single responsibility principle it's out of scope to add a SMTP server to the image. I'd recommend to use an external SMTP container or provider.
