### ISSUE TITLE
set nextcloud trusted domain via environment variable

### ISSUE THREAD

**Issue by mvillarejo** [nextcloud/docker#469]
Hello

I'm struggling to setup nextcloud to be accessible from the outside world because I can not setup trusted_domains within config.php file in my docker instance.

I've tried several combinations mounting remote routes (nfs) but no luck I end up having exceptions related to logging system which seems to be happening on several versions with no clear explanation about what's wrong.

said that, do you guys thing would it be possible to create (if it does not exist already) the configuration required using an environment variable?

something like: NEXTCLOUD_HOSTNAME=xxx.yyy.zzz:port 

thanks!

**Comment by mvillarejo** [comment]
Hello,

does anyone know if this queue of issues is being looked at? is the issue raised in the right queue?

thanks

**Comment by pierreozoux** [comment]
@mvillarejo could you open an issue against Nextcloud itself to just accept env variable?
https://medium.com/@kelseyhightower/12-fractured-apps-1080c73d481c
https://12factor.net/

Thanks!

This repo is a community effort, so if you have feature request, the best way to have it, is to open a PR :)

**Comment by mrtndwrd** [comment]
@mvillarejo did you end up submitting an issue against nextcloud? Can you link it? I'm running into the same problem.

**Comment by blizzz** [comment]
it can be set per occ after maintenance:install

**Comment by blizzz** [comment]
and setting trusted proxies _might_ be interesting as well. provided the IP can be determined.

**Comment by ettingshausen** [comment]
Use this command to query `trusted_domains`
```sh
docker exec --user www-data nextcloud php occ config:system:get trusted_domains
```
And set a new one:
```sh
docker exec --user www-data nextcloud php occ config:system:set trusted_domains 7 --value your.awesome.com
```
All the command can be found on the [official doc](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/occ_command.html) page.

**Comment by Yabbo** [comment]
kubectl exec --user www-data nextcloud-6786db4769-klm49 php occ config:system:get trusted_domains
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
error: auth info "www-data" does not exist

yet www-data owns the config when i look in the container.

**Comment by Kral2466** [comment]
@ettingshausen i love u mate u saved my ass
