### ISSUE TITLE
NextCloud always go to install page when I restart my docker container

### ISSUE THREAD

**Issue by nthack** [nextcloud/docker#475]
At first, I use: `docker run -d -p 8080:80 nextcloud` pull the nextcloud docker image and run it.
Then I have setup nextcloud, mariadb and admin account. And then login,  it's good.
Then I reboot my ubuntu system(without stop docker, straight reboot system).

I restart the `nextcloud` docker, using :
`docker run -d -p 8080:80 nextcloud`
to start up the `nextcloud` image again(already on my computer, not pull again), then visit :
`http://localhost:8080`
nextcloud needs to setup again, setup admin account and mariadb again.

Could someone know how to fix this? Or I did something wrong?

Environment:
`ubuntu 18`
`docker-ce`(lastest from apt install)
`mariadb 10.1`(from apt, database is good to run)

docker image:
`nextcloud`(official image)

**Comment by tilosp** [comment]
https://github.com/nextcloud/docker#persistent-data

**Comment by NorseGaud** [comment]
This should be reopened. The persistent-data url doesn't help.

**Comment by varun-ramraj** [comment]
This is affecting me too. Whenever I reboot my Raspberry Pi 3B and restart the docker containers, Nextcloud resets itself. I need to keep rescanning data with `docker exec --user abc nextcloud php /config/www/nextcloud/occ files:scan --all` and rebuilding my shares on my desktop client. I've got an external HDD connected, and it syncs/reads/writes just fine once I go through these steps.

**Comment by jjvereijken** [comment]
Same issue here, highly annoying. I sometimes need to restart the containers ten times for them to come up correctly.

**Comment by MbrCoding** [comment]
Why is that ticket closed? I use the docker image from docker hub and have the same issue. After reboot the install page appears. I can fix it with `docker-compose stop && docker-compose start`. Then my data is back. But thats anoying.

**Comment by wtangofoxtrot** [comment]
Agreed this should be re-opened, anytime I update the docker images and restart to use the latest I need to re-enter the nextcloud settings and re-login into all my clients. For a lot of users using mobile they dont even realize they have been logged out until they open the app. 

I am also using persistent data for the files/configs/db but why do I have to keep setting up the instance with every restart ?

**Comment by jjvereijken** [comment]
SOLVED?

I had this same problem for 18 months, consistenly and causing much frustration, and I have finally solved it! For me, it turned out to be a race condition!

I am using a iSCSI-backed volume to store all data files, like this

```  app:
    image: nextcloud:20
    restart: always
    depends_on:
      - db
      - cache
    volumes:
      - /local/nextcloud:/var/www/html
    ports:
      - 10080:80
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=cache
```     

where `/local/nextcloud` is the iSCSI-backed volume. After months of frustration, I discovered that in the boot process `/local/nextloud` only became available slightly later than that the Nextcloud container started. This caused the behavior that the install page appears, because Nextcloud saw an empty directory at `/var/www/html` (it saw the mountpoint, as `/local/nextcloud` wasn't mounted yet!), and it then assumes it still needs to be set-up.

After I fixed this issue, I never had the problem again!

**Comment by wtangofoxtrot** [comment]
> SOLVED?
> 
> I had this same problem for 18 months, consistently and causing much frustration, and I have finally solved it! For me, it turned out to be a race condition!
> 
> I am using a iSCSI-backed volume to store all data files, like this
> 
> ```
>     image: nextcloud:20
>     restart: always
>     depends_on:
>       - db
>       - cache
>     volumes:
>       - /local/nextcloud:/var/www/html
>     ports:
>       - 10080:80
>     environment:
>       - MYSQL_HOST=db
>       - REDIS_HOST=cache
> ```
> 
> where `/local/nextcloud` is the iSCSI-backed volume. After months of frustration, I discovered that in the boot process `/local/nextloud` only became available slightly later than that the Nextcloud container started. This caused the behavior that the install page appears, because Nextcloud saw an empty directory at `/var/www/html` (it saw the mountpoint, as `/local/nextcloud` wasn't mounted yet!), and it then assumes it still needs to be set-up.
> 
> After I fixed this issue, I never had the problem again!

Interesting, I am using doker-compse as well but with NFS shares and they are defined in the compose file. I wonder if docker is also not mounting them immediately but that sounds like a major docker bug.

**Comment by privilegejunkie** [comment]
Also having this issue. Volumes mounted on local machine over sshfs. Every restart of the container renders the initial setup screen.

**Comment by juanpabloxk** [comment]
I'm having this problem too, in addition to the above problems, using a docker-compose file to define the MariaDB and Redis services. If I run `docker-compose down` and `docker-compose up` I got this error:
> Username is invalid because files already exist for this user

**Comment by juanpabloxk** [comment]
SOLVED! (at least in my case)

To avoid a reinstall attempt, you have to persist the main `/var/www/html`, `/var/www/html/data`, and `/var/www/html/config` folders. If you only create a volume for the `data` subfolder, nextcloud will not know that the files inside that folder were created by him
