### ISSUE TITLE
Password not working during setup

### ISSUE THREAD

**Issue by MBurchard** [nextcloud/docker#48]
Today I faced a funny problem. I tried a lot to setup a new Nextcloud instance and thought it can't be... username and password work fine from everywhere but not from Nextcloud setup.

Than I changed the password to a very simple one **test** and everything worked fine. After the setup I changed this stupid password to a strong one manually in the config.php and also this strong one works fine.

It looks like during setup the password is not "encoded" correctly.

The password that has not worked during during install was something like this: TuriKatePeri9.

It might be the dot at the end...

**Comment by ambis** [comment]
I had similar problems with the MariaDB database password.

I was using Chrome. Had to use Safari instead to get past the initial installer with proper passwords.

Somehow the Javascript is buggy for the password fields.

**Comment by tilosp** [comment]
But this is not a bug in the docker image or am i wrong?

**Comment by MBurchard** [comment]
It is a bug in Nextcloud. I never had a problem with passwords in any browser, so the frontend implementation seems to have a problem...

**Comment by tilosp** [comment]
Then this issue belongs to the [nextcloud/server](https://github.com/nextcloud/server) repo
