### ISSUE TITLE
dockerfile - enable port 443 for images

### ISSUE THREAD

**Issue by JonasBVS** [nextcloud/docker#485]
when deploying nextcloud:latest(apache) https is not enabled by default. so running behind proxy is a pain.

i need to manually do the following:
- install ssl-cert package
- generate snakeoil cert or mount certs-volume
- enable default-ssl.conf
- enable ssl apache-modules

its a pain to script and cumbersome to maintain own images based on official image...

I believe it would be a great quality-of-life improvement for the image, and a simple improvement to implement making the image more user friendly.

**Comment by pierreozoux** [comment]
This image is aimed at being a building block for more complex setups.
For example on how to run it behind TLS, check the example folder.
For instance: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/docker-compose.yml

Hope it helps!

**Comment by JonasBVS** [comment]
The linked compose recipe is broken on https(443) as well as all other in this example pool.

problem is that the application is port aware, and if i proxy from 443 -> 80 it will return a http://URI wich breaks the app.

**Comment by SnowMB** [comment]
Can you please be more specific about the error you are experiencing? The http communication is internal to the docker host and the url for the visitor (and the app) will show as https.

**Comment by hom7** [comment]
Use this https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache
But nginx gives an error 503.
