### ISSUE TITLE
custom "full" build

### ISSUE THREAD

**Issue by XtraLarge** [nextcloud/docker#491]
Hello,

since version 14.1 a custom buld using the full example didn't work anymore. In the "full" example the CMD was changed from "apache-forground" to "/usr/bin/supervisord" so the installation or update process in the "/entrypoint.sh" script will never be triggered.
For my opinion the must be a third if clause so "supervisord" is also a trigger in the "/entrypoint.sh" script next "apache" and "php-fpm".

my solution is: (please be critical by checking it) file: [/entrypoint.sh]
```
#!/bin/bash
....
if [[ "$1" == *apache* ]] || [[ "$1" == *supervisord* ]] || [[ "$1" == *php-fpm* ]]; then
```

best regards
Willi

**Comment by J0WI** [comment]
Thanks for the hint, so we have to update our examples.
I would prefer using separate containers for `cron` and `libreoffice` instead of `supervisord`.

**Comment by SnowMB** [comment]
Great catch.

Modifying the entry point is not really practical because we can't add every other solution that users use to it. I'm thinking adding an environment variable like FORCE_AUTO_INSTALL might work.

Cc @tilosp.

**Comment by tilosp** [comment]
Yes a variable makes sense.
I would call the var something like NEXTCLOUD_UPDATER, and you can set it to true or false. If it's not set we can use the already existing detection based on the command.
@SnowMB calling it AUTO_INSTALL is kind of misleading because it would also enable or disable the update script.

**Comment by SnowMB** [comment]
Sure. I just realized that the latest change might have broken the update for existing deployments. That's really bad and should be fixed asap. 

For the solution I am stuck here:

Introducing a variable and if it's 
not present but the command is apache or php-fpm still doing updates is confusing. 

Maybe relying on the environment variable and taking out the check would be clearer. It's also easier to document.

But on the other hand this would brake the update for all users. So not really an option.

Going the other way round and doing an opt out style would break the docker library echo test again.

We might have to move the checks for existing instalation and the used command a bit.

Any thoughts?

**Comment by XA21X** [comment]
Just got caught out by this. I thought the 14.0.1 image was broken but after 14.0.2 also didn't take effect, I discovered the change in the entrypoint script. Note that some of the included examples use supervisord.

**Comment by SnowMB** [comment]
@tilsop yeah I came to the conclusion that this might be the best solution after all. If nobody beats me to it I'll try to fix this this weekend.

**Comment by benwaffle** [comment]
Even if we use the environment variable, it would be nice to support supervisord in the entrypoint script as that is the recommended way to get cron running

**Comment by tilosp** [comment]
> Even if we use the environment variable, it would be nice to support supervisord in the entrypoint script as that is the recommended way to get cron running

It's not the recommended way. The recommended way is to have a separate container for the cronjob.

**Comment by XtraLarge** [comment]
Hello,



You've forget to fix the "full" example. 



best regards ;)



Hans-Willi Werres

Brücker Mauspfad 564a

51109 Köln



Telefon +49 (221) 94642476

Fax +49 (221) 94642475

Mobile +49 (152) 53902692



-----Ursprüngliche Nachricht-----
Von: Tilo Spannagel <notifications@github.com>
Gesendet: Dienstag 16 Oktober 2018 16:45
An: nextcloud/docker <docker@noreply.github.com>
CC: XtraLarge <eMail@WilliWerres.de>; Author <author@noreply.github.com>
Betreff: Re: [nextcloud/docker] custom "full" build (#491)

Even if we use the environment variable, it would be nice to support supervisord in the entrypoint script as that is the recommended way to get cron running

It's not the recommended way. The recommended way is to have a separate container for the cronjob.

**Comment by tilosp** [comment]
> Hello, You've forget to fix the "full" example.  best regards ;)

CC: @SnowMB

**Comment by SnowMB** [comment]
Oooops. Haha. Will do tomorrow. Or if you want to step in... :wink:
