### ISSUE TITLE
Redirect URL incorrect 'cloudserver' 

### ISSUE THREAD

**Issue by peiying16** [nextcloud/docker#492]
After I log in, It redirects to `https://cloudserver/apps/files/`, but it should be `https://my.domain.com/apps/files/`.
If I replace `cloudserver` with `my.domain.com`, everything works fine. 
![image](https://user-images.githubusercontent.com/25106861/46634860-66452680-cb20-11e8-8fbb-e7982a68fbe1.png)

**Comment by peiying16** [comment]
I set up with docker-composer

```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always```

**Comment by peiying16** [comment]
I think the problem is on my nginx DNS config.
```
upstream CLOUDSERVER {
      server cloud;
    }

    server {
      listen    80;
      server_name  my.domain.com;
      location / {
        proxy_pass http://CLOUDSERVER;
      }
    }
```

Can I hard code my server name on config php file?

**Comment by naramski** [comment]
I think it is related to the autodetection of URL when Nextcloud is behind a reverse proxy. (See : https://docs.nextcloud.com/server/12/admin_manual/configuration_server/reverse_proxy_configuration.html) 

There are two parameters to change this : overwritehost and overwriteprotocol. 

I had the same problem and I have created a fix for this issue (Pull request : https://github.com/nextcloud/docker/pull/527). 

Hope it helps,

**Comment by J0WI** [comment]
@peiying16 Does https://github.com/nextcloud/docker/pull/527#issuecomment-434492082 fix your problem?
