### ISSUE TITLE
SSO & SAML authentication cannot be installed (mcrypt)

### ISSUE THREAD

**Issue by mlduber** [nextcloud/docker#497]
Using `image: nextcloud:14.0-apache` (that is 14.0.2), trying to "install and activate" *SSO & SAML authentication* official application will result in the following error message:
> App "SSO & SAML authentication" cannot be installed because the following dependencies are not fulfilled: The library mcrypt is not available.

    PHP_VERSION => 7.2.10

PHP version 7.2 won't support mcrypt, as we've been warned for months now.

**Comment by mrtndwrd** [comment]
Also ran into this problem today.

This is currently solving itself here: https://github.com/nextcloud/user_saml/issues/168
