### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/docker#5]
One last thing before being able to PR docker, we need a maintainer email.

Is `docker [at] nextcloud.com` good?

Let me know, and then, we can PR.

Pierre

**Comment by oparoz** [comment]
You should have an answer shortly :)

**Comment by MorrisJobke** [comment]
@pierreozoux Yes. Please use that :) Thanks

**Comment by oparoz** [comment]
You beat me to it :)

**Comment by pierreozoux** [comment]
Ok, great, then will PR docker :)
