### ISSUE TITLE
Redis-Image creates strange config.php

### ISSUE THREAD

**Issue by Tockra** [nextcloud/docker#517]
Hi,

I saw my https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm creates following lines in my config.php:
```php
'memcache.local' => '\\OC\\Memcache\\APCu',
'redis' =>
  array (
    'host' => 'redis',
    'port' => 6379,
  ),

```

But in the documentation there are just single `\` .: https://docs.nextcloud.com/server/11/admin_manual/configuration_server/caching_configuration.html 

Is that a bug or doesn't it matter?

T

**Comment by pierreozoux** [comment]
I remember having to use double. Try with simple and see if this works?

**Comment by tilosp** [comment]
Both should work. The config is just php code so `\\` will be an actual backslash.
But because of the single quotes `\O` should also be an actual backslash followed by `O`.
See: https://secure.php.net/manual/en/language.types.string.php#language.types.string.syntax.single

**Comment by pierreozoux** [comment]
@Tockra to avoid future confusion, maybe PR the documentation?
