### ISSUE TITLE
docker build for 'full' fpm example has empty /var/www/html

### ISSUE THREAD

**Issue by lhurt** [nextcloud/docker#520]
Hi,
I'm using the docker full example for the fpm container found at https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles/full/fpm for my docker-compose setup. My system is now on _14.0.1_ and as I wanted to upgrade to _14.0.3_ I noticed that the files in the fpm container were not updated.

## Cause ##
A quick inspection revealed that in fact the whole `/var/www/html` folder is empty in the container.

## Reason ##
Somehow the last line in the Dockerfile of the example above seems to cause this issue.

### Analysis ###
Using the [Dockerfile from the example](https://github.com/nextcloud/docker/blob/master/.examples/dockerfiles/full/fpm/Dockerfile) to build a new image with `docker build .` produces the following output

```
docker build .
Sending build context to Docker daemon  219.6kB
Step 1/5 : FROM nextcloud:fpm
 ---> fa164a1852d9
Step 2/5 : RUN mkdir -p /usr/share/man/man1     && apt-get update && apt-get install -y  ....

----- lots of unimportant stuff skipped ------

Build process completed successfully
Installing '/usr/local/lib/php/extensions/no-debug-non-zts-20170718/smbclient.so'
install ok: channel://pecl.php.net/smbclient-0.9.0
configuration option "php_ini" is not set to php.ini location
You should add "extension=imagick.so" to php.ini
configuration option "php_ini" is not set to php.ini location
You should add "extension=imagick.so" to php.ini
configuration option "php_ini" is not set to php.ini location
You should add "extension=smbclient.so" to php.ini
Removing intermediate container fd06579ddfae
 ---> 7a244bcfa85e
Step 3/5 : COPY supervisord.conf /etc/supervisor/supervisord.conf
 ---> 163241062121
Step 4/5 : ENV NEXTCLOUD_UPDATE=1
 ---> Running in 474abda5727e
Removing intermediate container 474abda5727e
 ---> 4c84a3c7a4b1
Step 5/5 : CMD ["/usr/bin/supervisord"]
 ---> Running in 55d9c1611bdc
Removing intermediate container 55d9c1611bdc
 ---> 1cadcd64f09c
Successfully built 1cadcd64f09c
```
### Result ###
A container created with image _**4c84a3c7a4b1**_ still contains the full `/var/www/html` folder but when using the final image _1cadcd64f09c_ this folder is gone.
```shell
root@5c93884d265d:/var/www/html# ls -la
total 8
drwxrwxr-x 2 www-data root 4096 Oct 15 18:39 .
drwxrwxr-x 5 www-data root 4096 Oct 15 22:06 ..

```

### Environment ###
Tested on Linux Ubuntu 18.0.3 and on MacOS High Sierra.

I played around with this numerous times but didn't find a reason why. May be it's even related to Docker.

Any help would be gladly appreciated.

**Comment by SnowMB** [comment]
We changed the behaviour of the entrypoint script. Notice that the image contains all files in `/usr/src/nextcloud` and the first start of the image will copy all the files to `/var/www/html`.

This process has now a condition to it (see #459, #515, and #519). It just happens when one of the following is true:

- The command is `apache*` or `php-fpm*`
- The image is started with `NEXTCLOUD_UPDATE=1`

So if you would do something like 

```
docker run -it --rm nextcloud:latest ls -alh /var/www/html
```

The install process is skipped and the directory would be empty.

I hope this makes it more clear.

**Comment by lhurt** [comment]
Works now for me now.
Seems like I'd missed the addition of the ENV entry in the Dockerfile because I ran the update pretty close to the 14.0.3 release where it was still not present.

Thanks
