### ISSUE TITLE
Sharing not working correctly 14.0.3-apache

### ISSUE THREAD

**Issue by JensPfeifle** [nextcloud/docker#523]
Hello,

we are seeing an issue with sharing in the 14.0.3-apache image. 

**Description:**
Sharing in itself works (i.e. the shared file is visible for the selected user). However, after sharing a file or folder to a user, the sidebar shows only the picture and name of the user, but none of the expected sharing controls (unshare, can edit, etc... ). The "Share via Link" option is not visible, even though the feature is enabled in the settings. Running with the 13.0.7-apache image, it works as expected. 

**Logs:**
- Settings -> Logging is empty ("Everything is working fine")
- No errors in nextcloud.log
- No errors  in the container log (docker logs -f nextcloud)

Please let me know if you would like to see these anyways.
 
**Behavior Nextcloud 14.0.3**
![14.0.3](https://user-images.githubusercontent.com/23027708/47420972-e81f8b80-d77f-11e8-8c0d-c03a3ae700e5.png)

**Behavior Nextcloud 13.0.7**
![13.0.7](https://user-images.githubusercontent.com/23027708/47425493-c4ae0e00-d78a-11e8-8ea8-63fe89419f1a.png)

Operating system and version:  Debian GNU/Linux 9.5 (stretch)
Docker version 18.06.1-ce, build e68fc7a
docker-compose version 1.22.0, build f46880fe

**Docker-compose service definition:**
```
version: '3.7'
services:
  nextcloud:
#    image: nextcloud:14.0.3-apache
#    image: nextcloud:13.0.7-apache
    container_name: nextcloud
    environment:
     - SQLITE_DATABASE=nextcloud
     - NEXTCLOUD_ADMIN_USER=nc_admin
     - NEXTCLOUD_ADMIN_PASSWORD=adminpassword
     - NEXTCLOUD_TRUSTED_DOMAINS=localhost:444
    volumes:
     - ${VOLUME_BASE_PATH}/nextcloud/html:/var/www/html
    ports:
      - 444:80

# note: we are using an external network in production which is not defined here
```

**Steps to reproduce:**
- Run nextcloud container with the above service definition
- Login as admin
- Create a second local user
- Share any of the default files with the Local User

Can anyone reproduce?

**Comment by JensPfeifle** [comment]
Some more testing shows this is Browser-specific. Firefox 62.0 shows the originally described behavior. 
Google Chrome Version 68.0.3440.106 works as expected.
OS is Linux Mint 19.

**Screenshot of working sharing from Chrome 68:**
image![chrome68](https://user-images.githubusercontent.com/23027708/47433209-3cd2fe80-d7a0-11e8-9fdf-ea824a5a427c.png)

**Comment by SnowMB** [comment]
Can't repuduce with Firefox 62.0.3. I also think you should report this issue upstream in [nextcloud/server](https://github.com/nextcloud/server).

**Comment by JensPfeifle** [comment]
Turned out to be an adblocker issue, probably due to the new social sharing features of NC 14.
Specifically: AdblockPlus and "Fanboy's Social Blocking List".
