### ISSUE TITLE
Update logo & text - account on https://store.docker.com/images/nextcloud

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/docker#529]
Hi,

I'd love access to https://store.docker.com/images/nextcloud so I can update the logo and text there ;-)

This looks pretty unprofessional.... Any chance I could get an email with login data ;-)

**Comment by SnowMB** [comment]
Hm. Since this is an official docker image I'm not sure where the logo comes from. Maybe @tianon can help.

**Comment by tianon** [comment]
Not sure where the Docker Store logo comes from -- you'd have to contact Docker support about that.

The canonical source for official images is Docker Hub, so https://hub.docker.com/_/nextcloud/, and as noted in the description there, the source for the description is the `nextcloud/` folder in https://github.com/docker-library/docs (https://github.com/docker-library/docs/tree/master/nextcloud).

**Comment by tilosp** [comment]
@tianon any news on the logo?
It looks like the new docker hub design displays the old and stretched logo too (See: https://hub.docker.com/_/nextcloud).

**Comment by tianon** [comment]
I've talked to some Docker folks about this and it's something they're very keen to fix so they're actively looking into it. :sweat_smile:

**Comment by jancborchardt** [comment]
The logo is not only stretched, it’s also the wrong one. :) Just changing it to the correct and square one will fix both problems:
![](https://raw.githubusercontent.com/nextcloud/promo/master/nextcloud-logo.png)

Link: https://github.com/nextcloud/promo/blob/master/nextcloud-logo.png

**Comment by tilosp** [comment]
> I've talked to some Docker folks about this and it's something they're very keen to fix so they're actively looking into it. :sweat_smile:

@tianon any news regarding this?

**Comment by tianon** [comment]
We've been informed that this might be something we'll be able to control for our images soonish, so hopefully sometime shortly we'll be able to update these directly/dynamically via our official `logo.png`/`logo.svg` files! :+1:

**Comment by tilosp** [comment]
@jancborchardt is this fine now? https://hub.docker.com/search?q=nextcloud&type=image&image_filter=official

**Comment by jancborchardt** [comment]
@tilosp @tianon looks better already! :) We do prefer the "white logo on blue background" version though, can we use that?

Also, since the Nextcloud Hub release last week the logo was adjusted a bit:

![](https://raw.githubusercontent.com/nextcloud/promo/master/nextcloud-logo.png)
Link: https://github.com/nextcloud/promo/blob/master/nextcloud-logo.png

**Comment by tilosp** [comment]
@jancborchardt it's updated to the new one now.
