### ISSUE TITLE
Using with tesseract OCR

### ISSUE THREAD

**Issue by itsthejb** [nextcloud/docker#530]
Hi all

Using this image for nextcloud, and it is of course fantastic. So thanks so much for this

Now I'd like to use tesseract for ocr, and ideally via another docker image. This seems tricky, however, since it's expected to be installed locally

Has anyone achieved this or could suggest a strategy? I'm reasonably experienced nowadays, so suggestions are fine

Hope someone can help! Thanks

**Comment by jkaberg** [comment]
All you need; https://github.com/jkaberg/dockerfiles/blob/master/nextcloud/Dockerfile

**Comment by itsthejb** [comment]
Great! I did a quick look into this myself, and did discover that a `FROM` custom image is the way to go. I notice that yours seem like they're a bit old though; have you tried using the repository link base image trigger on Docker Cloud:

![screen shot 2018-10-31 at 08 57 13](https://user-images.githubusercontent.com/557391/47773634-02f78000-dceb-11e8-956d-1396dc3adf37.png)

Seems this would keep both up to date with latest automatically

**Comment by jkaberg** [comment]
@itsthejb sure, I've enabled that now 🛩

**Comment by itsthejb** [comment]
Anyway, thanks @jkaberg for the great solution
