### ISSUE TITLE
502 Gateway Timeout on NGINX Web Container

### ISSUE THREAD

**Issue by cwillhelm** [nextcloud/docker#534]
After using the modifications from https://github.com/SnowMB/docker/commit/ea652e9c015a06355cbb718cd3a0fc68c8d8056c for #345 , I'm running into a nginx 502 gateway error, after attempting to configure the admin user via the web interface. 

This is using the `/insecure/postgres/fpm/docker-compose.yml` file.

When I don't use those modifications, it proceeds to the database configuration screen as referenced in #345, and then doesn't let me proceed further (by giving the same connect issue).

I theorized this was a timeout issue, but upon changing `nginx.conf` with:

```
location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+)\.php(?:$|/) {
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            # fastcgi_param HTTPS on;
            #Avoid sending the security headers twice
            fastcgi_param modHeadersAvailable true;
            fastcgi_param front_controller_active true;
            fastcgi_pass php-handler;
            fastcgi_intercept_errors on;
            fastcgi_request_buffering off;
            fastcgi_read_timeout 300;                  <------- THIS LINE ADDED
```

The timeout just takes longer, and still gives the same 502 error. 

I checked `/var/log/nginx/error.log` but there was no output and seems to just be linked to `/dev/stderr`, and not actually writing errors to the file.

**Comment by J0WI** [comment]
Use `docker-compose logs web` to check the logs of nginx. But I assume that your NextCloud container can't start for some reason.
