### ISSUE TITLE
Installation without user

### ISSUE THREAD

**Issue by akomm** [nextcloud/docker#537]
Currently you either have to provide admin user and password via environment, or you nextcloud starts in "setup" mode, which is accessible to the world.

__Without hacking on the base image and its entry point__, is it possible to install without user, so that I can later add one via shell: `docker-compose exec -u www-data php occ user:add -g admin username`

Or alternatively: `NEXTCLOUD_RANDOM_ADMIN_PASSWORD=yes`
This would generate random password, so that you do not have to specify one explicit in a config.
This enables you to later change it via `user:resetpassword`

**Comment by akomm** [comment]
I see your point.

Other question: 

Does something speak against `NEXTCLOUD_RANDOM_ADMIN_PASSWORD` ? I checked the entrypoint and I see it uses the occ cli to install with admin & pass from environment, if both provided. Basically this could  trigger a random pass generation. 

This would leave things as is for those who don't know better and give the option to those who know better :)

**Comment by SnowMB** [comment]
Hm technically not, but instead of using `NEXTCLOUD_RANDOM_ADMIN_PASSWORD` you could set your own pseudo random password with `NEXTCLOUD_ADMIN_PASSWORD`. But I would not argue against if someone takes time to implement it. Maybe there is a use case I don't see.

What I definitely agree on as improvement is that `NEXTCLOUD_ADMIN_USER`  should not be required. I missed that when I was implementing the auto install part.

**Comment by akomm** [comment]
Yes I could generate it myself. I already went through this idea and skipped it, because it does not solve the actual design flaw I want to prevent.

The password in environment does only matter during the initialization in entrypoint. Once an instance has been initialized and you save the volume, you can change the environment and it does not have any effect at all. The reason why is obvious. That is not the point. The point is, that I do not like to have stuff hanging in environment, that sometimes has effect ans sometimes not, depending on hidden conditions. I only have stuff in environment, that is reflected upon change.

For example using an unversioned env_file to configure instances, I have to generate something random into the file, that has no effect after first run and just keep hanging there between other relevant configs.

**Comment by joshtrichards** [comment]
Hi @akomm - As this is a fairly old issue that hasn't seen any further traction in nearly five years (and many things have changed), I'm going to close this out. Feel free to follow-up at the [Nextcloud Help Forum](https://help.nextcloud.com/) with questions or troubleshooting assistance. Or open a new Issue here if you have an actionable enhancement idea to discuss or bug to report related to the Nextcloud community Docker image itself.
