### ISSUE TITLE
Cannot write into config directory

### ISSUE THREAD

**Issue by monreal** [nextcloud/docker#544]
After updating my installation based on .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm I get the following error:

> ...
> Recreating fpm_web_1                 ... done
> Cannot write into "config" directory!
> This can usually be fixed by giving the webserver write access to the config directory

Looks like the app image was changed to alpine and this is causing the permission error. The permissions now look like this:

> drwxr-xr-x    2 xfs      root           136 Apr 29  2018 .
> drwxrwxr-x   15 www-data root          4096 Oct 18 20:17 ..
> -rw-r--r--    1 xfs      root           264 Apr 12  2018 .htaccess
> -rw-r--r--    1 xfs      root            70 Apr 12  2018 apcu.config.php
> -rw-r--r--    1 xfs      root           377 Apr 12  2018 apps.config.php
> -rw-r-----    1 xfs      xfs           1711 Nov 18 19:59 config.php
> -rw-r--r--    1 xfs      root         48041 Apr 12  2018 config.sample.php
> -rw-r--r--    1 xfs      root           141 Apr 12  2018 redis.config.php

I guess the user ID changed from the previous image to the alpine one? What would be the best way to fix this?

**Comment by mmarzantowicz** [comment]
According to [php:7.2-fpm-alpine3.8](https://github.com/docker-library/php/blob/b99209cc078ebb7bf4614e870c2d69e0b3bed399/7.2/alpine3.8/fpm/Dockerfile#L32-L34) files and directories should be writable by user which uid/gid is 82:82 . Check that or provide some more information about image versions etc.

**Comment by monreal** [comment]
Well, I don't know about the image versions, it's whatever "nginx:alpine" ended up to be this morning.
I was using the old "nginx" before, so the files/directories inside the volume have wrong permissions. I just want to make sure that chown'ing them to 82:82 is the way to go here...

**Comment by mmarzantowicz** [comment]
To see what version of image do you have issue:

`docker image ls | grep nextcloud`

Please see what happens when you change file owner (you have only 6 files, you can easily revert this change).

`chown 82:82 /path/to/config/dir/*`

Then (if in works) you may need to change ownership of other files related to `nextcloud` installation.

**Comment by monreal** [comment]
Alright, sudo docker-compose exec app chown -R 82:root /var/www/html seems to have fixed the problem with no negative side effect as far as I can see.

**Comment by yodog** [comment]
> Alright, sudo docker-compose exec app chown -R 82:root /var/www/html seems to have fixed the problem with no negative side effect as far as I can see.

this fixed it for me. thanks.

**Comment by SivertGullbergHansen** [comment]
Just wanted to point out to anyone in the future that I did not need to specify a user when performing the cronjob... `docker exec Nextcloud php /var/www/html/cron.php` was fine :)
