### ISSUE TITLE
nginx proxy config example

### ISSUE THREAD

**Issue by porjo** [nextcloud/docker#545]
I have nextcloud running in docker container (fpm-alpine) with Nginx on the docker host. I'd like to proxy from Nginx to the docker container, but struggling to get it working. I can login and see the main Nextcloud page, but it's completely broken after that. I'm using this Nginx config:

https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf

but I'm finding some files aren't served properly. For example, https://<nextcloud>/core/vendor/core.js?v=b23a5963-0 gets a redirect to https://<nextcloud>/apps/files/ which serves up HTML rather than JS!?

I found issue #240 but that's reporting 500 error, whereas mine is not erroring - it's just not serving files correctly.

**Comment by mmarzantowicz** [comment]
I can't see `server_name` directive (in `server` block) in this example. Maybe nginx must have one to serve your nextcloud site with predictable name.

**Comment by porjo** [comment]
ok, I see my error. I was thinking that the Nextcloud container would also serve the static files, but this is not the case. I've gotten too used to using Go where it does everything! :grin: 

The solution for me is to put my Nextcloud files in a folder on the host, and bind mount that into Nextcloud container - that way Nginx running on the host can serve the files properly.
