### ISSUE TITLE
Docker tags not updated

### ISSUE THREAD

**Issue by Greek64** [nextcloud/docker#548]
The "latest" tags of Docker still point to the previous version 14.0.3
In essence no 14.0.4 version is available on DockerHub (only the rc image)

**Comment by tilosp** [comment]
See: https://github.com/nextcloud/server/issues/12640

**Comment by Greek64** [comment]
Oh, thanks for the quick response. (Happy Holidays, I guess)
But why is it an issue in nextcloud/server? This is clearly a "docker" issue, right?

**Comment by tilosp** [comment]
yes it's in the wrong repo

**Comment by violoncelloch** [comment]
Ah so this just takes it's time – I see

**Comment by protree** [comment]
14.04 is now available on docker hub
