### ISSUE TITLE
Collabora deployment in docker-compose.yml can't work

### ISSUE THREAD

**Issue by danielmorlock** [nextcloud/docker#55]
This can't work since the port for upstream `collabora` is defined twice, in the upstream definition and in the `proxy_pass`: https://github.com/nextcloud/docker/blob/master/.examples/nginx.conf#L102

Can anyone confirm that the Collabora deployment is working?

**Comment by pierreozoux** [comment]
Hello!

I didn't try it, but yeah you are right that this is strange.
If you try it, it would be good if you can comment if it is working :)

Thanks!

**Comment by danielmorlock** [comment]
I can confirm that the Nginx configuration results in a working Collabora integration. There is a problem when a second user joins Collabora to work in collaboration on the same document. We have to further investigate this issue. We will open another issue if appropriate.
