### ISSUE TITLE
Setup errors / misunderstanding

### ISSUE THREAD

**Issue by leggettc18** [nextcloud/docker#551]
I'm trying to set this up for home use (and practice in using docker I guess). I wrote the docker-compose.yml for the apache image (like in the readme) and all goes well up until I go to create the admin account. At that point I get the following error: 
```
Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[08006] [7] FATAL: role "nextcloud" does not exist 
```
The only difference was I used a postregsql database instead of mariadb. I didn't do any sort of setup on the postgresql database container, was I supposed to that first? Or is the setup wizard supposed to be able to do that? I'm admittedly having trouble wrapping my head around Docker so I might just be dense. Some help would be appreciated.

**Comment by mmarzantowicz** [comment]
Yes, you must create database and role in postgres container first. You may refer to [docs](https://hub.docker.com/_/postgres/) for this but IMHO the easiest way is to create custom database image with simple init scripts for this.

**Comment by theOfficialJoeGG** [comment]
> ... IMHO the easiest way is to create custom database image with simple init scripts for this.
@mmarzantowicz Could you extrapolate on this?
