### ISSUE TITLE
Can't Browse DFS Tree

### ISSUE THREAD

**Issue by arnydo** [nextcloud/docker#554]
Attempting to mount a DFS namespace via External Storage.
This was working perfect on Nextcloud installed on a 18.04 box.
Once moved to Docker I see the Nextcloud image is based on 16.04.
There is a version difference between the two and whatever was changed allows it to work on 18.04 and not 16.04.
I have attempted to change the min/max SMB versions thinking that was the culprit in smb.conf, etc and still can't get it to work as expected.

Is there a way to force the Nextcloud image to use Ubuntu 18.04 OR does anyone know what may be causing this to occur?

Smbclient Version 4.5.12-Debian (FAILS)
Smbclient Version 4.7.6-Ubuntu (SUCCESS)

Thank you!

**Comment by mmarzantowicz** [comment]
Please read some docs on using SMB with docker containers. IMHO, Ubuntu version has nothing to do with your issue. More likely, it's docker vs. bare metal issue.

See this for example: https://stackoverflow.com/questions/27989751/mount-smb-cifs-share-within-a-docker-container

**Comment by arnydo** [comment]
@mmarzantowicz Thank you for the link but I have to disagree. I have done much testing on this issue prior to utilizing the Dockerized Nextcloud. This issue was reproduced exactly on bare Ubuntu 16.04 vs 18.04 and their respective Smbclient versions...

**Comment by J0WI** [comment]
Closing this for now. Further questions can be asked on https://help.nextcloud.com/.
