### ISSUE TITLE
Arm64v8 image not building in jenkins

### ISSUE THREAD

**Issue by gtinjr** [nextcloud/docker#566]
It seems the arm64v8 image is not building.

https://doi-janky.infosiftr.net/job/multiarch/job/arm64v8/job/nextcloud/

**Comment by tianon** [comment]
It seems it was stuck for a bit, but I'd kicked it this morning and it seems to be OK now (latest build is green).

cc @yosifkit

**Comment by gtinjr** [comment]
I was able to download and it is working fine thanks
