### ISSUE TITLE
Proposal: Official nextcloud cronjob container

### ISSUE THREAD

**Issue by rcdailey** [nextcloud/docker#569]
I've been working on a more flexible and simpler replacement to the typical `/cron.sh` entrypoint task for running `cron.php` in Nextcloud. I'd love some feedback on what I have so far, and if the maintainers of this repo would be interested in incorporating my work. Your time and feedback is appreciated.

https://github.com/rcdailey/nextcloud-cronjob

**Comment by J0WI** [comment]
There have been many discussions about cron in Docker. But Docker is not suitable for cronjobs and therefore we do not support a cron image.

The "Docker way" to run cronjob and IMHO the most easiest way is described here:
https://github.com/nextcloud/docker/issues/361#issuecomment-413383645

**Comment by rcdailey** [comment]
I disagree that Docker is not suitable for cronjobs. In fact you provide busybox's crond in your official image which is contradictory to your statement.

In either case, what i have works really well and I haven't noticed any functional issues. If you guys don't want to adopt it, that's fine. I'm just offering it in case you're interested. I'll go ahead and close this issue then.

**Comment by J0WI** [comment]
Yes, Busybox contains crond, but Docker containers are not designed to run multiple services (`supervisord` is a hack to workaround this).
