### ISSUE TITLE
Nextcloud 15 recommends 'imagick' to be installed

### ISSUE THREAD

**Issue by rcdailey** [nextcloud/docker#574]
I get this message using Nextcloud 15 apache container:

> This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them.
>
> * imagick

Can this be added to the image?

**Comment by J0WI** [comment]
Looks like the thumbnail generation fails because of this. Thanks for the heads up!

**Comment by gerroon** [comment]
I still have this issue even I have php-imagick installed on Debian Buster

**Comment by despens** [comment]
This issue persists with the theming app being installed, which comes with the apache container out of the box. (Using nextcloud:15.0.7-apache)

**Comment by J0WI** [comment]
Please see https://github.com/nextcloud/docker/issues/594#issuecomment-459859737

**Comment by despens** [comment]
I guess the right approach is to remove the message asking for Imagick to be installed. The issue can perhaps be closed once https://github.com/nextcloud/server/issues/13099 is resolved
