### ISSUE TITLE
Smb/Cifs docker 15.0.0

### ISSUE THREAD

**Issue by djam94** [nextcloud/docker#578]
Hey guys,

After update docker image 14.0.3 to 15.0.0 it is impossible to mount share.
php-smbclient is not present in debian image.

Apt install php-client => not found

Thanks!
DG

**Comment by J0WI** [comment]
This was never present in the official image. You probably built your own from https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles/full

**Comment by djam94** [comment]
In fact, with docker image 14.0.3, I just had to install php-smbclient package to enable SMB/CIFS in Nextcloud external storage.
But with 15.0.0 image, i can't install this package with apt.

**Comment by djam94** [comment]
Hey,

I have installed smbclient with pecl.

It work now !

Thanks
