### ISSUE TITLE
view full logs in nextcloud:fpm

### ISSUE THREAD

**Issue by nerijus** [nextcloud/docker#584]
How can I see full logs? Now I see when running "docker logs 818a7f0d1107":
192.168.0.1 -  15/Dec/2018:17:48:16 +0000 "POST /nextcloud/index.php" 303
192.168.0.1 -  15/Dec/2018:17:48:16 +0000 "GET /nextcloud/status.php" 200
192.168.0.1 -  15/Dec/2018:17:48:17 +0000 "HEAD /nextcloud/remote.php" 401
192.168.0.1 -  15/Dec/2018:17:48:17 +0000 "HEAD /nextcloud/remote.php" 401

I would like to see full error if possible, not just 401.

**Comment by J0WI** [comment]
You can set `"logfile" => "/dev/stdout",` in your `config.php`
