### ISSUE TITLE
Update to a newer version instructions incomplete

### ISSUE THREAD

**Issue by stuart12** [nextcloud/docker#585]
The instructions "Update to a newer version" in README.md are incomplete.  I was running Nextcloud 13 and followed the instructions.  They pulled the latest version (which was Nextcloud 15) and now I'm stuck as skipping major releases is not supported.  Perhaps the instructions should say: find your current version, pull the next major version and run it until this upgrade is complete then repeat until there are no more new major versions.

If you do run an image n+2 you no longer run an image n+1 as docker says: 

> Can't start Nextcloud because the version of the data (15.0.0.10) is higher than the docker image version (14.0.4.2) and downgrading is not supported. Are you sure you have pulled the newest image version?

When you run n+2 (Nextcloud 15 in my case), `php occ upgrade` fails with 

> Exception: Updates between multiple major versions and downgrades are unsupported.

**Comment by hanscees** [comment]
it would be superb to add this. And also if after an update via docker to a next version you need to run some script or not by going to the webserver.

It is really hard finding  the right documentation when upgrading a docker implementation

**Comment by all-the-good-ones-are-gone** [comment]
That would be helpful. 

I'm not even getting that. I changed my tag from nextcloud:14.0.0-fpm to nextcloud:14-fpm and while it appeared to pull new image the settings screen when I log in still reports that I'm on 14.0.0 and should update to 14.0.4
