### ISSUE TITLE
Docker image latest not starting Nextcloud 11.0.2

### ISSUE THREAD

**Issue by MBurchard** [nextcloud/docker#59]
Since weeks I see the hint "Nextcloud 11.0.2 is available" when I log into my nextcloud docker instance.

I pulled the new version and now have this images:

    sudo docker images
    REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
    nextcloud           latest              5d0d70f314ea        3 days ago          620 MB
    mysql               latest              5faba1a71ec4        4 days ago          407 MB

I started the image by

    sudo docker run --name nextcloud --link mysql:mysql -p 8080:80 -v /data/nextcloud:/var/www/html -d nextcloud:latest

I got PHP Version 7.1.3 which is really nice, but still not Version 11.0.2.

On the [Docker Hub][1] It's shown that version 11.0.2 is the same as latest:

11.0.2-apache, 11.0-apache, 11-apache, apache, 11.0.2, 11.0, 11, latest (11.0/apache/Dockerfile)

[1]: https://hub.docker.com/_/nextcloud/

**Comment by tilosp** [comment]
If you run this command `sudo docker run -it --rm nextcloud cat /var/www/html/version.php` you can see that the image contains the new version.
```
$ sudo docker run -it --rm nextcloud cat /var/www/html/version.php
<?php 
$OC_Version = array(11,0,2,7);
$OC_VersionString = '11.0.2';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array (
  0 => 9,
  1 => 1,
);
$OC_Build = '2017-02-26T19:43:43+00:00 f299c9b2f4cb98b6dcd79943882740f9b72dc3c0';
$vendor = 'nextcloud';
```
The problem is that you volume still contains the old version of nextcloud.
So you would need to delete the files in the volume which need to get upgraded (everything except the data, apps and config folder).

**Comment by MBurchard** [comment]
In the documentation is no hint about manual steps need for an upgrade.

> Update to a newer version
> 
> To update your Nextcloud version you simply have to pull and start the new container. (if you mounted > the full /var/www/html, you need to delete version.php. See persistent data for more information.)
> 
> $ docker pull nextcloud
> $ docker run -d nextcloud
> 
> When you access your site, the update wizard will show up.

I did not see an updated wizard.

Wouldn't it be nice and easy for the users, if the docker images does all necessary steps during an initial start up check?

**Comment by tilosp** [comment]
We are working on a better solution. #23

**Comment by MBurchard** [comment]
Partly my fault. as soon as I removed the version.php the update wizard was shown.

If this is the only file and works as a trigger, I'm fine with the upgrade process.

After the upgrade it shows an error message about files that have failed the integrity check.

	Technical information
	=====================
	The following list covers which files have failed the integrity check. Please read
	the previous linked documentation to learn more about the errors and how to fix
	them.

	Results
	=======
	- core
		- EXTRA_FILE
			- core/doc/user/_sources/pim/sync_kde.txt
			- core/doc/user/pim/sync_kde.html
			- core/doc/user/_images/kdes4.png
			- core/doc/user/_images/kdes2.png
			- core/doc/user/_images/kdes1.png
			- core/doc/user/_images/kdes5.png
			- core/doc/user/_images/kdes3.png
			- core/doc/user/_images/kdes7.png
			- core/doc/user/_images/kdes6.png
			- core/doc/user/_images/kdes.png
			- core/doc/user/_images/kdes9.png
	- logreader
		- EXTRA_FILE
			- webpack/dev-proxy.js

Anything I need to worry about?

**Comment by tilosp** [comment]
The version.php file is the only trigger.
I am not sure if this error is a problem, you could try to fix it by manually copying the listed files into the volume.

**Comment by MBurchard** [comment]
I removed **core**  and **apps/logreader** completely.

After container start and first access with error 503 all files have been restored and the next manually started integrity check was without any result...
