### ISSUE TITLE
Email missing php module in 15-apache

### ISSUE THREAD

**Issue by hriekehof** [nextcloud/docker#595]
When i configure my email server in the nextcloud:15-apache image i get the following error:

![image](https://user-images.githubusercontent.com/9348635/50651483-ca428400-0f83-11e9-949c-5ca130229cba.png)

> A problem occurred while sending the email. Please revise your settings. (Error: The BCMath functions must be enabled to use the NTLM authenticator.)

The same config works fine on my old 13 Installation. I'm not sure but is the php module missing in the docker version of nextcloud ?

Thanks in advance

**Comment by J0WI** [comment]
You may have a look at https://github.com/nextcloud/docker/tree/master/.examples#php-module-imap

**Comment by hriekehof** [comment]
ok i see. I wanted to avoid building the image so i just use the pre build image directly. Thanks alot :) I have to build then i think

**Comment by hriekehof** [comment]
Sorry to reopen this. I just build my nextcloud image with the full dockerfile for apache. docker/.examples/dockerfiles/full/apache/Dockerfile. 

I still get the error when i want to send mails

**Comment by J0WI** [comment]
Only SMTP is supported in Docker. Do you use something else?

**Comment by hriekehof** [comment]
this is my complete config

![image](https://user-images.githubusercontent.com/9348635/51169178-84eb5400-18ab-11e9-8f72-6a0632ff493f.png)

**Comment by J0WI** [comment]
@tilosp do you have any experience with NTLM?

**Comment by hriekehof** [comment]
Ok i think i fixed it. You have to activate bcmath with `docker-php-ext-install bcmath`. I added bcmath in line 33-34 for the full version of the Dockerfile.
```
docker-php-ext-install \
        bz2 \
        gmp \
        imap \
       bcmath \
    ; \
```
