### ISSUE TITLE
make sure to remove "user_external" from 15.0.2 build

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/docker#598]
@nextcloud/docker 
We removed the app user_external from the build for 15.0.1 and released it via appstore -- see:
nextcloud/user_external#22
nextcloud/server#13225
https://apps.nextcloud.com/apps/user_external

as you use a separate folder (`custom_apps`) for store apps, the old version is kept in the `apps` folder and not overwritten by the store update (this already happened in user_external#32 for the ones that already updated the app in 15.0.0)
can you make sure to remove the shipped version in `apps/` for the update to 15.0.1 when the appstore version is installed to `custom_apps/`?

cc @MorrisJobke

**Comment by J0WI** [comment]
I assume that `rsync` will handle this case:
https://github.com/nextcloud/docker/blob/8bd688664d389021e52e6adf589a42c3c2e0f680/docker-entrypoint.sh#L47

**Comment by violoncelloCH** [comment]
If this will remove user_external v0.4 form the `apps/` directory also on upgrade that should be fine! Then user_external v0.5.0 can be installed from the appstore to `custom_apps/` without any conflict...

**Comment by J0WI** [comment]
@violoncelloCH the now published 15.0.1 release does still ship with user_external 0.4

**Comment by violoncelloCH** [comment]
happened by accident -- see: https://github.com/nextcloud/server/pull/13346#issuecomment-453480999
15.0.2 won't ship it anymore...

**Comment by J0WI** [comment]
Thanks for the heads up, I verified the app is getting removed in 15.0.2.
