### ISSUE TITLE
Update Description

### ISSUE THREAD

**Issue by SnowMB** [nextcloud/docker#6]
Hey,

maybe we should update the description a little bit instead of just linking to [IndieHosters/Nextcloud](https://github.com/indiehosters/nextcloud): 

- Explain that this container does not include a webserver and needs one in front (even to run locally)
- How to update
- etc.

**Comment by pierreozoux** [comment]
Agreed :)

Could you PR?

here a nice example from piwik php-fpm: https://github.com/piwik/docker-piwik (It just got updated).
