### ISSUE TITLE
How to switch to alpine images ?

### ISSUE THREAD

**Issue by pgera** [nextcloud/docker#601]
I have been using the docker compose files satisfactorily for a while. I noticed that this commit https://github.com/nextcloud/docker/commit/aa5c0c192995e98836fc3c5435119583a78bef62  changes the images to alpine variants and removes the www-data user from nginx.conf. I tried to pull in these changes, but got a bunch of permission errors in the nginx log, presumably due to the difference in www-data ? My questions are:
1) Do I need to pull in these changes ? i.e., Would the original images (and their combination) be maintained for nextcloud ?
2) If it is advisable to change, what is the migration path ? I was reluctant to perturb a working config.

**Comment by pgera** [comment]
Thank you! This worked. Perhaps this should be added as documentation somewhere.

**Comment by SnowMB** [comment]
@pera could you write down your steps and submit a pr?

**Comment by pgera** [comment]
The steps are exactly the same as  https://github.com/nextcloud/docker/issues/601#issuecomment-453552857. I can submit a pr, but I don't know where this sort of documentation goes. There isn't an explicit category for this sort of thing. Maybe a new category with important breaking changes should be created where breaking is defined as anything that breaks if you do a git pull in your local install.

**Comment by joshtrichards** [comment]
The since added *Migrating an existing installation* section could probably hold this info under a sub-section.

**Comment by alexandra-branco** [comment]
@joshtrichards  
Is adding this information still missing from the [_Migrating an existing installation_](https://github.com/nextcloud/docker?tab=readme-ov-file#migrating-an-existing-installation) section?
You can assign me the issue and I will create a pull request for this issue.

**Comment by joshtrichards** [comment]
This Issue is still open and it doesn't appear there... So yes.

But there is no need to assign the issue. If you do create a PR, just link it to this issue.

Thanks!

**Comment by alexandra-branco** [comment]
PR https://github.com/nextcloud/docker/pull/2289
