### ISSUE TITLE
Upgrading stuck due to data and docker image version mismatch

### ISSUE THREAD

**Issue by westhomas** [nextcloud/docker#605]
I'm trying to upgrade from version 9.* 
I read the instructions to do a `dc pull && dc up -d`, which I did. This got me to 15.0.2.

When I started this up I received the message state that I can't upgrade across multiple major version. Ok, fine. I'll do one major version at a time then.

So I pinned my version to `nextcloud:10.0.6-fpm` and tried again. This time I get:

```
Can't start Nextcloud because the version of the data (15.0.2) is higher than the docker image version (10.0.6)
 ```

So now what?

**Comment by J0WI** [comment]
The easiest way would be to restore your data from backup.

**Comment by westhomas** [comment]
That would get me back to version 9. But what's the proper way to go about upgrading?

**Comment by J0WI** [comment]
You have to upgrade from 9 to 10, from 10 to 11 and so on. Use `-e NEXTCLOUD_UPDATE=1` to update the sources and `occ upgrade` for the database: https://docs.nextcloud.com/server/15/admin_manual/configuration_server/occ_command.html#command-line-upgrade-label

**Comment by nicbou** [comment]
### Fixed

I pieced a dozen old threads together and came up with a detailed solution: https://nicolasbouliane.com/blog/nextcloud-docker-upgrade-error

tl;dr:

1. Find your old version in config/config.php
2. Put that version everywhere in version.php
3. Roll back the docker image to that old version
4. Upgrade the image one major version at a time
5. Turn off maintenance mode
6. Thank your friendly neighbourhood contributors
