### ISSUE TITLE
(question) Can I migrate apache2 image to php-fpm + nginx image?

### ISSUE THREAD

**Issue by seonghobae** [nextcloud/docker#618]
Hello all,
Can I migrate apache2 image to php-fpm + nginx image?
Because I have too high loads caused by the apache2 web server, that makes me crazy. The apache2 sessions too heavy to me. That's why I want to switch existing image to php-fpm.
If not, How can I migrate them manually? 

My environment is 
```
Linux 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PostgreSQL 11.1 (Ubuntu 11.1-1.pgdg16.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609, 64-bit
```

Best,
Seongho

**Comment by J0WI** [comment]
Sure you can switch. Just make sure that you are using persistent volumes for all your apps, configs, data etc. While the Debian based `fpm` variant should work out of the box, you need to adjust permissions for `fpm-alpine` (they use a different `uid` for `www-data`).
You can find some examples here: https://github.com/nextcloud/docker/tree/master/.examples/docker-compose

**Comment by J0WI** [comment]
See also #601
