### ISSUE TITLE
error send email after upgrade to nextcloud 15.0.2 image

### ISSUE THREAD

**Issue by Judhianto** [nextcloud/docker#619]
After upgrade docker image to nextcloud:latest   ( version 15.0.2 ) , my nextcloud server can not send notification email.  Everything else is running well, except the notification email.

This is my SMTP configuration . It works perfectly in previous docker image version ( 15.0.0 )
![image](https://user-images.githubusercontent.com/1426001/51664030-00a37a00-1feb-11e9-9ed6-bc184c70d2a7.png)

image --> nextcloud:latest
database --> mariadb

Can somebody help me?
Thanks in advance

**Comment by jmdev68** [comment]
im facing the same / similar issue - only diff. I installed nextcloud under docker first time - hence can not comment if it worked with an older version

**Comment by jmdev68** [comment]
i was able to solve the problem by specifying the sender adress (or mail_from_address) and domain (mail_domain) with the same account data of my smtp provide (intially i thought i could use a local nexcloud fantasy name) but looks like my mail provider validates the same (and not only the login data)

**Comment by jorgensoares** [comment]
I have the same problem... i think the latest image has a problem because i see this in the logs:
```PHP Startup: Unable to load dynamic library 'imap.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20170718/imap.so (Error loading shared library libc-client.so.1: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20170718/imap.so)), /usr/local/lib/php/extensions/no-debug-non-zts-20170718/imap.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20170718/imap.so.so: No such file or directory)) at Unknown#0```

**Comment by J0WI** [comment]
The imap extension is not installed by default. You can find an example how to extend your image here:
https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles/imap
