### ISSUE TITLE
Dockerhub reports 28 vulnerable components

### ISSUE THREAD

**Issue by GuyPaddock** [nextcloud/docker#623]
When logged-in to Dockerhub, when I visit the tags page for Nextcloud, I see a report indicating that all of the current tags have vulnerabilities. I do not see this shown when I am viewing Nextcloud tags as an anonymous user.

![image](https://user-images.githubusercontent.com/2631799/51782712-33d52e80-20fb-11e9-9bb6-3de45b38a0f2.png)

Digging deeper, Dockerhub indicates "There are 28 vulnerable components":
![image](https://user-images.githubusercontent.com/2631799/51782719-49e2ef00-20fb-11e9-96d4-d5aee1135a25.png)

**Comment by laurawadden** [comment]
It would be great to see someone from Nextcloud respond to this, I just saw this and would like to know how you will handle these vulnerabilities.

**Comment by protree** [comment]
Yes, an explanation would be great!

**Comment by tilosp** [comment]
take a look at https://github.com/docker-library/faq#why-does-my-security-scanner-show-that-an-image-has-cves

**Comment by GuyPaddock** [comment]
Right... but what's the official stance on the specific CVEs that have been reported against _this_ image?

**Comment by tilosp** [comment]
This is a community maintained docker image, there is no dedicated security team for this image.
We always do our best to keep all the dependencies up to date. But we have to rely on others to fix security vulnerabilities. For example for CVEs in debian package we rely on the debian security team to fix them.
For nextcloud, php, .. we rely on upstream to fix security vulnerabilities .
You can for example use the [debian security-tracker](https://security-tracker.debian.org) to check if CVEs do really apply or if they are false positives.
