### ISSUE TITLE
Updating Trusted Domains in Docker Container

### ISSUE THREAD

**Issue by FunInfinity** [nextcloud/docker#625]
Hi,

I'm quite new to docker and I apologize if my question is silly, but I got stuck with it.
I've installed Docker Toolbox, run latest Nextcloud image.
Added port forwarding for VM, so it is now available under host IP in my home network, but now it is complaining about trusted domains, that I  need to add it to config.php

So, do I understand correctly that I need to add host IP as a trusted domain name or I should add whole subnetwork like '192.169.1.*'?

How can I access  and change that file? Should I mount docker volumes and after access the appropriate folder or it is done in another way?

Thank a lot

**Comment by Wheresitat** [comment]
Hello,

I believe i have a similar issue, i built my stack from the example here.
https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache

I can't find the config.php anywhere on my system. I've tried manually setting the config volume :
      - /home/docker/nextcloud/config:/config
Still, there is no config.php created.
using locate i get:

locate config.php
/home/docker/organizr/www/Dashboard/config/config.php

**Comment by J0WI** [comment]
Please have a look at the discussion in #527 and https://github.com/nextcloud/server/issues/13713.
The necessary config options are also documented here:
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by FunInfinity** [comment]
Sorry, I don't understand how it is related to my question.
For me main problem is that I don't know how to access config.php and its folder inside the docker.

**Comment by Wheresitat** [comment]
> Sorry, I don't understand how it is related to my question.
> For me the main problem is that I don't know how to access config.php and its folder inside the docker.

Or you can install portainer, from there you can easily login to the docker container as a shell.
