### ISSUE TITLE
Missing Local Storage option

### ISSUE THREAD

**Issue by Wheresitat** [nextcloud/docker#626]
Hello,

I am trying to add some local storage i've mounted in fstab, i can browse to the share fine in the container console however when i try to add a "local storage" in "external storage's" i don't have the local option:
Any ideas?
![image](https://user-images.githubusercontent.com/14259134/51818061-82fca880-2321-11e9-8ae3-aec3b9dd7c19.png)

**Comment by da3dsoul** [comment]
Go to apps, disabled apps, then External Storage needs to be enabled. Then you can add it like normal. If you are in a docker, then make sure to forward the path as a volume

**Comment by Wheresitat** [comment]
> Go to apps, disabled apps, then External Storage needs to be enabled. Then you can add it like normal. If you are in a docker, then make sure to forward the path as a volume

Hello, Thanks for the reply.
If you see my original post, the screen shows the external storage apps is already enabled.
I just don't have the option to add local storage? It's just not listed?

**Comment by da3dsoul** [comment]
Ah missed that obvious part. I ran into this. I'm having trouble remembering how I fixed it

**Comment by Wheresitat** [comment]
Have found the issue, i can see local storage when viewing the shares through settings - > administration 
 -> external storages (this was broken previously i had to truncate my database to fix as opposed to personal - > external storages.

![image](https://user-images.githubusercontent.com/14259134/51883158-e3e5b880-23d5-11e9-93b7-720d46cb97b9.png)
