### ISSUE TITLE
crontab question

### ISSUE THREAD

**Issue by hm400** [nextcloud/docker#627]
Im trying to use cron instead of ajax for background jobs. 
From docs.nextcloud.com  im trying to run 

#crontab -u www-data-l
*/5  *  *  *  * php -f /var/www/nextcloud/cron.php

but crontab is not found, how do i add this entry without crontab?
using docker image 15.0.2

**Comment by SnowMB** [comment]
The crontab is already included in the image. It uses the default 15 minute interval from the nextcloud documentation.

https://github.com/nextcloud/docker/blob/8d133d39e602151973fbe5c52defc588b58cc369/Dockerfile-debian.template#L15

If you want to use another setting you should make a derived image and build it on your own.

If you are fine with the default you have two possibilities to use that:

1. Use a second container that runs the `cron` command. You can find an example here: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb-cron-redis/apache/docker-compose.yml

2. Build an derived image that uses `supervisord` or another process manager to run both processes (webserver / cron) in one container. We also have an example for that: https://github.com/nextcloud/docker/tree/8d133d39e602151973fbe5c52defc588b58cc369/.examples/dockerfiles/cron/apache

**Comment by J0WI** [comment]
3. Use a local cronjob/timer and `docker exec -u www-data my-nextcloud php cron.php`

**Comment by hm400** [comment]
> 1. Use a local cronjob/timer and `docker exec -u www-data my-nextcloud php cron.php`

This worked and changed Ajax to Cron in admin->basic settings

**Comment by hm400** [comment]
ty for replies

**Comment by Iceman0073** [comment]
Dear SnowMB,

sorry I'm also new here and I want to ask you something about cron and the external cron container. I selected the example with the second container "cron" but I don't know the right setting to choose within nextcloud. Is it the right way to select Webcron or Cron within the Nextcloud Settings?

Many Thanks for your help.

**Comment by huuub** [comment]
> The crontab is already included in the image. It uses the default 15 minute interval from the nextcloud documentation.
> 
> https://github.com/nextcloud/docker/blob/8d133d39e602151973fbe5c52defc588b58cc369/Dockerfile-debian.template#L15
> 
> If you want to use another setting you should make a derived image and build it on your own.
> 
> If you are fine with the default you have two possibilities to use that:
> 
> 1. Use a second container that runs the `cron` command. You can find an example here: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb-cron-redis/apache/docker-compose.yml
> 2. Build an derived image that uses `supervisord` or another process manager to run both processes (webserver / cron) in one container. We also have an example for that: https://github.com/nextcloud/docker/tree/8d133d39e602151973fbe5c52defc588b58cc369/.examples/dockerfiles/cron/apache

Are you sure of this? In the container I can't see this. Can anybody confirm?

**Comment by Tintwo** [comment]
@huuub I have the same pb as you.
The content of cronjob is in the `/var/spool/cron/crontabs/www-data` file, but anyway the app crontab is not installed inside the image so it can't be executed every X minutes.

@hm400 Can you open again this issue ? We should have a possibility to use cronjob inside a container as long this option is available in parameters. To use other ways because this one was not checked in docker mode is a trick, not a solution.

Regards,
Hope this pb will be resolved soon (my experience, i have that issue since version 14)

**Comment by J0WI** [comment]
Please have a look at the [previous comments](https://github.com/nextcloud/docker/issues/627#issuecomment-458472499). There are three ways to run cron in Docker:

1. Use a second container that runs the `cron` command. You can find an example here: https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/insecure/mariadb-cron-redis
2. Build an derived image that uses `supervisord` or another process manager to run both processes (webserver / cron) in one container. We also have an example for that: https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles/cron
3. Use a local cronjob/timer and `docker exec -u www-data my-nextcloud php cron.php`

Please use https://help.nextcloud.com/ for further questions.

**Comment by andioz** [comment]
I ran in the same issue recently. I'm quite new in using docker images, but for me this looks a little bit strange. Running cron in background for some async work tightly coupled to Nexcloud should not be treated as "different process". And as I can read, Docker best practices says now: "decouple concerns", nothing about processes anymore. https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#decouple-applications.  On the other hand, running a different container on the same volume manipulating data from another container - this sound dangerous to me. 

Therefore, I fully agree with the OP, and I hope you can find a way to make the Nextcloud container more "self contained"; having the database in a different container make still sense of course.

**Comment by Mr-MooMoo** [comment]
> > The crontab is already included in the image. It uses the default 15 minute interval from the nextcloud documentation.
> > https://github.com/nextcloud/docker/blob/8d133d39e602151973fbe5c52defc588b58cc369/Dockerfile-debian.template#L15
> > 
> > If you want to use another setting you should make a derived image and build it on your own.
> > If you are fine with the default you have two possibilities to use that:
> > 
> > 1. Use a second container that runs the `cron` command. You can find an example here: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb-cron-redis/apache/docker-compose.yml
> > 2. Build an derived image that uses `supervisord` or another process manager to run both processes (webserver / cron) in one container. We also have an example for that: https://github.com/nextcloud/docker/tree/8d133d39e602151973fbe5c52defc588b58cc369/.examples/dockerfiles/cron/apache
> 
> Are you sure of this? In the container I can't see this. Can anybody confirm?

Just found it in /var/spool/cron/crontabs !

**Comment by huuub** [comment]
Let me know if you got that working...

**Comment by AndreKoepke** [comment]
@ashjas it's correct. `cron.php` don't produces any output,

Like @andioz already noticed, it feels not correct to mount a path-multiple times.  
So I updated the entrypoint-script to start the cron-script, when a env-var is set. It should be the default (but I think it is only my opinion).

Here is the pull-request: https://github.com/nextcloud/docker/pull/1242

**Comment by abartl** [comment]
For those who still have this issue:

First test whether you can manually execute the cron.php without crontab. Run the command on your server (not inside the container):
docker exec -it YOUR_CONTAINER_ID /usr/local/bin/php -f cron.php

Check in the Nexcloud Basic Settings whether it turned green. In certain cases php might be not in the PATH or is at other location. You can use this command to find the correct path:
docker exec -it YOUR_CONTAINER_ID which php

When you validated that the manual execution worked edit crontab on you server:
crontab -u www-data -e

Add the command that worked manually (you can skip the -it parameters and modify if php is somewhere else):
*/5  *  *  *  * docker exec YOUR_CONTAINER_ID /usr/local/bin/php -f cron.php

**Comment by AndreKoepke** [comment]
Nextcloud has a docker-image in which the cron is already configured. Read this comment:
https://github.com/nextcloud/docker/pull/1242#issuecomment-699019728

**Comment by im-n1** [comment]
for those using official docker container you need to run `cron.php` as www-data user and thats done like:

```
$ docker exec -it --user www-data nextcloud php cron.php
```
