### ISSUE TITLE
Add example for preview generation dependencies 

### ISSUE THREAD

**Issue by nalt** [nextcloud/docker#63]
Some dependencies for efficient preview generation are missing. Preview is a pretty important feature for most users.

According to https://docs.nextcloud.com/server/11/admin_manual/installation/source_installation.html:
For preview generation (optional):
PHP module imagick
avconv or ffmpeg
OpenOffice or LibreOffice

**Comment by tilosp** [comment]
This is to big to get included in the official image. But we can add an example Dockerfile for it.

**Comment by nalt** [comment]
Well, the idea of Docker is to provide fully working containers with all dependencies working and configured. It's true, they can become quite large, but what is "too large"? A Nextcloud image with "some dependencies" installed is rather a toy example.
Wouldn't it be feasible to have tags for that, like a minimal and full?
The footprint could be reduced with alpine Linux, and maybe nginx.

**Comment by pierreozoux** [comment]
```
FROM nextcloud:12-fpm
RUN apt-get update \
    && apt-get -y install \
            libmagickwand-dev \
        --no-install-recommends \
    && pecl install imagick \
    && docker-php-ext-enable imagick \
    && rm -r /var/lib/apt/lists/*
```

**Comment by Al2Klimov** [comment]
@tilosp Yes, just ffmpeg adds 300 megs or 50%. But couldn't you introduce extra tags with all providers, e.g. apache-full?

**Comment by tborychowski** [comment]
I just spent several hours trying to make video previews work, before finding it (I'm not a linux admin or docker expert).
This is ridiculous!
There isn't even a proper documentation that would mention, at least, that: "If you want the NextCloud to actually work - you need to DIY".
I'm using `docker-compose` to make it **easy** to deploy, update & backup apps.
If I need to build images myself - this gets complicated and, IMO, defeats the purpose of docker-compose & DockerHub.

I agree with my predecessors, that DockerHub's tags is the way to resolve that.

**Comment by FunctionDJ** [comment]
Until there's an official solution i'm using docker-compose to install ffmpeg into the container during creation, see https://github.com/nextcloud/docker/issues/1432#issuecomment-1326436158
