### ISSUE TITLE
Installation without user v2

### ISSUE THREAD

**Issue by km98333** [nextcloud/docker#631]
Hello guys,

I'm trying to install nextcloud on kubernetes with seperate mysql database in order to have scalable app. Issue that i face is each new pod requires new configuration which i tried to resolve with ENV, db configuration is fine but i'm always requested to configure admin user, when i provide ENV i get "account exists" when not i'm redirected to setup page. Is there any option to skip it because i want to use user which alredy exists in db.

**Comment by J0WI** [comment]
Have you already tried `'installed' => true,`?
https://docs.nextcloud.com/server/15/admin_manual/configuration_server/config_sample_php_parameters.html
