### ISSUE TITLE
Several security and compatibility issues

### ISSUE THREAD

**Issue by bd8392** [nextcloud/docker#635]
1. The __Host Prefix of the cookies isn't set properly -> leads to bad rating in security scan -> cant't influence this as the setting comes from the container
2. Nextcloud reports that the webserver isn't correctly configured to resolve
       /.well-known/caldav
       /.well-known/carddav
(using this Image with traefik reverse proxy)

**Comment by J0WI** [comment]
Duplicate of #632?

**Comment by marceljd** [comment]
See #527 for the .well-known issue, you have to change the .htaccess file.

**Comment by marceljd** [comment]
See #644 for Apache, the .well-known and HSTS errors will be gone. When you run Nextcloud behind a proxy you also need a trusted proxy entry in the config.php, I will create a PR for this next week. Both can be added with environment variables.

**Comment by mherzhoff** [comment]
> 
> 
> I was able to resolve the __Host prefix issue with this guide: https://docs.nextcloud.com/server/13/admin_manual/configuration_server/reverse_proxy_configuration.html

Have to admit you're right :-)
But adding only `overwriteprotocol` and `overwritehost` did the thing for me!

**Comment by SnowMB** [comment]
@bd8392 The Nextcloud 16 documentation includes a solution for the resolve issue without touching the .htaccess file: [click](https://docs.nextcloud.com/server/16/admin_manual/configuration_server/reverse_proxy_configuration.html)

Add the following labels to your nextcloud container: 
```
traefik.frontend.redirect.permanent: 'true'
traefik.frontend.redirect.regex: https://(.*)/.well-known/(card|cal)dav
traefik.frontend.redirect.replacement: https://$$1/remote.php/dav/
```

**Comment by bd8392** [comment]
Thanks that did the trick :-) the issue is resolved :-)
