### ISSUE TITLE
Dockerfiles are not working for COPY redis.config.php

### ISSUE THREAD

**Issue by kratan** [nextcloud/docker#642]
Hi,

docker/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/app/Dockerfile:
`COPY redis.config.php /usr/src/nextcloud/config/redis.config.php`

but actually there isnt a redis.config.php, so build will fail.

Greets

*Update*: seems to be addressed in pull request  #639

**Comment by tilosp** [comment]
Fixed via #639
