### ISSUE TITLE
Container for 15.0.4 needs to be created

### ISSUE THREAD

**Issue by SysEngDan** [nextcloud/docker#643]
v15.0.4 is available online but not in Docker Hub. Can someone please build v15.0.4 so it's available?

**Comment by mr-bolle** [comment]
You can create the image with this [Dockerfile](https://github.com/nextcloud/docker/blob/master/15.0/apache/Dockerfile) and follow command

`docker built -t test/nextcloud:15.0.4 Dockerfile`

And with this Tag you can uns the current image. Or you wait some hours if this will be officially released.

**Comment by mr-bolle** [comment]
Close

**Comment by J0WI** [comment]
Release have been made.
