### ISSUE TITLE
ENV support for SMB version

### ISSUE THREAD

**Issue by JonasBVS** [nextcloud/docker#648]
since SMBv1 is the default for the samba-client, and SMBv1 is depricated, i think it might be wise to support forcing the minimum SMB version to >=2, by the use of environments!?

- The example dockerfiles:
(https://github.com/nextcloud/docker/tree/master/.examples/dockerfiles/smb)

the /etc/samba/smb.conf needs to have these two lines added.

client min protocol = SMB2
client max protocol = SMB3

maybe this could be done setting SMB_MIN_VERSION=2 and SMB_MAX_VERSION=3.

another approach could be to let the settings be configurable from within nextcloud?

**Comment by cowai** [comment]
@JonasBVS Do you have occ files_external:notify working with this?

**Comment by JonasBVS** [comment]
I haven't had any problems, but i don't modify the files via the external filestorage... It is stored on SMB shares due to backup concerns and NFS being wonky

**Comment by J0WI** [comment]
Since SMB is not part of the image we won't add an additional ENV for it.
