### ISSUE TITLE
Imap errors after upgrading to 15.0.4

### ISSUE THREAD

**Issue by jorgensoares** [nextcloud/docker#649]
Hello,

After upgrading the image to 15.0.4 i start seeing this error on the logs every 15min:
```

  | PHP  Startup: Unable to load dynamic library 'imap.so' (tried:  /usr/local/lib/php/extensions/no-debug-non-zts-20170718/imap.so (Error  loading shared library libc-client.so.1: No such file or directory  (needed by  /usr/local/lib/php/extensions/no-debug-non-zts-20170718/imap.so)),  /usr/local/lib/php/extensions/no-debug-non-zts-20170718/imap.so.so  (Error loading shared library  /usr/local/lib/php/extensions/no-debug-non-zts-20170718/imap.so.so: No  such file or directory)) at Unknown#0
-- | --

```
this is my docker file:
FROM nextcloud:fpm-alpine

RUN set -ex; \
    \
    apk add --no-cache \
        ffmpeg \
        imagemagick \
        samba-client \
#       libreoffice \
    ;

RUN set -ex; \
    \
    apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        imap-dev \
        krb5-dev \
        libressl-dev \
        samba-dev \
        bzip2-dev \
        gmp-dev \
    ; \
    \
    docker-php-ext-configure imap --with-kerberos --with-imap-ssl; \
    docker-php-ext-install \
        bz2 \
        gmp \
        imap \
    ; \
    pecl install smbclient; \
    docker-php-ext-enable smbclient; \
    \
    runDeps="$( \
        scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
            | tr ',' '\n' \
            | sort -u \
            | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
    )"; \
    apk add --virtual .nextcloud-phpext-rundeps $runDeps; \
    apk del .build-deps

COPY redis.config.php /usr/src/nextcloud/config/redis.config.php

Thank you for the help! :)

**Comment by benurb** [comment]
I'm seeing the same problem and I'm not exactly sure what is causing it, but at least a possible fix is to make the alpine virtual package name unique. `.nextcloud-phpext-rundeps` is already used in the parent Dockerfile so you may change that to `.nextcloud-phpext-rundeps-imap` & `.nextcloud-phpext-rundeps-libreoffice`. Works for me

**Comment by jorgensoares** [comment]
@benurb  Thank you. That did the trick. I dont see the error anymore. Just curious about the root cause...

**Comment by benurb** [comment]
I guess the root cause is that virtual package names have to be unique, because they cannot be altered after creation. The alpine docs are not really helpful on this topic. The reason this problem showed up with nextcloud 15.0.4 probably is that alpine was updated from 3.8 to 3.9 with this release.
