### ISSUE TITLE
Dockerfile/Docker Compose for Complete Installation using Apache & PHP Web Server?

### ISSUE THREAD

**Issue by blackopscompany** [nextcloud/docker#653]
Hi guys, I'm really new in docker especially installing Nextcloud inside the Docker...

Could you help me to give me an example using Dockerfile/Docker Compose for Complete Secure Installation of Nextcloud using Apache & PHP Web Server just like in this example - > https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm ?

Thanks in advance :)

**Comment by SnowMB** [comment]
Do you want to use self signed certificates?

If you have a valid domain name, letsencrypt would be a better choice and is documented here:
https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache

**Comment by blackopscompany** [comment]
Thank you for your reply sir.

Yes, I would use self signed certificate because it would be my first time to install nextcloud inside the docker and i don't have a valid domain yet.

Does the link you've shared contained the full automatic installation for nextcloud docker with https enabled using self signed certificate?

Thank you.

**Comment by J0WI** [comment]
Here you can find an example with a self signed certificate:
https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm
