### ISSUE TITLE
MySQL Server can't connect

### ISSUE THREAD

**Issue by aocana** [nextcloud/docker#655]
hi, 

i have installed docker with NCP and seems that I'm faicing issues connecting with MySQL server when I restart this docker. 

here you have log with error;

```
Using 3137021952B for PHP,
Using 4 PHP threads,
Stopping redis-server: redis-server.,
Starting redis-server: redis-server.,
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")
```

the way to fix this issue is restarting again this docker, then I can access to NCP without problem.

any idea?

**Comment by aocana** [comment]
last report after try to restart mysql, now didn't work:

`019-02-23 13:16:35 4149958736 [ERROR] InnoDB: Tried to read 16384 bytes at offset 81920. Was only able to read 0.
2019-02-23 13:16:35 4149958736 [ERROR] InnoDB: Tried to read 16384 bytes at offset 81920. Was only able to read 0.
FAIL2019-02-23 13:16:35 f75b5850  InnoDB: Assertion failure in thread 4149958736 in file buf0rea.cc line 273
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to https://jira.mariadb.org/
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: http://dev.mysql.com/doc/refman/5.6/en/forcing-innodb-recovery.html
InnoDB: about forcing recovery.
190223 13:16:35 [ERROR] mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.

To report this bug, see https://mariadb.com/kb/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.

Server version: 10.1.37-MariaDB-0+deb9u1
key_buffer_size=16777216
read_buffer_size=131072
max_used_connections=0
max_threads=153
thread_count=0
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 351361 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x0
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0x0 thread_stack 0x30000
The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
information that should help you find out what is causing the crash.
2019-02-23 13:16:51 4147976272 [Note] InnoDB: innodb_empty_free_list_algorithm has been changed to legacy because of small buffer pool size. In
order to use backoff, increase buffer pool at least up to 20MB.

2019-02-23 13:16:51 4147976272 [Note] InnoDB: Using mutexes to ref count buffer pool pages
2019-02-23 13:16:51 4147976272 [Note] InnoDB: The InnoDB memory heap is disabled
2019-02-23 13:16:51 4147976272 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-02-23 13:16:51 4147976272 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2019-02-23 13:16:51 4147976272 [Note] InnoDB: Compressed tables use zlib 1.2.8
2019-02-23 13:16:51 4147976272 [Note] InnoDB: Using Linux native AIO
2019-02-23 13:16:51 4147976272 [Note] InnoDB: Using generic crc32 instructions
2019-02-23 13:16:51 4147976272 [Note] InnoDB: Initializing buffer pool, size = 128.0M
2019-02-23 13:16:51 4147976272 [Note] InnoDB: Completed initialization of buffer pool
2019-02-23 13:16:51 4147976272 [ERROR] InnoDB: Tried to read 16384 bytes at offset 81920. Was only able to read 0.
2019-02-23 13:16:51 4147976272 [ERROR] InnoDB: Tried to read 16384 bytes at offset 81920. Was only able to read 0.
FAIL2019-02-23 13:16:51 f73d1850  InnoDB: Assertion failure in thread 4147976272 in file buf0rea.cc line 273
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to https://jira.mariadb.org/
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: http://dev.mysql.com/doc/refman/5.6/en/forcing-innodb-recovery.html
InnoDB: about forcing recovery.
190223 13:16:51 [ERROR] mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.

To report this bug, see https://mariadb.com/kb/en/reporting-bugs

We will try our best to scrape up some info that will hopefully help
diagnose the problem, but since we have already crashed,
something is definitely wrong and this may fail.

Server version: 10.1.37-MariaDB-0+deb9u1
key_buffer_size=16777216
read_buffer_size=131072
max_used_connections=0
max_threads=153
thread_count=0
It is possible that mysqld could use up to
key_buffer_size + (read_buffer_size + sort_buffer_size)*max_threads = 351361 K  bytes of memory
Hope that's ok; if not, decrease some variables in the equation.

Thread pointer: 0x0
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 0x0 thread_stack 0x30000
The manual page at http://dev.mysql.com/doc/mysql/en/crashing.html contains
information that should help you find out what is causing the crash.`


any idea to recover the service?

**Comment by J0WI** [comment]
You should ask someone at MariaDB for issues with the database server.
How do you connect your NextCloud container to the database?
