### ISSUE TITLE
logfile-config ignored

### ISSUE THREAD

**Issue by boldt** [nextcloud/docker#656]
# Goal

Mount a separate log-folder for the log files, which is independent from the data folder.

# Issue

At the moment, I can view the logs by running

```bash
docker logs nextcloud
```
[The documentation provides the following example the following](https://docs.nextcloud.com/server/15/admin_manual/configuration_server/occ_command.html?highlight=add%20missing%20indices#logging-commands):

```bash
"log_type" => "owncloud",
"logfile" => "nextcloud.log",
"loglevel" => "3",
"logdateformat" => "F d, Y H:i:s",
```

I added the following to my `config.php`, which is mounted into my docker container:

```bash
"loglevel" => "0",
"logfile" => "nextcloud-new.log",
```

Unfortunately, the logs are not written to `nextcloud-new.log`. They are still written to syslog and the `nextcloud.log`.

**Comment by J0WI** [comment]
Do you use the apache or fpm variant?

**Comment by boldt** [comment]
I'm using the image with the name `nextcloud:16.0.1`, so it should be apache.

**Comment by J0WI** [comment]
`owncloud` is not a valid `log_type`, try again with `file`.
https://docs.nextcloud.com/server/16/admin_manual/configuration_server/logging_configuration.html#log-type
