### ISSUE TITLE
413 Payload Too Large when using simple SSL recommendation

### ISSUE THREAD

**Issue by bluepuma77** [nextcloud/docker#664]
I am using `Make your Nextcloud available from the internet` with `HTTPS - SSL encryption` and when uploading files larger 1MB I see the HTTP status 413 in the browser logs. 

Checking closed issues I assume it's not nextcloud itself, but the nginx proxy in between. As you recommend using it for SSL encryption, it would be great to have a direct hint in the docs on how to fix this to have a seamless start. 

Or at least have a stronger warning indicator in the main readme that problems like the 1MB limit will occur with a simple setup like below.

```
docker run --detach \
  --name nginx-proxy \
  --restart=unless-stopped \
  --publish 80:80 \
  --publish 443:443 \
  --volume /etc/nginx/certs \
  --volume /etc/nginx/vhost.d \
  --volume /usr/share/nginx/html \
  --volume /var/run/docker.sock:/tmp/docker.sock:ro \
  jwilder/nginx-proxy

docker run --detach \
  --name nginx-crypt \
  --restart=unless-stopped \
  --volumes-from nginx-proxy \
  --volume /var/run/docker.sock:/var/run/docker.sock:ro \
  jrcs/letsencrypt-nginx-proxy-companion

docker run --detach \
  --name nextcloud \
  --restart=unless-stopped \
  --volume /data/nextcloud:/var/www/html \
  --env "VIRTUAL_HOST=website.tld" \
  --env "LETSENCRYPT_HOST=website.tld" \
  --env "LETSENCRYPT_EMAIL=email@website.tld" \
  nextcloud
```

**Comment by SnowMB** [comment]
Hey please have a look at: https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache

In the `proxy` directory you will see, that we build a custom docker image for the image proxy. It just copies one file, the `uploadsize.conf` into the proxy container. 

If you don't want to use a custom build container, you can also mount the file from your host like this: 
(Assuming you copied the `uploadsize.conf`to `/data/uploadsize.conf`)
```diff
docker run --detach \
  --name nginx-proxy \
  --restart=unless-stopped \
  --publish 80:80 \
  --publish 443:443 \
  --volume /etc/nginx/certs \
  --volume /etc/nginx/vhost.d \
  --volume /usr/share/nginx/html \
  --volume /var/run/docker.sock:/tmp/docker.sock:ro \
+  --volume /data/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro \
  jwilder/nginx-proxy
```

**Comment by bluepuma77** [comment]
I found a hack I used like 3 years ago. This needs to be done every time you re-create the container.

```
# get a bash within the docker container
docker exec -it nginx-proxy bash

# change parameter within container
sed -i 's/.*sendfile.*/sendfile on;\nclient_max_body_size 512M;/' /etc/nginx/nginx.conf
cat /etc/nginx/nginx.conf
nginx -s reload
```
