### ISSUE TITLE
false positives at OWASP

### ISSUE THREAD

**Issue by nicosmaris** [nextcloud/docker#666]
I am using cloudflare WAF and the following setup:
https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache

When I sync a big file (about 800MB) the sync failed as it is stopped by the WAF due to the following faIse positives:

981176	Inbound Anomaly Score Exceeded (Total Score: 64, SQLi=13, XSS=15): Last Matched Message: IE XSS Filters - Attack Detected.	OWASP Inbound Blocking	Filter
960024	Meta-Character Anomaly Detection Alert - Repetative Non-Word Characters	OWASP SQL Injection Attacks	Filter
960032	Method is not allowed by policy	OWASP HTTP Policy	Filter
960901	Invalid character in request	OWASP Protocol Violations	Filter
960904	Request Containing Content, but Missing Content-Type header	OWASP Protocol Anomalies	Filter
973300	Possible XSS Attack Detected - HTML Tag Handler	OWASP XSS Attacks	Filter
973334	IE XSS Filters - Attack Detected.	OWASP XSS Attacks	Filter
973335	IE XSS Filters - Attack Detected.	OWASP XSS Attacks	Filter
981018	End XSS pattern check	OWASP XSS Attacks	Filter
981133	Prequalify PM	OWASP Generic Attacks	Filter
981231	SQL Comment Sequence Detected.	OWASP SQL Injection Attacks	Filter
981240	Detects MySQL comments, conditions and ch(a)r injections	OWASP SQL Injection Attacks	Filter
981242	Detects classic SQL injection probings 1/2	OWASP SQL Injection Attacks	Filter
981243	Detects classic SQL injection probings 2/2	OWASP SQL Injection Attacks	Filter
981245	Detects basic SQL authentication bypass attempts 2/3	OWASP SQL Injection Attacks	Filter
981257	Detects MySQL comment-/space-obfuscated injections and backtick termination	OWASP SQL Injection Attacks	Filter
981318	SQL Injection Attack: Common Injection Testing Detected	OWASP SQL Injection Attacks	Filter
981319	SQL Injection Attack: SQL Operator Detected	OWASP SQL Injection Attacks	Filter
2000001	Skip LFI Rules	OWASP Slr Et Lfi Attacks	Filter
2000004	Skip SQLi Rules	OWASP Slr Et SQLi Attacks	Filter
2000006	Skip XSS Rules	OWASP Slr Et XSS Attacks

When disabling the WAF, the sync works fine.

**Comment by J0WI** [comment]
This is probably not related to the Nextcloud image itself and we can't really do much about false positives.
