### ISSUE TITLE
Implementing more important environment variables

### ISSUE THREAD

**Issue by Askotion** [nextcloud/docker#668]
Hello,

is it possible to add some important environment variables from here: 
https://github.com/owncloud-docker/base#available-environment-variables

For example, the OVERWRITEPROTOCOL variable needs to be set to https to get certain things to work when using nextcloud behind an Nginx proxy. This can be done by using the PHP occ command but only if the nextcloud container is fully running. 

I wrote some bash scripts that automatically copy some files and my docker-compose.yml into a folder.  But it's not possible to run the PHP occ command inside the script as it says nextcloud isn't ready yet. (even with a 30-second sleep timer). 
I'm gettings this error:

```
Nextcloud is not installed - only a limited number of commands are available
                 
  There are no commands defined in the "config:system" namespace.  
```

I've tried to set environment variables using the NC_ prefix but I realized that only works for already present variables in the config.php (not for new / not added ones).

It would help a lot if it's somehow possible to get more then the available 10 environment variables.

EDIT:
I just found this PR which would solve the problem but I don't know if it's being continued?
https://github.com/nextcloud/docker/pull/527

**Comment by pnbecker** [comment]
I had to set the overwriteprotocol and overweritehost to https and my url to get the iOS and macOS apps working. I would highly appreciate to be able to set those as environment variables via docker-compose.

**Comment by J0WI** [comment]
6d2390726fe7110b406c447d48aa345fc9d07122
