### ISSUE TITLE
Can't upload big files.

### ISSUE THREAD

**Issue by li2xi** [nextcloud/docker#671]
Hi, I can't upload big files( bigger then a few MBs, I think ) on nextcloud.
When i upload, I got this on docker log.

`[Mon Mar 04 01:06:05.009187 2019] [authz_core:error] [pid 42] [client 172.17.0.1:48488] AH01630: client denied by server configuration: /var/www/html/config`

Here is my docker command
`docker run -d --name='nextcloud' --net='bridge' -e TZ="Asia/Shanghai" -e HOST_OS="Unraid" -p '7788:80/tcp' -v '/mnt/user/Nextcloud/':'/var/www/html/data':'rw' -v '/mnt/user/Config/nextcloud':'/var/www/html/config':'rw' -v '/mnt/user/Config/nextcloud_apps':'/var/www/html/custom_apps':'rw' 'nextcloud' `

And here is my .htaccess below

<ifModule mod_authz_core.c>
Require all denied
</ifModule>

<FilesMatch ".ocdata">
       <IfModule mod_authz_core.c>
          Require all granted
       </IfModule>
</FilesMatch>

# line below if for Apache 2.2
<ifModule !mod_authz_core.c>
deny from all
Satisfy All
</ifModule>

# section for Apache 2.2 and 2.4
<ifModule mod_autoindex.c>
IndexIgnore *
</ifModule>

**Comment by iMartyn** [comment]
This is almost certainly to do with `upload_max_file_size` which is not overridden in the dockerfile (at least for apache).

Given that nextcloud is mostly used for files, this seems like something that should be overridable in the entrypoint.sh.

There should be a way of overriding this in the htaccess file, I'm just researching this now.

**Comment by iMartyn** [comment]
So for me, I noticed that although the `upload_max_file_size` is not overridden in the docker image, it is overridden in the settings of nextcloud, and this works.  Unfortunately I also had a reverse proxy configuration (kubernetes nginx ingress controller) and that was actually the problem.

**Comment by li2xi** [comment]
@iMartyn fixed. turned out to be a bug on my router...
