### ISSUE TITLE
Support Redis Passwords

### ISSUE THREAD

**Issue by GuyPaddock** [nextcloud/docker#672]
The new environment-driven Redis config introduced in d3cd3b812fc75ffaa314c6d56f5343830e747774 is great and all, but it would be even better if it supported the `password` option which is needed in most secure setups.

In our current setup, our image is based on the Nextcloud 15 official image but we were already writing-out a Redis configuration. So, the new config file caught us by surprise since we started receiving the following errors:

```
RedisException: NOAUTH Authentication required. in /var/www/html/lib/private/Memcache/Redis.php:55
Stack trace:
#0 /var/www/html/lib/private/Memcache/Redis.php(55): Redis->get('...')
#1 /var/www/html/lib/autoloader.php(150): OC\Memcache\Redis->get('OC_User')
#2 [internal function]: OC\Autoloader->load('OC_User')
#3 /var/www/html/lib/private/User/Session.php(223): spl_autoload_call('OC_User')
#4 /var/www/html/lib/private/legacy/app.php(346): OC\User\Session->getUser()
#5 /var/www/html/lib/private/legacy/app.php(113): OC_App::getEnabledApps()
#6 /var/www/html/lib/base.php(654): OC_App::loadApps(Array)
#7 /var/www/html/lib/base.php(1068): OC::init()
#8 /var/www/html/console.php(46): require_once('/var/www/html/l...')
#9 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

Deleting `redis.config.php` from our image during the Dockerfile build worked for us, but others trying to use the stock image will have difficulty if a password is needed to access Redis.

**Comment by J0WI** [comment]
Would you like to provide a PR?

**Comment by algakzru** [comment]
> 
> 
> Would you like to provide a PR?

@J0WI 
Sent a PR - https://github.com/nextcloud/docker/pull/856

**Comment by pierreozoux** [comment]
Looks like the PR is merged :). closing.
