### ISSUE TITLE
Fix Remaining `woff` Font Loading Issues

### ISSUE THREAD

**Issue by GuyPaddock** [nextcloud/docker#674]
In #586, some (but not all) NGinx configuration examples were modified to allow loading of `.woff2` font files. 

However, the fix in that PR is not complete because it did not fix _all_ of the examples. The following examples were not corrected:
- [`.examples/docker-compose/insecure/mariadb-cron-redis/fpm/web/nginx.conf`](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb-cron-redis/fpm/web/nginx.conf#L123)
- [`.examples/docker-compose/insecure/mariadb/fpm/web/nginx.conf`](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb/fpm/web/nginx.conf#L123)
- [`.examples/docker-compose/insecure/postgres/fpm/web/nginx.conf`](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/postgres/fpm/web/nginx.conf#L123)

**Comment by J0WI** [comment]
Thanks!
