### ISSUE TITLE
Questions about mariadb-cron-redis fpm Docker image : localtime, cron, network

### ISSUE THREAD

**Issue by CedricGoby** [nextcloud/docker#681]
Hi,

I'm new to Docker and I'd like to migrate my existing Nextcloud installation to Docker.

I have a few questions about the **docker-compose.yml** file before trying this image : https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm

* I see a lot of people in the Nextcloud forum and elsewhere adding this volume in containers

       - /etc/localtime:/etc/localtime:ro
What is it for, is this really useful and if yes why this is not mentioned in the official **docker-compose.yml** file ?

* In the **docker-compose.yml** file there is the following container

      cron:
        image: nextcloud:fpm-alpine
        restart: always
        volumes:
          - nextcloud:/var/www/html
        entrypoint: /cron.sh
        depends_on:
          - db
          - redis
What is the purpose of this container and how to use it ?

* There are 2 networks mentioned in the **docker-compose.yml** file

      - proxy-tier
      - default

Should I declare those networks before using the image ? And how ?

Thanks for your help.

**Comment by SnowMB** [comment]
Hey,

Hope I can clear a few things. 

2: The cron container. This is a long discussion going on. On the one hand docker containers are preferred that use one process per container. This has the advantage that failing containers can easily be detected / debugged and the docker log is less cluttered. On the other hand many people prefer to combine a service in one container, thus combining necessary or convenient additional processes into one image. The nextcloud image follows the one process per container rule. So for running cron we start an additional container but it is changed to run cron as process. There is cron pre-installed in the image and the recommended crontab (15 minutes) is already created. 

In the examples section you can find a derived dockerfile that combines cron and apache / nginx into one image using supervisord to run both processes in parallel.

3. No, the networks are declared in the docker-compose file. They will automatically be created when you run `docker-compose up - d`.

**Comment by CedricGoby** [comment]
Thank you
