### ISSUE TITLE
Get recent files using an API 

### ISSUE THREAD

**Issue by SibeeshVenu** [nextcloud/docker#685]
I am just trying to get all the recent files created by the user using the Nextcloud API. I am able to get the files, upload the files, download the files etc (for example using this API `/nextcloud/remote.php/dav/files/{UserName}`). But I could not find any API which can get the recent files. I am using the Nextcloud version 14. I am looking for an API like `/nextcloud/remote.php/dav/files/{UserName}/recent`. Any help is really appreciated. Thank you.

**Comment by tilosp** [comment]
this is not related to the docker image. For general nextcloud questions use the [forum](https://help.nextcloud.com) or  ask on [IRC](https://webchat.freenode.net/?channels=nextcloud).
