### ISSUE TITLE
fpm container file ownership and permission changes

### ISSUE THREAD

**Issue by scottmckenzie** [nextcloud/docker#69]
The nextcloud:11.0.3-fpm container has changed the ownership and permissions of the files in /var/www/html.  This prevents my nginx container that has mounted the /var/www/html volume from accessing the files:
> 017/05/07 02:45:14 [crit] 7#7: *1718 stat() "/var/www/html/status.php" failed (13: Permission denied),

The files in nextcloud:11.0.3-fpm are owned by root:www-data and are not world readable:
> $ docker run -it --rm nextcloud:11.0.3-fpm ls -lha /var/www/html/version.php
> -rw-r----- 1 root www-data 380 Apr 22 06:29 /var/www/html/version.php

Previously (<=nextcloud:11.0.2-fpm) the files were owned by www-data:nogroup and were world readable.
> $ docker run -it --rm nextcloud:11.0.2-fpm ls -lha /var/www/html/version.php
> -rw-r--r-- 1 www-data nogroup 277 Feb 26 19:44 /var/www/html/version.php

Was this changed intended?

**Comment by tilosp** [comment]
This change was intentional they were set according to https://docs.nextcloud.com/server/11/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions. 
But why is this a problem the files are group readable by www-data. Are you using the official nginx image?

**Comment by scottmckenzie** [comment]
I'm using the official nginx:alpine container.  There is no www-data group and the nginx user is only a member of it's own group:
> $ docker run -it --rm nginx:alpine grep www /etc/group
> $ docker run -it --rm nginx:alpine grep nginx /etc/group
> nginx: x:101:nginx

**Comment by tilosp** [comment]
@scottmckenzie This is a problem we need to fix. For now you can use this Docker file:
 ```Dockerfile
FROM nextcloud:fpm

RUN find /usr/src/nextcloud/ -type f -print0 | xargs -0 chmod 0644 \
  && find /usr/src/nextcloud/ -type d -print0 | xargs -0 chmod 0755
```
@pierreozoux @cyphar How should we fix this? Just make everything except config and data world-readable?

**Comment by loki666** [comment]
still not working on my side are there any addtional options to pass to docker nextcloud fpm / nginx container ?

**Comment by tilosp** [comment]
The changes of #131 are not yet on docker hub

**Comment by loki666** [comment]
arf ok

**Comment by loki666** [comment]
how can I tell if it's in on docker hub ?

**Comment by tilosp** [comment]
When it is merged into [docker-library/official-images](https://github.com/docker-library/official-images) which it was in  https://github.com/docker-library/official-images/pull/3378
