### ISSUE TITLE
The database is missing some indexes / BigInt

### ISSUE THREAD

**Issue by robclay** [nextcloud/docker#690]
I just updated to 15.05 from 13.something.  

I get the following warning:
```

The database is missing some indexes. Due to the fact that adding indexes on big tables could take some time they were not added automatically. By running "occ db:add-missing-indices" those missing indexes could be added manually while the instance keeps running. Once the indexes are added queries to those tables are usually much faster.

    Missing index "owner_index" in table "share".
    Missing index "initiator_index" in table "share".

Some columns in the database are missing a conversion to big int. Due to the fact that changing column types on big tables could take some time they were not changed automatically. By running 'occ db:convert-filecache-bigint' those pending changes could be applied manually. This operation needs to be made while the instance is offline. For further details read the documentation page about this.

    activity.activity_id
    activity.object_id...

```
Should I try and correct these, as I assume we need to do the work on the persistent data scheme?  Or would the container figure out when it needed to upgrade?

Thanks,
Robert

**Comment by J0WI** [comment]
I'm not sure if we should proactively fix it in the container.
btw: you should be careful when upgrading, skipping major releases is not supported.

**Comment by robclay** [comment]
@J0WI , Thanks for the response.  That was my question - I am assuming that my persistent data needs some database work done to it...  So should I try to run some command to fix that?

When upgrading, I am using the following pull request `docker-compose -f ncqnap.yml build --pull` where ncqnap.yml is my docker-compose file.

What should the syntax be if I was trying to go from 13 to 14?  And should I redeploy a 14 container to make sure I am not skipping anything?

Thanks for any and all insights!

**Comment by J0WI** [comment]
You can run `occ db:add-missing-indices` and `occ db:convert-filecache-bigint` with `docker exec` to fix it.

You could stick to `nextcloud:15` in your `ncqnap.yml`. But if you update more frequently than major updates are released it shouldn't be problematic.

**Comment by robclay** [comment]
Thanks @J0WI , I ran those occ commands and all seems fine.  Thanks for your assistance, and I will start updating more frequently.  (I have no excuse, I am running the docker-compose, and it takes all of 1 minute to keep it up to date.
