### ISSUE TITLE
docker-compose update not actually updating software?

### ISSUE THREAD

**Issue by K73SK** [nextcloud/docker#694]
Ok... So I have a docker-compose file which contains all the info I need. However, I've tried following the instructions to update the current instance of Nextcloud that I have. The weird thing is, I don't know whether it's truly updating the software or not.

When I go to the GUI's update section, it says I'm on 15.0.4 and that there's an update available for 15.0.5. So I go into the terminal and type the two commands from the README:
```
 docker-compose pull
 docker-compose up -d
```
Afterwards, I confirm the version with `docker inspect <image>`:
`"NEXTCLOUD_VERSION=15.0.5"`

However, when I go into the UI and to the update section, it still says I'm on 15.0.4. with an update available for 15.0.5. 

Is there a step that's missing from the README or is something wrong w/ my installation?

**Comment by SnowMB** [comment]
Are you running a custom dockerfile with a different command? Then make sure that you set `NEXTCLOUD_UPDATE=1` in your environment variables. (as stated [here](https://github.com/nextcloud/docker#auto-configuration-via-environment-variables))

**Comment by K73SK** [comment]
I thought I didn't have a Dockerfile when I read that but I forgot I had it in a subfolder and was pointing to it to be built by the docker compose file lol. Got it working now, thank you 🙂
