### ISSUE TITLE
LDAP with fpm-alpine?

### ISSUE THREAD

**Issue by laueran** [nextcloud/docker#697]
Is php-ext enabled in nextcloud:fpm-alpine? If it isn't, is it possible to do so?
I have tried adding

RUN apk --update add \
    openldap-dev \
    docker-php-ext-configure ldap  --with-libdir=lib/ && \
    docker-php-ext-install ldap&& \
    rm -rf /var/cache/apk/* 

to the Dockerfile (web), but could not get it to work.
I am using the mariadb-cron-redis with-nginx-proxy docker-compose.yml from the examples.
Sorry, if this i the wrong place to askI am a newbie with docker.

**Comment by laueran** [comment]
Never mind, now it works, it was a configuration error, sorry!

**Comment by angrymeir** [comment]
@laueran Could you please describe how you configured the compose in order to get LDAP working?
