### ISSUE TITLE
any way to solve the table issue?

### ISSUE THREAD

**Issue by isnanx** [nextcloud/docker#701]
Recently I created nextcloud via docker with image nextcloud:fpm-alpine and after it was finished, warnings appeared.

**Some columns in the database are missing a conversion to big int. Due to the fact that changing column types on big tables could take some time they were not changed automatically. By running 'occ db:convert-filecache-bigint' those pending changes could be applied manually. This operation needs to be made while the instance is offline. For further details read the documentation page about this.**

- **filecache.mtime**

- **filecache.storage_mtime**

The documentation tells that I can just execute the command **sudo -u www-data php occ db:convert-filecache-bigint**, but there is no sudo in the image, so do I have to change another image or any other way to eliminate this warnings? thanks.

**Comment by SnowMB** [comment]
You don't need sudo, just use `docker-compose exec -u USER app COMMAND`.

**Comment by isnanx** [comment]
> You don't need sudo, just use `docker-compose exec -u USER app COMMAND`.
> 
> See https://docs.docker.com/compose/reference/exec/

Thank you so much! it works.
