### ISSUE TITLE
command line support inside the container

### ISSUE THREAD

**Issue by Thijzer** [nextcloud/docker#705]
command line support inside the container.

I couldn't find any support for this so I thought I would share this here.

how to execute cli commands inside the official docker container.

```
docker exec -i nextcloud su - www-data -s /bin/bash -c "/var/www/html/occ"
```

The main issue I think is that we don't have an actual user that is in sync the host.

**Comment by J0WI** [comment]
You should use the `--user` flag of `docker exec`, see also https://github.com/nextcloud/server/pull/13336
