### ISSUE TITLE
unrelease 15.0.6 from hub?

### ISSUE THREAD

**Issue by r2evans** [nextcloud/docker#709]
Since a hotfix is allegedly being released soon (ref: https://github.com/nextcloud/server/issues/14978#issuecomment-480880692), and 15.0.6 is not available on the download or changelog pages, would it make sense to un-release 15.0.6 from Docker Hub? Just a suggestion, as the release state seems inconsistent/incomplete at the moment.

**Comment by J0WI** [comment]
I'm not aware of a way to revert a release. You should just upgrade to `15.0.7`.
