### ISSUE TITLE
ServerTokens enabled in Apache Image

### ISSUE THREAD

**Issue by maxmeyer** [nextcloud/docker#71]
# Current

![error](https://cloud.githubusercontent.com/assets/114236/25792598/bf15039e-33c7-11e7-9116-72a9c60e8c86.png)

The current configuration of the apache does not have the ServerToken disabled.

# Expected

The apache webserver does not show the server version etc. in error messages + HTTP responses.

# Environment

~~~
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
nextcloud                    11                  76c9c2e2e771        2 days ago          622MB
~~~

**Comment by j-0ck3l** [comment]
Im not sure, if this is 100% linked, but I always get this message shown here? As I'm new to docker, I am not sure if any configuration could be fixed from my side. (But definitly can't figure out what)

I am using `nextcloud:11.0.3-apache`

The error message actually shows port 8080, which I have mapped to the exposed port.

Inside the container, same HTTP state occurs. Htaccess file in /var/www/html has got the right permissions set :(

**Comment by maxmeyer** [comment]
It's not link to this as I'm just want the guys to provide an image which does not expose the version numbers of the HTTP to the outer world.

**Comment by maxmeyer** [comment]
Besides this, I also got this message, but did not have time to find the reason for this. Would you mind to open another issue for this?
