### ISSUE TITLE
Stable Tag missing since 15.0.6

### ISSUE THREAD

**Issue by klixxezitz** [nextcloud/docker#711]
Hej guys,

I was using the "stable" tag in my docker-compose file.
However, it seems that this tag is no longer available.

Is this a wanted behaviour?

Best Regards,
Tim.

**Comment by mstenz** [comment]
same issue found here. just wanted to pull newest update and experienced this issue.

**Comment by mstenz** [comment]
> 
> 
> Is this the reason why `docker-compose pull` won't upgrade to 15.0.7?

as long as you use nextcloud:stable

**Comment by MartiniMoe** [comment]
> > Is this the reason why `docker-compose pull` won't upgrade to 15.0.7?
> 
> as long as you use nextcloud:stable

Yes I do. Okay then, I have the same question as @klixxezitz :)

**Comment by J0WI** [comment]
This has been is fixed with https://github.com/docker-library/official-images/commit/8e64b852a469c99d0906ac6876537a98edd6fcc0
@tilosp can we ensure that this does not happen again?

**Comment by klixxezitz** [comment]
Confirmed - using the stable tag now pulls version 15.0.7

**Comment by tilosp** [comment]
@J0WI yes by automating it (https://github.com/nextcloud/updater_server/issues/68)
