### ISSUE TITLE
Nextcloud Upgrade 13 -> 15

### ISSUE THREAD

**Issue by MVTec** [nextcloud/docker#722]
Hello, 
I am trying to upgrade Nextcloud 13 to 15 using docker-compose from
https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/postgres/apache/
I see database version mismatch in logs, expected 11 but created using 10.
So I got a fresh install and it runs , now I want to import DB , for this I have created dump from version 13 container (superuser postgres) and trying to import in version 15 container. But it doesn't have any superuser. Because of which statements fail. Please suggest how to proceed.
```
 # docker exec -ti nextcloud15_db_1 psql -U nextcloud
psql (11.2)
Type "help" for help.

nextcloud=> \du
           List of roles
 Role name | Attributes | Member of
-----------+------------+-----------
 nextcloud |            | {}

```
```
ERROR:  syntax error at or near "pg_dumpall"
LINE 1: pg_dumpall: executing SELECT pg_catalog.set_config('search_p...
        ^
SET
SET
ERROR:  syntax error at or near "pg_dumpall"
LINE 1: pg_dumpall: executing SELECT oid, rolname, rolsuper, rolinhe...
        ^
ERROR:  must be superuser to alter superusers
ERROR:  syntax error at or near "pg_dumpall"
LINE 1: pg_dumpall: executing SELECT provider, label FROM pg_catalog...
        ^
ERROR:  role "postgres" does not exist
ERROR:  syntax error at or near "pg_dumpall"
LINE 1: pg_dumpall: executing SELECT setconfig[1] FROM pg_db_role_se...
        ^
ERROR:  syntax error at or near "pg_dumpall"
LINE 1: pg_dumpall: executing SELECT setconfig[1] FROM pg_db_role_se...
        ^
ERROR:  database "nextcloud_db" does not exist
```

**Comment by MVTec** [comment]
I was able to get it running, however it is not fully functional, doesn't allow deleting user , on many operations displays "Interner Serverfehler"
screenshot attached
![grafik](https://user-images.githubusercontent.com/37447825/56728845-0dec1400-6754-11e9-8744-5114962348a8.png)

moreover there are discrepancies in database structure , it seems some tables habe been deleted 
´´´
admin_sections
admin_settings
group_folders
group_folders_applicable
personal_sections
personal_settings
registration
users_external

´´´
and new added like 
´´´
calendar_invitations
calendar_resources
calendar_rooms
directlink
ldap_group_mapping
ldap_group_mapping
ldap_user_mapping
twofactor_providers
whats_new
´´´

Please suggest how to proceed

**Comment by J0WI** [comment]
Skipping major releases is not supported. Please upgrade 13 -> 14 -> 15.

**Comment by bonanza123** [comment]
Maybe you want to head over to https://help.nextcloud.com/ for help. Also, jumping over releases is usually not advised. Mabe 13->14->15 would have worked better.

**Comment by MVTec** [comment]
Thanks a lot , it worked flawlessly
