### ISSUE TITLE
No Nextcloud 16 apache image

### ISSUE THREAD

**Issue by ntimo** [nextcloud/docker#725]
Hello,
I am wondering why there is no apache Docker image for NextCloud 16 on the Docker hub. Has this some kind of reason? And will the image be added soon?

Thanks

**Comment by tilosp** [comment]
yes there is a reason, @tilosp-bot was broken. It's fixed now. 
Now we are waiting for https://github.com/docker-library/official-images/pull/5824 to get merged.
This will probably happen on the next working-day.

**Comment by ntimo** [comment]
The image is now available :)
