### ISSUE TITLE
Port running on 80 instead of 9000

### ISSUE THREAD

**Issue by mcrapts** [nextcloud/docker#74]
I couldn't access anything on port 9000. I had to append -p 9000:80 to get the container working. Am I doing something wrong, or is the documentation not up-to-date?

**Comment by tilosp** [comment]
The docs are outdated. We are working on a fix in #53. 
If you specify no image tag you get the apache version of this image which has a webserver running on port 80.

**Comment by mcrapts** [comment]
Thanks for the answer, hope it gets merged soon.
