### ISSUE TITLE
Internal links are http instead of https

### ISSUE THREAD

**Issue by binarious** [nextcloud/docker#742]
I'm using the [nginx-proxy-mariadb-cron-redis-fpm](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm) example. Internal links are `http://` instead of `https://`. This is problematic when resources (audio files, images) are loaded via http and produce a mixed content warning.

Is seems like this is a proxy configuration issue that results in Nextcloud not knowing that it's served via https.

<details>
  <summary>docker-compose.yml</summary>

    version: '3'

    services:
      db:
        image: mariadb:10.4
        command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
        restart: always
        volumes:
          - db:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=XXX
        env_file:
          - db.env

      redis:
        image: redis:5.0-alpine
        restart: always

      app:
        build: ./app
        restart: always
        volumes:
          - nextcloud:/var/www/html
        environment:
          - MYSQL_HOST=db
        env_file:
          - db.env
        depends_on:
          - db
          - redis

      web:
        build: ./web
        restart: always
        volumes:
          - nextcloud:/var/www/html:ro
        environment:
          - VIRTUAL_HOST=XXX
          - LETSENCRYPT_HOST=XXX
          - LETSENCRYPT_EMAIL=XXX
        depends_on:
          - app
        networks:
          - proxy-tier
          - default

      cron:
        build: ./app
        restart: always
        volumes:
          - nextcloud:/var/www/html
        entrypoint: /cron.sh
        depends_on:
          - db
          - redis

      proxy:
        build: ./proxy
        restart: always
        ports:
          - 80:80
          - 443:443
        labels:
          com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
        volumes:
          - certs:/etc/nginx/certs:ro
          - vhost.d:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
          - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
          - proxy-tier

      letsencrypt-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        volumes:
          - certs:/etc/nginx/certs
          - vhost.d:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
          - /var/run/docker.sock:/var/run/docker.sock:ro
        networks:
          - proxy-tier
        depends_on:
          - proxy

    volumes:
      nextcloud:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: "${PWD}/volumes/nextcloud"
      db:
      certs:
      vhost.d:
      html:

    networks:
      proxy-tier:
</details>

<details>
  <summary>nginx.conf</summary>

    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        set_real_ip_from  10.0.0.0/8;
        set_real_ip_from  172.16.0.0/12;
        set_real_ip_from  192.168.0.0/16;
        real_ip_header    X-Real-IP;

        #gzip  on;

        upstream php-handler {
            server app:9000;
        }

        server {
            listen 80;

            # Add headers to serve security related headers
            # Before enabling Strict-Transport-Security headers please read into this
            # topic first.
            # add_header Strict-Transport-Security "max-age=15768000;
            # includeSubDomains; preload;";
            #
            # WARNING: Only add the preload option once you read about
            # the consequences in https://hstspreload.org/. This option
            # will add the domain to a hardcoded list that is shipped
            # in all major browsers and getting removed from this list
            # could take several months.
            add_header X-Content-Type-Options nosniff;
            add_header X-XSS-Protection "1; mode=block";
            add_header X-Robots-Tag none;
            add_header X-Download-Options noopen;
            add_header X-Permitted-Cross-Domain-Policies none;
            add_header Referrer-Policy no-referrer;

            root /var/www/html;

            location = /robots.txt {
                allow all;
                log_not_found off;
                access_log off;
            }

            # The following 2 rules are only needed for the user_webfinger app.
            # Uncomment it if you're planning to use this app.
            #rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
            #rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json
            # last;

            location = /.well-known/carddav {
                return 301 $scheme://$host/remote.php/dav;
            }
            location = /.well-known/caldav {
                return 301 $scheme://$host/remote.php/dav;
            }

            # set max upload size
            client_max_body_size 10G;
            fastcgi_buffers 64 4K;

            # Enable gzip but do not remove ETag headers
            gzip on;
            gzip_vary on;
            gzip_comp_level 4;
            gzip_min_length 256;
            gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
            gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;

            # Uncomment if your server is build with the ngx_pagespeed module
            # This module is currently not supported.
            #pagespeed off;

            location / {
                rewrite ^ /index.php$request_uri;
            }

            location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
                deny all;
            }
            location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
                deny all;
            }

            location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+)\.php(?:$|/) {
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                # fastcgi_param HTTPS on;
                #Avoid sending the security headers twice
                fastcgi_param modHeadersAvailable true;
                fastcgi_param front_controller_active true;
                fastcgi_pass php-handler;
                fastcgi_intercept_errors on;
                fastcgi_request_buffering off;
            }

            location ~ ^/(?:updater|ocs-provider)(?:$|/) {
                try_files $uri/ =404;
                index index.php;
            }

            # Adding the cache control header for js and css files
            # Make sure it is BELOW the PHP block
            location ~ \.(?:css|js|woff|svg|gif)$ {
                try_files $uri /index.php$request_uri;
                add_header Cache-Control "public, max-age=15778463";
                # Add headers to serve security related headers (It is intended to
                # have those duplicated to the ones above)
                # Before enabling Strict-Transport-Security headers please read into
                # this topic first.
                # add_header Strict-Transport-Security "max-age=15768000;
                #  includeSubDomains; preload;";
                #
                # WARNING: Only add the preload option once you read about
                # the consequences in https://hstspreload.org/. This option
                # will add the domain to a hardcoded list that is shipped
                # in all major browsers and getting removed from this list
                # could take several months.
                add_header X-Content-Type-Options nosniff;
                add_header X-XSS-Protection "1; mode=block";
                add_header X-Robots-Tag none;
                add_header X-Download-Options noopen;
                add_header X-Permitted-Cross-Domain-Policies none;
                add_header Referrer-Policy no-referrer;

                # Optional: Don't log access to assets
                access_log off;
            }

            location ~ \.(?:png|html|ttf|ico|jpg|jpeg)$ {
                try_files $uri /index.php$request_uri;
                # Optional: Don't log access to other assets
                access_log off;
            }
        }

    }
</details>

**Comment by oli-mo** [comment]
Hey there,
did you try to set the **overwriteprotocol** option to **https**?
You can find that in the config.php. For a reference see [config.sample.php](https://github.com/nextcloud/server/blob/master/config/config.sample.php#L451).

**Comment by binarious** [comment]
Yes, that seems to be a workaround. Thank you. I still think this needs to be addressed in a proxy configuration or similar. Therefore keeping the issue open.

**Comment by pnbecker** [comment]
I was no able to register the iOS and macOS app until I set `overwriteprotocol = 'https'` in config.php. I think the internal link is important for the apps as they don't seem to respect HTTP Strict Transport Security. See #792 and #668 as they are related issues.

**Comment by Sveeeeeen** [comment]
Yeah. I took me a long way too to figure it out set "overwriteprotocol" to https!

**Comment by MartiniMoe** [comment]
How to do this via docker-compose.yml?

**Comment by jonathanvansina** [comment]
Add the variable OVERWRITEPROTOCOL to your docker-compose file [https://github.com/nextcloud/docker#using-the-apache-image-behind-a-reverse-proxy-and-auto-configure-server-host-and-protocol](https://github.com/nextcloud/docker#using-the-apache-image-behind-a-reverse-proxy-and-auto-configure-server-host-and-protocol).
So for example:
```bash
environment:
      - OVERWRITEPROTOCOL=https
```

Did not tested this yet.

**Comment by J0WI** [comment]
https://github.com/nextcloud/docker#using-the-apache-image-behind-a-reverse-proxy-and-auto-configure-server-host-and-protocol
