### ISSUE TITLE
Update of .examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml

### ISSUE THREAD

**Issue by Tockra** [nextcloud/docker#743]
Can somebody explain how to update a nextcloud instance of the example: ".examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml" without losing all data? This example mounts the whole http-server to the nextcloud volume (which contains the current nextcloud version and all user files).
After a backup of the image (docker-compose build --pull) nothing changes, because the content of the nextcloud-volume still has the old files. If I remove the nextcloud volume, I lose my whole config and user files.

Is there a easy way?

**Comment by tilosp** [comment]
```bash
docker-compose pull
docker-compose build --pull
docker-compose up -d
```

**Comment by Tockra** [comment]
After a backup of the image (docker-compose pull) nothing changes, because the content of the nextcloud-volume still has the old files.

**Comment by tilosp** [comment]
yes but the container updates those files, have you run all 3 commands?

**Comment by kowjens** [comment]
I use the following commands in a bash since NC-V12 without any problems.

sudo docker stop $(sudo docker ps -a -q)
sudo docker image prune -a
sudo docker-compose build --pull
sudo docker-compose up -d

kr jens

**Comment by Tockra** [comment]
> yes but the container updates those files, have you run all 3 commands?

I think I have to reinstall my nextcloud instance because of some internal errors after my update trys.

I mounted the /var/www/html not to a volume nextcloud. I mounted it into my own filesystem. And then there changed nothing in my filesystem after running docker-compose build -pull commands. I still had the Nextcloud 14 html stuff in my ./data/files/ directory (which was mounted to /var/www/html). I see no reason, why there should change some files, because after mounting the extern directory the images directory /var/www/html should always contains the files of my host system.

**Comment by tilosp** [comment]
yes but the container will update the files in /var/www/html, once it is started. So the files will get updated once the old container is replaced by the new one and it is started. This is what the `docker-compose up -d` command does.

**Comment by Tockra** [comment]
Not for me...

**Comment by tilosp** [comment]
what is the output of:
```bash
docker-compose exec app cat /var/www/html/version.php
docker-compose exec app cat /usr/src/nextcloud/version.php
```

**Comment by Tockra** [comment]
> 
> 
> what is the output of:
> 
> ```shell
> docker-compose exec app cat /var/www/html/version.php
> docker-compose exec app cat /usr/src/nextcloud/version.php
> ```

I will try it when I am home. But I don't know if these output is still usefull information because of the odd state my installation has reached (internal error)

**Comment by Tockra** [comment]
Okay, I will wait until a update and then I will report.
