### ISSUE TITLE
Why is my pull-request not in master?

### ISSUE THREAD

**Issue by Tockra** [nextcloud/docker#744]
Hi folks,

I wrote a pull request a long time ago: https://github.com/nextcloud/docker/pull/514
It solutes the bug: https://github.com/nextcloud/docker/issues/503

After I reinstalled my nextcloud instance yesterday, I saw that I still get a lot of problems while syncing data because of locked files (with mariadb:latest).
To be fair I have to say, that I still has the lock "problem" with mariadb:10.3 but there I get 1 problem while syncing 50GB (a lot of small files), against more than 10 with mariadb:latest.

The bug in nextcloud seems not to be fully fixed, so I'm wondered that the pull request isn't accepted.

T

**Comment by J0WI** [comment]
Let's continue the discussion in #514
