### ISSUE TITLE
can't bring up docker-compose

### ISSUE THREAD

**Issue by cromulus** [nextcloud/docker#76]
```
Creating redis
Creating proxy
Creating collabora
Creating db
Creating nextcloud_fpm
Creating letsencrypt-companion
Creating nextcloud_webserver

ERROR: for web  Cannot start service web: containerd: container not started
ERROR: Encountered errors while bringing up the project.
```
Looks like this is the culprit:
```
db                       | error: database is uninitialized and password option is not specified
db                       |   You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```

Brand new ubuntu 16.04 host. Any ideas?

**Comment by tilosp** [comment]
You need to set [MYSQL_ROOT_PASSWORD](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose.yml#L68), [MYSQL_PASSWORD](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose.yml#L71) and [LETSENCRYPT_EMAIL](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose.yml#L44) in the docker-compose.yml file

**Comment by cromulus** [comment]
Got further along, but still had this error: 
```
web_1                    | container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:53: mounting \\\"/home/ubuntu/nextcloud/nginx.conf\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/de0c14779572de0ced6c0859ee3c2f4d3a9f12340536079570654e60c0868257\\\" at \\\"/var/lib/docker/aufs/mnt/de0c14779572de0ced6c0859ee3c2f4d3a9f12340536079570654e60c0868257/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\""
```

**Comment by cromulus** [comment]
Figured it out. Sorry.

**Comment by kunago** [comment]
@cromulus How did you figure this one out? Could you please share? I am having the same issue using the default docker-compose.yml. Obviously nginx container is shipping its own nginx.conf file which is the source of my issue.

**Comment by cromulus** [comment]
I didn't figure it out. 

Ran mailinabox install on a fresh host and using next cloud install there.

**Comment by tilosp** [comment]
@kunago have you got the same error as @cromulus

**Comment by kunago** [comment]
@tilosp I did but it was my stupidy really. The solution is very simple - just create the nginx.conf file in your docker-compose directory where docker-compose.yml is situated. It was not obvious to me previously but it is now.

**Comment by tilosp** [comment]
@kunago yes the idea is that you use the nginx.conf provided in the examples folder

**Comment by kunago** [comment]
@tilosp Yeah, true. I however have no such luck with the proxy container. It seems to run but only the container, inside it keeps restarting due to missing arguments. In the error log it states the following:

`
invalid number of arguments in "upstream" directive in /etc/nginx/conf.d/default.conf:49
nginx: [emerg] invalid number of arguments in "upstream" directive in /etc/nginx/conf.d/default.conf:49
`

**Comment by tilosp** [comment]
@kunago can you run `docker-compose exec proxy cat /etc/nginx/conf.d/default.conf` to get the content of this file

**Comment by tilosp** [comment]
@kunago have you changed this line in the docker-compose.yml file? `VIRTUAL_HOST=${DOMAIN}` 
The proxy searches for a container with this var set.

**Comment by kunago** [comment]
Yes, I did do this, I got it though. It was - once again - my bad (I am using a script to do this for me). Once you fail to fill in the DOMAIN variable, not only do you need to run `docker-compose down` to remove all the containers but you also need to remove the proxy folder which contains all the generated files, sometimes containg wrong syntax if you fail to do everything properly. So for testing it's always better to stop all containers and also remove all generated files and folders.

**Comment by kunago** [comment]
@tilosp Thank you very much for your help, I appreciate it.

**Comment by MaxenceG2M** [comment]
If someone like me have this error

    nginx: [emerg] invalid number of arguments in "upstream" directive in /etc/nginx/conf.d/default.conf:49

And don't figure out what is "_all generated files and folders_" and how to delete them, just do:

    docker volume rm $(docker volume rm)
