### ISSUE TITLE
CREATE TABLE groups error

### ISSUE THREAD

**Issue by JuWell** [nextcloud/docker#765]
hello,
i'm using nextcloud in docker, with bash script, but it is always get this error:

Error while trying to create admin user: An exception occurred while executing 'CREATE TABLE groups (gid VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY(gid)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'groups (gid VARCHAR(64) DEFAULT '' NOT NULL, PRIMARY KEY(gid)) DEFAULT CHARACTER' at line 1 

**i have tried to change the table name to create in navicat，it works well，but still get this error by using `groups`**

my mysql is 8.0.16，and run in docker

this is my bash script:
``` bash
docker run \
	--name nextcloud \
	-d \
	-p 10007:80 \
	-v /home/server-platform/nextcloud/apps:/var/www/html/custom_apps \
	-v /home/server-platform/nextcloud/config:/var/www/html/config \
	-v /home/server-platform/nextcloud/data:/var/www/html/data \
	-v /home/server-platform/nextcloud/theme:/var/www/html/themes \
	-e MYSQL_HOST=192.168.163.50:10004 \
	-e MYSQL_DATABASE=nextcloud \
	-e MYSQL_USER=nextcloud \
	-e MYSQL_PASSWORD=nextcloud \
	-e NEXTCLOUD_ADMIN_USER=root \
	-e NEXTCLOUD_ADMIN_PASSWORD=root \
	-e REDIS_HOST=192.168.163.50 \
	-e REDIS_HOST_PORT=10006 \
	--link 192.168.163.50:10004:mysql \
	--privileged \
	-u root \
	nextcloud:14.0.12
```

change the version to 16.0.1 of nextcloud is still error

**Comment by J0WI** [comment]
Please do not upgrade from 14 to 16. Skipping versions in major upgrades is not supported.
And for many reasons, you should avoid running the container in privileged mode.

**Comment by JuWell** [comment]
the upgrade is just test, and the error is all the same.

this nextcloud is running for myself, no need to consider security problem, so the privileged mode is the easy way to write data in host machine(there is a authority problem that if not use privileged mode)

**Comment by J0WI** [comment]
I was able to reproduce this using MySQL 8 and I just found https://help.nextcloud.com/t/nextclound-16-and-mysql-8-0-16/52689

Could you please file an issue at https://github.com/nextcloud/server?
As a workaround you can use MariaDB or an older version of MySQL.

**Comment by JuWell** [comment]
> 
> 
> I was able to reproduce this using MySQL 8 and I just found https://help.nextcloud.com/t/nextclound-16-and-mysql-8-0-16/52689
> 
> Could you please file an issue at https://github.com/nextcloud/server?
> As a workaround you can use MariaDB or an older version of MySQL.

you are right, this might be the right answer

i had submit new issue at https://github.com/nextcloud/server/issues/16004

thank you for your help~~^_^

**Comment by kesselb** [comment]
https://github.com/nextcloud/docker/blob/df048873ab32ed3dc226bef48c0c22e3590c7386/16.0/apache/config/autoconfig.php#L26 docker images sets `dbtableprefix` to "". More correct would be something like null or don't set it at all if it's empty.

https://github.com/nextcloud/server/blob/2e36069e24406455ad3f3998aa25e2a949d1402a/lib/private/Setup/AbstractDatabase.php#L89

And yes we need to escape groups as well :sunglasses:
