### ISSUE TITLE
with-nginx-proxy-self-signed-ssl example not working

### ISSUE THREAD

**Issue by FrederickChen** [nextcloud/docker#766]
I built an [example](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm) on Ubuntu 18.04.2 LTS with the latest docker version 18.09.5, but it doesn't work.
I only change the below vars  to my local hostname in docker-compose.yml file. 
      - VIRTUAL_HOST=myhostname
      - SSL_SUBJECT=myhostname
      - SSL_KEY=/certs/myhostname
      - SSL_CSR=/certs/myhostname
      - SSL_CERT=/certs/myhostname
I didn't see any error when I checked the logs of all docker containers, but I get the error page 503 Service Temporarily Unavailable when I visit the website.
Have I missed any setting and any idea to fix this problem?
Thanks.

**Comment by flowercow** [comment]
i met the same problem.

**Comment by flowercow** [comment]
503 means the certification is not available. All the environment variables should be setup correctly. myhostname should be an ip or real domain name. 
Do not del the extension of the key csr and cert. 
your configuration below is not correct, docker-compose can run without errors, but this cause there is no correct certification that the proxy can use.

- VIRTUAL_HOST=myhostname
- SSL_SUBJECT=myhostname
- SSL_KEY=/certs/myhostname
- SSL_CSR=/certs/myhostname
- SSL_CERT=/certs/myhostname

**Comment by joshtrichards** [comment]
This looks addressed. As this is a fairly old issue, I'm going to close this out. 

Feel free to follow-up at the [Nextcloud Help Forum](https://help.nextcloud.com) with further questions or for troubleshooting assistance. 

Or open a new Issue here if you have an actionable enhancement request or bug to report in the Nextcloud community Docker image itself.
