### ISSUE TITLE
Close issues

### ISSUE THREAD

**Issue by Nebucatnetzer** [nextcloud/docker#774]
There are a lot of open issues which should get closed IMO.
Keeping them open gives the impression that the repo isn't properly maintained.
If it helps I can compile a list of all rhe issues that should get closed im my opinion.

**Comment by wiswedel** [comment]
>  If it helps I can compile a list of all rhe issues that should get closed im my opinion.

👍

**Comment by Nebucatnetzer** [comment]
Okay I'll have a go. Might take a few days.

**Comment by J0WI** [comment]
@Nebucatnetzer what is the current status of this?

**Comment by Nebucatnetzer** [comment]
236 is over two years old and the author hasn't answered since over a year.
200 as well very old.
182 last comment over a year ago.
178 last comment over a year ago.
157 last comment over a year ago.
130 last comment over two years ago.
102 last comment over two years ago.

As a note to the issues listed here. I personally would close old stuff from time to time to keep things in order.
For certain issues it might be better to comment with something like "We'll put it on our feature list, no ETA however." and then close it.
Same goes for the stuff with the "Help wanted" label. Does it make sense to keep an issue around for two years?
IMO that just clogs things up.
Btw I'm not using the # in ordner not to necro post all the old issues.

**Comment by J0WI** [comment]
Thanks for the list!

**Comment by paulfantom** [comment]
You can implement something like [probot/stale](https://github.com/probot/stale) to do this automatically and also remind that you have stale issues :)

**Comment by Nebucatnetzer** [comment]
Aye that would work as well but that is up to the devs to decide if they want to automate this.

**Comment by joshtrichards** [comment]
Closing this. 😉 All the mentioned issues have been dealt with long ago. Any further needed "meta" discussions about repo management can go into new issue(s) or other channels.
