### ISSUE TITLE
ISP Blocks Port 80

### ISSUE THREAD

**Issue by fpernice518** [nextcloud/docker#779]
I'm very new to Docker, but I'm migrating my Nextcloud install from a Snap install because I couldn't seem to solve my SSL issues with Snap. 

My ISP (Altice One) blocks port 80 so getting LetsEncrypt working is a huge pain (especially for someone like myself who doesn't really touch networking).

In any case, I installed a fresh OS (Ubuntu 18.04) and downloaded the [files here](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb/apache) to the server. I modified them accordingly (in docker-compose-yml I put my domain behind `VIRTUAL_HOST` and `LETSENCRYPT_HOST`, my email behind `LETSENCRYPT_EMAIL`, made up a root password for `MYSQL_ROOT_PASSWORD`. In db.ev I made up a password for `MYSQL_PASSWORD`. I then ran `docker-compose build --pull` followed by `docker-compose up -d`, but I get an "Internal Server Error" when I load my domain. 

So I tried changing the port in the YML from 80:80 to 85:80 hoping that the bridge would bypass the port 80 restriction, but that seems to have made things worse. I can't even get to the site now and I'm at a loss.

One thing that seems noteworthy is that when running  `docker-compose build --pull` it skips LetsEncrypt because it's "an image" for some reason

Any help is much appreciated.

**Comment by flowercow** [comment]
what's your aim? get nc up with Let's encrypt SSL cert? or just works will ssl?
Because letsencrypt-companion only supports http-01 challenger that port 80 must be opened, and your isp block port 80, so this docker-compose file is not fit for you.
if you don't mind selfsigned ssl certification, you can try another plan, use this https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm

**Comment by fpernice518** [comment]
I'd like to get it up with LetsEncrypt (or other free SSL) rather than a self-signed cert. I share things with less tech savvy people who'll freak out when their browser tells them it's unsafe and I'd rather not have to explain to them it's not a virus every time haha.

**Comment by flowercow** [comment]
> 
> 
> I'd like to get it up with LetsEncrypt (or other free SSL) rather than a self-signed cert. I share things with less tech savvy people who'll freak out when their browser tells them it's unsafe and I'd rather not have to explain to them it's not a virus every time haha.
> 
> Basically all I want is to use HTTPS without the browser warning me the website is insecure.

So you should use tls-alpn challenger instead of http-01 offered by jrcs/letsencrypt-nginx-proxy-companion. There is no offical docker-compose file for this plan.

**Comment by J0WI** [comment]
Closing because it's not really an issue with the image.
