### ISSUE TITLE
v12 image

### ISSUE THREAD

**Issue by vladzaharia** [nextcloud/docker#78]
Since v12 was freshly released, do we have a timeline on getting a Docker image for it?

**Comment by tilosp** [comment]
Once https://nextcloud.com/changelog/ is updated we will automatically get a Docker image for v12.

**Comment by jeyglk** [comment]
@tilosp Will it happen eventually?

**Comment by jeyglk** [comment]
@tilosp Will it happen eventually?

**Comment by rodrigoaguilera** [comment]
FYI
I'm running a docker container from a custom that is just the 11.0 with the NEXTCLOUD_VERSION changed to 12.0.0 and I am very happy with the result

**Comment by tilosp** [comment]
nextcloud/nextcloud.com#473
Looks like it might happen this week.

**Comment by jeyglk** [comment]
This is getting a bit ridiculous, we're 2 weeks after the v12 release and there is no docker image. I appreciate this is all open source and voluntary work but it is really frustrating to be blocked on v11 because of release notes being behind.

**Comment by tilosp** [comment]
Fixed in #85
