### ISSUE TITLE
Container's capabilities

### ISSUE THREAD

**Issue by Heracles31** [nextcloud/docker#791]
Hi,

I noticed the Nextcloud Docker container has some capabilities that I doubt are required. Why to change MAC would be of any use for Nextcloud ? (Capability MAC_ADMIN).

One like NET_RAW is usually for forging packets or sniffing. Again, why would that be important for Nextcloud ? The typical answer here is PING, but there are so many other tests, is it really of use in the container ?

As for NET_BIND_SERVICE, the port is forwarded from the docker "external" IP and Port, so is not to be used or reached by clients. As such, to use a high port and remove that capability would be another plus.

In the same group, I also question the need for NET_BROADCAST, as Nextcloud is meant to be used over TCP, so peer-to-peer between the server and each single client.

To eliminate capabilities that are not required will just greatly increase the container's security...

**Comment by J0WI** [comment]
I assume they're all coming from the upstream PHP base image: https://github.com/docker-library/php
