### ISSUE TITLE
How to create a folder with a Dockerfile

### ISSUE THREAD

**Issue by vipera7** [nextcloud/docker#795]
I'm trying to create a new folder at `/var/www/html/local_data` at the docker image.

Here is my Dockerfile: 

```
FROM nextcloud

RUN mkdir /var/www/html/local_data; 
    
VOLUME /var/www/data
```

I'm trying to create an external storage using the folder `local_data`.
At the moment the container is running using the new image but it doesn't create the new folder.

Here is how I create my nextcloud container : 

`docker run -d --network nxnetwork --name nextcloud -v /home/user:/var/www/data -v /home/user/nextcloud:/var/www/html --user 1000:1000 -p 8080:80 --sysctl net.ipv4.ip_unprivileged_port_start=0 custom_nextcloud`

Logs when building : 

```
Step 1/3 : FROM nextcloud
 ---> xxxxxx
Step 2/3 : RUN mkdir /var/www/html/local_data;
 ---> Running in xxxxxx
Removing intermediate container xxxxxx
 ---> xxxxxx
Step 3/3 : VOLUME /var/www/data
 ---> Running in xxxxxx
Removing intermediate container xxxxxx
 ---> xxxxxx
```

**Comment by J0WI** [comment]
Be aware that `/var/www/html` is updated by the entrypoint
https://github.com/nextcloud/docker/blob/66c5d81dbd36f78b1c93d1219e20f54be8579b9d/docker-entrypoint.sh#L56

**Comment by vipera7** [comment]
Thanks for the info, here is my full issue (https://github.com/nextcloud/server/issues/16306), I thought I could workaround it with this current issue (https://github.com/nextcloud/docker/issues/795)

**Comment by J0WI** [comment]
Closing this for now. Further questions can be asked on https://help.nextcloud.com/.
