### ISSUE TITLE
update docker images for 16.0.2

### ISSUE THREAD

**Issue by pgassmann** [nextcloud/docker#802]
16.0.2 is released: https://nextcloud.com/blog/nextcloud-16.0.2-15.0.9-and-14.0.13-available-now/

On dockerhub, 16.0.2 is only available as RC, 16-* tags still point to 16.0.1 https://hub.docker.com/_/nextcloud?tab=tags

TODO:
- build image for 16.0.2 and push to docker hub
- update tags
- ensure future (monthly) releases are automatically updated

**Comment by tilosp** [comment]
This is already mostly automated, we are waiting for a required review from the @docker-library team.
See: https://github.com/docker-library/official-images/pull/6236
