### ISSUE TITLE
Upgrading over several version numbers using docker-compose?

### ISSUE THREAD

**Issue by amca01** [nextcloud/docker#804]
I'm trying to update my nextcloud.  If I stop and remove the current container, and then issue the commands

    docker-compose pull nextcloud
    docker-compose up -d

then when I visit nextcloud on my server, it tells me it's about to upgrade to 16.0.1, then immediately says that can't be done, as that would be jumping over several version numbers.  So I have two questions:

1. Why is this a thing?  I though that if I've removed the old container first, then pulling the new image should be equivalent to installing nextcloud for the first time.
2. If I have to upgrade one major version number at a time, how is that done with  docker and docker-compose?

Thanks!

**Comment by J0WI** [comment]
Skipping major releases is not supported by upstream.
https://docs.nextcloud.com/server/16/admin_manual/maintenance/upgrade.html

You have to manually checkout the sufficient tag (e.g. `14-apache` rather than just `apache`).

**Comment by rubo77** [comment]
Here you find, how to fix the issue if you accidentally upgraded over more major versions: https://help.nextcloud.com/t/updates-between-multiple-major-versions-are-unsupported/7094/7
