### ISSUE TITLE
403 Forbidden after finishing setup.

### ISSUE THREAD

**Issue by mohammedjammeh** [nextcloud/docker#807]
I am trying to configure Nextcloud to work with Docker. I have Docker running locally, cloned this package and followed the instructions twice.

At first, when I go to the host http://localhost:8080/, I get the expected page to create the admin and finish the setup.

However, once this is done, I get:
`Forbidden
You don't have permission to access / on this server.
Apache/2.4.25 (Debian) Server at localhost Port 8080
`

I've pretty much checked everywhere and even tried to edit `etc/apache2/httpd.conf` file but apparently, I should be be focusing on Docker and not my local Apache configuration.

Any ideas or suggestions would be really appreciated. Thank you.

**Comment by X2LR** [comment]
why did you close this? what was the fix?

**Comment by nekitozzz** [comment]
@mohammedjammeh same issue. Did you find how to fix it?

**Comment by Revdep** [comment]
Same problem . Anyone found a solution?
