### ISSUE TITLE
Nextcloud on "suburl" (domin.com/nextcloud)

### ISSUE THREAD

**Issue by nikitachukov** [nextcloud/docker#81]
Dear developers, thank you very much for what you are doing. Please add the ability to set the webroot at the start of the container. That is, after the addition -e webroot=**nextcloud**, nextcloud mast use url like domin.com/**nextcloud**

**Comment by nalt** [comment]
In most setups, this would be done in your public webserver, which runs in a different container and acts as a proxy for nextcloud. Nextcloud still needs corresponding configuration options in config.php. Maybe it is easier to modify this file directly?

**Comment by peperunas** [comment]
Yep, just edit config.php. I use nextcloud this way.
