### ISSUE TITLE
Cannot update to Nextcloud 16.0.3

### ISSUE THREAD

**Issue by Silent-Hunter** [nextcloud/docker#810]
I can't seem to get docker-compose to pull the latest image. It just stays on 15.0.7.

My docker-compose.yml looks like this, I added the `NEXTCLOUD_UPDATE=1` part.

```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<password>
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:latest
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - NEXCLOUD_UPDATE=1
    restart: always
```

In addition, I get an error when I try to run `sudo docker-compose up -d`

```
kavus@backup-storage:~$ sudo docker-compose up -d
Removing kavus_app_1
kavus_db_1 is up-to-date
Recreating 1faaf8a48f2a_kavus_app_1 ... error

ERROR: for 1faaf8a48f2a_kavus_app_1  Cannot start service app: b'driver failed programming external connectivity on endpoint kavus_app_1 (47806dffb2e55d7650694315447a516d9176610da47ad9ef566fbe6d3612b034): Bind for 0.0.0.0:8080 failed: port is already allocated'

ERROR: for app  Cannot start service app: b'driver failed programming external connectivity on endpoint kavus_app_1 (47806dffb2e55d7650694315447a516d9176610da47ad9ef566fbe6d3612b034): Bind for 0.0.0.0:8080 failed: port is already allocated'
ERROR: Encountered errors while bringing up the project.
```
I have always gotten this error however, and it didn't seem to actually cause an issue.

I only use Nextcloud from within my home network, so I don't use https with it.

**Comment by J0WI** [comment]
> Bind for 0.0.0.0:8080 failed: port is already allocated

You should check if another service or container is already using this port

**Comment by Silent-Hunter** [comment]
I don't think that's possible, because when I reboot I can access Nextcloud on that port. Also there are no other services running on this server, except for NFS.

**Comment by NIoSaT** [comment]
I have the same Problem.
The guide suggests `docker-compose build --pull` to update nextcloud but this command skips most of the images (including the app image).  
With `docker-compose pull` I was able to get the newest version of the nextcloud image.

**Comment by Silent-Hunter** [comment]
I've been doing `docker-compose pull` though.

**Comment by SnowMB** [comment]
> I have the same Problem.
> The guide suggests `docker-compose build --pull` to update nextcloud but this command skips most of the images (including the app image).
> With `docker-compose pull` I was able to get the newest version of the nextcloud image.

It depends on how you are using the image. The paragraph you are referring to explains building your own derived image and using nextcloud as base image (Dockerfile with `FROM ...`statement).

But if you're just pulling nextcloud indeed `docker-compose pull` is the correct command. Sorry for the confusion.

**Comment by helge000** [comment]
I also have the same issue. I am running `nextcloud:fpm-alpine` variant. When I run `docker-compose build --pull` does not work to update the images. Instead, I found this procedure works well:

```
$ docker-compose pull
$ docker-compose build
$ docker-compose up -d
$ docker-compose exec --user www-data app php occ db:add-missing-indices
```

**Comment by Silent-Hunter** [comment]
Do I have to do 'docker-compose build` then? I'm not building my own image, I'm using the prebuilt ones. Or is that not an option?

**Comment by helge000** [comment]
> Do I have to do `docker-compose build` then? I'm not building my own image, I'm using the prebuilt ones.

I think this section in the README is a bit misleading. Many of the 'official' compose configs need a [build step as you can see here](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml#L33).

I would still consider them as vanilla/prebuild and not as 'my own image'. Anyway, afaik `docker-compose build` will do nothing if there is no `build:` key in the yaml.

**Comment by J0WI** [comment]
Closing this for now. Further questions can be asked on https://help.nextcloud.com/.
