### ISSUE TITLE
Upgrade redefines data version before checking for supported route

### ISSUE THREAD

**Issue by taikedz** [nextcloud/docker#811]
### Steps to reproduce

1. Have an old nextcloud instance (e.g. NC 14)
2. Try to upgrade to new nextcloud (e.g. NC 16)
3. Nextcloud prepares target version, modifies data version indicator
4. See error indicating unsupported path
5. Replace nextcloud version with appropriate (e.g. NC 15)
6. Nextcloud checks for incompatible route.
7. See error saying that data is NC 16, downgrade not possible

### Expected behaviour

1. Have an old nextcloud instance (e.g. NC 14)
2. Try to upgrade to new nextcloud (e.g. NC 16)
3. *Before* Nextcloud modifies data version indicator, check for incompatible route
4. Fail, without modifying data

### Actual behaviour

After failed upgrade route, then attempting to upgrade via acceptable route, Nextcloud cannot upgrade the old data, because it carries a new version indicator (not sure where...).

User cannot use appropriate version upgrade path, because the old version complains that the data is too new - even though this is some indicator, the data wasn't (I think?) converted.

### Server configuration

**Operating system**:

Ubuntu 18.04, using docker

**Web server:**

Docker, using `nextcloud:*` images

**Database:**

MariaDB (docker: `mariadb:latest`)

(bad practice, I know. Migrating to better practice!)

**PHP version:**

As shipped in docker image `nextcloud:latest`

**Nextcloud version:** (see Nextcloud admin page)

Issue encountered when upgrading to `nextcloud:latest` Currently version 16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

not known. my bad. I didn't pin a version. will certainly do now :-/

**Where did you install Nextcloud from:**

Docker image `nextcloud:latest`

**Signing status:**

Cannot log in anymore, bad state

</details>

**List of activated apps:**

Unknown now, cannot start container

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
**Browser:**

Firefox normally

**Operating system:**

Linux, WIndows

**Comment by taikedz** [comment]
I believe this is related to the nextcloud app server itself, the PHP part.

Docker has no knowledge of what should or should not be in the data.

**Comment by SnowMB** [comment]
I collected related issues in #617.

**Comment by taikedz** [comment]
@SnowMB thanks - I'll close this particular issue then.

For the sake of people finding this and looking for an interim workaround/solution:

* Backup the current state of your database and nextcloud deployment folder (e.g. `/var/www/html`)
* The relevant info is in `$NEXTCLOUD_DIR/version.php` - reset the version arrays and strings to the earliest release of the original version (e.g. `14.0.0.0`), and deploy with latest release of the corresponding version (e.g. `nextcloud:14`).
* Start nextcloud to see if the application finds itself in the right state. If not, try a different version - remember to change both the nextcloud image and the `version.php` data if using docker
* Once the correct version is found, upgrade to the latest release of the next version up (e.g. from previous, just upgrade the nextcloud image to `nextcloud:15` - no need to adjust `version.php` anymore), visit nextcloud and perform the update
* And so on for each major release to upgrade

**Comment by nicbou** [comment]
Thanks for your comment, @taikedz . It was the last piece for fixing the problem.

I wrote a detailed solution for those who are stuck in that situation: https://nicolasbouliane.com/blog/nextcloud-docker-upgrade-error

tl;dr:

1. Find your old version in config/config.php
2. Put that version everywhere in version.php
3. Roll back the docker image to that old version
4. Upgrade the image one major version at a time
5. Turn off maintenance mode
