### ISSUE TITLE
Where is 'nextcloud.log' in the fpm example?

### ISSUE THREAD

**Issue by e1nh4nd3r** [nextcloud/docker#812]
Using https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm/docker-compose.yml as my starting point to build out my deployment for my home lab... I can't seem to locate `nextcloud.log` in _any_ of the containers that get created.

My `docker-compose.yml`: https://gist.github.com/e1nh4nd3r/22751cba84cd2b97fe539925b1b2fb2c

The reason why I'm looking for this file at all is because all I'm getting is this:
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

First: where is `nextcloud.log` located?
Second: why is mounting a data directory generating the above error, but when I comment it out (Line 21), everything works?

**Comment by J0WI** [comment]
`nextcloud.log` would be created in the data directory.
I doubt you've not set the correct permissions on `/mnt/media/nextcloud`. You can use `docker exec -it [nextcloud container name] sh` to see whats wrong.

btw. it's highly recommend to choose a data directory outside of `/var/www/html` (see `NEXTCLOUD_DATA_DIR`).

**Comment by leggettc18** [comment]
Hello, I recently updated my nextcloud instance to Nextcloud 17, and am receiving a similar error. The logs don't seem to indicate anything other than 500 errors when trying to access it. Could you elaborate on what permissions /mnt/media/nextcloud should have?

**Comment by J0WI** [comment]
It should be accessible by PHP, so probably owned and writable by `www-data`.

**Comment by leggettc18** [comment]
Hmmm, I don't seem to have that directory. I'll open up a separate issue, mine seems to be different from this one.

**Comment by J0WI** [comment]
This depends on your `NEXTCLOUD_DATA_DIR` and [logging](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html#logging) settings.
