### ISSUE TITLE
Raspberry docker  "NanoCPUs can not be set, as your kernel does not support CPU cfs period/quota or the cgroup is not mounted"  

### ISSUE THREAD

**Issue by baimard** [nextcloud/docker#821]
hi,

nextcloud work very well on my raspberry, but after the last update I have this error message, when I try to start the container nextcloud : 

 "NanoCPUs can not be set, as your kernel does not support CPU cfs period/quota or the cgroup is not mounted"   

My cgroup are available, and work for all my container but not for nextcloud. :(

any help ?

Docker image nextcloud latest
Raspberry 3B+
No exotic configuration

compose : 

 nextcloud:
    image: nextcloud
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.frontend.headers.STSSeconds=15552000"
        - "traefik.frontend.redirect.permanent=true"
        - "traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav"
        - "traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/"
        - "traefik.frontend.headers.referrerPolicy=strict-origin"
        - "traefik.frontend.rule=Host:next.app.41m4rd.ovh"
        - "traefik.backend=nextcloud"
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.port=80"
      resources:
        limits:
          cpus: '0.80'
          memory: '768M'
    volumes:
      - "/mnt/rasp/nextcloud/http:/var/www/html:rw"
      - "/mnt/rasp/nextcloud/php.ini-production:/usr/local/etc/php/php.ini-production:rw"
      - "/mnt/rasp/nextcloud/php.ini-development:/usr/local/etc/php/php.ini-development:rw"
    networks:
      - web

**Comment by honomoa** [comment]
I have same problem.
Env:
```
$ uname -a
Linux pi 4.19.58-v7+ #1245 SMP Fri Jul 12 17:25:51 BST 2019 armv7l GNU/Linux
$ lsb_release  -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by juxorevo** [comment]
My env : 

```
$ uname -a
Linux cian 4.19.58-v7+ #1245 SMP Fri Jul 12 17:25:51 BST 2019 armv7l GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
```

**Comment by bullimog** [comment]
It would appear that cfs is not compiled in the Raspbian Kernel. :(

**Comment by baimard** [comment]
> It would appear that cfs is not compiled in the Raspbian Kernel. :(

Would we have to open a ticket in raspbian project ?

**Comment by bullimog** [comment]
You could open a ticket, but (guessing) I think cfs is disabled intentionally, to maximise performance for regular end user applications.
https://raspberrypi.stackexchange.com/questions/87779/missing-cpu-cfs-period-us-cgroup-subsystem-in-raspbian-stretch-on-raspberry-pi-z

I am looking at using hypriot to get Docker on RPI, instead.

**Comment by J0WI** [comment]
This is something we can't fix in the Nextcloud image.
