### ISSUE TITLE
Nginx examples: tune proxy buffering

### ISSUE THREAD

**Issue by xordspar0** [nextcloud/docker#824]
The Nginx examples leave the proxy buffer settings at the default, which, [according to the Nextcloud docs](https://docs.nextcloud.com/server/stable/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=big%20file#nginx), limits downloads to 1 GB. For my own deployments, I would like proxy buffering to be disabled as suggested by the Nextcloud docs. If there are reasons to leave it enabled, then maybe the `proxy_max_temp_file_size` Nginx setting could be increased, or a comment could be added to the config file.

**Comment by J0WI** [comment]
I think this have been fixed in #651
