### ISSUE TITLE
raspbian buster NTFS local usb storage unable to read or write

### ISSUE THREAD

**Issue by rawesomeawesome** [nextcloud/docker#826]
Using a raspberry pi 4 i was able to install docker and nextcloud, but on the setup page when attempting to select the external drive it always claims that it cannot read or write. nfts-3g is installed and the drive is mounted. I can create and edit files on the drive from the default user. the permissions of the drive are set to allow anyone to have full access to it. any suggestions?

**Comment by J0WI** [comment]
https://help.nextcloud.com/ might be a better place for questions
