### ISSUE TITLE
Using a custom user and getting permission error

### ISSUE THREAD

**Issue by vipera7** [nextcloud/docker#832]
I'm trying to run the container using a custom user. He has uid : 1000 and gid : 1000.
I gave him permission on the folder `/home/foo/nextcloud`. I'm running the following command : 

`docker run -d --name nextcloud -v /home/foo/nextcloud:/var/www/html --user 1000 -p 8080:80 nextcloud`

And I have this permission error when I'm doing `docker logs nextcloud` : 

```
Initializing nextcloud 16.0.3.0 ...
Initializing finished
New nextcloud instance
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
```

**Comment by J0WI** [comment]
Port `80` is in the range of privileged ports. I'm closing this since this has already been discussed in https://github.com/nextcloud/docker/issues/359#issuecomment-467859596
