### ISSUE TITLE
16.0.4 missing from Docker Hub

### ISSUE THREAD

**Issue by willvousden** [nextcloud/docker#839]
My Docker-based Nextcloud instance is ~~telling~~ nagging me that 16.0.4 is available.

On Docker Hub, there's no such tag (just the release candidates):
https://hub.docker.com/_/nextcloud?tab=tags

This has happened before; for example, 16.0.1 and 16.0.2 are also missing from Docker Hub.  This means I'm unable to upgrade my Nextcloud instance 🙁 

Is this perhaps related to the following test failures?
https://drone.nextcloud.com/nextcloud/server/20902

**Comment by kesselb** [comment]
cc @nextcloud/docker :man_shrugging:

**Comment by J0WI** [comment]
https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what
https://github.com/docker-library/official-images/pull/6466

**Comment by kesselb** [comment]
Thank you @J0WI :+1: I didn't know how that works :see_no_evil:
