### ISSUE TITLE
Question: Which Docker Tag?

### ISSUE THREAD

**Issue by sscholl** [nextcloud/docker#840]
Hello,
since a while I am using the production tag for my docker deployment. Because of  #831 I received today a unexpected major version upgrade - which disabled all the custom apps for a while. Therefore I was wondering, if there is:
1. A definition of the production tag and the difference to the stable, latest, apache or <latest-major-version>-apache. All point to the same image. This sounds wrong to me!
2. If you could add a <major-version>-production tag, if question 1. shows, that the production tag even makes any sence.
3. If there is an automatic update mechanism for custom apps.

Thanks!
Simon

**Comment by J0WI** [comment]
Please have a look at:
* https://nextcloud.com/release-channels/
* There is an `app:update` command for `occ`

If you want to stick with a major release I'd recommend you to use the version number (e. g. `16`) in the tag.

**Comment by sscholl** [comment]
@J0WI with docker, the update will be done by exchanging the images. Your answer is not really related to docker image tags. The theory of production and stable is clear. But do you live it with docker image tags? It does not look like it (see above). 
You are proposing the same as I do: production tags per major version (question 2.). They do not exist.

**Comment by J0WI** [comment]
I propose `16-apache` if you want to stick with 16 and apache. If you don't want to maintain the version tag, you should use `stable`or `production`. They work the same as the internal NextCloud updater does.
It's not recommend to use an older version.
