### ISSUE TITLE
Make logging verbosity configurable

### ISSUE THREAD

**Issue by oliversalzburg** [nextcloud/docker#845]
It would be extremely helpful if there was a way to configure the container to be more verbose to troubleshoot installation issues.

**Comment by J0WI** [comment]
Could you clarify what kind of logs you need?
There is https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level for NextCloud itself.

**Comment by oliversalzburg** [comment]
That is exactly what I would like to have configurable on the container.

I currently configure the entire instance through environment variables. Making changes to files inside the container is a very cumbersome operation. In the container orchestration service I use (AWS ECS) I would have to roll a lot of additional resources and code to modify `config.php` inside the container instance.

**Comment by oliversalzburg** [comment]
This is one of the situations I find myself in regularly when trying to set up Nextcloud (which I have been trying to do unsuccessfully for a couple of months now).

![image](https://user-images.githubusercontent.com/1658949/64202681-04a54d80-ce92-11e9-9446-15faffdc0aaa.png)

This is something that happened after I recreated my database from an earlier snapshot. The setup process seems to think that it's a new installation, even though I restored the database from an earlier snapshot, when nextcloud was already partially set up.

When creating a new instance, there is barely any relevant logging output to analyze the various issues that occur during setup. It's very frustrating and there is no easy way to get more relevant information.

As all configuration of the container is done through environment variables (as it should be IMO), it should be possible to control logging verbosity through this mechanism as well.

**Comment by J0WI** [comment]
The logs from `docker-entrypoint.sh` and the logs from NextCloud itself are two different issues. But we'd welcome a PR to make the option configurable.

**Comment by sveneh** [comment]
There's an undocumented hack in Nextcloud. You can change some `config.php` variables via environment variables, e.g. `NC_log_type=errrorlog` to get Nextcloud errors merged into the docker log.

**Comment by swaggi** [comment]
Is there also a possibility to show access.log output in the docker log?
Background: I try to monitor http (get) requests with a Grafana/Loki/Promtail setup. There is docker logging driver, which reports the container log to Loki, that you do not have to configure a Promtail instance for each container. But this logging driver is sending docker log output only and AFAIK is not configurable to send other logfiles from the container.

**Comment by bjesuiter** [comment]
> There's an undocumented hack in Nextcloud. You can change some `config.php` variables via environment variables, e.g. `NC_log_type=errrorlog` to get Nextcloud errors merged into the docker log.

This looks cool, but it seemed to have stopped working on nextcloud 22-apache docker image (didn't test previous images, as I try to setup version 22 from scratch with object storage)

**Comment by bjesuiter** [comment]
> Could you clarify what kind of logs you need? There is https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level for NextCloud itself.

The problem is, that this does not seem to be configureable with docker environment variables. 
This would require changing the config.php by hand in the nextcloud docker image, 
which is way less convenient than setting all the options via ENV vars in docker compose. 

So, to clarify: I'm fine with reading the logfile from inside the container, I simply want to change the log level of nextcloud via docker env vars.

**Comment by JMoVS** [comment]
Moving the discussion back to here - I tried both syslog and errorlog and in neither cases did I see the nextcloud logs in the logs of the docker container (but I always see the apache logs) - anybody has an idea why that doesn't work?

**Comment by oliversalzburg** [comment]
I'm really disappointed to see that poor logging and poor troubleshooting ability is still a standing issue with Nextcloud. Luckily, I stopped wasting my time with the product back then.

Please open new issues about this sad state of affairs, so that I don't get notifications about issues in a product I no longer care about. Thanks :)

**Comment by bjesuiter** [comment]
@oliversalzburg What do you use instead? I'm also looking, since I don't need these Hub functions but I want a fast and relieable FileServer with Web Interface.

**Comment by oliversalzburg** [comment]
@bjesuiter I don't use anything comparable. Nextcloud is probably the most mature solution in the space and still is a sad sight when it comes to software quality.

I replaced my need to host files with the ability to sync files through Syncthing. Whenever I do need to host something publicly, I either use AWS S3+CloudFront or GitHub Pages. For private media, Emby works reasonably well.

I know I could just help improve the product instead of complain about it, but the amount of obvious oversights in the installation process alone made it appear like a pointless effort. And that was already with a containerized solution :D

**Comment by bjesuiter** [comment]
Thanks for answering my question on this closed thread of yours. I understand your frustration with this. I also thought to build my own docker container for Nextcloud but frankly I don't want to deal with the inner workings of this php stuff. 
Will try more ideas, have some stuff in the pipeline, like seaweeds, but it's not production ready unfortunately.

**Comment by Timoses** [comment]
FWIW in Kubernetes it is easy to do a `commond: ['sh', '-x', '/entrypoint.sh']`. Or even extract the entrypoint `kubectl exec nextcloud -- cat /entrypoint.sh` and mount it via a ConfigMap into the container as a volume.
