### ISSUE TITLE
Enable browser cache on thumbnails

### ISSUE THREAD

**Issue by stefaang** [nextcloud/docker#848]
Is there any reason not to enable the browser cache for image thumbnails?
Currently cache control is only applied to the generic [svg icons](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf#L130) but not on [jpg](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/web/nginx.conf#L154-L158).

Thumbnails can change when the underlying picture/document has been modified, so maybe it should just be a performance recommendation.

**Comment by J0WI** [comment]
Please open a PR for https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/nginx.rst

**Comment by stefaang** [comment]
My lighttpd based setup wasn't handling the caching headers properly. There was no problem with the nginx setup.
