### ISSUE TITLE
overwrite protocol

### ISSUE THREAD

**Issue by fractalf** [nextcloud/docker#851]
There are problems logging in with the iOS app which requires one to set `'overwriteprotocol' => 'https'` in the config.php (ref: https://github.com/nextcloud/ios/issues/768)

Is there any way of putting this into a `.env` constant for docker-compose or something?
The fix right now is basically connecting to the container, installing vim and edit manually.

Thanks

**Comment by SnowMB** [comment]
There's work on it. See #819.

**Comment by J0WI** [comment]
Duplicate of #742
