### ISSUE TITLE
Insecure permissions within container need to be fixed! (please don't do chmod 777)

### ISSUE THREAD

**Issue by zem** [nextcloud/docker#858]
There is no reason to do chmod 777 on any unix systems ever, except if you actively want to introduce security risks.  

The container does not help when the users Data is at stake! Even /tmp is better secured (with chmod 1777) It is absolutely feasible to run the nextcloud with more restrictive permissions. 

The Directory I found is /var/www/html: 

`root@docker1:~/docker_compose_ports/nextcloud# docker exec -t -i b117e7f7bd67 bash
root@b117e7f7bd67:/var/www/html# ls -ld .
drwxrwxrwx 15 www-data root 4096 Sep  8 00:49 .
root@b117e7f7bd67:/var/www/html# 
`

**Comment by J0WI** [comment]
We don't do chmod 777, that's in the upstream base image. Inside the container are only `root` and `www-data` present. Both of them have access to the directory anyway.
