### ISSUE TITLE
example docker-compose does not work on ubuntu 14.04.5

### ISSUE THREAD

**Issue by bdina** [nextcloud/docker#86]
I am unable to get the docker-compose example working on ubuntu 14.04.5 (which i'm running at my home installed on bare metal) with docker and docker-compose versions:

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:06 2017
 OS/Arch:      linux/amd64
 Experimental: false

docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.6
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
```

I have copied the docker-compose.yml and nginx.conf files to my system, created an environment file to set my domain and mysql passwords (with mysql variables that i added into the docker-compose.yml file).

At this point I set my **DOMAIN** to be the real domain name of my server (i.e. a public domain name).

I executed ``docker-compose up -d``, which failed because the compose file included a docker network that did not exist (**nginx-proxy**).

Next, I created the docker network: ``sudo docker network create nginx-proxy``, which succeeded. Now running the above docker-compose up completed without visible errors.

On attempting to open the web page, I receive HTTP 503 errors. Not working.

I tried changing my domain from the public domain name, to a local domain name (which works only on my private network), docker-compose down and up, and same result - HTTP 503.

Lastly, I changed my domain name to ``localhost`` and this time I am able to get to a Nextcloud page, but instead of a login, I see an error message which says:

```
Can't write into config directory!

This can usually be fixed by <a href="https://docs.nextcloud.com/server/11/go.php?to=admin-dir_permissions" target="_blank" rel="noreferrer">giving the webserver write access to the config directory</a>.
```

I am not sure what else to do at this point, there really isn't any documentation to help me understand what I should be using for a **DOMAIN**, or whether this should work on my version of Ubuntu and Docker.

**Comment by protree** [comment]
"Can't write into config directory!" -> the server has no write permissions for the config-directory.

Take a look at the docker-compose.yml file:
`  app:
    image: nextcloud:fpm
    container_name: nextcloud_fpm
    links:
      - db
    volumes:
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
    networks:
      - proxy-tier
    restart: always
`

check if the folder <docker-compose.yml folder>/nextcloud/config folder exists and is writable by www-data (this is also valid for the apps and data folder)

**Comment by bdina** [comment]
here is the contents of my `docker-compose.yml` file:
```
  app:
    image: nextcloud:fpm
    container_name: nextcloud_fpm
    links:
      - db
    volumes:
      - ./volumes/nextcloud/apps:/var/www/html/apps
      - ./volumes/nextcloud/config:/var/www/html/config
      - ./volumes/nextcloud/data:/var/www/html/data
    networks:
      - proxy-tier
    restart: always
```
my working directory is `/home/bdina/docker-compose/nextcloud`, using that root here is what the directory tree looks like:
```
.
├── docker-compose.yml
├── nginx.conf
└── volumes
    ├── nextcloud
    │   ├── apps
    │   ├── config
    │   │   └── apps.config.php
    │   ├── data
    │   │   └── nextcloud.log
    │   └── db
    │       ├── aria_log.00000001
    │       ├── aria_log_control
    │       ├── ibdata1
    │       ├── ib_logfile0
    │       ├── ib_logfile1
    │       ├── multi-master.info
    │       ├── mysql [error opening dir]
    │       ├── nextcloud [error opening dir]
    │       ├── performance_schema [error opening dir]
    │       └── tc.log
    ├── nginx
    │   └── nginx.conf
    └── proxy
        ├── certs
        │   ├── bdina-server.local
        │   ├── cloud.bryandina.com
        │   ├── dhparam.pem
        │   ├── domain.name
        │   └── localhost
        ├── conf.d
        │   └── default.conf
        ├── html
        └── vhost.d
            └── default
```
i checked on whether the **config** directory was writable by *www-data* and it wasn't, so i changed it (recursively), so now the file attributes on the config folder:
```
drwxr-x--- 36 root www-data 4.0K May 22 04:26 apps
drwxr-xr-x  2 root www-data 4.0K Jun  3 10:30 config
drwxr-xr-x  2 root www-data 4.0K Jun  3 11:32 data
drwxr-xr-x  5  999 docker   4.0K Jun 10 11:57 db
```
in the above you can see the **db** directory looks suspect given a user of **999**.

at any rate, i'm using a **DOMAIN** value of `localhost` right now, and on bringing the system up by running `sudo docker-compose up -d` i'm now receiving an HTTP 503 from the server, so it's back to plain ol' not working again.

**Comment by bdina** [comment]
i found the following in the *nextcloud_fpm* log:
```
[10-Jun-2017 16:19:09] WARNING: [pool www] child 17 said into stderr: "NOTICE: PHP message: {"reqId":"JWsu3luonANHYX4GORnr","level":3,"time":"2017-06-10T16:19:09+00:00","remoteAddr":"172.19.0.3","user":"--","app":"PHP","method":"GET","url":"\/","message":"fopen(\/var\/www\/html\/data\/nextcloud.log): failed to open stream: Permission denied at \/var\/www\/html\/lib\/private\/Log\/File.php#121","userAgent":"curl\/7.35.0","version":""}"
```
so i'm seeing evidence of more permissions issues
