### ISSUE TITLE
Does not start due to /var/run and /var/lock being symlinks

### ISSUE THREAD

**Issue by vondrt4** [nextcloud/docker#864]
Hi!
Some of your underlying container layers changed /var/run and /var/lock to symlinks while your initialization script is trying to call mkdir on them. The result is an error. The container does not start.
Version: 16.0.4-apache c6420b6d4c56
Environment: Docker 17.09 on WSL on Windows 10. But is should be reproducible anywhere.

**Comment by J0WI** [comment]
No, I can't reproduce this. Where did you see a `mkdir` on `/var/run` or `/var/lock`?
