### ISSUE TITLE
Kubernetes Support

### ISSUE THREAD

**Issue by LorbusChris** [nextcloud/docker#87]
Hello Everyone,
first of all, thanks for the great work here!

I'd love to see an official Helm Chart for Nextcloud.
There is one already for ownCloud (https://github.com/kubernetes/charts/tree/master/stable/owncloud)
which one might be able to use for reference.

It'd be awesome to see somebody take it on!
Otherwise I'll give this a shot when I come round to it, but that won't be for some time.

Greetings, Chris

**Comment by LorbusChris** [comment]
Note to self / FYI http://kompose.io
Perhaps this might not need more than just running `kompose convert`

**Comment by LorbusChris** [comment]
Second Note to self / FYI:
Alternatively, an APB (Ansible Playbook Bundle) could be written (instead of the Helm Chart).
see https://github.com/fusor/ansible-playbook-bundle

**Comment by pierreozoux** [comment]
My 2 cents, I think helm is pretty straightforward, I'm not sure of the value of adding yet another layer such as APB.
(I didn't know APB, so I might be wrong)

If you want to contribute an helm chart, please create a PR directly to the official charts.
Just ping us here if you want an extra review?

I'll close the issue, as it is not directly related to this repo.

**Comment by pierreozoux** [comment]
Ok, let's reopen :)

This is related to https://github.com/nextcloud/server/issues/9086

So, yes, we need an official helm chart. Does anybody has any work done around that? I think we can safely reuse the ownCloud one to get started, and start from there.

**Comment by m-ueberall** [comment]
FYI, the above (stale) pull request has been closed in favour of the merged https://github.com/helm/charts/pull/10922.
