### ISSUE TITLE
nextcloud:latest (upgrade from 16.0.4 -> 17) and breaks desktop-client login

### ISSUE THREAD

**Issue by TidhoAmla** [nextcloud/docker#872]
After docker-compose pull && docker-compose up -d it upgrades to nextcloud 17.0.0.9 linux desktop app (ubuntu / nextcloud client 2.5.2) couldn't login anymore, the login mask itself is seen and can also respond to a wrong password, but with the right password the circle keeps rotating...

Tried this also under windows 10 with the newest windows client (2.6.0), there the browser opens and it hangs there at giving the access.

Normal browser login works and my android device app keeps his login status.

My Server Configuration:
docker-compose.yml 
`version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
      - MYSQL_PASSWORD=xxx
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    ports:
      - 127.0.0.1:8090:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
`

/etc/nginx/sites-enabled/nextcloud
`server {
        listen 80;
        listen [::]:80;
        server_name ...;
        rewrite ^ https://$http_host$request_uri? permanent;    # force redirect http to https
}

server {
        listen 443 ssl;
        listen [::]:443 ssl;
        server_name ...;

        ssl on;
        ssl_certificate ...;
        ssl_certificate_key ...;  

        location / {
                add_header Strict-Transport-Security "max-age=15552000; includeSubDomains" always;

                proxy_headers_hash_max_size 512;
                proxy_headers_hash_bucket_size 64;
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Remote-Port $remote_port;

                add_header Front-End-Https on;
                proxy_pass http://127.0.0.1:8090;

                # Redirects for DAV clients
                location = /.well-known/carddav {
                        return 301 $scheme://$host/remote.php/dav;
                }

                location = /.well-known/caldav {
                        return 301 $scheme://$host/remote.php/dav;
                }

        }

        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';

        ssl_prefer_server_ciphers on;
        ssl_dhparam /etc/ssl/dhparams.pem;
}
`

**Comment by budimanjojo** [comment]
I can confirm this. Having the same issue here.

**Comment by budimanjojo** [comment]
Updating the desktop client to version 2.6 fixed the problem. But it's not available in the nextcloud ubuntu PPA yet. I had to use the appimage version for now and hope the PPA would be updated soon.

**Comment by Happyfeet01** [comment]
i was wondering why nextcloud:latest tag is updating to 17.0.0. 
Good to know that i am not the only Person.

**Comment by fyah** [comment]
Hello,

same here. I was expecting to receive 16.0.5 and was surprised to see my instance upgrade to 17.0.0

would be good to have a way to know to which target release the upgrade will be before actually doing it

and still I don't understand why we get to 17, it is still not officially released, is it?

**Comment by TidhoAmla** [comment]
Was expecting the same, but then had a look on nextcloud - server - tag list, and there the version 17 is released ( https://github.com/nextcloud/server/tree/v17.0.0 )

It's still not on stable channel or the recommended version, but that's a different story, maybe the docker manuel should be extended to use image: nextcloud:stable instead of latest.

@budimanjojo  good to know the AppImage is updated to 2.6, at creating the ticket latest version on https://nextcloud.com/install/#install-clients for linux was 2.5.3

Since i downgraded my installation, can anyone confirm that the 2.6 Version for windows also works? Because it didn't for me, and we can close this ticket then.

**Comment by fyah** [comment]
Advice is to change 

FROM nextcloud:fpm-alpine

to

FROM nextcloud:stable-fpm-alpine 

in my Dockerfile ?
how to see the mapping between tags and actual versions ?

now that I am on 17, is it worth and possible to get back to 16.0.5 ?

Thanks !

**Comment by Happyfeet01** [comment]
Good question. Would be nice to be on a stable version

Von meinem iPhone gesendet

**Comment by budimanjojo** [comment]
@TidhoAmla I don't know about windows since I don't use it

**Comment by Happyfeet01** [comment]
Downgrade possible with Dockerfile?

**Comment by Happyfeet01** [comment]
> Was expecting the same, but then had a look on nextcloud - server - tag list, and there the version 17 is released ( https://github.com/nextcloud/server/tree/v17.0.0 )
> 
> It's still not on stable channel or the recommended version, but that's a different story, maybe the docker manuel should be extended to use image: nextcloud:stable instead of latest.
> 
> @budimanjojo good to know the AppImage is updated to 2.6, at creating the ticket latest version on https://nextcloud.com/install/#install-clients for linux was 2.5.3
> 
> Since i downgraded my installation, can anyone confirm that the 2.6 Version for windows also works? Because it didn't for me, and we can close this ticket then.

I installed today the latest version of the windows desktop client. It works

**Comment by TidhoAmla** [comment]
Sorry used the wrong word, downgrade is not possible, it set image: nextcloud to image: nextcloud:16 and completely reinstalled the nextcloud instance (was anyway a test instance)

For the next upgrade I'll have an backup & restore concept =)

@fyah I'm not sure if there is a stable-fpm-alpine ( it's not listed on https://hub.docker.com/_/nextcloud but same goes for :stable and this exists ) and since downgrading is not possible I would suggest to use 17-fpm-alpine so you have no problems with the next release.

Since @Happyfeet01 has tested the windows client to work I can close this Issue

**Comment by Happyfeet01** [comment]
> Sorry used the wrong word, downgrade is not possible, it set image: nextcloud to image: nextcloud:16 and completely reinstalled the nextcloud instance (was anyway a test instance)
> 
> For the next upgrade I'll have an backup & restore concept =)
> 
> @fyah I'm not sure if there is a stable-fpm-alpine ( it's not listed on https://hub.docker.com/_/nextcloud but same goes for :stable and this exists ) and since downgrading is not possible I would suggest to use 17-fpm-alpine so you have no problems with the next release.
> 
> Since @Happyfeet01 has tested the windows client to work I can close this Issue

For me it was an production Instance. :-/ maybe the guys from Nextcloud can fix this issue to prevent other Users or Company’s to install 17.0.0 instead 16.0.5

**Comment by Happyfeet01** [comment]
@karlitschek

**Comment by fyah** [comment]
Thanks for the feedback.
So the best way to control the upgrades version is to set manually the target version in the dockerfile 
I still do not get how to verify easily what's behind the named tags other than comparing the hashes
