### ISSUE TITLE
Upgrade from 16.0.4 to 17.0.0 fails

### ISSUE THREAD

**Issue by RRFfm** [nextcloud/docker#875]
On a Raspberry Pi 4, running occ upgrade fails:

docker exec -u www-data -it docker_nextcloud_1 php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Updating <dav> ...
An unhandled exception has been thrown:
TypeError: Return value of OCA\DAV\Migration\Version1012Date20190808122342::changeSchema() must implement interface OCP\DB\ISchemaWrapper or be null, none returned in /var/www/html/apps/dav/lib/Migration/Version1012D                                                            ate20190808122342.php:115
Stack trace:
#0 /var/www/html/lib/private/DB/MigrationService.php(475): OCA\DAV\Migration\Version1012Date20190808122342->changeSchema(Object(OC\Migration\SimpleOutput), Object(Closure), Array)
#1 /var/www/html/lib/private/DB/MigrationService.php(411): OC\DB\MigrationService->executeStep('1012Date2019080...', false)
#2 /var/www/html/lib/private/legacy/app.php(906): OC\DB\MigrationService->migrate()
#3 /var/www/html/lib/private/Updater.php(373): OC_App::updateApp('dav')
#4 /var/www/html/lib/private/Updater.php(252): OC\Updater->doAppUpgrade()
#5 /var/www/html/lib/private/Updater.php(128): OC\Updater->doUpgrade('17.0.0.9', '16.0.4.1')
#6 /var/www/html/core/Command/Upgrade.php(258): OC\Updater->upgrade()
#7 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(908): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)                                                            )
#9 /var/www/html/3rdparty/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\C                                                            omponent\Console\Output\ConsoleOutput))
#10 /var/www/html/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/console.php(97): OC\Console\Application->run()
#13 /var/www/html/occ(11): require_once('/var/www/html/c...')

What can I do?

**Comment by RRFfm** [comment]
the same from 16.0.5
any help??

**Comment by rcdailey** [comment]
IIRC you aren't supposed to use Nextcloud's upgrade feature. Wait until a new image is built for version 17 and install it via the appropriate docker tag.

**Comment by RRFfm** [comment]
Hi Robert,

 

I pulled the image via 'docker-compose pull' (using Tag 'latest' in docker-compose.yml).

How can I recognize that the pulled image is not supposed for my Raspberry? And: which is the correct tag to wait for?

 

 

Rgds,

Roland

 

Von: Robert Dailey [mailto:notifications@github.com] 
Gesendet: Mittwoch, 16. Oktober 2019 22:09
An: nextcloud/docker <docker@noreply.github.com>
Cc: RRFfm <git@roland-roeder.de>; Author <author@noreply.github.com>
Betreff: Re: [nextcloud/docker] Upgrade from 16.0.4 to 17.0.0 fails (#875)

 

IIRC you aren't supposed to use Nextcloud's upgrade feature. Wait until a new image is built for version 17 and install it via the appropriate docker tag.

**Comment by J0WI** [comment]
Closing in favor of #810
