### ISSUE TITLE
SSL Mixed Content Error, preventing Login via Client Application

### ISSUE THREAD

**Issue by christianvw** [nextcloud/docker#876]
Hi,

when you login to your Nextcloud (Server 17.0)  via the Client Application (2.6.0 Windows), you can not log in due to a mixed content error.

The Button for granting access **links to a http url**:

````
<form method="POST" action="http://cloud.nextcloud.com/login/v2/grant">
    <input type="hidden" name="requesttoken" value="aaaa">
    <input type="hidden" name="stateToken" value="bbbb">	
    <div id="submit-wrapper">
        <input type="submit" id="submit" class="login primary" title="" value="Grant access">
	<div class="submit-icon icon-confirm-white"></div>
    </div>	
</form>
````

Due to this, every web browser prevents submitting this form. Is this my fault or is this a bug?

**Comment by christianvw** [comment]
I use Nginx as a Reverse Proxy Server which handles the SSL and redirects to Nextcloud, maybe that is a problem?

**Comment by sauroter** [comment]
You can force using https by adding.
`'overwriteprotocol' => 'https',`
to the config/config.php.

**Comment by christianvw** [comment]
I got the following command which has to be executed by the host:

`docker exec --user www-data <<<containername>>> php occ config:system:set overwriteprotocol --value="https" `

This does exactly what @sauroter described, thanks for that!
