### ISSUE TITLE
nginx permission denied when using fpm example

### ISSUE THREAD

**Issue by taaem** [nextcloud/docker#883]
When using [mariadb-cron-redis](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/insecure/mariadb-cron-redis) and possibly the other images as well, the nginx process is running as nginx:nginx (see https://github.com/nginxinc/docker-nginx/commit/b749353968a57ebd9da17e12d23f1a5fb62f9de9#diff-2803676de07439b8d816bd56f7e53776) which is mapped as 101:101 and thus has no read access to the /var/www folder which has www-data:root permissions.

This leads to nginx not being able to read css and js files and the Nextcloud page being completly broken.

I fixed this with adding:
```
adduser --system --no-create-home --home /nonexistent --gecos 'www-data user' --shell /bin/false --uid 82 www-data
```
to the web/Dockerfile and 
```
user www-data;
```
to web/nginx.conf

Maybe there is a better way to work around these permission issues but for now this is a bug and here is the workaround.
Thanks in advance!

**Comment by xcffl** [comment]
Same problem here

**Comment by thresheek** [comment]
Why not just chmod 755 /var/www/ ?

Running nginx workers as the same uid as php-fpm isnt needed at all.

**Comment by anthraxn8b** [comment]
Hi! How far did you get fixing your example within the last two years? :-)
I believe that building an nginx container just to add a config is a little bit misleading.
But solving the problem for me just works by adding the missing user to the image - as described above - or by mounting the hosts passwd file in the container.
Do you have other ideas?

**Comment by taaem** [comment]
I'm still using the workaround as described above, not beautiful but works.

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/docker/issues/980#issuecomment-1773423598
