### ISSUE TITLE
Docker Hub nextcloud logo looks squashed

### ISSUE THREAD

**Issue by kesselb** [nextcloud/docker#885]
![image](https://user-images.githubusercontent.com/3902676/66003654-0a00b280-e4a7-11e9-95a8-23fb307cc2e0.png)

https://hub.docker.com/_/nextcloud

Sorry I don't know where to report this :see_no_evil: 

cc @jospoortvliet @jancborchardt

**Comment by tilosp** [comment]
Duplicate of #529

**Comment by kesselb** [comment]
> Duplicate of #529

Indeed.
