### ISSUE TITLE
Wrong default in php-fpm/postgres setup

### ISSUE THREAD

**Issue by wucke13** [nextcloud/docker#886]
docker/.examples/docker-compose/with-nginx-proxy/postgres/fpm
will create a db with the name `postgres` yet the `docker-compose.yml` names the db `nextcloud`. In order to make it work, one has to add `POSTGRES_DB=nextcloud` to the db image environment. Without it, the db will be named as `POSTGRES_USER`.

**Comment by tilgovi** [comment]
Confirmed. This was my experience, too.
