### ISSUE TITLE
mariadb not used with docker-compose example config

### ISSUE THREAD

**Issue by davewood** [nextcloud/docker#887]
I am following the instructions on https://hub.docker.com/_/nextcloud -> Running this image with docker-compose. This should start up an instance of nextcloud with mariadb as database.

However, when im accessing the web interface I get this warning:

```
Performance warning

You chose SQLite as database.

SQLite should only be used for minimal and development instances. For production we recommend a different database backend.

If you use clients for file syncing, the use of SQLite is highly discouraged.
```

**Comment by davewood** [comment]
oh, i need to select the database running in the docker container. my bad.

**Comment by theOfficialJoeGG** [comment]
@davewood How did you do this?

> oh, i need to select the database running in the docker container. my bad.

**Comment by davewood** [comment]
im reciting from memory so pardon if i get something wrong

after starting up you visit the web-interface for the first time and there you can select mariadb as your RDBMS if i remeber correctly

**Comment by andreapx** [comment]
It's a problem with the ocker image of mariadb 10.6.3 (which is used with mariadb:latest).
Using mariadb:10.5 solves the problem.
Have a look at **[issue 1536](https://github.com/nextcloud/docker/issues/1536)**
