### ISSUE TITLE
Nextcloud Version 12 not available in Docker Hub

### ISSUE THREAD

**Issue by ellerbrock** [nextcloud/docker#89]
Hi there,

thanks for the great work.
I saw you already made the Nextcloud update to version 12 but its not available on [Docker Hub](https://hub.docker.com/_/nextcloud/) yet :(
You could configure a [automatic build](https://docs.docker.com/docker-hub/builds/) to do this automatically on changes. I could help with that if you want ...

![keep it calm in the cloud](https://media.giphy.com/media/l3q2UZGFTdIKqsSje/giphy.gif)
Cheers Maik

**Comment by lightweight** [comment]
I'm just uploading an instance built from this repo's 12 recipe... kiwilightweight/nextcloud:12-fpm

**Comment by ellerbrock** [comment]
hi @lightweight, thanks for the info.
i forked it myself and have a automatic build running (https://hub.docker.com/r/ellerbrock/nextcloud-docker/) but i would prefere to use the official library version in the future ... is there a reason why the version 12 is not available on docker hub yet?

**Comment by tilosp** [comment]
You can't fully automate the build process of official images. Once we change something in this repo a Pull Request (https://github.com/docker-library/official-images/pull/3025) is created in the [docker-library/official-images](https://github.com/docker-library/official-images) repo. This PR has to pass a few tests and gets merged within a few days. Once it's merged the new images will show up on docker hub.

**Comment by nicokaiser** [comment]
I think this relates to nextcloud/nextcloud.com#473 – then changelog on the website still shows version 11.0.3. And the automated Docker tagging process fetches version names from there.

**Comment by tilosp** [comment]
Yes but i changed it in #85 to use https://download.nextcloud.com/server/releases/
We are just waiting for docker-library/official-images#3025 to get merged.

**Comment by tilosp** [comment]
Docker Hub is now up to date

**Comment by DrMurx** [comment]
The tags for version 12 are still not there, so apparently the images are not yet built...
