### ISSUE TITLE
Add a wait for mysql before install

### ISSUE THREAD

**Issue by forty** [nextcloud/docker#892]
I use docker-compose to start my containers, and when launching for the first time, the DB takes some time to start, and it happens that sometimes the installation fails because there were to many tries. I would like to add a wait for the DB port to be open before launching the install (using https://github.com/eficode/wait-for/blob/master/wait-for for example)

**Comment by kevlar1818** [comment]
Ditto, except that wait-for-it seems a bit more popular for this: https://github.com/vishnubob/wait-for-it

**Comment by kevlar1818** [comment]
I got around this for now by cloning wait-for-it, mounting wait-for-it.sh in the image, and changing the entrypoint to run `wait-for-it.sh [wait-for-it args] -- [the usual entrypoint script and args]`.

**Comment by joshtrichards** [comment]
The Docker way of doing this today is using `depends_on` with a `condition: service_healthy`. An example for MariaDB is here:

- https://github.com/MariaDB/mariadb-docker/blob/master/examples/compose-replication.yml

All commonly used Docker-based database images (e.g. MariaDB, MySQL, PostgreSQL) can/do readily support the `healthcheck` option that can be used for the `service_health` target.

- https://docs.docker.com/compose/startup-order/
- https://github.com/MariaDB/mariadb-docker/blob/master/examples/compose-replication.yml
- https://mariadb.com/kb/en/using-healthcheck-sh/
- https://github.com/MariaDB/mariadb-docker/blob/master/healthcheck.sh
- https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/

You can even easily tweak your own healthchecks depending on your local needs - e.g:

- https://github.com/docker-library/mysql/issues/930#issuecomment-1463541157

**Comment by sfatula** [comment]
The depends_on method only works if the database is in the same compose file, which is not always the case. When it is in a separate compose file, one needs another method.
