### ISSUE TITLE
Production channel still in 16.0.4

### ISSUE THREAD

**Issue by doc75** [nextcloud/docker#896]
Hello,

It seems that production channel is still on 16.0.4 and not on 16.0.5.
Is there any reason behind that ?
I can submit a PR to fix this, but just wanted to be sure this is not intentional.

**Comment by kesselb** [comment]
> It seems that production channel is still on 16.0.4 and not on 16.0.5.

I see 16.0.5 at https://hub.docker.com/_/nextcloud

**Comment by doc75** [comment]
@kesselb, 16.0.5 is tagged as stable, not production. This is the reason for opening this issue.
The file which contain the information is https://github.com/nextcloud/docker/blob/master/generate-stackbrew-library.sh (cf. line 5 & 6)

**Comment by kesselb** [comment]
cc @nextcloud/docker

**Comment by J0WI** [comment]
That's on purpose, see https://github.com/nextcloud/updater_server/issues/269

**Comment by doc75** [comment]
@J0WI, thanks for your answer. I'll wait.
