### ISSUE TITLE
Command "maintenance:install" is not defined.

### ISSUE THREAD

**Issue by barbymarquina** [nextcloud/docker#898]
I had an image of Nextcloud (v. 14) in my production environment (AWS ECS). On September 22, the service stopped because the volume was full. Expanding the CPU, the error that appears to me is ** The "maintenance: install" command is not defined. ** I have not made any modifications to the cluster. This error started when the CPU reached the limit. I tried to update the version, but the error is the same. I still haven't found the solution.

**Comment by vicky528** [comment]
and now?

**Comment by fle108** [comment]
same error with latest and stable version.
I can't delete a deploy in k8s and keep data because when a re-deploy nextcloud want ton re-install

**Comment by J0WI** [comment]
Closing, since this mentions an EOL version.
