### ISSUE TITLE
Forwarding IP fails

### ISSUE THREAD

**Issue by KopfKrieg** [nextcloud/docker#90]
Hello everyone, I'm nut sure if I have an error in my proxy configuration or if it's an error in the nextcloud-docker configuration, but maybe someone can help me.

Im running Nextcloud 11.0.3 via Docker behind an nginx proxy and I am not able to forward the real client's ip address to the nextcloud docker container. E.g. every time the brute force protection kicks in, nextcloud logs the ip address of my proxy, and therefore all clients are throttled because nextcloud can't differ between the clients.

Does anyone else have this issue or is it just me?

This is the relevant part of my nginx proxy configuration:

```
server {
    listen      443 ssl http2;
    listen [::]:443 ssl http2;
    server_name example.org;
    root /var/www/nextcloud;
    index index.html;

    # Raise maximum file upload size
    client_max_body_size 512m;

    # Maximum download size (maximum zip32 file size in this case…)
    proxy_max_temp_file_size 4096m;

    # Nginx proxy for nextcloud docker
    location / {
        # Additional headers
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
        add_header Referrer-Policy "same-origin";

        # Secure Cookie / Allow cookies only over https
        proxy_cookie_path / "/; secure; HttpOnly";

        # Proxy parameters
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        #proxy_set_header X-Forwarded-For $remote_addr; # No visible effect
        #proxy_set_header X-Forwarded-Host $remote_addr; # Fails
        #proxy_redirect off; # No visible effect

        # Connect to local port
        proxy_pass http://127.0.0.1:32768;
    }
}
```

Any ideas?

**Comment by tilosp** [comment]
You have to add you proxy as a trusted one. Take a look at https://docs.nextcloud.com/server/12/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by KopfKrieg** [comment]
Whoops, I'm sorry. That fixed my problem, thank you very much.
