### ISSUE TITLE
Passman don't detect I'm behind a proxy

### ISSUE THREAD

**Issue by JOduMonT** [nextcloud/docker#906]
Hi;

I'm using this [docker-compose](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm/docker-compose.yml) which works perfectly.

The only issue is Passman consider nextcloud running on a non HTTPS server, which technicaly is true when you look at [nginx config](https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm/web/nginx.conf)

My 1st question is: the issue is on your side or on Passman side because it did'nt dectect I'm behing a proxy ?

My 2nd question is: How I should configure nginx.conf to use https ?

Thank you

ref: https://github.com/nextcloud/passman/issues/630

**Comment by J0WI** [comment]
https://github.com/nextcloud/docker#using-the-apache-image-behind-a-reverse-proxy-and-auto-configure-server-host-and-protocol
