### ISSUE TITLE
Add examples for manipulating the sources

### ISSUE THREAD

**Issue by arnaudmm** [nextcloud/docker#91]
Hi,

Upgrade process (rsync) is way much better that the legacy one (tar) but I'm facing an issue when upgrading as I edited some files like .user.ini : they got reseted

Any advice/tips on how to avoid that ?

**Comment by SnowMB** [comment]
Hey,

I got an idea for your problem. You write our own derived Dockerfile and copy the modified files to the folder '/usr/src/nextcloud'. So when the upgrade process kick in, the new sources contain your files.

It would look something like this:
```
FROM nextcloud

COPY <your_user.ini> /usr/src/nextcloud/.user.ini
```

**Comment by arnaudmm** [comment]
It looks fair enough, I will try! Thanks
