### ISSUE TITLE
Docker Image is not up to date.

### ISSUE THREAD

**Issue by b-reich** [nextcloud/docker#920]
The image with tag "apache" is still on version 17.0.0 not on 17.0.1

https://hub.docker.com/layers/nextcloud/library/nextcloud/apache/images/sha256-48f315a94efa5faacbca6c19c11811f3acc7b2f738cee200231f6e3bec8165f2

**Comment by tilosp** [comment]
See: https://github.com/nextcloud/docker/pull/917#issuecomment-552233970
