### ISSUE TITLE
Editing config.php breaks Nextcloud

### ISSUE THREAD

**Issue by Doblanko** [nextcloud/docker#926]
I am trying to edit the config.php file to add in preview generator options. However, whenever I edit the config file it creates a bunch of errors. Either internal server errors or other random issues. Anyone know how to safely edit the config file?

**Comment by blackerking** [comment]
May you post your config file?

this is mine:
```
  'preview_max_x' => 2048,
  'preview_max_y' => 2048,
  'preview_max_filesize_image' => 20,
  'preview_max_scale_factor' => 5,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\PDF',
    4 => 'OC\\Preview\\MSOffice2003',
    5 => 'OC\\Preview\\MSOfficeDoc',
    8 => 'OC\\Preview\\Photoshop',
    9 => 'OC\\Preview\\TIFF',
   10 => 'OC\\Preview\\SVG',
   11 => 'OC\\Preview\\MP3',
   12 => 'OC\\Preview\\OpenDocument',
)
```

**Comment by Doblanko** [comment]
The issue was around permissions of files in docker for this package. The second you edit a file it breaks the permissions and messes up the program. The fix for me was to use the linuxserver-nextcloud docker package that allows you to change the owner of all the files.
