### ISSUE TITLE
NAME_MAX 255 uploading error

### ISSUE THREAD

**Issue by sloslo4** [nextcloud/docker#929]
Recently some users join to my nextcloud instance and want to upload some files, w filenames like this one:

> ййцшугенегпыыгвафщгятфугшптугвшгтупгупгфтщшфщфцт ц ефцщ фцт щец е ьцф ецф ьфц щьфцщ ецфьцей опылвтмдг ввущцш едуфуыптд фт ефт ешфуг тефудге тдфуге тдфуги ефугши фугдшеифушгеифуг еифуг иф гшиегшфи угефи шифуг шфуеи егшфуи .pdf 

that is not real name just obfuscated example, but name length is saved, that max length what u can do with Win* systems = 226 chars 

when this user upload file on my nextcloud (i use docker) i got this (original length saved):

> OCA\DAV\Connector\Sabre\Exception\InvalidPath: File name is too long

> fopen(/var/www/html/data/admin//files/Jurists/10.10.19/SomeFolder/йцукенгшзхфываполлжяячсйцукенгшзхфываполлжяячсмимттьбюцукенгшзхфываполлжяячсмимтмимттьбюцукенгшзхфываполлйцуке (шзхфываполлжяячсмимтгшапсмимт.pdf.ocTransferId188919490.part): failed to open stream: Filename too long at /var/www/html/lib/private/Files/Storage/Local.php#301

look length here just only 173 chars, why when docker have 255 limit?

I have something around 2k files like this and Desktop Client stuck.
So what i already do, trying change my drive FS to (reiserFS) and patch linux kernel:
getconf NAME_MAX /mnt/datamount/
1023

but inside docker i got 255
so then trying change docker (/var/lib/docker) to support btrfs and again patch kernel to btrfs (like this http://wiki.etersoft.ru/Linux/VLFN)

but again inside docker i got 255 limit. 

Guys i rly need some workaround here, pls help!

**Comment by sloslo4** [comment]
My host os: Linux linux 5.3.12 #5 SMP Thu Nov 21 11:48:02 UTC 2019 x86_64 GNU/Linux

17.0.1 nextcloud

docker -v
Docker version 19.03.5, build 633a0ea838

**Comment by DatAres37** [comment]
> that is not real name just obfuscated example, but name length is saved, that max length what u can do with Win* systems = 226 chars

The 255 limit includes the file path, so if your document name is already 225 chars, it's probably too long. 
Could also be a problem with the encoding/charset.

**Comment by blackerking** [comment]
These kind of problems are everywhere. Even Word and Excel(some versions of it) can't call files with more than 255 chars. Trying to minimize foldernames is the only solution.

**Comment by J0WI** [comment]
This is not related to Docker. Many Unix-like systems do not support filenames > 255 chars by default.
https://github.com/nextcloud/server/issues/9907 is related, but not limited to Docker.
