### ISSUE TITLE
docker build erro 

### ISSUE THREAD

**Issue by liaoqiArno** [nextcloud/docker#934]
When I build a image
Step 4/4 : ADD ${JAR_FILE} /app/code/app.jar
`failed to export image: failed to set parent sha256:24b9ba7e5e60d53deae385425d7658e4eb1d3a6a0977bff0345310c4974a6f60: unknown parent image ID sha256:24b9ba7e5e60d53deae385425d7658e4eb1d3a6a0977bff0345310c4974a6f60`
But I try again ,it's success!
I only get this mistake once in a while.

my OS: centos7
kernel version： 3.10.0-957.5.1.el7.x86_64
docker version : 18.09.2

**Comment by J0WI** [comment]
Doesn't seem to be reproducible. See also https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
