### ISSUE TITLE
SSL Mixed Content Error, Windows Client

### ISSUE THREAD

**Issue by r33net** [nextcloud/docker#935]
I have the same error as described in #876 run NC in Docker behind nginx proxy. 

The Button for granting access links to a http url:

	<p id="redirect-link">
		<form method="POST" action="http://nextcloud.domain.de/login/v2/grant">
			<input type="hidden" name="requesttoken" value="11111" />
			<input type="hidden" name="stateToken" value="222222" />	
			<div id="submit-wrapper">
				<input type="submit" id="submit" class="login primary" title="" value="Zugriff gewähren" />
				<div class="submit-icon icon-confirm-white"></div>

**My config.php**
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'nextcloud.domain.de',
  ),
  'overwrite.cli.url' => 'https://nextcloud.domain.de',
  'overwriteprotocol' => 'https',
  'overwritehost' => 'nextcloud.domain.de',
);

**Comment by cropse** [comment]
Same issue here, it's a mixed http form submit url in https page.

**Comment by J0WI** [comment]
https://github.com/nextcloud/docker#using-the-apache-image-behind-a-reverse-proxy-and-auto-configure-server-host-and-protocol
