### ISSUE TITLE
Internal Server Error after upgrading to 17.0.0

### ISSUE THREAD

**Issue by leggettc18** [nextcloud/docker#938]
After running `docker-compose pull` and `docker-compose up -d` to update my nextcloud:apache docker image for nextcloud, I am now getting an internal server error when I try to access my nextcloud instance. The server logs (obtained from docker logs) show 500s and 503s. Whenever I try to access it. I'll post some better logs later on, I am limited to the web console right now which is difficult to copy-paste out of. In the meantime if anyone has any ideas I'd love to hear them.

**Comment by rafaelgou** [comment]
Hi. Not sure if you get any success.

I got the same error, in my case checking data/nextcloud.log pointed to a redis misconfiguration (I didn't have the linked correctly on docker-compose.yml).

**Comment by J0WI** [comment]
If this happens again, you may use [occ](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html) to debug the issue. A common fix is to update 3rd party apps and validate the config.
