### ISSUE TITLE
Apache image creates files world-readable

### ISSUE THREAD

**Issue by Gigadoc2** [nextcloud/docker#945]
I am using the `docker.io/library/nextcloud:17-apache` image and noticed that new files uploaded/created by users are written to disk with world-readable permissions.
It does not seem to matter what permissions the parent folders have.

**Comment by joshtrichards** [comment]
The `datadirectory` is mode 770:

```
www-data@87a531937a48:~/html/data$ ls -ld
drwxrwx--- 10 www-data www-data 4096 Oct 20 00:55 .
```

The permissions of files underneath it are irrelevant.
