### ISSUE TITLE
17.0.1 -> 17.0.2 upgrade: big int conversion

### ISSUE THREAD

**Issue by BitBernd** [nextcloud/docker#947]
Hi,

I upgraded from 17.0.1 to 17.0.2 and now I get the following warning:

Some columns in the database are missing a conversion to big int. Due to the fact that changing column types on big tables could take some time they were not changed automatically. By running 'occ db:convert-filecache-bigint' those pending changes could be applied manually. This operation needs to be made while the instance is offline. For further details read the documentation page about this.

    mounts.storage_id
    mounts.root_id
    mounts.mount_id

I tried to execute the commands described in the docs:
https://docs.nextcloud.com/server/17/admin_manual/configuration_database/bigint_identifiers.html

Bit I am not able to su into www-data inside the container, which would be necessary for this to work.
Furthermore, in my understanding it would be against best practice to mess around inside my docker container, wouldn't it?

So, how can I fix this ?

kind regards and thank you for your help!

**Comment by BitBernd** [comment]
Ok,

I was stupid xD
Fixed it by running:

docker exec --user www-data <nextcloud-container-name> php occ db:convert-filecache-bigint

**Comment by mschoettle** [comment]
I had this on a fresh installation of 17.0.2. Thanks for the command to fix it.
