### ISSUE TITLE
Having trouble setting this up using podman with an nginx reverse proxy

### ISSUE THREAD

**Issue by leggettc18** [nextcloud/docker#948]
I was attempting to set this up using podman rather than docker. This means I cannot use docker-compose, and the automated letsencrypt setup will not work as it requires mounting the docker socket to the jwilder and letsencrypt helper containers, for which podman has no equivalent. I already set up an nginx reverse proxy container and a letsencrypt container for the certs, and I have that set up and working with cockpit already. I can enter cockpit.domain.tld and access that through SSL using a wildcard certificate.

However, I'm having trouble getting this to work with the nextcloud container. I can access it through the IP and port just fine, but when I try to access it with nextcloud.domain.tld, depending on some tinkering I've done with the nextcloud.conf file in nginx/conf.d/sites-enabled, I either get a blank page, "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.", a 502 Bad Gateway, or a 504 Gateway Time-out.

NGINX config files

nginx.conf
```
events {
    worker_connections 4096;
}

http {
    include /etc/nginx/conf.d/sites-enabled/*.conf;
}
```

nextcloud.conf
```
upstream nextcloud {
    server	<publicIP>:8080;
}

server {
    listen	443 ssl;
    server_name nextcloud.domain.tld;
    
    include common.conf;
    include /etc/nginx/ssl.conf;

    location / {
        proxy_pass	http://nextcloud;
	include		common_location.conf;
    }
}
```

common.conf
```
add_header Strict-Transport-Security	"max-age=31536000; includeSubDomains" always;
add_header X-Frame-Options		SAMEORIGIN;
add_header X-Content-Type-Options	nosniff;
add_header X-XSS-Protection		"1; mode=block";
```

common_location.conf
```
proxy_set_header	X-Real-IP		$remote_addr;
proxy_set_header	X-Forwarded-For		$proxy_add_x_forwarded_for;
proxy_set_header	X-Forwarded-Proto	$scheme;
proxy_set_header	Host			$host;
proxy_set_header	X-Forwarded-Host	$host;
proxy_set_header	X-Forwarded-Port	$server_port;
```

ssl.conf
```
ssl_protocols 			TLSv1 TLSv1.1 TLSv1.2;
ssl_ecdh_curve			secp384r1;
ssl_ciphers			"ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384 OLD_TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 OLD_TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256";
ssl_prefer_server_ciphers	on;
ssl_dhparam			/etc/nginx/dhparams.pem;
ssl_certificate			/etc/ssl/private/fullchain.pem;
ssl_certificate_key		/etc/ssl/private/privkey.pem;
ssl_session_timeout		10m;
ssl_session_cache		shared:SSL:10m;
ssl_session_tickets		off;
ssl_stapling			on;
ssl_stapling_verify		on;
```

A few notes. If I set the upstream server to the public IP:8080 (the port I forwarded the container's port 80 to) I get the 504. If I set the upstream server to nextcloud:80 (which I set the hostname of the container to), I get the blank pages and the "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable" message. If I leave everything else untouched and navigate directly to the public IP port 8080, it appears to work fine. If I go to domain.tld:8080, I get an SSL_ERROR_RX_RECORD_TOO_LONG.

The server is running CentOS 8. I have tried with SELinux both enabled and disabled. If any further information is needed just ask.

Actual domains and IPs removed for security reasons.

**Comment by Gymnae** [comment]
I'm looking to migrate from docker to Podman, your issue seems to be a logical problem of Podman having no daemon and no sockets. Have you solved your problem?

**Comment by leggettc18** [comment]
Sort of, my problem ended up being a networking issue between the nextcloud and nginx containers, solution ended up being for reverse proxy container's network to be set to host, there's been a podman update on CentOS since then so that might not be necessary anymore, not sure.

**Comment by monreal** [comment]
Would be nice to have some more information and config samples on how you replaced the jwilder and letsencrypt helper containers, @leggettc18.
