### ISSUE TITLE
nextcloud:fpm Request Entity Too Large

### ISSUE THREAD

**Issue by l0calh05t** [nextcloud/docker#95]
I am running a docker-compose setup using nextcloud:fpm, nginx, nginx-proxy and docker-letsencrypt-nginx-proxy-companion (based on the example in .example, but without a non-sqlite db, redis or collabora). This works for the most part, however I cannot upload files larger than 2MB. According to #32 docker-letsencrypt-nginx-proxy-companion can cause this, but adding a `client_max_body_size` setting to the default or VIRTUAL_HOST-specific vhost.d files has no effect.

Could this be caused by the fast_cgi in the fpm module? I tried adding `fastcgi_param PHP_VALUE "upload_max_filesize = 4000M \n  post_max_size=4000M";` to the server config but this doesn't appear to have any effect either.

**Comment by SnowMB** [comment]
Seems like your proxy setting was fine, but the error is in the image: #97

**Comment by kunago** [comment]
Using docker-compose there should be some way to overwrite the conf files but trying nearly everything I am still unable to make it work. Does anyone have a hint?

**Comment by bang-uin** [comment]
Seem like the error is coming from the nginx proxy.

Please try to add 

`client_max_body_size 10G;`

to the end of _proxy/vhost.d/default_

Restart the proxy and try to upload a > 2MB file.

**Comment by l00ptr** [comment]
I have the same issue. It works if I add the client_max_body_size 1G; to proxy/vhost.d/default. But this file is eresased/templated if I restart the letsencrypt-companion container. Don't know where I can put some extra config for it nginx or letsencrypt container.

**Comment by bang-uin** [comment]
Hmm, this is strange. 
I have updated everything, restarted all instances and even rebooted.
My entry is still there.

**Comment by l00ptr** [comment]
did you restart your letsencrypt-companion container? 

Restarting it in my case always overwritte the default file

```
 % sudo cat default    
## Start of configuration add by letsencrypt contain
location /.well-known/acme-challenge/ {
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
client_max_body_size 1G;
## End of configuration add by letsencrypt container


 % sudo docker restart letsencrypt-companion
letsencrypt-companion



 % sudo cat default 
## Start of configuration add by letsencrypt container
location /.well-known/acme-challenge/ {
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
## End of configuration add by letsencrypt container
```

**Comment by pr4xx** [comment]
I had the same issue and resolved it via creating a `my.con` in `proxy/conf.d` with the following content:
`client_max_body_size 10G;`

**Comment by l00ptr** [comment]
Thx @pr4xx  that's almost what  I did after reading the nginx docker documentation :)

**Comment by romainreignier** [comment]
@l00ptr You have to add the line from @bang-uin **after** the last comment about `letsenscrypt` otherwise it will be overwritten.

```
## Start of configuration add by letsencrypt contain
location /.well-known/acme-challenge/ {
    allow all;
    root /usr/share/nginx/html;
    try_files $uri =404;
    break;
}
## End of configuration add by letsencrypt container

client_max_body_size 10G;
```

**Comment by SnowMB** [comment]
You don't have to edit the `default.conf`. Just add another file with any name containing just the line @pr4xx posted. So you have 2 files in your `conf.d` folder. 

`my.conf`:
```
client_max_body_size 10G;
```

**Comment by LeConcepteur1976** [comment]
> client_max_body_size 10G;

Thank you very much dud
