### ISSUE TITLE
Container apache web server inaccessible

### ISSUE THREAD

**Issue by Dextroz** [nextcloud/docker#958]
Using the basic run command: `sudo docker run -d -p 8080:80 nextcloud`

The container is inaccessible with port 80 opened. Possibly due to the apache server binding to the docker interface?

`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3.`

**Comment by J0WI** [comment]
You just mapped the containers port `80` to your local port `8080`: https://docs.docker.com/engine/reference/commandline/run/#publish-or-expose-port--p---expose
