### ISSUE TITLE
Upgrade from 17.0 to 17.0.2

### ISSUE THREAD

**Issue by Riflerat** [nextcloud/docker#960]
Hello,

I'm not expert in docker and I don't wanna make any bad things. I would like to safety upgrade my Nextcload to 17.0.2. Unfortunately the Open updater doesn't work (link to https://mydomain.domain/settings/admin/overview#) 
What is the most safe mode for upgrade?
Thanks for all answers.

**Comment by J0WI** [comment]
You can pull the latest 17 version and set the `NEXTCLOUD_UPDATE` [environment variable](https://github.com/nextcloud/docker#auto-configuration-via-environment-variables).

**Comment by Riflerat** [comment]
There is no info, sorry, how to update.

**Comment by Bleuzen** [comment]
If you use docker-compose:

```
docker-compose down
docker-compose pull
docker-compose up -d
```
