### ISSUE TITLE
local external storage

### ISSUE THREAD

**Issue by flower1024** [nextcloud/docker#962]
hello,

do you have a solution for local "external" storage and uid/gid?
i made this dockerfile to change the uid and gid of www-data but a cleaner solution would be appreciated.
[Dockerfile.txt](https://github.com/nextcloud/docker/files/4051629/Dockerfile.txt)

**Comment by patrick-motard** [comment]
relates to #359

**Comment by joshtrichards** [comment]
Fixed by #1812
