### ISSUE TITLE
php.ini settings

### ISSUE THREAD

**Issue by hpl0815** [nextcloud/docker#97]
Hello,

I think this is maybe a pretty dummy question, but due to the fact that the docker concept and nextcloud is quite new to me, I hope someone can give me a hint where to find the php.ini within my container? I would like to configure opcache and max file size limitation.

Thanks in advance!

**Comment by githtz** [comment]
I've got the same problem here. I cannot change the max upload filesize in the nextcloud admin menu ('Missing permissions to edit from here.'). The other settings are as well not configured the way they're supposed to be.

**Comment by githtz** [comment]
Found a hackish solution for my problems.

Enable PHP OPcache
```# docker cp nextcloud:/usr/local/etc/php/conf.d/opcache-recommended.ini /var/tmp/opcache.ini```
Then edit the file with any editor, remove all content from it and insert:
```
opcache.enable=1
opcache.enable_cli=1
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.memory_consumption=128
opcache.save_comments=1
opcache.revalidate_freq=1
```
Then write the file contents back into the docker image.
`# docker cp /var/tmp/opcache.ini nextcloud:/usr/local/etc/php/conf.d/opcache-recommended.ini`

To increase the max upload size I modified this [nginx-template](https://github.com/jwilder/nginx-proxy/blob/master/nginx.tmpl). Within each block that starts with 
`server {`
I added 
`client_max_body_size 100G;`

After those modifications I didn't get any warning message anymore. Any cleaner approach is most welcome.

**Comment by ebrainte** [comment]
Thats because (i think) the following lines in the Dockerfile are not working:

```
RUN { \
  echo 'opcache.enable=1'; \
  echo 'opcache.enable_cli=1'; \
  echo 'opcache.interned_strings_buffer=8'; \
  echo 'opcache.max_accelerated_files=10000'; \
  echo 'opcache.memory_consumption=128'; \
  echo 'opcache.save_comments=1'; \
  echo 'opcache.revalidate_freq=1'; \
  } > /usr/local/etc/php/conf.d/opcache-recommended.ini
RUN a2enmod rewrite
```


@tilosp Made the last commit on the dockerfiles

Maybe if we modify it this way it will work.

```
RUN echo $' \n\
opcache.enable=1; \n\
opcache.enable_cli=1; \n\
opcache.interned_strings_buffer=8; \n\
opcache.max_accelerated_files=10000; \n\
opcache.memory_consumption=128; \n\
opcache.save_comments=1; \n\
opcache.revalidate_freq=1;' > /usr/local/etc/php/conf.d/opcache-recommended.ini
```

I dont know if its really a good practice to do it this way (i'm really new in docker), but as i saw on internet it could work (see https://stackoverflow.com/questions/33439230/how-to-write-commands-with-multiple-lines-in-dockerfile-while-preserving-the-new)

**Comment by hpl0815** [comment]
@githtz Thanks, that "workaround" works for me too. As you stated, any cleaner approach is very welcome.

**Comment by tilosp** [comment]
Why do you think my changes are not working? The problem is that it is not jet published to docker hub. And even if published it gets only applied if nextcloud is updated or newly setup.

**Comment by ebrainte** [comment]
Thats why i wasnt sure.

I made a fresh install of the last updated image ( from 3 days ago), and these changes on the .ini file werent being applied, thats why i thought the published docker image had this commit inside... If its not, we just have to wait till the new images gets uploaded

Thanks

**Comment by githtz** [comment]
Has anyone been able to get memory caching to work with the nextcloud docker image?

@tilosp Your changes did fix the problem!
