### ISSUE TITLE
18.0.0: "This directory is unavailable, please check the logs or contact the administrator"

### ISSUE THREAD

**Issue by jbglaw** [nextcloud/docker#970]
Hi!
I've been playing around with some 17.x.y docker version previously which seemed to work just find. As I found out, a new release was on the fly and pulled the current docker version and started from scratch.
Externally, there's Nginx:

>         location /nextcloud/ {
>                proxy_set_header        X-Real-IP       $remote_addr;
>                proxy_set_header        X-Forwarded-For $remote_addr;
>                proxy_set_header        Host            $host;
>                proxy_pass              http://localhost:8081/;
>                client_max_body_size    10000M;
>        }

Nextcloud is started like this:
>exec docker run                                                                 \\
>        --volume  `pwd`/nextcloud_data:/var/www/html                            \\
>        --env     "POSTGRES_DB=${POSTGRES_DB}"                                  \\
>        --env     "POSTGRES_USER=${POSTGRES_USER}"                              \\
>        --env     "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"                      \\
>        --env     "POSTGRES_HOST=${POSTGRES_HOST}"                              \\
>        --env     "NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}"                \\
>        --env     "NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}"        \\
>        --publish 8081:80                                                       \\
>        nextcloud:apache

config.php was changed at two places:

1. Add '*' as a trusted domain (needed for Nginx reverse proxy, I failed to get it working using $NEXTCLOUD_TRUSTED_DOMAINS, probably due to quoting issues.
1. I added "'overwritewebroot' => '/nextcloud/'" for the reverse proxy as well.

With the current 18.0.0 version (Docker: nextcloud/apache, ef0f07bbd853), I'm getting an error pop-up telling "This directory is unavailable, please check the logs or contact the administrator", and after login, my URL looks like https://jbglaw-octopus.dyn.lug-owl.de/nextcloud//apps/files/ . I guess that apps/files might be an issue, whereever it is coming from.

Looking through settings/admin/overview, there are a number of issues that seem to be new (compared to 17.x.y):

- Your web server is not yet properly set up to allow file synchronization, because the WebDAV interface seems to be broken.
- Missing index "calendarobject_calid_index" in table "oc_calendarobjects_props".
- Missing index "schedulobj_principuri_index" in table "oc_schedulingobjects".
- Missing bigint conversion: mounts.storage_id, mounts.root_id, mounts.mount_id

I dropped the PostgreSQL database beforehand and wiped the supplied /var/www/html directory, so this is a completely new installation. I would have expected that for a fresh installation, the column types and indices were readily created?

Most probably, each of the issues is only a small thing to fix, please let me know if/how I can assist. The previous Docker worked quite well for testing, I quite like that setup, would be perfect to get that up'n'running for the 18.0.0 release as well. (And maybe fix the issues with trusted domain and overwritewebroot as mentioned before, so no further manual config file editing would be needed.)

Thanks a lot!
Jan-Benedict

**Comment by otto802** [comment]
Hi, I've got the same issue. Where you able to resolve it? I'm also running nginx as proxy in front of the docker installation (containing fpm, another nginx). I also would like to use a "subdir"-webpath.

**Comment by otto802** [comment]
this fixed it:

    location  /share {
        proxy_headers_hash_max_size 512;
        proxy_headers_hash_bucket_size 64;
        add_header Front-End-Https on;

        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host:$server_port;
        proxy_set_header X-Real-IP         $remote_addr;

        rewrite /share/(.*) /$1  break;
        proxy_pass         http://localhost:8080;
        proxy_redirect     off;
        proxy_set_header   Host $host;
    }

before I tried just "proxy_pass http://localhost:8080/;" (with a trailing slash). This usually needs no extra rewrite rule (nginx does that internally). Somehow that seems not to work properly -

**Comment by joshtrichards** [comment]
Hi @jbglaw - I hope you found a solution through another channel. As this is a fairly old issue and many things have changed, I'm going to close this out. Feel free to follow-up at the [Nextcloud Help Forum](https://help.nextcloud.com) with questions or troubleshooting assistance. 

Or open a new Issue here if you have an actionable enhancement request or bug to report in the Nextcloud community Docker image itself.
