### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by pcoves** [nextcloud/docker#974]
Hi!

I'm using Nextcloud on a dedicated (kimsufi) server using Docker.
It's been up for almost two years but I kind of broke it yesterday while updating.

Here is what I did:
```bash
cd docker/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/
docker-compose stop
git stash push # Save DB and Let'sEncrypt config
git pull
git stash pop 
docker-compose build --pull
docker-compose up -d
```
As far as I remember I always did it this way but I could be wrong.

Now, whenever I try to access the cloud I'm greeted by this message (French, sorry) :
```
Erreur interne du serveur

Le serveur est incapable d'exécuter votre requête.

Si cela se reproduit, veuillez envoyer les détails techniques ci-dessous à l'administrateur du serveur.

Le fichier journal du serveur peut fournir plus de renseignements.
Renseignements techniques

    Adresse distante : XX.XX.XX.XX
    ID de la demande : kbWNOxHZ97f1vNNxzHtL
```
Basically an *internal server error* with ID *kbWNOxHZ97f1vNNxzHtL*.

So, I went to the `nextcloud.log` file but there is no such an ID and the last line in it was from two days ago.

I went to both the `fpm_web_1` and `fpm_app_1` docker and looked for log files but the did not find anything in the  first and the second outputs its error logs to `/dev/stderr`.
So, I did `docker logs fpm_app_1 -f` and discovered that I introduced permissions issues while updating (did not take time to copy the log, my bad).

Here is where I f*cked up I gess : 
```
docker exec -it fpm_app_1 sh
chown -R www-data:www-data *
```

Now, I don't even have the Nextoloud page but a black on white text : 
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

Si basically, I destroyed the files permissions without thinking twice and have no clue on how to fix it.
Any help would be greatly appreciated!

**Comment by pcoves** [comment]
Up?

**Comment by rafaelgou** [comment]
Hi. Not sure if you get any success.

I got the same error, in my case checking `data/nextcloud.log` pointed to a redis misconfiguration (I didn't have the linked correctly on `docker-compose.yml`).

**Comment by pcoves** [comment]
Hi @rafaelgou 

Did not succeed at the moment as I've no idea what to do.

It's still sitting on a server, waiting for something but it might well be its end.

**Comment by rafaelgou** [comment]
@pcoves , why don't you copy/paste the content of `data/nextcloud.log`? The stack trace is pretty informative. If you use volumes, it's supposed to be either in (depending on your configuration):

- `/YOUR-NEXTCLOUD-DIRECTORY/data`
- or `/var/lib/docker/volumes/nextcloud_data/_data/nextcloud.log`

**Comment by pcoves** [comment]
Copied data to another server and start anew.
