### ISSUE TITLE
"Unknown error" when open OnlyOffice document in Nextcloud 18

### ISSUE THREAD

**Issue by b3nis** [nextcloud/docker#975]
Hello,

I have installed Nextcloud 18 (with ngix, mariadb, letsencrypt) and everything works flawless with https/ssl and file management - but today I enabled OnlyOffice document server (the one built in) and when I open the OnlyOffice connector setting the address to my server was pre-filled, but only "http" and it did not connect. I changed to https and the rest of the settings popped up. I manage to create documents and when I click on them they open in OnlyOffice but then I get thrown this error "Unknown error" in OnlyOffice. See [this screen record](https://youtu.be/RL79ToCvff0) (sorry for the bad cropping).

I have no weird apps and this is a fresh install - so I would guess it's some kind of bug or bad setup (I follow [this guide](https://blog.ssdnodes.com/blog/installing-nextcloud-docker/) to set it up).

From the log:

> {"reqId":"5j1BJ53FJJkc3mXqxtdG","level":3,"time":"2020-01-24T00:14:24+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"svQLLlWzFh1av3Fxzn96","level":3,"time":"2020-01-24T00:14:25+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"sTld2GdbjSbhI7qGjdAU","level":3,"time":"2020-01-24T00:14:25+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"UdNmJeSVjc2R5mvzTr3B","level":3,"time":"2020-01-24T00:14:25+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"uwACv2js2Iw2cVS2dElS","level":3,"time":"2020-01-24T00:14:26+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"7UAu5XGyho8LuMuOIAjN","level":3,"time":"2020-01-24T00:14:30+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"0Qk23swFbZBLqhnAtbV7","level":3,"time":"2020-01-24T00:14:30+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"JXIxSC2nqlup5kHEWlKG","level":3,"time":"2020-01-24T00:14:30+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}

_(my.server.com is, of course, not the real domain)_

Big thanks in advance!

**Comment by Drizztfire** [comment]
I have the same issue

**Comment by swillert** [comment]
Me too.

**Comment by enzyx** [comment]
Same here

**Comment by b3nis** [comment]
I fixed it when I was trying to fix the login issues I had with the desktop sync client.

'overwriteprotocol' => 'https', (add)
'overwrite.cli.url' => 'https' (change)

In the config.php for NextCloud. I am not sure which one sorted it out, I haven't had time to try yet.

Let me know if it works for you as well!

**Comment by enzyx** [comment]
Confimed. Fixed it by adding

'overwriteprotocol' => 'https',

in the config.php of my nextcloud installation.

**Comment by b3nis** [comment]
Glad to hear that! 

How can I ping the Nextcloud-docker people about this?

**Comment by Drizztfire** [comment]
Confirmed !

`'overwriteprotocol' => 'https',`

Fixed !

**Comment by mr-bolle** [comment]
Alternative Workaround -- found here https://github.com/nextcloud/docker/issues/792

`docker exec -it -u www-data nextcloud bash -c './occ config:system:set overwriteprotocol --
value="https"'`

**Comment by mr-bolle** [comment]
Have you found a solution to run this adjustment out of the box, without without any manually modification of the config.php?

**Comment by semanuelgr86** [comment]
Fellows, Onlyoffice DocumentServer 5.5.1 seems to be broken. I have downgraded to Onlyoffice Document Server 5.5.0 using GitHub deb file and my Nextcloud instance is connecting back to the Document Server without issues. 
Here is the link I used to download deb file. I followed all pre-requisites installation instructions including postgresql from the Onlyoffice forum.
https://github.com/ONLYOFFICE/DocumentServer/releases

**Comment by RundleSG** [comment]
> I fixed it when I was trying to fix the login issues I had with the desktop sync client.
> 
> 'overwriteprotocol' => 'https', (add)
> 'overwrite.cli.url' => 'https' (change)
> 
> In the config.php for NextCloud. I am not sure which one sorted it out, I haven't had time to try yet.
> 
> Let me know if it works for you as well!

Confirmed this fixed it for me
'overwriteprotocol' => 'https', (add)

**Comment by csanto10** [comment]
> I fixed it when I was trying to fix the login issues I had with the desktop sync client.
> 
> 'overwriteprotocol' => 'https', (add) 'overwrite.cli.url' => 'https' (change)
> 
> In the config.php for NextCloud. I am not sure which one sorted it out, I haven't had time to try yet.
> 
> Let me know if it works for you as well!

Thank you!  worked like a charm!!!
