### ISSUE TITLE
App update required on container restart

### ISSUE THREAD

**Issue by franco-martin** [nextcloud/docker#977]
Hello, im running nextcloud on rancher. I have a mysql 8 statefulset and a nextcloud 17 scaleset. Every time i create a new container either from a restart or scaling, i am prompted to update with the "App update required" message.
I read the documentation but i didnt find anything related to my issue other than the following:
"The install and update script is only triggered when a default command is used (apache-foreground or php-fpm). If you use a custom command you have to enable the install / update with
NEXTCLOUD_UPDATE (default: 0)"
maybe im missing something but i dont think its related.

**Comment by eorn** [comment]
Same issue here.
I'm using the  `nextcloud:17.0.3-apache` Docker image.

**Comment by franco-martin** [comment]
@eorn I created a cypress test to bypass that freaking screen untill this is solved.
https://gitlab.com/francomartin3/nextcloud-update Feel free to create issues.
