### ISSUE TITLE
Problem force https over WAN 

### ISSUE THREAD

**Issue by ErAzOr2k** [nextcloud/docker#978]
My setup:

NC Host: 10.0.3.11 (v18 alpine insecure docker)
Reverse Proxy: 10.0.3.5 (traefik 2.0, but als tried with nginx)

I try to force https  when coming from WAN over reverse proxy.
For this I configured like this:

`  'trusted_proxies' =>
  array (
    0 => '10.0.3.5',
  ),
  'overwritecondaddr' => '^10\\.0\\.3\\.5$',
  'overwriteprotocol' => 'https',
`

The problem is, that the variable $_SERVER["REMOTE_ADDR"] (checked with phpinfo), is not the IP of the reverse proxy, instead it's the actual IP of the client. In this case, the parameter "overwritecondaddr" is without effect.

Any ideas?

**Comment by ErAzOr2k** [comment]
I think the issues comes from this pull: https://github.com/nextcloud/docker/pull/297

so $_SERVER["REMOTE_ADDR"] is always the real IP instead of the reverse proxy IP. In this case, the parameter "overwritecondaddr" is useless.

**Comment by cronoself** [comment]
Have the exact same problem, there are already some solution?

**Comment by J0WI** [comment]
https://github.com/nextcloud/docker#using-the-apache-image-behind-a-reverse-proxy-and-auto-configure-server-host-and-protocol
