### ISSUE TITLE
[FR] Envvar for allowed proxies

### ISSUE THREAD

**Issue by JuniorJPDJ** [nextcloud/docker#979]
Hello!
It would be great to be able to set allowed proxy IP by envvar.
IMO in docker environment it's essential to have reverse proxy settings exposed for easy configuration.

**Comment by J0WI** [comment]
I guess you mean trusted proxies? https://github.com/nextcloud/docker#using-the-apache-image-behind-a-reverse-proxy-and-auto-configure-server-host-and-protocol
