### ISSUE TITLE
Containers in example composes are working on other UIDs (nginx + alpine php-fpm)

### ISSUE THREAD

**Issue by JuniorJPDJ** [nextcloud/docker#980]
At the moment nginx is working on uid=101 as we can see here:
https://hub.docker.com/_/nginx in section "User and group id"
and alpine php-fpm is working with id=82 as we can see here:
https://github.com/docker-library/php/blob/master/7.3/alpine3.11/fpm/Dockerfile#L34

It makes me (and probably other people too) having files readable by other users which is pretty bad solution to the problem.

**Comment by joshtrichards** [comment]
Hi @JuniorJPDJ - Today you can use the `--user` (command-line) or `user: UID:GID` (Compose) if your local environment requires it.

Implemented in #1812

That's one approach; there are others depending on how you use Docker and volumes [e.g. https://docs.docker.com/engine/security/userns-remap/].

As this is a fairly old issue and many things have changed, I'm going to close this out. Feel free to follow-up at the [Nextcloud Help Forum](https://help.nextcloud.com) with questions or troubleshooting assistance. Or open a new Issue here if you have an actionable enhancement request or bug to report (and that is specific to the community Docker image obviously).
