### ISSUE TITLE
使用docker安装，然后用nginx做反向代理共用80端口，地址跳转有问题

### ISSUE THREAD

**Issue by zhangziying1998** [nextcloud/docker#983]
背景描述如下
使用docker安装，然后用nginx做反向代理共用80端口，服务器给nextcloud的端口是8010
用nginx把我的域名(pan.xxx.com)反向代理到服务器本地地址(localhost:8010) 
问题描述如下：
1. 部分地址跳转有问题， 跳转到到了http://localhost:8010/xxx (应该跳转到http://pan.xxx.com/xxx)
2. 页面显示链接错误（凡是像下面这样直接显示链接的都有问题）
![image](https://user-images.githubusercontent.com/39129243/73467043-b1daae00-43bd-11ea-9595-c0bf491098e9.png)
3. 部分图片图标显示不了
![image](https://user-images.githubusercontent.com/39129243/73467221-fcf4c100-43bd-11ea-997a-ef5d1b26db21.png)
点击之后跳转链接也是
![image](https://user-images.githubusercontent.com/39129243/73467280-1564db80-43be-11ea-8ff6-932feb16e88b.png)
4. 之前网址挂了ssl证书(现在过期了就没挂了)，分享链接复制后问题同上(去除ssl后没有问题)

总的来说，用nginx做反向代理后，网盘系统的地址出现代理的地址，而不是要显示的域名

**Comment by FTFX** [comment]
在顶级Nginx中添加`proxy_set_header Host $host;`

**Comment by realnacht** [comment]
用nginx-proxy和letsencrypt-nginx-proxy-companion需要配置一下nextcloud, 在config/config/php中添加: 
```
'overwriteprotocol' => 'https'
```
我加了后解决了你提到的部分图片显示不了以及我碰到的桌面端登陆不了的问题。  

具体: 
>```bash
>docker exec -it nextcloud /bin/bash
>cd config/
>vim config.php
>insert the line: 'overwriteprotocol' => 'https'
>```
来源:
https://help.nextcloud.com/t/connection-wizard-is-looping-between-log-in-and-grant-access/46809/5

**Comment by J0WI** [comment]
6d2390726fe7110b406c447d48aa345fc9d07122
