### ISSUE TITLE
Docker-swarm and bind-mounts

### ISSUE THREAD

**Issue by bf8392** [nextcloud/docker#986]
Hi, I'm trying to migrate from an old serverinstallation to docker swarm and have a huge problem...when I set bindmounts for the datadirecetory (which is samba) the group and permission show xfs...so the container can't access it without beeing root....has somebody solved this? or found a wa around?

**Comment by bd8392** [comment]
I found out that it was an issue of rancheros (which I'm using) sorry for posting! But there is still an issue with permissions...I mounted the data to /data inside the container...but nextcloud (www-data) can't access it, even if uid and gid are 33...

**Comment by joshtrichards** [comment]
Hi @bf8392 - I hope you found a solution through another channel. As this is a fairly old issue and many things have changed, I'm going to close this out. Feel free to follow-up at the [Nextcloud Help Forum](https://help.nextcloud.com) with questions or troubleshooting assistance. Or open a new Issue here if you have an actionable enhancement request or bug to report in the Nextcloud community Docker image itself.
