### ISSUE TITLE
Ship 17.0.3 on stable channel

### ISSUE THREAD

**Issue by Bleuzen** [nextcloud/docker#989]
Stable docker version is still on 17.0.2, but 17.0.3 is out more than a week now.

17.0.3 is shipped to 100 % on stable channel on official updater:
https://github.com/nextcloud/updater_server/commit/b471bc1ef9c55e7b309d938eb198e797a732f9b8

**Comment by tilosp** [comment]
Fixed by https://github.com/nextcloud/docker/commit/ddf60930f1f6d8b102f5bb78cd626de326fa9dcd
