### ISSUE TITLE
18.0.3 update is not available fast enough on Docker Hub.

### ISSUE THREAD

**Issue by jtagcat** [nextcloud/docker#999]
![image](https://user-images.githubusercontent.com/38327267/74559843-32241600-4f5d-11ea-9f35-e6aabbe3faa7.png)
When I click the `Open Updater` I get redirected to `/apps/files`.

**Comment by danofun** [comment]
I experience the same issue when attempting to upgrade to 18.0.3.

**Comment by jtagcat** [comment]
Do `docker pull` and depending on your setup `docker-compose up -d`.

**Comment by SimJoSt** [comment]
@jtagcat unfortunately there is no 18.0.3 tag on Docker hub.

**Comment by jtagcat** [comment]
You can't expect upstream to be here right after it comes out.

**Comment by kesselb** [comment]
Closing because 18.0.3 is available now. The process is automated but needs manual approval.
